### ISSUE TITLE
Settings freeze

### ISSUE THREAD

**Issue by kromonos** [owntracks/android#101]
Settings intent freezes, when trying to opening in 0.5.03.
Also after reinstall

**Comment by binarybucks** [comment]
Is this still a thing with 0.5.04 from the Play Beta?

**Comment by jpmens** [comment]
I don't know what "settings intent freezes" means, but I've had no issues with preferences, if that's what it means, in 0.5.04. :)

**Comment by binarybucks** [comment]
also fixed for me

**Comment by kromonos** [comment]
Fixed in 0.5.04
