### ISSUE TITLE
Change the way owntracks stores location updates when the phone has no internet connection 

### ISSUE THREAD

**Issue by AlertSubject** [owntracks/android#1018]
I don't know if it's possible to implement but it would be great if owntracks could store location updates that haven't been sent yet on the phones storage

I don't know what the current implementation does but whenever the app crashes or the phone runs out of battery etc, all un-sent location updates will get lost. :(
Sadly this has happened many times to me which is why I'd be very happy to see it changed

**Comment by growse** [comment]
This has been on the to-do list for a while, and finally got fixed in b22b2ed so should be available in the next version when that gets released.

Please feel free to reopen or file a new issue if you still have issues once the next version is out.
