### ISSUE TITLE
Delete waypoints by remote configuration

### ISSUE THREAD

**Issue by LucaPiccirillo** [owntracks/android#1022]
Hello, it seems there is no way to delete a waypoint by remote configuration on Android. 
Is it possible to add this feature?

**Comment by growse** [comment]
Certainly! It's probably missed the cutoff for 2.4, but I'll try and get it into 2.5.

**Comment by growse** [comment]
Just re-opening for tracking.

**Comment by wir3z** [comment]
Just checking what is the method to delete a waypoint.  When I try the iOS method of entering invalid coordinates, latitude gets clamped at +/- 90, and longitude stores whatever the invalid number is, and the app still retains the invalid region.  Thanks!
