### ISSUE TITLE
Location not reported after restart until app interacted with 

### ISSUE THREAD

**Issue by dannysauer** [owntracks/android#1023]
* **App build number**: 2.3.0 (23024)
* **Android version**: 11
* **Device**: Samsung Galaxy S10+ (SM-G975U) 

I don't know if this is a misconfiguration, phone limitation, or app issue - but after restarting my phone, my location isn't sent to mqtt until after I open the app once. The notification of move monitoring mode is visible automatically on start, and the app is whitelisted to not be powet-save'd. It just doesn't send my location until I tap the notification and open the app once. I don't have to do anything in the app; just open it.

**Comment by growse** [comment]
See #976, #969, #967

Next release will detect this and add a new notification to prompt you to open the app.

**Comment by dannysauer** [comment]
Thanks for the links; my search was clearly ineffective. :D

**Comment by jonferreira** [comment]
@growse been using owntracks for years and recently (deffo after updating to android 11 but pretty sure it did worked OK for a couple of days afterwards) OT in Significant Changes mode is only reporting location when the app is opened.

The app is and has been whitelisted, autostarting, High power conumption location permissions, notification with last report present but still no reports unless I manually open it. I did noticed that while apps like google maps, home automation and many others have the "allow all the time" permission OT doesn't - unsure if it's related?

Tried to install the new beta (both apk, unsure what the difference is?) but just get a "App not installed" warning at the very end :(

**Comment by growse** [comment]
@jonferreira what device?

**Comment by jonferreira** [comment]
ooops my bad.

Realme X2 Pro with Android 11

**Comment by growse** [comment]
Hmmm. I don't suppose you can get a hold of the log (either in-app, or logcat)?

Realme doesn't score particularly well on the dontkillmyapp site (https://dontkillmyapp.com/realme), and I wonder if later versions are preventing foreground services from receiving a location on their latest firmware. It wouldn't be the first time we've heard of some vendors restricting that sort of thing (or hiding the restriction behind a setting).

Unfortunately there's not a lot that can be done on the app site. We test pretty extensively on both the emulator and the pixel devices, but there's so many vendors with different behaviours it's essentially impossible to say what's going on for certain on a device that's not been explicitly tested on.

> Tried to install the new beta (both apk, unsure what the difference is?) but just get a "App not installed" warning at the very end :(

This *is* weird. Do you get that as a toast after installing it? If you could grab a screenshot, that would be useful.

(There's two builds, as we're moving towards creating a non-Google version that has no dependencies on Google Play Services, or any of the closed-source google libs, e.g. maps. I hope to be able to distribute the `oss` version on F-droid at some point.)

**Comment by jonferreira** [comment]
Sorry for the delay @growse was at a work meeting lol

OK so Realme, been using them for 2 years and never had an issue. That said Android 11 is pretty new so who knows...what's weird is:

a) OT isn't killed, it's there, i.e. I have both the Persistent Notification and I can see the app running on the Background (I even tried locking the app so that it's always "open")
b) other apps such as HA, Tasker, Google Maps, Covid bla bla bla seem to work and update fine on the foreground

![Screenshot_2021-08-05-17-43-58-80_92b64b2a7aa6eb3771ed6e18d0029815](https://user-images.githubusercontent.com/7714292/128389094-9bad6c4b-a1d6-434f-af03-c9c266346a42.jpg)

Logs: Happy to share a log. It's weird because as far as I can see the log "starts" the second I open the app.
https://pastebin.com/V8tDwNey
https://pastebin.com/Gqbh8v5Q

New apk: yeah that. Progress bar goes all they way to the end and then I get that notification.

![Screenshot_2021-08-05-17-46-45-09_3d73e98b1ad3bd2575f7a56513d89a0c](https://user-images.githubusercontent.com/7714292/128389062-06d5d665-a1e3-46e5-b525-5821710841a1.jpg)

**Comment by growse** [comment]
Thanks - I'll try and digest shortly/

**Comment by jonferreira** [comment]
Another bit of information which may or may not help.

I've just drove back home and my last location update was when I've opened OT manually. 

I've tried expanding the notification and click "report" which then sucessfully sent a location update (I'm using HTTP btw) *but* with the "wrong location", i.e. the location shown on the print, i.e. the location where I was last time I've opened the app.

![Screenshot_2021-08-05-18-32-06-67_92b64b2a7aa6eb3771ed6e18d0029815](https://user-images.githubusercontent.com/7714292/128395254-185cb848-f5f3-4056-b0b4-4e23cb262e34.jpg)

**Comment by growse** [comment]
That smells an awful lot like the foreground service isn't receiving *any* location updates, despite asking for them.

**Comment by jonferreira** [comment]
Yeah that would make sense.

Anything I can do to diagnose this or even better, prevent it from happening?
________________________________

**Comment by growse** [comment]
I've not been able to reproduce your apk issues - downloading them on the emulator with Chrome, I can successfully install (once I allow Chrome to install applications from unknown sources). Can you try running `adb logcat` while you're doing the installation to see if there's any errors you can see that?

**Comment by jonferreira** [comment]
OK I'll try to figure out how to do that lol
