### ISSUE TITLE
Waypoints are not imported

### ISSUE THREAD

**Issue by kromonos** [owntracks/android#103]
Importing exports does not imports waypoints

**Comment by jpmens** [comment]
Confirm missing waypoints import in 0.5.04

**Comment by binarybucks** [comment]
I know, there is no code in place to do that (yet) :D

**Comment by binarybucks** [comment]
done

**Comment by juzam** [comment]
I've update to 0.5.11 yesterday. Waypoints was wiped after the update, So I went and tried to import a saved config I had on Dropbox, Owntracks crashed after confirming the import (and no waypoint was imported)

**Comment by binarybucks** [comment]
Yeah, sorry about this. The 0.5.11 release is quite broken because I forgot
to actually merge in many changes before building the release.
0.5.12 is in the works.

On Thu, Mar 26, 2015 at 11:26 AM, Giovanni Angoli <notifications@github.com>
wrote:

> I've update to 0.5.11 yesterday. Waypoints was wiped after the update, So
> I went and tried to import a saved config I had on Dropbox, Owntracks
> crashed after confirming the import (and no waypoint was imported)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/android/issues/103#issuecomment-86442025>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust

**Comment by juzam** [comment]
@binarybucks No problem! I just wanted to report this, thanks for all the work you and everybody contributing is doing.

**Comment by jpmens** [comment]
@juzam thank you for confirming the import crashes the app; @binarybucks just didn't want to believe me! :-) :-)
