### ISSUE TITLE
Question - battery use during move mode, deep sleep not allowed between position reports?

### ISSUE THREAD

**Issue by jbrepogmailcom** [owntracks/android#1038]
* **App build number**: 
* **Android version**:    
* **Device**: 

Hello,

how does battery usage work while in between position reporting in MOVE mode? Is the phone allowed to deep sleep or disabled? If I set reporting interval to 5 minutes in MOVE mode, is the phone allowed to sleep most of the time? According to battery usage it looks like the deep sleep is disabled all time.

**Comment by growse** [comment]
Hi - I don't think the app has any control over the power state of the device. In move mode, the app simply creates a  `com.google.android.gms.location.LocationRequest` at a priority of `PRIORITY_HIGH_ACCURACY` (https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest), and then sets the interval to be whatever you ask for in the app. If it's 5 minutes, Android effectively invokes a callback every 5 minutes.

What the device does in the meantime is sort of up to the device, and ultimately up to Google (who own that API). The difference between `PRIORITY_HIGH_ACCURACY` and the other priority levels is that the device is much more likely to use GPS as a source, and I can imagine that keeping the GPS listener up and running might affect the device power state.
