### ISSUE TITLE
[0.5.03] Setting waypoints

### ISSUE THREAD

**Issue by kromonos** [owntracks/android#104]
After adding the first waypoint, trying to add a second one:
* Pressing the add button and return without entering something results into a cloneing of existing waypoints just in view: http://bka.li/Screenshot_2015-02-23-17-06-35.png
* Adding a second waypoint, the first will be overwritten. Just in view or real? Example http://bka.li/Screenshot_2015-02-23-17-12-23.png

**Comment by binarybucks** [comment]
Already closed in #99
