### ISSUE TITLE
Autostart does not work

### ISSUE THREAD

**Issue by ipod86** [owntracks/android#1046]
Owntracks doesn't start for me after restarting my smartphone.  
No location is transmitted.  
If I start the app manually everything works again.  

Unfortunately, I can't do it any other way.  Eg start the service with tasker.

Android 11 Samsung S21 Ultra.
Owntracks 2.3.0 same on beta 2.3.4

**Comment by growse** [comment]
The app doesn't start, or it does start but doesn't send a location?

If the latter, then it's the same issue as #976, #969, #967 & #1023. It's an android restriction, and 2.4 (currently in beta) will prompt you with a notification.

**Comment by ipod86** [comment]
I just tested again.  The app starts (I just don't notice anything because I've switched off notifications from the app).  I think the app starts and does not transmit a position.  As in https://github.com/owntracks/android/issues/1023

Possibly a hint in the app helps, where you activate the autostart, that there can be problems.

Excuse my english.  I use the google translator

**Comment by growse** [comment]
> I just tested again.  The app starts (I just don't notice anything because I've switched off notifications from the app).  I think the app starts and does not transmit a position.  As in https://github.com/owntracks/android/issues/1023
> 
> Possibly a hint in the app helps, where you activate the autostart, that there can be problems.
> 
> Excuse my english.  I use the google translator
> 
> 

Ah, you make a very good point - some people do disable notifications and therefore won't see it. 

It's a good idea to display a message on the device autostart preference where appropriate, warning the user about this behaviour. I'll add it into the beta for 2.4.

**Comment by growse** [comment]
This was fixed in f68fc83ff9d0976df989d8a9359c3fd221ae1f57
