### ISSUE TITLE
Lack of contrast in foreground text in dark mode when configuring options

### ISSUE THREAD

**Issue by ljr55555** [owntracks/android#1049]
* **App build number**: 2.4.0 (24031)
* **Android version**: 11 Security Patch Level March 1, 2021
* **Device**: TCL 10L

Actual behavior: When using dark mode, configuration screens have very little contrast between the background color and the user-configurable text components. 

![Screenshot_2021-07-29-23-41-32-759](https://user-images.githubusercontent.com/24596267/127597827-25c29f94-c783-4416-a149-e53e8fa56b99.jpg)

You are able to click into the configuration text and edit the value
![Screenshot_2021-07-29-23-41-37-401](https://user-images.githubusercontent.com/24596267/127597823-2c18f5aa-5952-45b9-a2a8-40e5e53dbd19.jpg)

But it is difficult to see the values. 

Expected behavior: Foreground and background text are contrasting colors as in the light theme

![Screenshot_2021-07-29-23-41-18-697](https://user-images.githubusercontent.com/24596267/127597825-f6dd1e84-8f35-4e62-88a9-001a6618b296.jpg)

(Images have been edited to remove the first four digits of the lat/long)

**Comment by growse** [comment]
Not sure how this one slipped through - I'll do an update and a new beta.

Thanks!
