### ISSUE TITLE
Long press vs tap for face on map

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#105]
Face on map. I tried long-press (as I did in, say, friends list) in order to see details / assign face/name, but nothing happened.

Sometime later, by mistake, I tapped (short press), and bingo!

This may be confusing to others. 

0.5.04

**Comment by jpmens** [comment]
Tap on face on map.

**Comment by jpmens** [comment]
... after which white card thing pops up.

**Comment by binarybucks** [comment]
Jup. When you long tap that it takes you to the contacts context menu like everywhere else on Android, doesn't it?

--
Alexander Rust

**Comment by jpmens** [comment]
When I long press the white card thing, yes.

I was expecting to be able to long-press the face. I guess all I'm saying is long-press and tap (on the face) should bring up the white card thing.

**Comment by jpmens** [comment]
Closing as irrelevant
