### ISSUE TITLE
[Feature Request] Ability to use TLS client certificates from the system keystore

### ISSUE THREAD

**Issue by valpackett** [owntracks/android#1061]
I already have a client certificate installed in Android's system keystore (which can be hardware-backed). It is used by e.g. Chromium-based browsers and the openHAB client. OwnTracks should be able to use it too, rather than requiring an app-specific import.

**Comment by growse** [comment]
This seems reasonable. I think there's a couple of UX questions that would need to be thought about, such as "How does the user specify a client cert that's in the system store, and which one it is".

Depending on device support, I wonder if it's worth migrating the job of client cert certificate to the OS itself, so the "choose a client cert" option just becomes a name picker for the system store. Bit of research needed.
