### ISSUE TITLE
[Feature request]show geofence boundaries on map 

### ISSUE THREAD

**Issue by ghost** [owntracks/android#1068]
It has been a time since I have used ios, but I seem to remember that the ios version of owntracks supports showing regions in the map. It'd be a neat feature for android, too, in my opinion.

**Comment by jpmens** [comment]
I believe you mean the geofence region. Yes, iOS displays those.

**Comment by growse** [comment]
This should be a Thing That Should Be Done.

I'll try and get it in 2.5. I wonder if I should create some.... milestones?
