### ISSUE TITLE
blue dot is off

### ISSUE THREAD

**Issue by ghost** [owntracks/android#1078]
Hello, I just wanted to report this so it doesnt get lost when 2.5.0-dev is merged, but the blue dot in the OSM map seems off. When I zoom out, it changes its position on the map (probably because the image of the blue dot is bigger than the actual graphic itself or something like that and thus the bottom right corner of the image stays on the right position whereas the actual center of the blue dot changes position.

* **App build number**: 2.5.0-dev branch (737b325c3489679dc467d944d76183c4f61e9a3f)
* **Android version**: Android 11
* **Device**: Google Pixel 3

**Comment by growse** [comment]
Yeah, it's a bit wonky at the moment. I'll try to get it sorted before merging.

Thanks for testing the latest work-in-progress though! (y)

**Comment by nikitaindik** [comment]
Hey, @growse! Does the fix also apply for the OSS version? Having this issue on v2.4.9 OSS (20409000), OnePlus 7 Pro, Android 11. 

As you zoom out, the dot shifts. Attached a few screenshots to show the behavior.

![Screenshot_20220626-215130](https://user-images.githubusercontent.com/15949146/175829609-76ada843-3dd7-491f-8317-a323a00a06b5.jpg)

![Screenshot_20220626-215135](https://user-images.githubusercontent.com/15949146/175829635-00404e6d-0b1d-4a3f-8e7d-472478f1075f.jpg)

![Screenshot_20220626-215152](https://user-images.githubusercontent.com/15949146/175829641-ca75a5b2-d95a-4991-b284-412fb697f77f.jpg)

**Comment by growse** [comment]
Eurgh, that shouldn't happen.

I'll see if I can figure out what's going on. Thanks for noticing and posting.

**Comment by growse** [comment]
This should be sorted in next version, out shortly.
