### ISSUE TITLE
Subscribe switch not being persisted

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/android#108]
If I set the 'Subscribe' option ON and specify a topic I don't see any other locations being listed. When I go back into the Advanced preferences the 'Subscribe' option is OFF again.

Also, when I turn the option back on the Remote Dump Command and Remote Configuration options flick on at the same time.

**Comment by binarybucks** [comment]
Changed subscriptions are currently only reestablished when you connect.
State of the Subscribe switch is correctly persisted here.  

Remote commands are disabled when subscribe is off, like the subscribe topic.
- If they where on and you disable subscribe, they are greyed out but active (knob on the right). 
- If they were off and you disable subscribe they are greyed out and inactive (knob left).

**Comment by sumnerboy12** [comment]
Thanks Alex - looks like subscriptions are working after manual disconnect/connect. And the subscribe option now appears to be being persisted. Was definitely seeing it get disabled, perhaps it was something to do with me no re-connecting before re-opening the Advanced Preferences screen? It is now working however so I will close the bug.

**Comment by sumnerboy12** [comment]
This is definitely an issue. If I go into the Advanced settings page and the Subscribe option is ON, if I then scroll down so that option is no longer visible, when I scroll back up the option is now OFF. This is reproducible 100% of the time.

**Comment by binarybucks** [comment]
Not on my device unfortunately.. 
What Android version are you using? 

When the switch changes states when scrolling out of view, this is not something I can influence but a bug (besides many others) in the Android Support library.

**Comment by sumnerboy12** [comment]
4.4.3. Ok - so this is confirmed as an Android bug? If so feel free to close this item again.

**Comment by sumnerboy12** [comment]
BTW - it doesn't do it for the Publish Retained option, but does for the Ranging option.

**Comment by binarybucks** [comment]
Yes, I probably cannot do anything about this. 
I don't know why it just happens for this option as it is not different then all the others.  


I hope Google releases a new version of the Support Library later. There are so many issues and missing features.

E.g. on Android 5 they got rid of the AppBar for navigation back button and view titles and replaced it with the Toolbar. Nice thing is that this toolbar is not supported in the preferences. This is why the blue toolbar in the preferences scrolls. It is just a ordinary preference element styled as toolbar because per default you cannot go back once in the preferences.

**Comment by binarybucks** [comment]
There are other users that see this too, so I'll look into it. 
Besides that, the dependency of the remote commands on the sub switch was wrong anyway. The app always subscribes to it's base topic and the sub switch only defines an additional topic to which it will subscribe. 

As remote commands are always published to the base topic, they are in no way influenced by the sub switch.
