### ISSUE TITLE
Configuration incomplete 

### ISSUE THREAD

**Issue by MichaelBest01** [owntracks/android#1083]
This is on android. Why does owntracks say configuration incomplete? Idk what to do. I press change monitoring but it doesn't do anything

**Comment by growse** [comment]
"Configuration Incomplete" usually means that you haven't configured at least an MQTT host (in MQTT mode) or a URL (in HTTP mode) to send locations to.

How have you configured it?

**Comment by MichaelBest01** [comment]
I never did any of that stuff. What URL do I put for http mode?

**Comment by growse** [comment]
The URL of an instance of OwnTracks Recorder that you (or someone you know) is running on the internet.

It might be worth reading through the booklet (https://owntracks.org/booklet/) to get a bit more context: 

> To be quite clear, you also run the backend in order to ensure that only you and the people you authorize have access to the data published by the apps.
