### ISSUE TITLE
Use case: OwnTrack - VPN - OwnTrack server lacking and low usability.

### ISSUE THREAD

**Issue by mats-nk** [owntracks/android#1091]
TLDR: User case: Have a OwnTrack server infrastructure on prem, uses VPN between OwnTrack App and OwnTrack server infrastructure.

I left a review that the developer found confusing, so I will try to give you my use case.

When I found OwnTrack I was thrilled, a app on the phone and not a company tracking me as I could have my own server.

So I installed OwnTrack on my Android phone, and started a OwnTrack servcer on my docker host.

Since Im into IT security I intended to use a VPN from my phone to my VPN server so my phone could reach the OwnTrack server. This is a dual security meassure, the OwnTrack server isn't exposed to Internet and the communication between my phone and the OwnTrack server is also protected.
 
But what a hassle! As soon as I got outside my network and intended to use the OwnTrack app on my phone on the road I had:
- Start the VPN client manually
- The OwnTrack app started to complain when it lost the connection (and very often with no way to configure it)
- And I'm curious, is the tracking information cached when the client looses the connection.

I thought this was one of the use cases for OwnTrack as I quote your web:

_"OwnTracks allows you to keep track of your own location. You can build your private location diary..."

"or follow the guide in our Booklet to set up your own."_

**Comment by jpmens** [comment]
We typically recommend using TLS between the OwnTracks client and the server which, for most people, should provide at least adequate eno  security. This can be enhanced further using client certificates and/or passwords. 

I’m not familiar with Android and VPN software (which?) so cannot comment on how auto connect should work or how (un-)reliable it may be. In any case that’s beyond our scope I think.

**Comment by growse** [comment]
Thanks for raising the issue, it's now a lot clearer what you're trying to do.

Firstly, I think the booklet recommends that HTTP / MQTT connections should be secured with TLS, which should provide sufficient protection (confidentiality/integrity) of the network traffic. That said, I do appreciate that there are some who want to tunnel to their endpoint over a VPN, as you've said.

Secondly, we try and limit the complexity of functionality within the app as much as possible, specifically when it comes to automating the device configuration or responding to the environment. There are many, many apps out there which can take care of automation cases such as "When I drop off my Wifi, turn on my VPN" ([Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=en_GB&gl=US) is a well-known app that I've found works well at this sort of thing). OwnTracks provides intent receivers that effectively allows it to be configured by theses sorts of apps. In other words, noticing that your device has had its network environment changed and should now activate a VPN tunnel is not something that OwnTracks should, or would be doing. 

> * The OwnTrack app started to complain when it lost the connection (and very often with no way to configure it)

This is interesting - when OT loses its connection, it should automatically reconnect. If it's not, then I'd be interested in gathering some log data or descriptions of what it actually does / says to try and figure out what's going on here.

> * And I'm curious, is the tracking information cached when the client looses the connection.

Yes. Messages are held in a queue (as of recent versions, this is device file-backed) and only removed once acknowledgement of upstream publish has been received.

**Comment by mats-nk** [comment]
> 
> We typically recommend using TLS between the OwnTracks client and the server which, for most people, should provide at least adequate eno security. This can be enhanced further using client certificates and/or passwords. I’m not familiar with Android and VPN software (which?) so cannot comment on how auto connect should work or how (un-)reliable it may be. In any case that’s beyond our scope I think.

In Androids settings, Network, Advanced is the built in VPN.

TLS is only protecting the communication, and the server port needs to be exposed to Internet.

And as a IT Security Pro that is a bad advice if a VPN could be used.

**Comment by growse** [comment]
> 
> 
> > We typically recommend using TLS between the OwnTracks client and the server which, for most people, should provide at least adequate eno security. This can be enhanced further using client certificates and/or passwords. I’m not familiar with Android and VPN software (which?) so cannot comment on how auto connect should work or how (un-)reliable it may be. In any case that’s beyond our scope I think.
> 
> In Androids settings, Network, Advanced is the built in VPN.

Ah ok, that makes sense. I suggest something like [MacroDroid](https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid&hl=en_GB&gl=US) or Tasker (above) to detect and enable this.

> TLS is only protecting the communication, and the server port needs to be exposed to Internet.
> 
> And as a IT Security Pro that is a bad advice if a VPN could be used.

Well..... it depends entirely on your threat model. VPNs can also be useful, but they can also introduce new fun vulnerabilities. Everything is a trade-off. Personally, I have no issues putting an MQTT broker (or, even, a webserver) on the internet. Horses for courses.

**Comment by mats-nk** [comment]
> 
> We typically recommend using TLS between the OwnTracks client and the server which, for most people, should provide at least adequate eno security. This can be enhanced further using client certificates and/or passwords. I’m not familiar with Android and VPN software (which?) so cannot comment on how auto connect should work or how (un-)reliable it may be. In any case that’s beyond our scope I think.

In Androids settings, Network, Advanced is the built in VPN.

TLS is only protecting the communication, and the server port needs to be exposed to Internet.

And as a IT Security Pro that is a bad advice if a VPN could be used.
