### ISSUE TITLE
Owntracks -  Doesn't automatically start tracking after reboot

### ISSUE THREAD

**Issue by austwhite** [owntracks/android#1094]
Whenever the phone is rebooted, Owntracks will stop tracking location.    This seems to be due to background location usage not being available.  
I get the message "Location Tracking Paused.  This version of Android restricts OwnTracks from receiving locations when started in background until the app is opened.  Click this notification to open the app and start tracking location"
Once I open Owntracks and then send it back to the "background" it will work fine.
I do not have this issue with Life360 or the Home Assistant companion app, which also do real time location tracking.  
The only difference I can see in permissions is that OwnTracks does not have the "Allow all the time" option in Location settings.  All the other tracking apps that start properly when the phone reboots have this option, and successfully track real time.
It's a minor annoyance more than a real deal breaker, but I would like to know if there is a way to get OwnTracks to start tracking automatically when the phone boots like other apps can do.   Not sure if the issue is my device or just something I am doing wrong :).
Thanks

* **App build number**: Version 2.4.2 (24208) - Google Play 
* **Android version**:  11 build RP1A.200720.012.G970FXXSCFUH5 - One UI version 3.1   
* **Device**:  Samsung Galaxy S10E

**Comment by growse** [comment]
You're not doing anything wrong, this is an Android limitation. OwnTracks doesn't request background location permissions for a number of reasons:

1. It doesn't need them. Holding a foreground service and requesting location updates there allows OT to receive updates at the desired rate and accuracy as long as that foreground service is running.
2. The Google Play Store has a policy around allowing publishing of apps that request background locatoin (https://support.google.com/googleplay/android-developer/answer/9799150). In short, there's a lot of work required to convince Google that background location is "required". 
3. Even if we did that and were allowed to use background location permission, we'd still be subject to the [background location limits](https://developer.android.com/about/versions/oreo/background-location-limits) on devices > Android 8 (API 26). From the backgroudn limits article "If your app is running in the background, the location system service computes a new location for your app only a few times each hour. This is the case even when your app is requesting more frequent location updates." If we did this for OT, what you'd see is very infrequent location publishes after device boot, until you interacted with the app in some way, and then updates would suddenly become more frequent. 

I'm not familiar with what Life360 or HA are doing (although [HA seems to request background location](https://github.com/home-assistant/android/blob/master/app/src/main/AndroidManifest.xml)) but they'd be subject to the same policies and restrictions as above. 

That said, the current plan is to include background location permission in the OSS flavour build of the app, which will be distributed on [F-Droid](https://www.f-droid.org/). Hopefully, we can get some user feedback about how background location behaves there on real-world devices (after reboots, upgrades etc.) and then take another look at jumping through the necessary hoops to add it to the Google Play Store version.
