### ISSUE TITLE
cannot see friends in oss build

### ISSUE THREAD

**Issue by bemdark** [owntracks/android#1097]
## problem
using the new oss version, I can't seem to see any of my friends. when using nexttracks (which is based off an earlier ot version with the same mqtt account), I can see friends.
unfortunetly, i cannot try another owntracks versio since my os doesnt support google play service

## logs
https://bin.snopyta.org/?8bc35ffff66ec6dc#C1HYjMdruFgBMCdJkXt71CSHJCLmyMC68LiRHJMf3Gb7

* **App build number**: owntracks-release-oss.apk from releases: v2.4.2
* **Android version**: GrapheneOS (latest)
* **Device**: Pixel 4

**Comment by growse** [comment]
Seems to work here?
![Screenshot_20211007-160908_Owntracks](https://user-images.githubusercontent.com/378067/136413481-7a74088b-68d6-4389-b3bc-afa93df4ff4a.png)
![Screenshot_20211007-160848_Owntracks](https://user-images.githubusercontent.com/378067/136413484-1f2b4050-c114-4e0a-a132-2906e7658df1.png)
![Screenshot_20211007-160858_Owntracks](https://user-images.githubusercontent.com/378067/136413486-af673a9e-31cc-41f5-9c22-87d671aa56c0.png)

Do you see anything in the logs when you get location pings from other contacts on the same broker?

**Comment by bemdark** [comment]
The only thing that is different is the message itsself, from nexttracks it contains fewer information (i think the owntracks messages also contain wifi ssid, created_at etc.) Could this be a problem that causes incompatibility?

**Comment by bemdark** [comment]
Just as a thought, maybe there should be some kind of warning in the status page if OwnTracks can detect that it uses another mqtt protocol version than the server, as it was quite confusing that it just showed "Connected!" in the status page as if every was working correctly.

**Comment by ckrey** [comment]
@bemdark

It is the responsibility of the server to reject incompatible protocols specified in the CONNECT message. The client cannot determine the protocol of the server in MQTT.

Why are you using an MQTT broker which does not implement the MQTTV3.1.1 specification from 2014? It is 2021 now!
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

The default version used in `mosquitto_sub` is MQTTV3.1.1 since 3 years now.
Why are you using an outdated `mosquitto_sub` version?

**Comment by bemdark** [comment]
I wasn't using an outdated version of mosquitto_sub, it's just that the mqtt broker I'm using (which isn't mine) doesn't seem to be able to use mqttv3.1.1. The broker is also mosquitto but obviously doesnt reject the incompatible protocols as I could connect fine but just wasn't able to subscribe to any topics.

**Comment by growse** [comment]
I guess what's confusing is that mosquitto 1.6.8 supports MQTT 3.1, 3.1.1 and 5. MQTT5 support landed in 1.6, and MQTT3.1.1 has existed since 1.4 (released back in 2015). I can't even figure out how you'd disable MQTT 3.1.1 on a 1.6.8 broker, so it's weird that it would behave like that.
