### ISSUE TITLE
SubscriberMethodFinder.java line 75

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#110]
#### in de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/54f0e2b47d7854d7c993f80d](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/54f0e2b47d7854d7c993f80d)

**Comment by binarybucks** [comment]
Under certain conditions Android is unable to find Contacts class in package. Fixed by reinstalling. Needs investigation

**Comment by binarybucks** [comment]
unable to reproduce with latest master. Reopen if it occurs again.
