### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by Allineer** [owntracks/android#1116]
Please, check the POEditor's comments (Russian)

**Comment by Allineer** [comment]
PS: missing strings:

https://github.com/owntracks/android/blob/30ceb6bb129a14a7cc1737680b0d607acd38c604/project/app/src/main/java/org/owntracks/android/ui/preferences/load/LoadActivity.java#L189-L192

**Comment by growse** [comment]
Thanks - I'll take a look and ask for clarification over at POEditor if I don't quite know what's going on.

**Comment by growse** [comment]
> 
> 
> PS: missing strings:
> 
> https://github.com/owntracks/android/blob/30ceb6bb129a14a7cc1737680b0d607acd38c604/project/app/src/main/java/org/owntracks/android/ui/preferences/load/LoadActivity.java#L189-L192

This specific feature is actually disappearing in 2.5.0 - you won't need to restart after an import. So rather than make everyone translate some strings that will just become redundant, I left them as is.

**Comment by Allineer** [comment]
@growse Thanks, Andrew!

How about this strings for the Russian?

https://github.com/owntracks/android/blob/0d53f665a98578b519f03043a605380494be08aa/project/app/src/main/res/values/strings.xml#L232-L234

**Comment by growse** [comment]
Should be in the Theme preference:

![image](https://user-images.githubusercontent.com/378067/140894744-808a2527-7b26-4688-87ee-099b2a3cd5ae.png)

**Comment by Allineer** [comment]
but no strings in POeditor

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/1168049/140921708-e6cdbb70-8f49-4c47-b47f-7b62799cb6a9.png">

**Comment by growse** [comment]
Huh, I don't think POEditor supports `string-array`: https://poeditor.com/localization/files/android

Would you be able to edit directly on github?

**Comment by Allineer** [comment]
> I don't think POEditor supports `string-array`: https://poeditor.com/localization/files/android

Hm.

> String Array
> - XML resource that provides an array of strings.

**Comment by growse** [comment]
> I can and it will be even more convenient for me. But how do you then combine the results with POEditor and my corrections directly?
> 

So POEditor can commit its translations to the repo, or I can pull from the repo into POEditor. 

I don't think there's any conflict resolution though, just "last write wins". So if you PR edit the string arrays, they shouldn't get overwritten by POEditor, but other keys may get overwritten.

**Comment by Allineer** [comment]
@growse, job is done.
can you build a new beta (OSS is desired) for testing?

**Comment by growse** [comment]
There's one other bug I want to sort before beta3, but hopefully will get to it today.
