### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Allineer** [owntracks/android#1123]
https://github.com/owntracks/android/blob/bb80ae2fc1614b7a9d73fd0a4a958500705eeca1/project/app/src/main/java/org/owntracks/android/ui/map/MapViewModel.kt#L244

https://github.com/owntracks/android/blob/30ceb6bb129a14a7cc1737680b0d607acd38c604/project/app/src/main/res/xml/about.xml#L35

https://github.com/owntracks/android/blob/30ceb6bb129a14a7cc1737680b0d607acd38c604/project/app/src/main/res/xml/about.xml#L58

https://github.com/owntracks/android/blob/30ceb6bb129a14a7cc1737680b0d607acd38c604/project/app/src/main/res/xml/about.xml#L61

https://github.com/owntracks/android/blob/30ceb6bb129a14a7cc1737680b0d607acd38c604/project/app/src/main/res/xml/about.xml#L62

Can we translate this strings?

- - -

https://github.com/owntracks/android/blob/01660eeee98d3936c31106b5ec94022ec3f380d9/project/app/src/main/res/values/strings.xml#L197

How about plurals for "languages"?

- - -

![image](https://user-images.githubusercontent.com/1168049/141726898-98bacfee-c1c0-4d76-b132-fafb838830c6.png)

Can we move this block to the left a few pixels?
One character for the string contactDetailsDistance does not fit in the space allotted to it :(

**Comment by Allineer** [comment]
@growse I have checked my translation on beta 3 and have a number of fixes. I will prepare a PR in the next few hours. Sorry :(

**Comment by growse** [comment]
No problem - we can do another release pretty easily, I just wanted to get a tag for v2.4.3 so I could actually work on getting it submitted to F-Droid.

Thanks!

**Comment by Allineer** [comment]
@growse How about questions in the first message?

**Comment by growse** [comment]
Sorry, forgot to say. 

Yes, all good points. I'll update extracting some of those as string resources shortly, and look at re-laying the contact bottom sheet to prevent truncation.

On the plurals, I didn't bother setting it to be a plural, because it's essentially never going to be singular.

**Comment by Allineer** [comment]
451 languages = 451 язык
452 languages = 452 языка
456 languages = 456 языков

**Comment by growse** [comment]
Touché :D

**Comment by growse** [comment]
Resources updated. Looking at the bottom sheet layout now.

**Comment by Allineer** [comment]
@growse,

https://github.com/owntracks/android/blob/bb80ae2fc1614b7a9d73fd0a4a958500705eeca1/project/app/src/main/java/org/owntracks/android/ui/map/MapViewModel.kt#L244

**Comment by growse** [comment]
I added `contactDetailsDistanceUnitKilometres` and `contactDetailsDistanceUnitMeters`

**Comment by Allineer** [comment]
@growse, Andrew, we still have an issue from the first screenshot.

![image](https://user-images.githubusercontent.com/1168049/144977323-ba6d29b5-9904-492a-9d1a-59cf0d8ea1d6.png)

**Comment by growse** [comment]
Good spot. I thought the auto-sizing was working properly, but obviously not. Let me try and figure out.

**Comment by Allineer** [comment]
Oh no :'(

https://github.com/owntracks/android/commit/2e8bbab7054d86ba016650b3ffb088240fe62bf8

@growse , can you revert this commit for the Russian translation?

Or I need to update it on POEditor?

**Comment by growse** [comment]
Ah boo - I missed that. I'll try and revert the Russian translations and then get POEditor up to date.

**Comment by growse** [comment]
Ok, I've reverted those changes. @Allineer can you check the latest on `master` and let me know if it looks right, and then I'll pull those into POEditor?

**Comment by Allineer** [comment]
@growse, I confirm. Everything is correct. Thanks a lot!
