### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by tuuure** [owntracks/android#1145]
* **App build number**: v2.4.4

Chinese translation is unfinished, but it's already used in the latest release. It's so confusing for users. 
![Compare](https://user-images.githubusercontent.com/27071251/145580148-b2e119b3-66fa-4f49-aa8d-c68c76fce5fe.png)

**Comment by growse** [comment]
Huh - I expected untranslated strings to fall back to the default. Let me check why that's happening.

**Comment by tuuure** [comment]
Exporting only translated text should solve this problem.
![2021-12-11 08-56-59 的屏幕截图](https://user-images.githubusercontent.com/27071251/145658672-b15e1f5c-71ae-4941-9f6e-d01b90b8a949.png)
