### ISSUE TITLE
Big font size in the contact's info

### ISSUE THREAD

**Issue by Allineer** [owntracks/android#1153]
24600 OSS

Big font size in the contact's info.
It is ok?

![IMG_20211219_185001_938](https://user-images.githubusercontent.com/1168049/146681375-36be3dd6-e970-493c-b5b0-384d5f792576.jpg)

**Comment by jpmens** [comment]
Are you saying you find the font size is too large?

**Comment by growse** [comment]
I suspect what's happened here is that since I fiddled with the layout to tell the content to auto-reduce its size to fit if its too large, it's now auto-increasing the size to fit if its too small.

I'm not convinced this is an issue, but will happily take advice on what a maximum size value should be.

**Comment by Allineer** [comment]
I think the font size is pointlessly large.

I would suggest using the size as in the rest of the application.

By example:
![Screenshot_2021-12-19-19-21-45-490_org owntracks android](https://user-images.githubusercontent.com/1168049/146682409-742a5bae-1f72-44a1-8a29-1663d2203714.jpg)

PS distance and direction (azimuth) to contact is no longer available?

**Comment by growse** [comment]
I guess that's a fair point. Will see if I can set a maximum on the auto sizing,

You don't get a distance / direction to a contact if either there is no local location fix or if the contact has no location available (hasn't published since we started up and connected for the first time).

**Comment by kri164** [comment]
Just FYI, how it looks in another laguage.

![Screenshot_20211220-180002_OwnTracks](https://user-images.githubusercontent.com/52274164/146807059-9ddc0d99-8828-4312-815f-e1a6cbce0318.png)

**Comment by kri164** [comment]
Why there are icons on upper right corner on some phones, while there is 3-dot (hamburger) menu on others?

**Comment by Allineer** [comment]
> how it looks in another laguage.

In Russian with Vzdalenost and Smer is looks very similar :)

**Comment by Allineer** [comment]
@growse how about decreasing the distance between the blocks instead of changing the font size?

**Comment by growse** [comment]
> Why there are icons on upper right corner on some phones, while there is 3-dot (hamburger) menu on others?

Screen resolution. Android hides / shows actionbar menu items depending on the amount of horizontal space available.

> @growse how about decreasing the distance between the blocks instead of changing the font size?

I'm going to stick with limiting the font size for the moment, and then see if we need to do anything else.

**Comment by Allineer** [comment]
![image](https://user-images.githubusercontent.com/1168049/185856991-10cb4d84-e57b-44bb-9b82-e1bc5c19e0c7.png)

@growse how about to show this labels with a **some** font size?

**Comment by growse** [comment]
(do you mean "same"?)

The labels are currently autosizing to fit, up to a max. Do you think that all the labels should be sized the same so that the longest one fits?

**Comment by Allineer** [comment]
> (do you mean "same"?)

yup :)

> Do you think that all the labels should be sized the same so that the longest one fits?

Right.
I think different font sizes looks terrible. Perhaps if you make them equally small, like the "Distance" label in the screenshot, it should turn out more pretty.
Can you try this?

**Comment by growse** [comment]
I'll see if there's a way of hooking into the text drawing mechanism post-sizing calculations, so that I can set all the sizes to be the same. This'll be a different value depending on lang and display (orientation/dpi etc.) so would have to be worked out on the fly.

**Comment by growse** [comment]
What think?

(I should probably do something about that awful floating point latlng issue too...)

![image](https://user-images.githubusercontent.com/378067/186761462-89a6c6ae-6fe6-4631-89fc-f4b1c5c34e77.png)
![image](https://user-images.githubusercontent.com/378067/186768262-3355ffaf-f8ea-4f29-b43e-213414d0838e.png)

**Comment by Allineer** [comment]
@growse I like it!

**Comment by jpmens** [comment]
@growse I agree on both accounts: the fonts look much neater now, and the lat,lon looks meh. :-)

**Comment by growse** [comment]
I'll create a PR for the 2.4.11 release, and a separate issue about truncating latlngs to a sensible number of dps.
