### ISSUE TITLE
ViewGroup.java line 3103

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#116]
#### in android.view.ViewGroup.drawChild

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/550026577d7854d7c9b1661a](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/550026577d7854d7c9b1661a)

**Comment by binarybucks** [comment]
This is a bug in the Android support library.
