### ISSUE TITLE
Feature Request: Publish current monitoring mode on location updates

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#1160]
As suggested for iOS in https://github.com/owntracks/ios/issues/694 (and implemented by @ckrey) I would like to propose we add this to Android as well, and I welcome discussion on https://github.com/owntracks/ios/issues/695

**Comment by growse** [comment]
So if I've got this right, per https://github.com/owntracks/booklet/commit/d4876781f801a8b006587e26ca3fba27328596b0 we just add the value of the mode number as an `m` field in the message if "Report Extended Data" is true?

```
public static final int MONITORING_QUIET = -1;
    public static final int MONITORING_MANUAL = 0;
    public static final int MONITORING_SIGNIFICANT = 1;
    public static final int MONITORING_MOVE = 2;
```

Should be pretty straightforward to add for 2.5.0 if so.

**Comment by jpmens** [comment]
That's great, thank you.

In addition what @ckrey has implemented and which goes hand-in-hand with this is [change tracking mode when entering/leaving a region](https://github.com/owntracks/ios/issues/683).
