### ISSUE TITLE
HardwareCanvas.java line 29

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#117]
#### in android.view.HardwareCanvas.<init>

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5500771e7d7854d7c9b229a6](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5500771e7d7854d7c9b229a6)

**Comment by binarybucks** [comment]
This is a bug in the Android support library.
