### ISSUE TITLE
[Feature Request] Add "disabled for Interval(s)" option (timer)

### ISSUE THREAD

**Issue by dora71** [owntracks/android#1195]
Hi folks,
it would be nice to have the mentioned feature in owntracks.

Why? Despite of the "significant changes mode" the app is still consuming lots of battery life (on actual Samsung phones I tried).
As I have people, who don't care of changing the mode of the app manually, it would be nice, if there would be a possibility to stop propagating the GPS position (e. g. during night time) without manual action or disabling the GPS device itself.
That would at least increase the battery life for people who just run the app in the background.

Regards, Rainer

**Comment by jpmens** [comment]
I think this should already be doable with Tasker, e.g. setting OwnTracks to quiet mode and then re-enabling when you need it?

**Comment by dora71** [comment]
> I think this should already be doable with Tasker, e.g. setting OwnTracks to quiet mode and then re-enabling when you need it?
Thank you for the quick answer. Problems with this solution:
- I haven't worked with Tasker yet (but I think I remember it's a paid app, isn't it?)
- Acceptance of my fellows (just another app to install, especially if it is an app for which you have to pay)

**Comment by growse** [comment]
> > I think this should already be doable with Tasker, e.g. setting OwnTracks to quiet mode and then re-enabling when you need it
> > Thank you for the quick answer. Problems with this solution:
> 
>     * I haven't worked with Tasker yet (but I think I remember it's a paid app, isn't it?)

Tasker is free

>     * Acceptance of my fellows (just another app to install, especially if it is an app for which you have to pay)

The flipside is there's a significant cost (both now and ongoing) in re-implementing functionality within OT that's already available (and likely to work much better) in another app designed to do exactly that.
