### ISSUE TITLE
UI update request

### ISSUE THREAD

**Issue by mirhunter** [owntracks/android#1197]
seems to me the "Move monitoring mode" and the "Significant changes monitoring mode" should have the revers icons and "Move monitoring mode" should have the ">" icon while the "Significant changes monitoring mode" should have the "||>" icon in the media world vcr/dvd/streaming media the "||>" means slow playback which in my mind equates to slow updates aka "Significant changes monitoring mode"

* **App build number**: 2.4.7 (24704)
* **Android version**: 9
* **Device**: moto z3
* **Installation source**: Google Play

**Comment by mar565** [comment]
The current mode should be shown in full text beside the icon. There is enough room and after over a year of usage I still have to stop and think about meaning of the icon.
