### ISSUE TITLE
a few questions :)

### ISSUE THREAD

**Issue by deknos** [owntracks/android#1198]
Hello,
i have seen your tool and wanted to know if it could be a replacement for [wikiloc](https://www.wikiloc.com/) which i currently use and i prefer to use free software, if possible :) Therefore i have a few questions, which i did not find in the booklet (i am not native english speaker, therefore i might have missed something) :

* is it possible to use it for hikes? or will the phone tell the movement to seldomly?
* does it also record altitudes and speed, at least in the generated movement data?
* is gpx export from the server possible?
* can i load such hikes into the android app (or another app) as we repeat the hikes and without the direction on the map we sometimes would have missed turns

my girlfriend and me use wikiloc and a freedom preserving alternative we would like very much. I use degoogled phone with frdoid, one android and she has an apple device.. :)

**Comment by jpmens** [comment]
>* is it possible to use it for hikes? or will the phone tell the movement to seldomly?

it is, though if set to "move mode" which provides greater precision it might be quite a drain on the battery.

>* does it also record altitudes and speed, at least in the generated movement data?

yes, the data collected on the Android device is enhanced with altitude and velocity

>* is gpx export from the server possible?

our command-line ocat utility can do so, yes.

>* can i load such hikes into the android app (or another app) as we repeat the hikes and without the direction on the map we sometimes would have missed turns

no, that is not possible. The Android app records positions and reports these to a server you provide; it's not the task of our Android app to actually display different routes, hikes.

>my girlfriend and me use wikiloc and a freedom preserving alternative we would like very much. I use degoogled phone with frdoid, one android and she has an apple device.. :)

I'm not familiar with wikiloc, so cannot compare. On Android and iOS our OwnTracks apps are similar in terms of features, and both can be used to send device positions to a central service.

**Comment by deknos** [comment]
Thanks for your answers!

> it is, though if set to "move mode" which provides greater precision it might be quite a drain on the battery.

Why is this the case?

**Comment by jpmens** [comment]
Move mode gets data more frequently from GPS and transfers more locations to the backend, both of which “cost” battery consumption

**Comment by deknos** [comment]
Thanks. i will test that.
