### ISSUE TITLE
Feature reqeuest: Unescape json string before parsing

### ISSUE THREAD

**Issue by Joshy-2010** [owntracks/android#1220]
App Version: 2.4.8; Install Source: Google Play Store; Android Version: 12; Device: Samsung S10

Hello guys, this is not really an issue but more of an "nice to have": I am currently trying to built a diy GPS tracker from an Aithinker A9 GPRS + GPS module, which sends its gps position to the same mqtt broker my owntracks android app is subsribed to. I have managed to manually add data entries in my mqtt broker in the json format of owntracks and I have succesfully been able to show custom gps coordinates as a "friend" in my android app. This is exactly the functionality I need.

Now to the problem: Unfortunate, the A9 GPRS module cannot send the character '**"**' in its mqtt messages, because it is already used to mark the start and the end of parts of the AT command. I can however, send the 2 characters '**\ "**' . 
Meaning, I would a get a text string looking like this: **{\ "_type\ ":\ "location\ ",\ "lat\ "50.9894999,\ "lon\ ":18.1370658,\ "tst\ ":1653862122}**
EDIT: I had to add spaces between \ and ", otherwise github will automatically convert it into "

I know this is not a valid json string, as far as I know it is a specially escaped string meant NOT to be able to be parsed.
There are however, rather easy methods for converting an escaped json string into a normal json string (basically removing all the \ ) which then can be parsed, some methods even do it automatically.

I am currently thinking of different methods how to fix this. I have only limited experience with android studio. Do you think I can recompile a modified application which adds the functionality to unescape the string before parsing it? Can anyone give me a hint there the json decoding part is located in the code

**Comment by jpmens** [comment]
Instead of changing OwnTracks, how about creating a republisher which reformats the data as you need it for your target application?

**Comment by Joshy-2010** [comment]
Oh yeah, I havent thought about that. Clearly much easier. Thanks!
