### ISSUE TITLE
setConfiguration monitoring fails - wrong variable type

### ISSUE THREAD

**Issue by mpsd** [owntracks/android#1221]
* **App build number**: 2.4.8 (20408019)
* **Android version**: 12   
* **Device**: Google Pixel4a
* **Installation source**: Google Play Store

Hi team,

thank you for developing owntracks.

While trying to set "monitoring" mode to "2" via MQTT cmd setConfiguration I'll get the following error on my phone:

`2022-05-30 15:47:13.604 E Preferences: Tried to import monitoring but value is wrong type. Expected: org.owntracks.android.support.MonitoringMode, given `java.lang.Integer``

The MQTT message is (anonymized):

`mosquitto_pub  -m '{"_type":"cmd", "action":"setConfiguration", "configuration": {"_type": "configuration", "monitoring": `2}}'``

The monitoring mode is set to Silent -1 and I'd like to get location updates only when needed. I have tried cmd reportLocation as well, but didn't get any reported data. Thus I'm trying to activate monitoring mode remotely.

Can you please help?

Thanks and best regards
Markus

**Comment by growse** [comment]
Looks like a regression, thanks for picking up.
