### ISSUE TITLE
Import dialog meassages are not translatable

### ISSUE THREAD

**Issue by kri164** [owntracks/android#1227]
On file project/app/src/main/java/org/owntracks/android/ui/preferences/load/LoadActivity.java
at line 188 are some strings, displayed to user, what seems to be untranslatable

    public void showFinishDialog() {
        (new AlertDialog.Builder(this)
                .setTitle("Import successful")
                .setMessage("It is recommended to restart the app to apply all imported values")
                .setPositiveButton("Restart", (dialog, which) -> eventBus.post(new Events.RestartApp()))
                .setNegativeButton("Cancel", (dialog, which) -> finish())).show();
    }

**Comment by growse** [comment]
Good spot, but this alert is actually shortly going away (hopefully in the next version). Shout (re-open this) if you find any more!
