### ISSUE TITLE
F-Droid build fails

### ISSUE THREAD

**Issue by kri164** [owntracks/android#1233]
Look at F-Droid builds, please.
They seems to fails to build.

**Comment by growse** [comment]
Got any details you care to share?

**Comment by growse** [comment]
Oh! I found the log, took a lot of digging:

https://monitor.f-droid.org/builds/log/org.owntracks.android/20409000

**Comment by kri164** [comment]
Im using this app to monitor build status of my fauvorite apps.

https://f-droid.org/en/packages/de.storchp.fdroidbuildstatus/

Thank you


12. června 2022 14:42:35 SELČ, Andrew Rowson ***@***.***> napsal:

**Comment by growse** [comment]
Great tip - shows the log as well so I don't need to go hunting :)

**Comment by kri164** [comment]
The last build batch was successful.
Can close.

**Comment by IzzySoft** [comment]
Now that you're back and up-to-date at F-Droid itself: shall I still keep your app in my repo? Usually I remove apps once they reached F-Droid.org – but I can of course keep apps if there's a need for some reason.

**Comment by IzzySoft** [comment]
OK, going for the default procedure then (removing the app from my repo). Should you for any reason need it re-listed, just drop me a note: it's easily restored.
