### ISSUE TITLE
[Feature Request] Map rotation

### ISSUE THREAD

**Issue by rhysperry111** [owntracks/android#1236]
Hi, currently the map view does not support rotation. This is rather odd, and can make it quite hard to understand where somebody is if the map isn't orientated in the way you expect.

It does seem that osmdroid supports rotation already, so this should be fairly easy to implement, no?

**Comment by growse** [comment]
I added that snippet in after seeing the issue raised. Still some bits to work on, but should be in the next release.

**Comment by rhysperry111** [comment]
Ah cool, thanks :)
