### ISSUE TITLE
MqttConnectOptions.java line 458

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#124]
#### in org.eclipse.paho.client.mqttv3.MqttConnectOptions.validateURI

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5508ca095141dcfd8f2743fd](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5508ca095141dcfd8f2743fd)

**Comment by binarybucks** [comment]
Tracked as https://github.com/owntracks/android/issues/127
