### ISSUE TITLE
0.5.08 crashes

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#125]
as soon as it connects.

**Comment by binarybucks** [comment]
What connect settings have you set?

Sent from my iPhone

On 18 Mar 2015, at 06:36, JP Mens <notifications@github.com> wrote:

as soon as it connects.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/125>.

**Comment by jpmens** [comment]
Well, same as for .06; imported from backup. Hostname, port, TLS, etc. all look sane.

**Comment by jpmens** [comment]
Picked up phone. Opened app. I see locations....

**Comment by binarybucks** [comment]
Weird. Can you send me your config (minus username and pw) please? I'd like
to reproduce it here. The crash report isn't helpful in this case.

On 18 Mar 2015, at 06:50, JP Mens <notifications@github.com> wrote:

Picked up phone. Opened app. I see locations....

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/125#issuecomment-82755457>.
