### ISSUE TITLE
Make map rotation toggleable

### ISSUE THREAD

**Issue by bemdark** [owntracks/android#1266]
The new map rotation feature feels kind of sluggish and I always rotate the map a bit when I just want to zoom in/out. Thus I'd suggest making it toggleable like e.g. like "Show Regions" is toggleable.

**Comment by growse** [comment]
Is this on OSM? I've not noticed a performance difference between Google and OSM on a real device.

Also, the "re-northing" feature in OSM (that you can do in Google by just tapping the compass) is still TODO.

**Comment by bemdark** [comment]
yeah, i just tried the current f-droid version, and zooming in/out is really smooth, as you would expect.
However, when I build the new osm version from git HEAD, zooming in (where you always rotate a little but if you don't move your fingers exactly to a pixel-size) is kind of shuttery (for lack of a better word, I'm not a native english speaker). It's like you are zooming out at 5fps.

**Comment by growse** [comment]
Huh, I tried this on my device just now and get a pretty smoth experience, although it is a newish pixel 6a. So I can appreciate that on other devices the experience might be different.

I think it probably makes sense to have a toggle. Will put something together.
