### ISSUE TITLE
Unable to setup owntracks with mqtt

### ISSUE THREAD

**Issue by felislynx-silae** [owntracks/android#1281]
I've generated certificates for hivemq using your sh script from toolbox and i've got MessageProcessorEndpointMqtt: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found on Pixel 4XL (android 13). Same cert is also not working in ios (iphone 11).

**Comment by jpmens** [comment]
Try [mkcert](https://github.com/FiloSottile/mkcert)

**Comment by felislynx-silae** [comment]
Will try and write results tomorrow

**Comment by felislynx-silae** [comment]
Nope. On Android i've got same exception. On iOS MQQTReasonCode135. In my android projects, when this happens, usually Admins "fix" the cert. To be honest i don't know how :/ And it seams that mkcert/toolboxscript is not generating cert with whole cert path or i'm using them wrong :)

**Comment by ckrey** [comment]
MQTT reason code 135 means “not authorized”

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901079

**Comment by felislynx-silae** [comment]
I've pulled cert using openssl and using it on android works like charm. On iOS after installing this crt file, i've got MQTTReasonCode5. I think i'll have to move to ios repo to ask about ios

**Comment by ckrey** [comment]
MQTT reason code 5 means basically the same: "not authorised"

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718035

**Comment by jpmens** [comment]
@felislynx-silae you are speaking to @ckrey who is our iOS developer.
