### ISSUE TITLE
No Friends on Android HTTP Mode with FDroid build

### ISSUE THREAD

**Issue by TheOneValen** [owntracks/android#1285]
* **App build number**: 20409000
* **Android version**: 12.0.0.134
* **Device**: P30 Pro
* **Installation source**: FDroid (works with Play Store Build)

I use the HTTP Mode on my own server.

I added the following settings to `--load=friends` as mentioned in the documentation.

`user-device1 ["user/device2"]`

But the friends are not shown. Adding `user/device1` also, does not change anything (i.e. does not show self)

**Comment by jpmens** [comment]
As per the documentation of the Recorder, you will likely want two users as friends; the "real" friend, and yourself so that your own position is shown on the map.

```
jane-phone ["john/android", "jane/phone"]
```

Please note there is exactly one space between key (`jane-phone`) and value, and that the value must parse to a JSON array.

Has your `user/device2` actually already published data? Do you  see that in their `rec` file on the server?

**Comment by TheOneValen** [comment]
The friends feature works as advertised if I install owntracks from Google Play Store. It does not work (same configuration) with the FDroid store version.

**Comment by growse** [comment]
Hmm, having difficulty reproducing this one:

![image](https://user-images.githubusercontent.com/378067/188843814-b7ca9036-ef22-43f3-8f85-a18ccc86c33b.png)

![image](https://user-images.githubusercontent.com/378067/188843885-cafba027-d5ec-46c1-acc1-a5c270df1c87.png)

![image](https://user-images.githubusercontent.com/378067/188843955-8818df3a-cbe3-471b-9a2a-8be2b24c4e65.png)

**Comment by RobertoCravallo** [comment]
I also see no friends on my new phone SAMSUM S23 ULTRA. Data is sent to HA and that is shown correctly. My wife's phone has friends, as did my S21 ULTRA.

In the logs I get a: Received incoming message: MessageUnknown on NOKEY. GOOGLE was no help with the NOKEY. :-(

**Comment by growse** [comment]
Can you post your redacted config?

**Comment by RobertoCravallo** [comment]
Gladly, if I knew what that is?

Regards from Germqny....

**Comment by growse** [comment]
"MessageUnknown" means that it can't parse the message that it's receiving from the endpoint.

I'll need to have a look and see if I can reproduce this with HA specifically, as I've not tested with that.

I wonder if HA needs to be configured to send friends to a new deviceId when that changes. Your current `deviceId` is "S23", so I assume it was "S21" on your old device. I believe the OT recorder would need to be explicitly told to send friends to a new device when the id changes, but not sure if the same is true for HA.

**Comment by RobertoCravallo** [comment]
![Einstellungen – Home Assistant 2023-03-13 13-20-21](https://user-images.githubusercontent.com/112649622/224700309-d14a135a-1595-42ee-b64b-258ed72ed014.jpg)

The device S23 is not "found" bei HA. That is my wife's device showing. Can not figure out, how to get HA to even find the device.

**Comment by growse** [comment]
If HA isn't showing it as a device, then that's a smell that the location messages from your device aren't even making it to HA. Have you double-checked the configured URL in OT? What do the HA logs say?

**Comment by RobertoCravallo** [comment]
I just removed OWNTRACKS from HA and reinstalled it. Then I reinstalled the apps on both devices and now everything is working again. 

"Problem" solved!
