### ISSUE TITLE
Pixelated/low-res map most of the time (Wikimedia/OSM)

### ISSUE THREAD

**Issue by qbinary** [owntracks/android#1291]
* **App build number**: 20410000
* **Android version**: Android 12 (LineageOS 19-20220916-NIGHTLY-vayu) without Play Services and with MicroG
* **Device**: Xiaomi POCO X3 PRO
* **Installation source**: F-Droid

On either the Wikimedia and OpenStreetMap the zoom levels update very late which results in a very pixelated and low resolution map most of the time.

**Comment by growse** [comment]
Related to #1223 ?

It seems like when using rasterised tiles (which we do for OSM layers), there's a balance between text size and pixellation / quality. Some people want smoother images, others want bigger fonts. We added a scale factor setting that should allow this to be tweakable.

Can you try fiddling with `osmTileScaleFactor` in the config editor to see if that helps? Values <1.0 should mean less pixellation (but smaller text).
