### ISSUE TITLE
Requiring the app to be manually started on reboots has made it mostly useless for my family

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#1296]
* **App build number**: 2.4.10 (204110048)
* **Android version**: 12
* **Device**: Samsung Galaxy S22 Plus
* **Installation source**: Google Play Store
 
I've been using owntracks for a long time now, and I love it. It's been great for my family. Unfortunately, the update that requires users to start the app before the location is tracked has rendered if effectively useless. I've told everyone to keep an eye out for the notification, and that they need to start the app for it to work, but they get so many damn notifications they never see it and never start the app.

I know this is an Android API thing, and not really an owntracks thing, but I wanted to give the feedback in hopes that there's something that can be done or changed. Or maybe we have to bang on Google's door and tell them to fix the Android API

**Comment by growse** [comment]
There's lots of things that can be done or changed. Unfortunaely, they all require time and effort.

**Comment by kaysond** [comment]
> There's lots of things that can be done or changed. Unfortunaely, they all require time and effort.

Like what? I might be able to contribute something of moderate complexity. It would have a huge benefit for me!

**Comment by jpmens** [comment]
@kaysond if you want to contribute, you could start by browsing through the list of issues to see if there's something you could tackle. Documentation is something we're always looking for, and the Booklet needs a LOT of love.

**Comment by kaysond** [comment]
@jpmens I was thinking specifically of doing whatever is necessary to address the startup behavior wrt to modern android.

**Comment by growse** [comment]
It needs coding (mostly done, because the OSS version available from F-Droid auto-starts), tests written and performed, and most importantly, Google needs convincing that we have a legitimate use for accessing background location, which means we need to fill out a bunch of forms and make them a video: https://support.google.com/googleplay/android-developer/answer/9799150?hl=en-GB.

If you can't wait for that, you might want to look at the OSS version from F-Droid which doesn't have this restriction.

**Comment by kaysond** [comment]
> we need to fill out a bunch of forms and make them a video: https://support.google.com/googleplay/android-developer/answer/9799150?hl=en-GB.

Ugh gross. Come on Google.

Let me start digging through the codebase to get familiar. If you have a sec to point me to the relevant files on the oss/gms side, that would help me get up to speed quicker.

**Comment by growse** [comment]
So, as a to-do list of sorts:

# Manifest permission

This is currently in the OSS manifest only, so would need moving to the main `AndroidManifest.xml`

https://github.com/owntracks/android/blob/59647d5caafd203690813a05b76dd275aecbdb04/project/app/src/oss/AndroidManifest.xml#L7-L8

# Permission request dialog

The current location permission request dialog only asks for `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION`. So this probably needs to be updated in line with the Google guidelines: https://developer.android.com/training/location/permissions#background-dialog-target-android-11

https://github.com/owntracks/android/blob/59647d5caafd203690813a05b76dd275aecbdb04/project/app/src/main/java/org/owntracks/android/ui/map/MapActivity.kt#L248-L293

# Notification re-word

It's still possible for the end-user to grant foreground but not background location, so the notification still needs to exist in that case to notify on startup that there's no permission. But now it probably needs to be re-worded slightly to indicate what's going on and how they can fix it. 

https://github.com/owntracks/android/blob/59647d5caafd203690813a05b76dd275aecbdb04/project/app/src/main/res/values/strings.xml#L17-L18

# Espresso tests

A few of the espresso tests grant `ACCESS_FINE_LOCATION` when certain activities start. Need to think about whether we grant background location on these tests, as well as whether we need extra tests to test behaviour when the user does and doesn't grant access to the background location.
