### ISSUE TITLE
Using OwnTracks android app in the backend for a PWA

### ISSUE THREAD

**Issue by kprohith** [owntracks/android#1305]
How would I go about replacing the front-end of the android app with a webview component that loads a PWA webpage? I also want to know if there is away for me to link a "Start Tracking"/ "Stop Tracking" button on the loaded webpage to start/stop location reporting in the owntracks app?

**Comment by growse** [comment]
As far as I know, it's not possible for a browser-based app to fire an android intent. One way of doing this would be to wire up a URI template to specific OT intents, and then have the web app make requests to those URIs.

It'd need a bit of testing, but in theory this would allow you to effectively send intents to OT from a webpage. 

What the permissions / security model is around this.... I don't know.
