### ISSUE TITLE
OT removed from F-droid?

### ISSUE THREAD

**Issue by kri164** [owntracks/android#1306]
I dont see OwnTrack at F-droid on any on my phones.
Is it removed due authors ignore warning about non-free code?

**Comment by growse** [comment]
See #1298.

**Comment by kri164** [comment]
Hello Andrew,

what Im doing wrong?

Thanks



9. října 2022 19:18:04 SELČ, Andrew Rowson ***@***.***> napsal:

**Comment by jpmens** [comment]
You are not doing anything wrong. Just read the issue are you were linked  to. The app has been pulled from F-droid because it contains non-free source. We are working on getting this resolved, time to resolve is at the moment unknown.

**Comment by kri164** [comment]
I see.

My previous statment "authors ignore warning about non-free code" was completely wrong.
Better to say "too much work and too little time for fix it".

Thank you for bring us this great program and hope you will find solution.

**Comment by growse** [comment]
We've got a plan, and actively working on it. Hopefully will be back in for the next release.

**Comment by mcmikemn** [comment]
How's the progress going? Until you're able to re-factor, is there a way to install Owntracks OSS without FDroid? Can we get an APK?

**Comment by growse** [comment]
Getting there. 

APKs are available on each github release.

**Comment by mcmikemn** [comment]
> Getting there.
> 
> APKs are available on each github release.

Awesome! Thanks.
