### ISSUE TITLE
Send request position

### ISSUE THREAD

**Issue by GianZambo** [owntracks/android#1316]
Hi,
yesterday I installed Owntracks to send position from mobile (android) to my pc with node red > Worldmap.

I'd like to have the opportunity to send a request of position from pc to mobile and get the data.

The command to get the location is {"_type":"cmd","action":"reportLocation"} but I don't understand how to use it into node red.

Can you help me?

**Comment by jpmens** [comment]
Remote commands must be enabled on the device. After that, if you publish an MQTT message with QoS>0 to the topic `owntracks/user/device/cmd` with a payload as you rightly showed of `{"_type":"cmd","action":"reportLocation"}`, the device should report its current location via a normal `_type: location` message.

**Comment by GianZambo** [comment]
Ok, thank you so much ....

**Comment by GianZambo** [comment]
Sorry @jpmens and for HTTP what's the command?

**Comment by jpmens** [comment]
>Sorry @jpmens and for HTTP what's the command?

for HTTP this is very difficult to accomplish, as the client (the app) gets data only when it speaks to your endpoint. When your endpoint gets a position request it can respond with an array of objects which are consumed and processed by the app. However this defeats the purpose of what you want to do: you are interested in telling the app to do something, but via HTTP it is the app that must initiate the conversation.

This was a very verbose way to basically say: "it's not possible to do".

**Comment by GianZambo** [comment]
Ok, thank you again .....

**Comment by GianZambo** [comment]
Hi,
with difficulty (for my skills of course) I connected OwnTracks with MQTT (HiveMQ cloud) to my node red and works fine, but I can't to send a request to position.
IF when I receive data from mobile I have in node red this report ...

![uno](https://user-images.githubusercontent.com/105095607/201516285-8bbf9b7f-19e0-4a2c-a930-dd67ef2e6588.png)

but if I publish an MQTT message with QoS>0 to the topic owntracks/giamma/001/cmd

I have this report ...

![due](https://user-images.githubusercontent.com/105095607/201516402-68a3e98c-52f5-41da-af71-ea45015825b6.png)

Please tell me where is the mistake .....

**Comment by jpmens** [comment]
The message must be published to `owntracks/giamma/001/cmd` with the correct payload. Note: `/cmd` **with** `"_type": "cmd"`

**Comment by GianZambo** [comment]
This is my mqtt node ....

![tre](https://user-images.githubusercontent.com/105095607/201517424-84f1dee8-fcfa-4fcb-bc43-9db1b7ac9d2e.png)

and this is my function node with payload ....

![quattro](https://user-images.githubusercontent.com/105095607/201517448-b0da650c-f4a5-40b9-8eff-ed2a74d1c8a2.png)

It seem right, but evidently I can't see mistake ...

**Comment by GianZambo** [comment]
I also tried ...

const output = [null];

msg.payload =  '{"_type": "cmd", "action": "reportLocation"}'
msg.topic = "owntracks/giamma/001/cmd"

return msg;`
`
but without success ....

**Comment by jpmens** [comment]
Do you have remote commands enabled on the Android device?

**Comment by GianZambo** [comment]
Yes ....

**Comment by GianZambo** [comment]
Well, now works but ....
the app must be in "Significant Changes" and ...
the app must be open .....
I cannot close the app even if se app is always active because at the top of mobile I have the icon's app with the function of Report and changes monitoring mode ....

**Comment by jpmens** [comment]
I confirm that it is not working for me: upon publishing a `reportLocation` request

```console
echo '{"_type":"cmd","cmd":"reportLocation"}' | mosquitto_pub --cafile $cafile -h $h -u $u -P $p -s -q 1 -t owntracks/jpm/s8/cmd
```

I do not see a location response with `”t”: “r”`.

**Comment by growse** [comment]
Smells like a bug.

**Comment by GianZambo** [comment]
Hi, there is news for the resolution of this bug?

**Comment by jpmens** [comment]
It is still pending. As soon as it is addressed, the status of this issue will change.

**Comment by GianZambo** [comment]
ok ....

**Comment by underdog** [comment]
is this issue back?  I'm on iOS, running OT 16.4.1.  seems the app has to be in the foreground to execute a cmd sent to it. I opened the app, went to another app and waited for my cmd to be sent.  saw it sent from my mqtt pub stream, but never say a sub come back from app.  Placed app in foreground, waited for pub to be sent for cmd.  cmd was sent and location was sent back to mqtt feed from OT app.

**Comment by jpmens** [comment]
@underdog this is a closed Android issue, and  you are reporting this for iOS. If you are having trouble please open a new issue on our iOS tracker (github.com/owntracks/ios/issues), but before you do so, iOS behaves differently from Android: make sure you are publishing a QoS>0 payload to /cmd, and if the app is in the background, you'll have to wait until it wakes to process your command.
