### ISSUE TITLE
HardwareRenderer.java line 258

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#132]
#### in android.view.HardwareRenderer.isAvailable

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/550d4ea85141dcfd8f30b20d](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/550d4ea85141dcfd8f30b20d)

**Comment by binarybucks** [comment]
should be fixed in next build
