### ISSUE TITLE
Is Android or OwnTracks enabling WiFi during move mode?

### ISSUE THREAD

**Issue by iarp** [owntracks/android#1336]
* **App build number**: 2.4.10 (20410051)
* **Android version**: 9.0.6
* **Installation source**: Google Play

I'm unsure which system is enabling wifi automatically on me or why. When I head out, I disable wifi as its quite inaccurate and I enabled Move mode. Usually within 20-30 minutes I'll double check notifications and wifi has turned itself back on. Is this owntracks doing?

**Comment by growse** [comment]
Don't think there's anything in OT that's changing the Wifi state. In fact, I don't think it even has this permission.

Do you have android's "turn on wifi automatically" function switched off?

![image](https://user-images.githubusercontent.com/378067/204258506-8dddd2ad-9bf3-448c-9305-29f730c63cc0.png)

**Comment by iarp** [comment]
Ah ha. I did search android settings but for whatever reason that option didn't show up until I turned location services on. It's hidden when it's off on my phone.
