### ISSUE TITLE
No http connection to host which has ipv4 and ipv6 addresses registered @DNS

### ISSUE THREAD

**Issue by 0xbeefbeef** [owntracks/android#1339]
When using URL to homeassistance server API webhook, like
_http://my.server.name:myport/api/webhook/......_,
owntracks tries to connect to following URL (which fails, of course):
_http://my.server.name/resolved_ipv6_address:myport
When deleting the ipv6 dns entry at my ddns service (and disabling ipv6 support on my router), everything works as expected.

This happens only from within owntracks, calling the URL with curl from another computer is working as well.

* **App build number**: 2.4.10 (204110051)
* **Android version**:  13
* **Device**: Pixel 4 XL
* **Installation source**: Google Play Store

**Comment by jpmens** [comment]
If DNS for your server name offers a AAAA record modern operating systems will attempt to use that. If your service is not reachable via IPv6 the connection will likely fail as there’s no fallback. The solution in this case, if you have only IPv4, is to remove the AAAA  record from the DNS.

**Comment by 0xbeefbeef** [comment]
I did, and that resolves the issue. However, I can call the link (the same I used in the owntracks preferences) with curl with no errors. For me it seems that the URL that owntracks tries to connect to is somehow scrambled, because it still contains the servers name followed by the ipv6 address.

**Comment by growse** [comment]
How do you know it's "scrambling" the URL?

What do the logs say?

**Comment by hoopahmadness** [comment]
I believe what beef was saying is that the logs show that the url includes the ipv6 address. I'm seeing the same thing:

```
Caused by: java.net.ConnectException: failed to connect to track.mydomain.com/<myResolvedIPV6>  (port 443) from /<myDeviceIPV6> (port 44794) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
```
I can connect by using the server's ipv4 address and port on my local network, but as soon as I attempt to use DNS it's unable to connect.

**Comment by hoopahmadness** [comment]
Android app version 2.5.0 btw
