### ISSUE TITLE
Not on F-Droid

### ISSUE THREAD

**Issue by kwagnitz** [owntracks/android#1340]
Contrary to the documentation and F-Droid link given, OwnTracks is not on F-Droid.

**Comment by jpmens** [comment]
OwnTracks had to be pulled from F-Droid pending a change documented in https://github.com/owntracks/android/issues/1298

**Comment by kwagnitz** [comment]
The faulty link to F-Droid is still on the code page.
So is this issue closed because you don't intend publishing with F-Droid, or just to reduce the number of open issues?

**Comment by jpmens** [comment]
It’s closed because it’s a duplicate and we’re tracking it in the linked issue

**Comment by kwagnitz** [comment]
OK.  Not trying to be critical.  Its just that the email I got when it was closed says "Closed #1340 as completed.".
Which is not the same as saying its closed because its a duplicate.

**Comment by growse** [comment]
Sure - there's no "closed - dupe" option, so I picked the least worst. It'll definiately be back in the next release, just need to actually do the (not insubstantial) work to actually make that happens.

**Comment by aadityabhatia** [comment]
https://search.f-droid.org/?q=owntracks

>  It looks like F-Droid does not have any apps matching your search string "owntracks"

This issue does not appear to be resolved, while #1298 was fixed (non-FOSS library removed). One depends on the other but are they really duplicates? I suggest re-opening this issue until the desired goal is achieved, i.e. the app appears on the F-Droid.

**Comment by growse** [comment]
No thanks.
