### ISSUE TITLE
Bug: Tapping on friend does not seem to zoom to and center friend on map.

### ISSUE THREAD

**Issue by matt-8319** [owntracks/android#1349]
Hi,

In both the f-droid and play builds, when I select a friend, I am sure it used to zoom to and center the friend on the map. It no longer seems to do this?

Thanks,

**Comment by growse** [comment]
Do you mean on the marker on the map?

Currently, the behiour should be clicking on the friend in the friend list should center the map on that friend:

![friend](https://user-images.githubusercontent.com/378067/208946020-314769ab-4fe5-4644-9782-a4aef224be04.gif)

And clicking the contact on the map itself brings up the small bottom sheet. Long-clicking on the bottom sheet should center the contact on the map:

![friend2](https://user-images.githubusercontent.com/378067/208946163-520e9725-e102-49d9-85cc-75193881739c.gif)

**Comment by matt-8319** [comment]
Clicking on the friend in the friend list does not centre the map for me. However clicking on the bottom sheet of the friend does center the map on the friend marker as expected.

I am running the play build with openstreetmap maps on GrapheneOS.

**Comment by growse** [comment]
Hmmm. That should definitely work. Let me see if I can reproduce it.

**Comment by kri164** [comment]
I reported this bug on august last year as v2.4.10-beta1 report bug #1280.
Not resolved. Observed on android 10, 11, different phone vendors, owntracks-oss flavour.
