### ISSUE TITLE
wrong location recordings

### ISSUE THREAD

**Issue by SlrG** [owntracks/android#1350]
In the last few weeks I started to get wrong location recordings like this extreme one:
![grafik](https://user-images.githubusercontent.com/978967/208990861-b47e3694-abd6-41c7-b162-dd9209813d64.png)

I never was in Sweden in the middle of the night even if owntracks thinks otherwise.

So there are two problems I would like to resolve: 

**First:** the accuracy is shown as 333m, which can't be correct, as I am from Germany and did not leave my home that night. Were there changes on the android side, that cause gps data to be that incorrect? Or is my gps broken, though it seems to work fine most of the time? I have other location detections, that show an accuracy within 100m. But albeit they are closer to my real location they are still off by around 50 to 100 km.  **Edit:** But most of the wrong ones show an accuracy of 331m or 333m. There are to many to not assume it to be a pattern. 

**Second:** I have set ignoreInaccurateLocations to 200 on my phone. Shouldn't the above location have been ignored by the android app and never get uploaded?

* **App build number**: 2.4.10 (20410051)
* **Android version**: Android 13/One UI 5
* **Device**: Samsung S22 Ultra
* **Installation source**: Google Play

**Comment by mar565** [comment]
I encounter similar issues. I regulary visit a specific spot in Berlin despite beeing hunderds of kilometers away.
The log shows this:
`BackgroundService: location result received: LocationResult(lastLocation=Location[network 52.467655,13.492892 hAcc=1000.0 et=+5d2h29m56s922ms {Bundle[EMPTY_PARCEL]}])`

Running OSS 2.4.10 apk.

**Comment by growse** [comment]
> he accuracy is shown as 333m, which can't be correct, as I am from Germany and did not leave my home that night. Were there changes on the android side, that cause gps data to be that incorrect? Or is my gps broken, though it seems to work fine most of the time? I have other location detections, that show an accuracy within 100m. But albeit they are closer to my real location they are still off by around 50 to 100 km. Edit: But most of the wrong ones show an accuracy of 331m or 333m. There are to many to not assume it to be a pattern.

The "333m" value that you're seeing in the frontend is the *altitude*, not the *accuracy* (see https://github.com/owntracks/frontend/blob/aaef18114184a09c958f6ca0f99cad3ac731c1e3/src/components/LDeviceLocationPopup.vue#L23). 

> I have set ignoreInaccurateLocations to 200 on my phone. Shouldn't the above location have been ignored by the android app and never get uploaded?

I'd be interested in digging into what the reported accuracy was for that point. My guess is that it's <200m, but >20m, hinting that it's probably come not from GPS, but from a cell or Wifi database lookup. Wifi BSSIDs are neither unique, nor always stationary, so sometimes the device can be both pretty confident and wrong about its location. Tweaking / lowering `ignoreInaccurateLocations` is the best recipe here. 

In some cases, the device will outright lie about its location and accuracy. If that's the case, not much any application can do about that. :shrug: 

> I encounter similar issues. I regulary visit a specific spot in Berlin despite beeing hunderds of kilometers away.
The log shows this:
BackgroundService: location result received: LocationResult(lastLocation=Location[network 52.467655,13.492892 hAcc=1000.0 et=+5d2h29m56s922ms {Bundle[EMPTY_PARCEL]}])

This has an accuracy (`hAcc`) of 1km, which is definitely not from GPS.

>Also from Germany (Mannheim) and not really happy with his App. For instance: The App shows me in the right spot, but does not update HA, even when I force it. A lot of times it just seems to get "confused" and reports nothing back. Would be really cool if it worked as expected, but I am not relying on the information at this moment.

Not really sure what to do with this, or how it's relevant to the original issue.
