### ISSUE TITLE
OSS version fails when ssl websockets proxied via nginx

### ISSUE THREAD

**Issue by fluxsmith** [owntracks/android#1355]
* **App build number**: 
* 2.4.10 (20410051)
* **Android version**: 
* Fire OS 5.7.0.0 (626549020)
* **Device**: 
* Fire HD 8 (6th Generation)
* **Installation source**: 
Installed from OSS apk

I use a LetsEncrypt wildcard certificate internally, and a cloudflare wildcard certificate externally, it is impractical to obtain per-host or per-service certificates.  IOS version of OwnTracks accepts the wildcard certificate just fine.
(This is an MQTT Websocket connection)

**Comment by growse** [comment]
Hmm, works here with the following mosquitto.conf

```
allow_anonymous false
log_type all
password_file /mosquitto/config/mosquitto.password

listener 1883

listener 8883
cafile /mosquitto/config/rootCA.pem
keyfile /mosquitto/config/key.pem
certfile /mosquitto/config/cert.pem

listener 8080
protocol websockets
cafile /mosquitto/config/rootCA.pem
keyfile /mosquitto/config/key.pem
certfile /mosquitto/config/cert.pem
```

and the attached cert for `*.docker.local` on my emulator:

```
-----BEGIN CERTIFICATE-----
MIID/zCCAmegAwIBAgIQanp1e1/fOPghAvgnDaxlnDANBgkqhkiG9w0BAQsFADBT
MR4wHAYDVQQKExVta2NlcnQgZGV2ZWxvcG1lbnQgQ0ExFDASBgNVBAsMC2dyb3dz
ZUBCVU1QMRswGQYDVQQDDBJta2NlcnQgZ3Jvd3NlQEJVTVAwHhcNMjMwMTA0MTUw
NjU2WhcNMjUwNDA0MTQwNjU2WjA/MScwJQYDVQQKEx5ta2NlcnQgZGV2ZWxvcG1l
bnQgY2VydGlmaWNhdGUxFDASBgNVBAsMC2dyb3dzZUBCVU1QMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAycRa1huGzen9VkxVg+r4vmlTTOoRnFl2KBT2
biP15ed/IfIPkWPzQ6x4m7pF1SsAXRryMPzJiDYggwe0NFDG9siMAw3nYuJhoX3X
9szo2UoWi0cSoVW3knpHqPpgLt3W8DKukw1z+nlERCm4N8cRKSOLsqKVR1KPw/gU
HKXyQJh3Q85JEdstNqNkU/i8LF4puoxptV3pkaacXFiwyek3pHH6pLrSplwTDTlw
GhTE9sM9yXQhps8HR3lk8DLII1R039z8u4K0Me1npbz0zZvyphvJ5JoUAXWhLF+O
YdL3tiPIPkb55l+bmROrGKhMrvXbV6Wmqmaf6F2zL0DLEwneKQIDAQABo2MwYTAO
BgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwHwYDVR0jBBgwFoAU
3dkz+xBq4idv7gg05jtjb2xfTskwGQYDVR0RBBIwEIIOKi5kb2NrZXIubG9jYWww
DQYJKoZIhvcNAQELBQADggGBAJpT7kT1ttrCKPnp9t6o7h+Bz4sHLuAaNjcEWhBD
R0vwhzhCqBJsZcXvV1j/9CZIOTI/TPNEuv97ntJYr9cGKzpqltPeyeBEx1s4DZFo
gxo9D9zcbqbnJ01W3dW562C7FRcU6nak8ES2YpzesG0wqABm7xGLOC3in26GyYv1
Z6v5lVRKbRHfp6YBXbhNNQz0fMXU0cnbVGyr5vdKQwb5hieiL5SWutHSf/wdOzoY
+TAbfp2sF9dVNX38eeeBBYeuTyKJNOUciRe1Uiz/0Ywokfdl/fFYH6bh00jrSGQ3
rzZRWZp5wGFNOi7WSA1VLXCnJ6J0sM+B4u28A/Er/bbTo3o0Q24oVK7CWJsUr059
xK1vJkrDxMM7FWq8yhMFloE7W8YgjUkUnHuWtkkFcx70+MCfgw37xNlCLvEPSCoR
Vdwq0q7QIvx24kxLq9Z0TbgwKFvK8nrFttauPiwoUPjb/Z6MYyvXWvYVgU7x/DZ0
ipr+Bb1Vwhqs69RZO64i4ZHzqw==
-----END CERTIFICATE-----
```

What's your mosquitto config and what error message do you get?

**Comment by fluxsmith** [comment]
My apologies for having misstated the issue.  Your reply prompted me to try connecting on port 8884, and that worked fine with the OSS app.  My Mosquitto is a Home Assistant addon, and while I'm sure I could find the conf file it generates, apparently that isn't the problem.
I'm now thinking the problem is in my nginx config (I need to forward the connection from port 443).  One reason I thought the issue was the wildcard cert is because the error shown in the log includes TLSV1_ALERT_UNRECOGNIZED_NAME.  The ios owntracks app works perfectly with my current config, but the android app fails when going through the proxy.  I'm currently intending to terminate TLS at nginx and forward mqtt to the non-tls port.  In preparing this reply I also gave a crack at forwarding to the tls port, but the error was the same.  My nginx config is:
```
 server {
        server_name mqttws.fluxsmith.com;

        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        server_name mqttws.fluxsmith.com;

        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        ssl_certificate /ssl/fullchain.pem;
        ssl_certificate_key /ssl/privkey.pem;

        ssl_dhparam /data/dhparams.pem;

        listen 443 ssl http2;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        proxy_buffering off;

        location / {
            proxy_pass http://homeassistant.local.hass.io:1884;
            proxy_set_header Host $host;
            proxy_redirect http:// https://;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
```

**Comment by growse** [comment]
Do you see anything useful in the nginx logs? `TLSV1_ALERT_UNRECOGNIZED_NAME` is a boringssl error, which I think comes from within Android itself....

**Comment by fluxsmith** [comment]
Good evening.  I'm not seeing anything in the nginx error log.  In the access log I see only:
172.30.32.1 - - [13/Jan/2023:15:31:42 -0800] "GET /mqtt HTTP/1.1" 101 6 "-" "-"

**Comment by fluxsmith** [comment]
I still can't get Owntracks working on Android.  I've confirmed the same problem exists with the playstore version.  Not only can the ios apps handle my existing config just fine, so can every other mqtt tool I've tried on the Android tablet.  My most recent attempt is the following nginx config.  Everything commented has also been tried:
```
    upstream mqttws.fluxsmith.com {
        server homeassistant.local.hass.io:1884;
    }

    server {
        server_name mqttws.fluxsmith.com;

        listen 80;
        listen [::]:80;
        return 301 https://$host$request_uri;
    }

    server {
        error_log /var/log/nginx/mqttws.error.log debug;
        access_log /var/log/nginx/mqttws.access.log;
        server_name mqttws.fluxsmith.com;

        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        ssl_certificate /ssl/fullchain.pem;
        ssl_certificate_key /ssl/privkey.pem;
#        ssl_dhparam /ssl/ssl-dhparams.pem;

        listen 443 ssl;
        listen [::]:443 ssl;

 #       proxy_buffering off;

        location / {
            proxy_pass http://homeassistant.local.hass.io:1884;
            proxy_http_version 1.1;
#            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#            proxy_set_header X-Real-IP $remote_addr;
#            proxy_set_header X-Forwarded-Host $host;
#            proxy_set_header X-Forwarded-Server $host;
#            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
#            proxy_set_header Sec-Websocket-Protocol "mqtt";
        }
    }
```

**Comment by growse** [comment]
I'm getting this error on your endpoint:
```
Response header: Incorrect upgrade.
```

The only way I can reproduce this error is if I configure nginx to always output a normal HTTP response and ignore the ws upgrade. I notice you've got `$connection_upgrade` set, but there's no definition for what that should be. 

This is my nginx config that works with OT connecting to nginx over TLS, websockets and port 8888 (broker is running with websockets enabled, non tls on 8080):

```
daemon off;
error_log /dev/stdout info;
pid /tmp/nginx.pid;
http{
        access_log /dev/stdout;
        upstream websocket {
                        server localhost:8080;
        }
        server {
                listen 8888 default_server ssl;
                server_name localhost;
                ssl_certificate /mnt/c/Users/andrew/Projects/owntracks-android/util/mqtt-local/_wildcard.docker.local.pem;
                ssl_certificate_key /mnt/c/Users/andrew/Projects/owntracks-android/util/mqtt-local/_wildcard.docker.local-key.pem;
                location / {
                        proxy_pass http://websocket;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                }
        }
}
```

**Comment by kri164** [comment]
Can you try this with caddy reverse proxy?

Config should look like

```
cat /etc/caddy/Caddyfile

https://mqttws.fluxsmith.com {
        reverse_proxy homeassistant.local.hass.io:1884;
}
```

For mqtt websockets on homeassistant.local.hass.io:1884 accesses from client as mqttws.fluxsmith.com:443

Note: Caddy do complete LetsEncrypt certs management by auto.

**Comment by growse** [comment]
Running caddy on 8083 with TLS certs, and configuring OT to TLS MQTT-over-WS to 8083 seems to work fine.

Caddyfile:
```
:8083 { 
    reverse_proxy  mosquitto:8080
    tls /tls/cert.pem /tls/key.pem
}
```

I put the docker compose stack that I used into the repo here: https://github.com/owntracks/android/tree/master/util/mqtt-local

**Comment by fluxsmith** [comment]
I eventually got it working on Fire OS 7.3.2.6.  It still fails on Fire OS 5.7.0.0.  My conclusion is that it is because the LetsEncrypt root CA certificate is not trusted.  Ideally the app would have the same "Allow Untrusted Certificates" option that the IOS app has, but beyond that suggestion, it's not worth pursuing further for this old device.  Thank you for everyone's effort and input.
