### ISSUE TITLE
Geocoder problem shown in notifications 

### ISSUE THREAD

**Issue by grumpazoid** [owntracks/android#1359]
I have been testing on two different phones.

Both phones show geocoder error intermittently in notifications.
"Geocoder Problem An error was received from the geocoder service:java.ioException:edfv:UNAVAILABLE

Also they do not seem to always want to update at the notification interval - we are using significant changed mode. This often leaves the location showing inaccurately for way longer then the notification interval when someone has arrived at a destination.

As a workaround, I am going to try and send a remote command to force an update if no messages are received within the set interval.

Both apps from play store
Version 2.4.10
Samsung S22 and Xiaomi redmi note 11 both running android 13

**Comment by growse** [comment]
Which reverse geocoder are you using?

**Comment by grumpazoid** [comment]
Google

**Comment by growse** [comment]
If the device is saying that the service is unavailable, then.... It's unavailable. Not much else we can do with that.

If you'd rather not see the notifications, you can toggle them off in the preferences.

**Comment by grumpazoid** [comment]
Ok. Thanks for looking. Will disable the notifications.
On the other issue of update frequency, I have been graphing the time between location messages for both phones. While still exceeding the notification interval things improve greatly when moving. I had forgotten to set battery to unrestricted on the Samsung which had an adverse effect. Now much improved on movement.
I have tried my workaround of sending a location command at regular intervals and that works as expected.

**Comment by growse** [comment]
Good to hear it's working better. We've got other users on Samsung devices who are seeing issues with update frequency, so if you get a chance could you add to this issue the exact steps you took to changing the battery setting (screenshots would be a bonus).

Thanks.

**Comment by grumpazoid** [comment]
Setting that work best for me on Samsung Android 13 (I will edit If things change)
Settings Apps Owntacks
Permissions Location Set to Allow only while using the app (Note there is no option for allow always as with some other apps)
Notifications off (see above)
Battery Unrestricted

Fix for location interval not updating when phone has stopped moving - send mqtt request location command at desired interval (I use node red for this)
