### ISSUE TITLE
No enter/leave event on significant move and manual mode

### ISSUE THREAD

**Issue by lsteelandt** [owntracks/android#1384]
* **App build number** : 2.4.10 (20410051)
* **Android version**:  13
* **Device **: Oppo Find X3 neo (CPH2207_11_F.62)
* **Installation source**: Google Play

* **MQTT server** : https://www.hivemq.com

When apps is on "Significant Changes" or "Manual" (Only region transitions published automatically), there is not publication on MQTT of any event transitions when entering or exiting regions. 
I received sometimes event but randomly. 

Is it a fact of android 13 ? A bad configuration ? 

In move mode, there is no problem. 

My configuration below :  

{
  "_type" : "configuration",
  "waypoints" : [ {
    "_type" : "waypoint",
    "desc" : "Home",
    "lat" : 45.62094,
    "lon" : 3.14729,
    "rad" : 20,
    "tst" : 1678574220
  }, {
    "_type" : "waypoint",
    "desc" : "Arrivee1",
    "lat" : 45.620269,
    "lon" : 3.147478,
    "rad" : 25,
    "tst" : 1678616300
  }, {
    "_type" : "waypoint",
    "desc" : "Arrivee2",
    "lat" : 45.621055,
    "lon" : 3.146558,
    "rad" : 15,
    "tst" : 1678616625
  }, {
    "_type" : "waypoint",
    "desc" : "region domicile",
    "lat" : 45.621976,
    "lon" : 3.148315,
    "rad" : 40000,
    "tst" : 1679040606
  } ],
  "_build" : 20410051,
  "autostartOnBoot" : true,
  "cleanSession" : false,
  "clientId" : "oppoLuc",
  "cmd" : true,
  "connectionTimeoutSeconds" : 30,
  "debugLog" : true,
  "deviceId" : "oppoLuc",
  "enableMapRotation" : true,
  "experimentalFeatures" : [ ],
  "fusedRegionDetection" : true,
  "host" : "_xxxxx-hiden-xxxxx._eu.hivemq.cloud",
  "ignoreInaccurateLocations" : 0,
  "ignoreStaleLocations" : 0.0,
  "info" : true,
  "keepalive" : 1200,
  "locatorDisplacement" : 250,
  "locatorInterval" : 600,
  "locatorPriority" : 2,
  "mapLayerStyle" : "GoogleMapDefault",
  "mode" : 0,
  "monitoring" : 0,
  "moveModeLocatorInterval" : 10,
  "mqttProtocolLevel" : 4,
  "notificationEvents" : true,
  "notificationGeocoderErrors" : true,
  "notificationHigherPriority" : false,
  "notificationLocation" : true,
  "opencageApiKey" : "",
  "osmTileScaleFactor" : 1.0,
  "password" : "_xxx-hiden-xxxx_",
  "pegLocatorFastestIntervalToInterval" : false,
  "ping" : 30,
  "port" : 8884,
  "pubExtendedData" : true,
  "pubQos" : 1,
  "pubRetain" : true,
  "pubTopicBase" : "owntracks/%u/%d",
  "remoteConfiguration" : true,
  "reverseGeocodeProvider" : "Device",
  "showRegionsOnMap" : true,
  "sub" : true,
  "subQos" : 2,
  "subTopic" : "owntracks/+/+",
  "theme" : 1,
  "tid" : "LS",
  "tls" : true,
  "tlsCaCrt" : "",
  "tlsClientCrt" : "",
  "tlsClientCrtPassword" : "",
  "username" : "lsteelandt",
  "ws" : true
}

**Comment by growse** [comment]
Hmm. The challenge I have here is that this works great on my device, so I'm suspicious that your device is actually delivering location updates to OT in Significant or Manual mode.

In Significant mode, are you still getting location updates?
