### ISSUE TITLE
Possible to send a "report" / manual update via an intent?

### ISSUE THREAD

**Issue by snakedoctr** [owntracks/android#1408]
Hi,
  I just got intents working with Macrodroid -- it's working great!  Awesome work!

  I did have one question, though.  Is it possible to send a manual report / push a location update immediately via an intent?  If there isn't an intent for that specifically, maybe a mode change to move mode and then back to significant changes or manual would force an update to get pushed?

Thanks for the awesome app and work you do on this project!

**Comment by growse** [comment]
I think you want 'org.owntracks.android.SEND_LOCATION_USER`. Can you try that and see if that works?

We should probably have a short section in the booklet just explaining what intents are available.

**Comment by snakedoctr** [comment]
Bingo -- `org.owntracks.android.SEND_LOCATION_USER` works great!  Thanks so much, growse!
