### ISSUE TITLE
StringifiedJSONObject.java line 116

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#141]
#### in org.owntracks.android.support.StringifiedJSONObject.getStringifiedJSONArray

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5511b8c25141dcfd8f3965da](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5511b8c25141dcfd8f3965da)

**Comment by binarybucks** [comment]
big derp.
