### ISSUE TITLE
TLS encryption with LetsEncrypt Certificate

### ISSUE THREAD

**Issue by timhae** [owntracks/android#1420]
* **App build number**: 2.4.10 (20410051)
* **Android version**: 13 (kernel 5.10.149-android13)
* **Device**: Google Pixel 6a
* **Installation source**: Google Play

Thanks a lot for the app! I encountered an issue when switching from unencrypted traffic to TLS encryption. I have a webserver that has a TLS certificate created by LetsEncrypt. I changed my `mosquitto.conf` to include this certificate:
```
per_listener_settings true
persistence true
log_dest stderr
log_type all
listener 1883
acl_file /nix/store/6wba8c6rbknj92zyj3jifhgxzva2vyd5-mosquitto-acl-0.conf
password_file /var/lib/mosquitto/passwd-0
allow_anonymous false
cafile /var/lib/acme/my.domain/chain.pem
certfile /var/lib/acme/my.domain/cert.pem
keyfile /var/lib/acme/my.domain/key.pem
```
Then I enabled TLS on both devices that I am using (Pixel 6a and iPhone 13 mini). The iPhone is able to establish a connection, the Pixel fails with `failed to reconnect to MQTT broker, failed to connect to my.domain/ipv6::1 (port 1883) from /my-phone-ipv6:port`. In the server log I can sometimes see lines like these:
```
New connection from ip-redacted:17234 on port 1883.
OpenSSL Error[0]: error:0A000416:SSL routines::sslv3 alert certificate unknown
OpenSSL Error[0]: error:0A00010B:SSL routines::wrong version number
```
I tried setting the tls version on the server with `tls_version tlsv1.2` but that gave
```
OpenSSL Error[0]: error:0A000418:SSL routines::tlsv1 alert unknown ca
Client <unknown> disconnected: Protocol error.
```
Any idea what might be wrong here? Thanks for your help!

**Comment by growse** [comment]
The only way I can get a similar message is trying to connect to a TLS-enabled broker from a client that is not using TLS:

`OpenSSL Error[0]: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

Can you double check that you've got TLS enabled, and are connecting on the right port (8883 is typical for TLS-enabled MQTT, 1883 for unencrypted MQTT).

**Comment by timhae** [comment]
Thanks for getting back to me so quick. I was able to connect before enabling TSL on my server, I enabled it by simply including `cafile`, `certfile` and `keyfile` in the `mosquitto.conf` (is there anything else I am missing?). I left the `listener 1883` so I suppose the service is still listening on that port (can confirm with `netstat -tulpen`). I tried enabling and disabling TSL several times, also rebooted my device, is there anything else I can try? How can I confirm it is actually using TLS on the iPhone? It has `mqtts` as protocol for the server so I assume it is using TLS..

**Comment by jpmens** [comment]
As @growse alluded to, using `listener 1883` is quite confusing as this is typically the NON-encrypted port which you would use locally, say, with `mosquitto_sub` to read from your own MQTT broker.

I'd like to reccomend you add an additional listener for port `8883`, which is the TLS port; the config would then look a bit like this (with paths replaced to your files, of course)

```
# -- 1883 ----- Plain
listener 1883 127.0.0.1

# -- 8883 ----- TLS
listener 8883
cafile /etc/ssl/owntracks/fullchain.pem
certfile /etc/ssl/owntracks/cert.pem
keyfile /etc/ssl/owntracks/key.pem
```

After restarting the Mosquitto broker, ensure you can talk to it with `mosquitto_sub` on its plain (i.e. `1883`) port, and then configure your OwnTracks devices to use TLS on port 8883.

**Comment by timhae** [comment]
I have configured mosquitto like this:
```
per_listener_settings true
persistence true
log_dest stderr
log_type all
listener 1883 127.0.0.1
acl_file /nix/store/6wba8c6rbknj92zyj3jifhgxzva2vyd5-mosquitto-acl-0.conf
password_file /var/lib/mosquitto/passwd-0
allow_anonymous false
listener 8883
acl_file /nix/store/w2ng048hghy2j3jmqy828ihspfbhh2kf-mosquitto-acl-1.conf
password_file /var/lib/mosquitto/passwd-1
allow_anonymous false
cafile /var/lib/acme/my.domain/chain.pem
certfile /var/lib/acme/my.domain/cert.pem
keyfile /var/lib/acme/my.domain/key.pem
```
`netstat -tulpen` shows it is listening like this:
```
tcp        0      0 127.0.0.1:1883          0.0.0.0:*               LISTEN      246        1093428    1271683/mosquitto
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      246        1093433    1271683/mosquitto
tcp6       0      0 :::8883                 :::*                    LISTEN      246        1093434    1271683/mosquitto
```
on the server that is hosting the service I can connect with
```
mosquitto_sub --url mqtts://my.domain:8883/owntracks/# -u "me" -P "my pw"
and
mosquitto_sub --url mqtt://localhost:1883/owntracks/# -u "me" -P "my pw"
```
on another machine I try `mosquitto_sub --url mqtts://my.domain:8883/owntracks/# -u "me" -P "my pw"` but that hangs for quite some time and then errors out with `Client null sending CONNECT` and on the server I can see
```
Jun 03 23:50:04 server mosquitto[1271683]: 1685829004: New connection from residential.ip:12039 on port 8883.
Jun 03 23:50:04 server mosquitto[1271683]: 1685829004: OpenSSL Error[0]: error:0A000126:SSL routines::unexpected eof while reading
Jun 03 23:50:04 server mosquitto[1271683]: 1685829004: Client <unknown> disconnected: Protocol error.
```
I am able to resolve the hostname on the other machine just fine with e.g. `host my.domain`. The certificate itself is working for nginx in my browser.. Do you have any other ideas on what I could try?

**Comment by jpmens** [comment]
> on another machine I try `mosquitto_sub --url mqtts://my.domain:8883/owntracks/# -u "me" -P "my pw"` but that hangs 

I'm not sure whether the `--url` requires it, but could you please try adding `--cafile xxx` with `xxx` being the path to the Let's Encrypt CA file which ought to be located on this "other" machine somewhere, or you can copy it in from your `/var/lib/acme/my.domain/chain.pem` from the Mosquitto server.

**Comment by jpmens** [comment]
Does `my.domain` have both an `A` and a `AAAA` record in the DNS? Do you actually have IPv6? If there's a `AAAA` record, applications are going to attempt to use that before falling back to IPv4 and the `A` record, which _might_ explain some of the time for connection initiation.

**Comment by timhae** [comment]
The domain has both ipv4 and ipv6 on that host. When I copy the `chain.pem` from the server that is running mosquitto and nginx with my domain to my local computer and specify it with `--cafile` it works! Thanks a lot! I will try to copy that to my mobile phone and include it in the app. Will I need to update this file everytime the acme bot renews my certificate?

**Comment by timhae** [comment]
Unfortunately, it still doesn't work in the app.. Adding the certificate in my phone as app user certificate doesn't change anything and specifying it in own tracks as ca certificate gives me
```
2023-06-04 12:34:16.056 E MessageProcessorEndpointMqtt: org.owntracks.android.services.MqttConnectionException: java.security.cert.CertificateException: org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
```
I did not try to resolve that error yet but maybe it is something obvious..

**Comment by ckrey** [comment]
If you use well known CAs (e.g. letsencrypt) and not self signed host certificates there is no need to install the CA‘s chain on the mobile devices. Please try again with iPhone and Android and compare the mosquitto log

**Comment by jpmens** [comment]
> Unfortunately, it still doesn't work in the app

I think you're going to have to share configuration or some screenshots with your settings with us. You can do so via email to support@owntracks.org

**Comment by timhae** [comment]
Thanks a lot for your support, I will send an email right away.

**Comment by timhae** [comment]
I have no idea what made the difference but it seems like changing the password in the client and server made it work again.. Before I did not see any connection attempts from the android phone, somehow they started to show up again this morning. Thanks a lot for your time and effort!

**Comment by timhae** [comment]
It seems like the original issue was that my server has a AAAA DNS entry but is actually not reachable by that ipv6, similar to what happened [here](https://github.com/nextcloud/android/issues/7400).
