### ISSUE TITLE
"t" parameter missing when using report-button in notification area

### ISSUE THREAD

**Issue by hoalex** [owntracks/android#143]
Just a minor issue I found: When pressing the report-button in the notification area, no "t" parameter is submitted to the MQTT broker. When pressing the report button inside the app itself, it is correctly set.

```
from notification area: {"_type":"location","lon":"XXX","tid":"YYY","batt":"38","acc":"45.23","tst":"1427310073","lat":"ZZZ"}
from inside the app: {"_type":"location","lon":"XXX","t":"u","batt":"38","tst":"1427310314","tid":"YYY","acc":"15.6","lat":"ZZZ"}
```

Tested using v.0.5.11 on 4.4.4.

**Comment by binarybucks** [comment]
Oh, good catch!
Will be fixed in 0.5.12 due later this week.
