### ISSUE TITLE
Wrong Timestamp Reported

### ISSUE THREAD

**Issue by tobru** [owntracks/android#1431]
* **App build number**: 20410051
* **Android version**: 12
* **Device**: Samsung
* **Installation source**: F-Droid

For unknown reasons, the field `tst` is always way-off. Example payload:

```
{
  "_type": "location",
  "acc": 4,
  "alt": 544,
  "batt": 63,
  "bs": 1,
  "conn": "m",
  "created_at": 1687453740,
  "lat": 47.redacted,
  "lon": 8.redacted,
  "m": 1,
  "t": "p",
  "tid": "gn",
  "tst": 1068138065,
  "vac": 6,
  "vel": 3
}
```

The `created_at` value is correct, as well as `lat` and `lon`. It's just that `tst` is way off, compared to `created_at`.
How can that be?

**Comment by growse** [comment]
I'll double-check, but I think `tst` is simply populated from the timestamp field on the location given to OT by the device. So if the device gives it a location and timestamps it as 10 years ago, that's what OT'll report.

Not heard of this before though, so I'll do some digging.

**Comment by tobru** [comment]
I finally had a chance to upgrade the device to LineageOS 20.0, aka Android 13. And with that, the issue is gone and correct `tst` is reported.
