### ISSUE TITLE
Hostname error

### ISSUE THREAD

**Issue by 78davidcross** [owntracks/android#1438]
Location changes are not being submitted.

Error: HTTP code 503: Unable to resolve host "hooks.nabu.casa". No address associated with hostname.

If the HTTP endpoint has changed in HA for some reason, how do I find out what that now is.  There is no "Configure" option in the HA integration so how do we check\confirm what the settings are??

* **App build number**: 2.4.10
* **Android version**: 13
* **Device**: OnePlus 10 Pro 5G
* **Installation source**: Google Play

**Comment by jpmens** [comment]
that error means DNS was not able to resolve the name into an address; reasons can include inaccurate Android configuration, VPN in use, or simply incorrect hostname.

**Comment by 78davidcross** [comment]
You are correct.

But the app was working fine before the recent update.

This is not an issue with my phone, my DNS, my connections. The error occurs on two devices we own, both on 4G and our home WiFi, and the same error on my geographically separate work WiFi.

And just because it appears to be a name resolution error, doesn't mean that is actually what is going on.

Regards,

David Cross

(Sent whilst mobile)
________________________________

**Comment by growse** [comment]
Last release was 10 months ago, so not sure what you mean by a "recent update":

![image](https://github.com/owntracks/android/assets/378067/fd5c61a3-7cfa-4a33-8739-8c68211326ef)

**Comment by jpmens** [comment]
delete which "instance"? instance of what?

**Comment by jpmens** [comment]
Ah, ignore, I think you said it earlier:

> If the HTTP endpoint has changed in HA for some reason, how do I find out what that now is

I think you'll have to take that up with the folks at the HA project.

**Comment by 78davidcross** [comment]
Thanks.  I've posted a message on the HA Discord to see if others can point me in the right direction.
