### ISSUE TITLE
"conn" key missing when offline and publishing messages

### ISSUE THREAD

**Issue by jules-ch** [owntracks/android#1442]
Step to reproduce:

- Set application to move mode
- Enable Airplane mode
- Disable Airplane Mode
- Messages are missing the `conn` key

When online

```json
{
  "_type": "location",
  "acc": 15,
  "alt": 224,
  "batt": 25,
  "bs": 1,
  "conn": "m",
  "created_at": 1689714607,
  "lat": redacted,
  "lon": redacted,
  "m": 2,
  "tid": "jc",
  "tst": 1689714607,
  "vac": 1,
  "vel": 0
}
```

When sent after being offline

```json

{
  "_type": "location",
  "acc": 16,
  "alt": 224,
  "batt": 25,
  "bs": 1,
  "created_at": 1689714603,
  "lat": redacted,
  "lon": redacted,
  "m": 2,
  "tid": "jc",
  "tst": 1689714601,
  "vac": 1,
  "vel": 0
}
```

* **App build number**: 2.4.10
* **Android version**: 13
* **Device**: Google Pixel 6A
* **Installation source**:  Google Play

**Comment by growse** [comment]
Mmm, smells like a bug. Need to check the booklet, but think it should be there with value `o`?

**Comment by jules-ch** [comment]
https://github.com/owntracks/android/blob/4807e79696645b38ac6112805b8dc665874854dd/project/app/src/main/java/org/owntracks/android/support/DeviceMetricsProvider.kt#L45C34-L54

Seems like it comes from those lines

**Comment by jules-ch** [comment]
Yep looks like a missing else with offline no ?
