### ISSUE TITLE
Zone name configuration

### ISSUE THREAD

**Issue by RobertoCravallo** [owntracks/android#1443]
* **App build number**: 2.4.10
* **Android version**: 13
* **Device**: SAMSUNG S23
* **Installation source**: Google Play

Thank you for this piece of software, it works just fine for me here in Germany. One issue I have, is the name of the zone that the app sends to HOME ASSISTANT. It contains my user name, phone name and location name. I can not figure out how to set this up, so only the location name is sent. I don't want / need the other data, I know that I am pulling the date from my phone.

So instead of "roberts phone S23 - At work" I would like to just receive "At work". Better yet, maybe configure it to say the device name and location. That way I would receive "S23 - At work".

Where or can I even, configure the zone name sent by OWNTRACKS?

Thank you and sorry, if I wasted your time by not finding this info with GOOGLE.

**Comment by jpmens** [comment]
Our apps publish a topic name, and optionally a tracker ID (`tid`) which is a two-letter identifier you can set within the app. The topic name is used as an addressing system in order to identify multiple devices.

I am not familiar with the term "zone name" and I assume this is something **in** home assistant, as you cannot set this in OwnTracks itself.

**Comment by RobertoCravallo** [comment]
Wow, that is some response time!!! I might have figured it out. In HA I need to adjust the customize.yaml and give the waypoint a "friendly name", like so:

zone.roberto_cravallo_s23_test:
  friendly_name: Test   

Now I can name it anyway I want to. Let's see, if this stays that way...  ;-)
![Einstellungen – Home Assistant 2023-07-20 08-48-01](https://github.com/owntracks/android/assets/112649622/9c1b2356-ee06-4169-901a-3dc4649841f7)

Thank you for your quick response.

**Comment by jpmens** [comment]
Glad you got it working!
