### ISSUE TITLE
Google map layers not working

### ISSUE THREAD

**Issue by GP920** [owntracks/android#1460]
* **App build number**:  2.4.11
* **Android version**:   Android 13, One UI 5.1.1
* **Device**:  Samsung Galaxy Z Fold 5
* **Installation source**:  installed from Play Store

The map doesn't load and this error is in the logs:

GoogleMapFragment: Unsupported map layer type OpenStreetMapNormal   

OpenStreetMap layers work and are visible, but Google Maps layers don't work.

**Comment by growse** [comment]
This looks like an API key issue, will fix and push a new version.

**Comment by growse** [comment]
2.4.12 sent to Google for review.

Thanks for raising - please raise more if you see any issues. Google's rushed me into this slightly hacky release to hit an arbitrary deadline, so hyper-aware there may be more things that I've missed.

**Comment by GP920** [comment]
No problem at all! Thanks for the prompt response!
