### ISSUE TITLE
How to copy the coordinates of a friends location?

### ISSUE THREAD

**Issue by nep2ner** [owntracks/android#1465]
* **App build number**: 2.4.12 OSS
* **Android version**: 13
* **Device**: Pixel 6a
* **Installation source**: Github APK

Does there exist a way to copy a friends location so I can paste it into my maps app? I thought this might be behind a long press or short tap on one of the various places coordinates are shown, but I've had no luck.

**Comment by growse** [comment]
Adding a coordinates field to the contact.

![image](https://github.com/owntracks/android/assets/378067/9761d4cd-fa54-4eae-b744-2e08174597a6)

**Comment by jpmens** [comment]
Nice!

**Comment by growse** [comment]
Playing around with a "share" fab. It'd be nice if I could combine the navigate and "share coordinates" into a single button, but need to read up on how to do app-dependent content in a share intent first....

**Comment by growse** [comment]
Here's where we ended up:

![Screenshot_20230906_204806](https://github.com/owntracks/android/assets/378067/d0e8d29c-9848-4c5b-8dbd-f091dc643a80)
