### ISSUE TITLE
Sometimes GPS stays on, after going in background mode (0.5.11, Android 5.0.1)

### ISSUE THREAD

**Issue by juzam** [owntracks/android#147]
I don't know if someone else is seeing this, so I'll report it anyway.

Androind 5.0.1 (nex4) set up with gelocation services in high precision.
Owntracks 0.5.11 setup to be in Balanced power mode in background accuracy and High power mode when in foreground.

Very frequently I'm seeing that the GPS stays on after opening the app and (for example) editing waypoints or just being in foreground. this results in battery drain.

Am I the only one seeing this?

**Comment by binarybucks** [comment]
No, I'm looking into that at the moment.
I cannot really say why that is though.

On Thu, Mar 26, 2015 at 11:43 AM, Giovanni Angoli <notifications@github.com>
wrote:

> I don't know if someone else is seeing this, so I'll report it anyway.
>
> Androind 5.0.1 (nex4) set up with gelocation services in high precision.
> Owntracks 0.5.11 setup to be in Balanced power mode in background accuracy
> and High power mode when in foreground.
>
> Very frequently I'm seeing that the GPS stays on after opening the app and
> (for example) editing waypoints or just being in foreground. this results
> in battery drain.
>
> Am I the only one seeing this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/android/issues/147>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust
