### ISSUE TITLE
HardwareRenderer.java line 258

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#148]
#### in android.view.HardwareRenderer.isAvailable

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/551430805141dcfd8f3ebafd](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/551430805141dcfd8f3ebafd)

**Comment by binarybucks** [comment]
should be fixed in next build
