### ISSUE TITLE
owntracks not loaded after home assistant reboot

### ISSUE THREAD

**Issue by sflichel** [owntracks/android#1495]
Need some help here, as the title states, rebooting home assistant, the integration says not loaded.    It works perfectly fine after I reintegrate and do the necessary url and authentication steps.   shows me on the home assistant map and everything.   Then I reboot and it fails.   what could be the issue?

**Comment by jpmens** [comment]
This is probably a question better asked on the HomeAssistsent end; please see if they’ve an issue tracker where you can ask.

**Comment by sflichel** [comment]
I left one there too, thanks
