### ISSUE TITLE
Issue getting _cmd reportLocation working

### ISSUE THREAD

**Issue by hastyeagle** [owntracks/android#1525]
**App build number:** 2.4.12
**Android version:** 14
**Device:** Google Pixel 7a, 6a
**Installation source:** Github/APK

Hi!  I'm trying to get the `_cmd: reportLocation` working.  I can publish a message to the `owntracks/<user>/<device>/cmd` topic, and I see it when I subscribe to the topic:

> 2023-11-09T18:11:18Z	cmd               	{"_type":"cmd","cmd":"reportLocation"} 00

On the device in the Owntracks logs page I'm seeing `E MessageProcessorEndpointMqtt: message failed validation`.  Remote commands are enabled.  The command I'm running to publish the message is:

>echo '{"_type":"cmd","cmd":"reportLocation"}' | mosquitto_pub --cafile ca.crt --cert owntrack_client.crt --key owntrack_client.key -h \<MQTTIP\> -p \<PORT\> -t 'owntracks/\<USER\>/\<DEVICE\>/cmd' -u \<USERNAME\> -P "\<PASSWORD\>" -q 1 -s

I'm not sure what the `00` is at the end in the message log (it's not in the command I published).  Any ideas where I screwed up?

Thanks!

**Comment by jpmens** [comment]
There’s something wrong with your mosquitto_pub command, IMO. First you’re missing a value for `-h` and for `-p` and second I’d use `-l` (read line) instead of `-s` (send file from stdin).

Other than that the command looks ok to me.

**Comment by snakedoctr** [comment]
Sorry -- I forgot to escape the host and port on the post.  I changed to `-l` and now the `00` is not appearing when I publish the message, but the app is still throwing the `message failed validation` error.

**Comment by jpmens** [comment]
`mosquitto_pub … -s` is adding an additional newline (`\n`) to the payload, whereas `-l` doesn’t.

**Comment by jpmens** [comment]
Could you please humor me and try

```
printf '{"_type":"cmd","cmd":"reportLocation"}' | mosquitto_pub …. -l
```

(use printf i/o echo to avoid the initial newline)

**Comment by snakedoctr** [comment]
Same thing

**Comment by jpmens** [comment]
Is `allowRemoteLocation` enabled (`true`) in your settings? (Use the configuration editor to check/set)

**Comment by snakedoctr** [comment]
hmmm, I'm not seeing `allowRemoteLocation` in the config.

**Comment by jpmens** [comment]
Forgive me for leading you up the garden path: the message needs an `action` and not a `cmd` in it:

```
mosquitto_pub -t owntracks/jpm/s8/cmd -m "$(jo _type=cmd action=reportLocation)" -q 1
```

This should provoke a location publish with `t: r` in it:

```
{"_type":"location","t":"r","tid":"s8","tst":1699562723, ... }
```

**Comment by snakedoctr** [comment]
OK, we're getting farther now!  Now when the app receives the message it says `"[...] Received incoming message: MessageCmd on [...]`.  It's not pushing a location, though.  Could it be related to the `allowRemoteLocation` config option not being present?  I tried adding it, but it said it wasn't a valid key.

**Comment by jpmens** [comment]
That configuration option (allowRemoteLocation) doesn’t exist on android; I’ve amended the documentation. 

Please ensure the device is connected to MQTT; that could be a reason for the missing publish.

**Comment by snakedoctr** [comment]
Gotcha on `allowRemoteLocation` only being on iOS.

The app is definitely connected to MQTT.  It's seeing the MessageCmd come through, and I see it has an updated location.  It's just not publishing the location back to MQTT.

I'm guessing it disregards the `Minimal location displacement` and `Location interval` when it gets the `reportLocation` command?

**Comment by jpmens** [comment]
It ought to just report the last obtained location, but I think we need expert help here now. 

@growse management summary: `cmd` with `action: reportLocation` is coming in, but @snakedoctr's device isn't publishing a location (my S8 does). What are we doing wrong?

**Comment by growse** [comment]
Do you have debug logging enabled? If so, do you see a `On demand location request` debug log entry shortly after the `Received incoming message` message?

**Comment by snakedoctr** [comment]
I do:

> 2023-11-10 10:38:05.049 I MessageProcessor: Received incoming message: MessageCmd on owntracks/user/device
2023-11-10 10:38:05.051 D BackgroundService: On demand location request
2023-11-10 10:38:05.052 D GMSLocationProviderClient: Removing location updates clientcallback=201885842
2023-11-10 10:38:05.052 D GMSLocationProviderClient: Requesting location updates priority=0, interval=null clientCallback=201885842
2023-11-10 10:38:05.053 D GMSLocationProviderClient: transformed location request is Request[PRIORITY_HIGH_ACCURACY requested=3600000ms fastest=600000ms expireIn=60000ms num=1]
2023-11-10 10:38:05.082 D ConnectionPool: BackgroundService On-demand location result received: LocationResult(lastLocation=Location[fused \<LAT\>,\<LON\> hAcc=48.0 et=+0d13h18m30s28ms alt=120.0 vAcc=04.0 vel=0.0 sAcc=2.859375 {Bundle[{satellites=0, maxCn0=0, meanCn0=0}]}])
2023-11-10 10:38:05.155 D GMSLocationProviderClient: GMS Background location update request completed: Success=true Cancelled=false

**Comment by growse** [comment]
Huh. So it's asking for, and receiving a location. The only thing that would prevent a location being published at that point is this conditional:

https://github.com/owntracks/android/blob/47ffad433e6cb91390170a81505a37e8e6627a51/project/app/src/main/java/org/owntracks/android/services/BackgroundService.java#L513-L525

So it looks like the device is giving OT a location that's already been published. Now, this is definitely a bug, because the fact that it's an on-demand location request should override this check - that's been fixed in 2.5.0.

https://github.com/owntracks/android/blob/e99e3226e2e77ce881a93816b65776313eeaab72/project/app/src/main/java/org/owntracks/android/services/BackgroundService.kt#L571-L580

It's only going to get triggered when the device doesn't go and get a fresh location, which is what it should really do with a `PRIORITY_HIGH_ACCURACY` location request.

**Comment by snakedoctr** [comment]
Thanks @growse for fixing this!  Looking forward to v2.5.0.

Thanks @jpmens for the help as well!

**Comment by wir3z** [comment]
Excited to try this as well.  Any ETA on v2.5.0?  Or Beta version that we can sign up for and exercise for you?  :)

**Comment by growse** [comment]
There's a couple of showstopper bugs and at least one feature still to be sorted, but I'm plugging away at them.

**Comment by growse** [comment]
Tentatively closing this as I think the bug's been fixed in the 2.5 beta.

**Comment by hastyeagle** [comment]
Thanks, @growse.  I installed the latest beta and _cmd is now working in non-manual modes.  One thing I noticed is that if manual mode is set, Owntracks will refuse to publish the location due to manual mode being set:

`LocationProcessor: Not publishing location: message suppressed by monitoring settings: manual`

My thinking is that even in manual mode, Owntracks should send the location as requested.  Essentially, it's as if I pushed the "Report Location" button (which works even in manual mode) and I'd expect the location to get published as requested.

**Comment by ckrey** [comment]
@hastyeagle I don’t agree: if the owner of the phone decides to stay quiet or send updates only manually, then nobody else from the outside should be able to query the location.

This is the same in iOS.

**Comment by ckrey** [comment]
@hastyeagle I don’t agree: if the owner of the phone decides to stay quiet or send updates only manually, then nobody else from the outside should be able to query the location.

This is the same in iOS.

**Comment by jpmens** [comment]
Works like we designed it. :-)

**Comment by hastyeagle** [comment]
@ckrey Yea, but there are "manual" and "quiet" modes.  I could see not sending an update in quiet mode, but sending the update in manual mode still makes sense to me.  I'm fine leaving it the way it is, it's just not how I would have thought it would work.

**Comment by podstawski** [comment]
Still does not work in quiet mode :-(
Modes it works in are battery draining....

**Comment by wir3z** [comment]
> Still does not work in quiet mode :-( Modes it works in are battery draining....

It will NEVER work in quiet mode as mentioned above.  What is wrong with manual mode?  That won't send locations until you query the phone or click the report location button.  I don't see how that mode would differ in battery consumption vs quiet mode, unless you have a region that you are in with a very small radius that forces you to bounce in and out of it.

**Comment by podstawski** [comment]
I use mqtt reportLocation and it works neither in quiet nor manual mode. I'm not interested my kid's phone keeps reporting his position unless I want to and send a topic cmd ;)

**Comment by wir3z** [comment]
In that case, you could use significant mode, and just try changing the detection windows:
- monitoring: Significant
- locatorDisplacement: movement in meters
- locatorInterval: time in seconds

Make the displacement 10000 meters and time 3600 seconds or something large.  That should reduce the detection sensitivity and the amount of updates it does which is causing the battery usage.

**Comment by podstawski** [comment]
I did it, but it still is workarround ;)

**Comment by wir3z** [comment]
You would need to check your phone logs to see why it's disconnecting.
