### ISSUE TITLE
setWaypoints command logging a JsonParseException in HTTP mode

### ISSUE THREAD

**Issue by wir3z** [owntracks/android#1527]
* **App build number**: 420412000
* **Android version**: 14 (UP1A.231105.003)
* **Device**: Google Pixel 7
* **Installation source**: Google Play

I'm trying to get the `setWaypoints` command to function.  I created a sample location command:
`{ "_type": "cmd", "action": "setWaypoints", "waypoints": { "_type": "waypoints", "waypoints": { "desc": "Test", "rad": 500, "lon": 12.345, "lat": 56.789, "tst": 1698635212, "_type": "waypoint" } } }`

When sent over HTTP, the app parses the above and adds a region to the list, but is logging an error:

    2023-11-11 09:56:53.003 I MessageProcessorEndpointHttp: Message id=1699721812722-f76742 sent in 276ms
    2023-11-11 09:56:53.003 E MessageProcessorEndpointHttp: JsonParseException HTTP status: 200
    2023-11-11 09:56:53.004 D MessageProcessor: message:HTTP status 200, JsonParseException, 
    2023-11-11 09:56:53.004 D MessageProcessor: onMessageDelivered in MessageProcessor Noop. ThreadID: Thread[networkHandlerThread,5,main]

Also noted that it seems to be keying off the `tst` field not the `desc` field labeled in the documentation.  As long as I keep the `tst` constant, any addition  `setWaypoints` will update that region (but still logs a parsing error).  `tst` is a better choice for unique ID though!

**Comment by jpmens** [comment]
Can't test just now, but please note `_type: waypoints` expects an array of waypoints, so I think your JSON should look like

```json
{
  "_type": "cmd",
  "action": "setWaypoints",
  "waypoints": {
    "_type": "waypoints",
    "waypoints": [
      {
        "desc": "Test",
        "rad": 500,
        "lon": 12.345,
        "lat": 56.789,
        "tst": 1698635212,
        "_type": "waypoint"
      }
    ]
  }
}
```

**Comment by jpmens** [comment]
As to your comment regarding the key, I note we've not documented this for Android. Your quote is specifically labelled as _on iOS_. I only very vaguely recall we did change this at some point in order to be able to rename a waypoint.

@ckrey and @growse: I please need your input here do possibly amend the docs: what is the _key_ for a waypoint in the `setWaypoints` command?

**Comment by wir3z** [comment]
I've tried it framed as any array, and same deal.  Just to double check, I copied the waypoint block from a publish waypoints as well as the a configuration export, and same error.  Processes the JSON fine, loads/modifies the waypoints as expected, just logs the parse exception.

On Android, `TST` seems to be the key, which is working great.  I was wanting to be able to automates a single edit location, and then push those to the other "friends" which is working -- just the parser error.

**Comment by jpmens** [comment]
On Android there's a primary key which isn't surfaced to the API, and `tst` is a uniquely-constrained value which effectively acts like a key.

**Comment by wir3z** [comment]
Found root cause of this one.  Classic "issue between keyboard and chair".  When you send an array of waypoints to the app, the app echo's back each one that it processed.

The "exception" was me not returning an empty JSON array of [] so that was showing up as invalid in the JSON parser.
