### ISSUE TITLE
owntracks doesn't have location permission "allow all the time"

### ISSUE THREAD

**Issue by tve** [owntracks/android#1585]
* **App build number**: 2.4.12 installed from Google Play (would much prefer F-Droid!)
* **Android version**: Android 14, degoogled version of AOSP, CalyxOS to be specific
* **Device**: Pixel 7

I've been having zero luck with the owntracks app. I just doesn't track me unless I have it open and am staring at the map live. One thing I noticed is that other apps on my phone have the location permission "all the time" while owntracks has it only "while in use":
![Screenshot_20240124-174406](https://github.com/owntracks/android/assets/39480/9df2189d-27f9-47f1-a8c0-0e46eb9dcd67)
![Screenshot_20240124-174420](https://github.com/owntracks/android/assets/39480/606be23a-8563-484e-824f-f51333427184)

As you can see, I don't have the options to give owntracks location permission "all the time":
![Screenshot_20240124-174437](https://github.com/owntracks/android/assets/39480/a92d6c1a-3284-4b87-9c53-e36b44fb5720)

I'm not sure of the ramifications, but it seems suboptimal.

**Comment by growse** [comment]
There's been a few issues raised about this.

In short:
* Current version doesn't need it (it uses a Foreground Service, which doesn't need background location)
* Actually becomes an issue at reboot, where user interaction is required to get full location resolution
* Will become an option to enable in the next version, which should mean interaction-free location tracking continues across reboots, and may (?) better locations on certain devices.

>  just doesn't track me unless I have it open and am staring at the map live. One thing I noticed is that other apps on my phone have the location permission "all the time"

Does it publish locations when the activity is closed in move mode? I've not tested on CalyxOS so don't know how their location provider behaves.

**Comment by tve** [comment]
I have the app in move mode and it's been sitting on my desk and mostly clocking in the updates. Except between 6:27 UTC and 8:35 UTC it only reported two times. The HTTP POSTs also have that gap. The phone must have been laying here untouched, weird.
The reboot issue has caught me a couple of times...

**Comment by growse** [comment]
When you select move mode, OT requests the highest priority, most energy-hungry type of location updates, which should kick in an active GPS search. Should be the same as opening a maps application in the foreground and getting an instant location that way.

If you're not seeing that, then your device isn't delivering locations to OT in response to its request. 

If you get a chance, there's one other thing you can try: if you put the device in move mode and don't observe a location arriving every `moveModeLocatorInterval` seconds, leave it a bit, and then open up a different mapping application (e.g. Google maps, or Organic maps). Does that now trigger OT to send a location update?
