### ISSUE TITLE
Fully reset configuration when changing mode and/or host/port

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#1598]
As briefly discussed internally, I suggest an enhancement which will reset our apps' configuration and internal database on change of host/port for a particular mode or on change of  mode (iOS does the latter already).

The reasoning is that if I'm hosted on a particular broker but change to a different friend's broker, say, there's no reason to keep a list of locations I've received in the past, nor is there a reason to see prior friends, as they'll likely not be on the  new broker / server.

In particular we should wipe:

- current list of friends (contacts received)
- accumulated and not yet transmitted locations (which might even be destined for an incorrect topic)

Tracked on iOS at https://github.com/owntracks/ios/issues/771

**Comment by jpmens** [comment]
Additional ground [for a wipe](https://github.com/owntracks/ios/issues/771#issuecomment-1925686773)

**Comment by growse** [comment]
There's currently no code that wipes the outstanding queue, so that'll take some thought. Clearing the contacts should be straightforward.
