### ISSUE TITLE
Russian translation (2.5.0)

### ISSUE THREAD

**Issue by Allineer** [owntracks/android#1603]
Hello!

An invitation from POEditor has been received, but.
Can I ask for apk with strings that need to be translated?

**Comment by growse** [comment]
Hi! Not quite sure what you're asking - can you not see the strings on POEditor?

**Comment by Allineer** [comment]
I see the strings in POEditor, but I want to see them in the application before and for translating.
As far as I understand, they are not from 2.4.12 release.

**Comment by growse** [comment]
Oh! I see what you mean. Understood.

In theory, the annotations on POEditor should be enough context, but they're woefully incomplete at the moment.

I'll bob a build on this issue when I next get near an actual computer.

**Comment by growse** [comment]
grr, can't attach an apk here. Hang on

**Comment by growse** [comment]
[app-oss.debug.zip](https://github.com/owntracks/android/files/14185626/app-oss.debug.zip)
 Obviously i can attach a zip file.

**Comment by Allineer** [comment]
Thanks!

**Comment by Allineer** [comment]
title_activity_contacts => Friends
contactsListPlaceholder => No contacts found

So, we have a friends or contacts in the app?

**Comment by jpmens** [comment]
Friends are the people who share an MQTT broker and may see eachother. The term "Contacts" is sometimes used in the Android app (though I must say I dislike that as for me it implies "contacts as in my address book", which is not the case.).

Generally these are "Friends".

**Comment by Allineer** [comment]
Мне тоже кажется, что это разные вещи - в приложении у нас не просто контакты, а близкие люди.

**Comment by jpmens** [comment]
Unless @growse corrects me, there are only "Friends" -- that's the OwnTracks terminology.

**Comment by growse** [comment]
Yeah, we use "contacts" internally to the labels and class names, but the user facing experience is "friends".

(I think this is historical)

**Comment by Allineer** [comment]
Can we split deleteWaypointTitle to deleteWaypointDialogTitle & deleteWaypointButtonText?

**Comment by Allineer** [comment]
@growse, can I ask for the new apk to check the translation before new version released?

**Comment by growse** [comment]
Should be able to check in the beta when we get there. Beta -> release is where I expect small things to be fixed.

Alternatively, you can grab the oss APK from a recent successful build on master, e.g. https://github.com/owntracks/android/actions/runs/7847453148

**Comment by Allineer** [comment]
WOW, I didn't know about the artifacts. The question is closed. Thank you!
