### ISSUE TITLE
"Tap here to request notification permission" in 2.5.0 not working

### ISSUE THREAD

**Issue by Allineer** [owntracks/android#1604]
"Tap here to request notification permission" in 2.5.0 with pink icon are not working - nothing happened on tapping.

Or am I too early? :)

* **App build number**: 2.5.0 with pink icon
* **Android version**:  11 RKQ1.200826.002 / MIUI 12.5.1 Global stable
* **Device**: Xiaomi mi9se
* **Installation source**: APK from #1603

**Comment by growse** [comment]
Is this in the welcome activity? Or the dialog on the map?

**Comment by Allineer** [comment]
Settings > Notifications activity on top of three switches.
In the welcome activity I don't see this at all.

**Comment by growse** [comment]
Oh, you shouldn't be seeing that at all unless you're on Android >=14.

Will investigate.

**Comment by growse** [comment]
Ok, I got somewhere. Whether or not that banner is displayed depends on the result of `NotificationManagerCompat.from(context).areNotificationsEnabled()`. I'd assumed that'd only return false on API>34 when permissions haven't been granted yet, but you can also get it to return false by just turning off notifications for an app.

![image](https://github.com/owntracks/android/assets/378067/398d1aec-5714-451b-9aae-7b925b9daef9)

Good bug! Will fix.
