### ISSUE TITLE
No map visible on new install

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#1609]
Occurrs with latest version on hardware (Samsung S8) and on emulator (Pixel 7) with all Google maps

![rabbit-10704](https://github.com/owntracks/android/assets/60706/9fd26a24-6ff8-44c7-bae7-42219ef39bf0)

Switching to OpenStreetmap reveals the map.

![rabbit-10705](https://github.com/owntracks/android/assets/60706/f538f000-a9bb-4649-a959-bfb52ea12588)

**Comment by jpmens** [comment]
Likewise on simulator Android 14.0 / 34

**Comment by growse** [comment]
Google maps needs an API key, which you don't get out of the box with the source code.

Probably should patch the contributing docs to make that a little more explicit.

**Comment by jpmens** [comment]
I thought I experienced the issue with Play Store version, but after doing a fresh install on S8 I cannot reproduce it.

Closing.
