### ISSUE TITLE
[Feature Request] Support multiple groups of friends using one MQTT server

### ISSUE THREAD

**Issue by qingz2004** [owntracks/android#1610]
I think it is a very useful feature to have a single server work for multiple friend groups and family, since my family doesn't need to know where my friends are, and my friends from different groups don't need to see each other's locations.

**Comment by jpmens** [comment]
This is something you ought to be able to configure MQTT-broker-side with ACLs.

**Comment by qingz2004** [comment]
Will try.
Thanks!
