### ISSUE TITLE
Return blank location packet for ping/manual location even though there is no location or accuracy is poor

### ISSUE THREAD

**Issue by wir3z** [owntracks/android#1619]
On occasions when a device has been stale for a while, it will generate a "no location", and the app will not send data to the host.  Also, as per design, the app does not send data if the location accuracy is below the locatorDisplacement value.

For remote management, having the ability to send back configurations should one set a bad locatorDisplacement value, or general keep alive message is desirable if in a location of poor accuracy.

I had forked a version and for only the "ping" and "manual" locations, sent out a tst=0 for these messages and filtered them on the incoming host.   Not sure how that would impact other integrations, or perhaps using invalid coordinates is a better approach?

This allows a heartbeat to be detected at the host side, regardless of the state of the phone.  The host could then initiate a remote restart of the locations are stale to correct the issue.

**Comment by jpmens** [comment]
No locations respectively suppression on bad accuracy is per design or per configuration. Reporting location with incorrect data seems counterproductive to me.

**Comment by ckrey** [comment]
If you want to sent a "nolocation" message, send a message with {"_type":"nolocation"}. This should be transparent to other integrations

**Comment by wir3z** [comment]
> No locations respectively suppression on bad accuracy is per design or per configuration. Reporting location with incorrect data seems counterproductive to me.

What this addresses is the ability for the app to pull back configurations are indicate that it is still alive.  The ping message is create, but it gets suppressed if the phone is misconfigured or gets bunged up.  In 2.4.12, the app will eventually stale out and get stuck with "no locations" in the log and never call home.  If it did report something, you could send back a restart command to address this.

**Comment by growse** [comment]
> In 2.4.12, the app will eventually stale out and get stuck with "no locations" in the log and never call home. If it did report something, you could send back a restart command to address this.

I'd want to wait and see how upcoming 2.5 behaves. The location reporting should hopefully become more reliable.

**Comment by wir3z** [comment]
I'm patiently waiting for this one!  I've seen a ton of improvement changes in the commits.

**Comment by wir3z** [comment]
Closing this one.  Fixes in the 2.5.x version around the locator + ability for high accuracy on ping mostly fixes/eliminates this need.
