### ISSUE TITLE
Secure connection failing with "Could not validate certificate: null" on Android

### ISSUE THREAD

**Issue by rkoshak** [owntracks/android#165]
Android  running on a Moto X
OwnTracks 0.5.11
Using a self-signed CA and the custom certificate path (though I tested by importing the CA to the phones trusted store and got the same error).

I've been using OwnTracks beta for a few weeks now without any trouble until early this morning when it stopped being able to connect. I've not change anything in the configuration on either the phone or the server. The error reported in the app is:

"com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null"

On the server side running Mosquitto it logs:

New connection from 123.45.67.89 on port 8883.
Socket error on client <unknown>, disconnecting.

This didn't seem to be the same as Issue #94 and I couldn't find any other issues that looked similar.

Thanks

Rich

**Comment by binarybucks** [comment]
Haven't seen that one before either. If it worked correctly without changing anything it is unlikely a bug in the app. 

- Can you check if time is in sync between server and your device? Time drift or timezone foo often interferes with certificate setups.
- Is your certificate still valid?

**Comment by rkoshak** [comment]
Looks like its my bad. I thought I created the cert to not expire until
2016 but double checking it shows it expired at 4am this morning.

Thanks for pointing me in the right direction and I thank your for your
time.

On a related note, is this something that OwnTracks can detect and provide
a more informative error message?


Rich Koshak

**Comment by srilakshmimalla** [comment]
Hi Rich Koshak 

How did you create the certificate? where it has to be updated. My certificate expired as well. But i am not sure what this certificate and where it has to be updated. 

Thanks
Srilakshmi

**Comment by rkoshak** [comment]
http://www.steves-internet-guide.com/mosquitto-tls/

**Comment by srilakshmimalla** [comment]
Hi Rich Koshak

I have a android game app which is not working now. It says "com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: certificate is expired. We have never created a certificate before. Is it something which has to be updated in server end once created? 

Thanks
Sri

**Comment by binarybucks** [comment]
This issue tracker is for Owntracks releated issues and not a forum for general problems regarding TLS certificates. The folks over at Stackoverflow/[SuperUser ](https://superuser.com/) will be happy to help you.
