### ISSUE TITLE
pubExtendedData  / extendedData config setting

### ISSUE THREAD

**Issue by ckrey** [owntracks/android#1654]
In the iOS app and in the booklet, the setting is called `extendedData`. In the Android app the setting is called `pubExtendedData`. 

https://owntracks.org/booklet/tech/json/#_typeconfiguration

**Comment by jpmens** [comment]
Thanks for finding that, @ckrey!! I was wondering why that person had a problem with Quicksetup-configured Android device and wasn't seeing battery level. (I'd not specifically tested that.)

https://github.com/owntracks/quicksetup/blob/3afb9f43e9e70b9d06bacf1f0bc27d747e4c2cd1/files/otrc.j2#L11

**Comment by growse** [comment]
I need to work out how to support both for backwards compatibility.
