### ISSUE TITLE
BeaconParser.java line 217

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#166]
#### in org.altbeacon.beacon.BeaconParser.setBeaconLayout

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5526a8da5141dcfd8f6504bd](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/5526a8da5141dcfd8f6504bd)

**Comment by binarybucks** [comment]
postponed until beacon code is fixed
