### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by wir3z** [owntracks/android#1673]
For an automation integration I created, having the geocoded address returned with the location packet would be outstanding since it was already decoded 'for free' from Android.

I had stitched that into the v2.4.12 version, but the codebase has deviated from that to it's current tip.  For v2.4.12, I had added:
        // capture the address and pass the the locationProcessor
        if (this.lastLocationMessage != null) {
            locationProcessor.lastAddress = this.lastLocationMessage.getGeocode();
        }

To the 'BackgroundService.java' file and then attached 'lastAddress' to the outgoing JSON packet.  I'd like to do a PR for this feature, but not sure where this functionality resides now.

Thanks!

**Comment by jpmens** [comment]
> having the geocoded address returned with the location packet would be outstanding since it was already decoded 'for free' from Android.

It may or may not be 'for free', but it's rate-limited so there's not guarantee of having an address. This [has been previously discussed for iOS](https://github.com/owntracks/ios/issues/769).

When using OpenCage with an API key which permits more queries than the free tier does this would not be a problem on Android, but I don't think many people do so.

**Comment by wir3z** [comment]
Understood.  Currently my "backup" was for the app that receives the locations from OwnTrack to allow the user to use a Google, Opencage or Geoapify geocode key.  The issue is not all people are comfortable signing up for the keys (reasons unknown).

For the most part, I've found that as long as the OwnTracks app is configured to report locations in a reasonable interval, it has been robust in returning a valid location on each location update.  It would failover to a lat/lon which was deemed acceptable in the rate limiting cases.
