### ISSUE TITLE
OwnTracks reporting old location to server

### ISSUE THREAD

**Issue by libreivan** [owntracks/android#1675]
* **App build number**: 420412000
* **Android version**: 14 (Graphene OS, no gms)
* **Device**: Google Pixel 7a
* **Installation source**: GitHub (APK)

Hello! I am using OwnTracks 2.4.12 (OSS) to share my real-time location. But, even though it correctly detects where I am, as the blue dot is exactly where it's supposed to be, the location information sent to the server seems to be in this place I was months ago.

I tried everything. I honestly, don't know what to do about it, and logs look just fine to me.

**Comment by jpmens** [comment]
> and logs look just fine to me

They might look fine to you, but not to us. ;-)

Seriously. Send us the logs please, together with a publish you get when you press up-arrow to publish the current location. Kindly do not redact data other than passwords; we will treat your data carefully. Send by email to support@owntracks.org and mention this issue number please.

If you want us to look, that is.

**Comment by libreivan** [comment]
Done! And thanks for the quick response. :)

**Comment by libreivan** [comment]
Well, my location was accurately being depicted by the blue dot, it's just that the data sent to the server seems always to be that same spot. Also, I had internet data available, so it's sadly not that. :(

**Comment by libreivan** [comment]
Hey, contributors. I know this issue is kind of dead, but I just realized this might have something to do with the fact that I am using the HomeAssistant integration. Is this a known issue?

**Comment by compuguy** [comment]
> Hey, contributors. I know this issue is kind of dead, but I just realized this might have something to do with the fact that I am using the HomeAssistant integration. Is this a known issue?

Out of curiosity are you sending your location directly to home Assistant or mirroring another MQTT server to Home Assistant?

**Comment by libreivan** [comment]
> > Hey, contributors. I know this issue is kind of dead, but I just realized this might have something to do with the fact that I am using the HomeAssistant integration. Is this a known issue?
> 
> Out of curiosity are you sending your location directly to home Assistant or mirroring another MQTT server to Home Assistant?

Hello! I'm directly to home assistant with the OwnTracks integration. 🙂

**Comment by wir3z** [comment]
@libreivan Shouldn't matter what the endpoint the data is sent to (Home Assistant or otherwise).  The app just bundles the data and sends it into the "ether".

Have you tried the new 2.5.0-Beta2?  There was a lot of fixes around location bugs that may have this addressed.
