### ISSUE TITLE
[Feature Request] Switch mode based on charging or battery

### ISSUE THREAD

**Issue by mikedolx** [owntracks/android#1690]
Hi,

as got my own tracks finally working 😁 I'd kindly like to request a feature.
I would like to be able to switch mode, depending if the phone is connected to a charger, or running on battery.

For example, when I'm in the car, I usually connect the charger. I also switch the mode to movement, due to the "higher velocity" of the vehicle.
Because I usually forget to switch back to minimal or significant change, my battery drains quite fast.

Is this already possible to implement with the current  version of owntracks? 

Thanks and BR,
Michael;

**Comment by growse** [comment]
We usually recommend Tasker or some other device orchestration app for this type of thing. I'm not sure I want to re-invent a rules engine within OT itself.

**Comment by jpmens** [comment]
Tasker is protocol un-specific; ask your local search engine for examples

**Comment by growse** [comment]
Booklet has a section here: https://owntracks.org/booklet/features/android/#automation-via-tasker-automagic-etc
