### ISSUE TITLE
Way point circles do not appear on the map

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#1691]
With the latest beta release (which is amazing! Yay background location permissions!) I'm not seeing my way points drawn on the map no matter where or how big they are. 

* **App build number**: 2.5.0 420500002
* **Android version**: 14
* **Device**: Samsung Galaxy S22+
* **Installation source**: Play Store

**Comment by compuguy** [comment]
They don't show up for me either on 2.5.0 Beta 2.

**Comment by wir3z** [comment]
Are you seeing pins at all?  I have the waypoints showing in regions, but no pins or circles.

**Comment by growse** [comment]
It's a bug down to the fact that the Map fragment subscribes to waypoint updates from the repo, but fails to collect the initial set of waypoints on init.

**Comment by compuguy** [comment]
> Are you seeing pins at all?  I have the waypoints showing in regions, but no pins or circles.

I'm not seeing waypoints either. Sometimes the friends tab doesn't list other clients. Also the locations I see of other clients/people are out of date by several days.

**Comment by wir3z** [comment]
> > Are you seeing pins at all?  I have the waypoints showing in regions, but no pins or circles.
> 
> I'm not seeing waypoints either. Sometimes the friends tab doesn't list other clients. Also the locations I see of other clients/people are out of date by several days.

Are you using Beta2 or Beta1?  Beta1 had a bug where it could timeout sending data and not report for a long time.  I haven't seen any issues with the Friends tab on Beta2.  Only the map missing regions/pins.
