### ISSUE TITLE
TLS connection doesn't work - SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by mwildbolz** [owntracks/android#1694]
Since the last updates (also with Beta2) I'm not able to connect via TLS to my mosquitto broker any more.
Owntracks just says "**TLS Error: MqttException**", owntracks log:
```
2024-04-27 23:48:47.130 I [DefaultDispatcher-worker-4] MQTTReconnectWorker: MQTT reconnect worker job started
2024-04-27 23:48:47.241 I [DefaultDispatcher-worker-4] MQTTMessageProcessorEndpoint$connectToBroker: Connecting to ssl://xxyy.ddns.net:8884?# timeout = 30s
2024-04-27 23:48:47.536 E [DefaultDispatcher-worker-4] MQTTMessageProcessorEndpoint$connectToBroker: MQTT client unable to connect to endpoint
MqttException (0) - javax.net.ssl.SSLPeerUnverifiedException: Host: xxyy.ddns.net, Peer Host: xxyy.ddns.net
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host: xxyy.ddns.net, Peer Host: xxyy.ddns.net
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(Unknown Source:143)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:75)
	... 6 more

2024-04-27 23:48:47.536 I [DefaultDispatcher-worker-4] MQTTReconnectWorker: MQTT reconnect worker job completed, status Retry
```
On the broker side I see the following log entry:
```
1714254527: New connection from 212.197.138.213:47906 on port 8883.
1714254527: Client <unknown> closed its connection.
```

Certificates were generated using instructions from [this site](http://www.steves-internet-guide.com/mosquitto-tls/)
TLS connection to the broker in principle works - mosquitto_sub, paho (python) mqtt client and also MQTT-Explorer are able to connect using the installed CA certificate (with validation turned on).

I don't have an idea where to look further. Debug Log switched on on owntracks side does not bring more information.
Debug logging on broker side is also not more verbose during the connection attempt.
CA certificate is installed inside Android

* **App build number**: 2.5.0 (420500002)
* **Android version**: 14
* **Device**: Samsung Galaxy A34
* **Installation source**: Google Play

**Comment by growse** [comment]
Did you install the CA certificate in the device CA cert store?

**Comment by mwildbolz** [comment]
Yes, I did. I also tried with another certificate and there the error was clearly a not accepted certificate.

**Comment by growse** [comment]
Can you either post or mail us your CA cert and endpoint so i can test?

**Comment by jpmens** [comment]
@mwildbolz our email address is support@owntracks.org

**Comment by mwildbolz** [comment]
> @mwildbolz our email address is [support@owntracks.org](mailto:support@owntracks.org)

Mail sent - thanks in advance!

**Comment by growse** [comment]
Got it.

The certificate presented by your endpoint is missing a X509v3 Subject Alternative Name, or SAN. OT (and the rest of the modern web) doesn't validate names against CN any more - your hostname that you want to connect to needs to be present as a SAN field. Example from https://owntracks.org cert:

```
$ openssl x509 -in owntracks.org.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
...
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                58:C9:B2:AA:68:E6:A5:48:CC:D8:2B:E8:42:B2:BF:7F:BE:45:66:68
            X509v3 Authority Key Identifier:
                14:2E:B3:17:B7:58:56:CB:AE:50:09:40:E6:1F:AF:9D:8B:14:C2:C6
            Authority Information Access:
                OCSP - URI:http://r3.o.lencr.org
                CA Issuers - URI:http://r3.i.lencr.org/
            X509v3 Subject Alternative Name:
                DNS:owntracks.org
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
```

Suggest you use a tool like [mkcert](https://github.com/FiloSottile/mkcert) for generating modern self-signed CA certs, or delegate it to a real CA like Letsencrypt.

**Comment by mwildbolz** [comment]
Thanks, sounds promising.
I already tried adding the SAN information into the certificate before, but maybe there was an error doing this with my openssl commands. I'll give a short notice after trying again!

Just one thing to mention:
Would be fine, if one could get this information out of the logs (at least in DEBUG mode), maybe there is a way to implement logging in this area.

Thanks a lot!

**Comment by Tarpon907** [comment]
I've spent the last day and a half trying to figure this out before finding this thread.

Can you please update the booklet to say that this is required?  It doesn't, currently.  In addition, your x509 certificate sample does not have an SAN.

**Comment by jpmens** [comment]
IIRC Chrome began requiring names in SAN instead of CN already seven years ago, and as @growse rightly said above

> and the rest of the modern web) doesn't validate names against CN any more

Whether or not Mosquitto works fine or doesn't isn't the issue.

This [sentence pretty much covers it](https://support.dnsimple.com/articles/what-is-ssl-san/):

> From a technical standpoint, every certificate issued today is effectively a SAN certificate, as the CA/B forum requires the certification authority to add the content of the common name to the SAN as well. Even if the certificate covers a single name, it will still use the SAN extension and include that single name.

Note the word **requires**.

That said, if you would give us an idea of how and where you'd think this should be documented, possibly even with a PR for the Booklet, I'll gladly see to its inclusion.

**Comment by growse** [comment]
> I've spent the last day and a half trying to figure this out before finding this thread.
> 
> Can you please update the booklet to say that this is required?  It doesn't, currently.
> 
> Mosquitto works fine without a SAN in the CA certificate when instances talk to each other for bridging, as does MQTT Explorer.  It's an unexpected and undocumented requirement when adding Own Tracks into the mix.
> 

The behaviour is documented in [RFC9525](https://www.rfc-editor.org/rfc/rfc9525#appendix-A-2.2). We try to follow the IETF standards.

**Comment by Tarpon907** [comment]
Considering that the TLS page says, "Obtain a TLS certificate/key pair (see below on how to do this) if you don't yet have one," people are going to point fingers at owntracks being the problem when they already have a certificate/key pair that has worked flawlessly with mosquitto.  Whether it's a bug that mosquitto does not require a SAN and violates RFCs doesn't matter when things work fine until trying to make owntracks work.

I would suggest adding a note to the TLS section at thttps://owntracks.org/booklet/features/tls/#tls saying, "Note: an existing certificate/key pair that works with mosquitto will not work if the server certificate does not have a Subject Alternative Name (SAN).  To verify that your server certificate has a SAN, you can look at the certificate in x509 form (see below, in "The nitty gritty")."

**Comment by growse** [comment]
> Users will look for documentation to fix the problem on your site, not in RFCs.

Sure, but we don't reproduce the entire contents of the RFCs that we depend on in our documentation. I also don't think it's our job to teach people about how TLS has changed over the last 20 years. Others may disagree with this.

> I would suggest adding a note to the TLS section at thttps://owntracks.org/booklet/features/tls/#tls saying, "Note: an existing certificate/key pair that works with mosquitto will not work if the server certificate does not have a Subject Alternative Name (SAN). To verify that your server certificate has a SAN, you can look at the certificate in x509 form (see below, in "The nitty gritty")."

Pull requests welcome. I think it'd be a useful addition.

**Comment by jpmens** [comment]
Modified note added to Booklet.

**Comment by gsteele13** [comment]
Hi all, 

I'm trying now to set up a server using self signed certs 

(The reason is that both the machine that hosts my owntracks recorder, and a separate synology NAS, sit behind a router: I have Let's encrypt certs for my synology for the routers external IP, but then it seems very complicated to set up a separate let's encrypt for the separate linux machine that i will run owntracks on....at least it seemed pretty complicated when I googled it...)

For this reason, I've gone down the self signed certs road and used the script to make the certs:

https://github.com/owntracks/tools/blob/master/TLS/generate-CA.sh

The Android app, however, gives the error "TLS Error: MqttException". Some google searching led me to this issue. Here is a snipped from the log files exported from the android app:

```
2026-05-08 20:39:23.555 I [DefaultDispatcher-worker-5] MQTTReconnectWorker: MQTT reconnect worker job completed, status Retry
2026-05-08 20:39:33.579 I [DefaultDispatcher-worker-5] MQTTReconnectWorker: MQTT reconnect worker job started
2026-05-08 20:39:34.087 E [DefaultDispatcher-worker-5] MQTTMessageProcessorEndpoint$connectToBroker: MQTT client unable to connect to endpoint
MqttException (0) - javax.net.ssl.SSLPeerUnverifiedException: Host: steele-home.synology.me, Peer Host: steele-home.synology.me
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:233)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:520)
	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
	at java.lang.Thread.run(Thread.java:1564)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host: steele-home.synology.me, Peer Host: steele-home.synology.me
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SourceFile:144)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:66)
	... 6 more
```

Is this related to the post above? Or is this a different issue? 

Thanks!
Gary
