### ISSUE TITLE
Cannot use "mock location"

### ISSUE THREAD

**Issue by gobftald** [owntracks/android#1714]
Version 2.4.12
Android version: 8.1.0
Device: Blackview BV9500
Source: Google Play

OwnTracks Android app cannot use "mock location". So I cannot use external GPS receiver.

**Comment by jpmens** [comment]
I think you're going to have to explain what exactly you intend to use, what you want to accomplish, and what your expectations are of our Android app.

**Comment by gobftald** [comment]
I thought it was clear. I want your OwnTracks Android apps send location information based on the input of an external GNSS (GPS) receiver. But OwnTracks app can only use Android internal location services, the phone internal GPS receiver.
I've installed a proper program which connects my USB connected GNSS (GPS) receiver and "push/route" the external position information into Android "mock location service". Every of my other location based apps (like Google Maps, Locus Maps, all types of GPS tracker apps) can see and use this data stream instead of the phone internal GPS. This is the goal of this "mock location" on Android systems. Your OwnTracks app somehow "knows/feels that there is GPS inputs, since it does not complain that "Device location disabled", however it is not able to receive that information and update it location information. I'm not an Android OS expert, but OwnTracks app should somehow manage to use transparently all sources of location  info coming from the system, either from internal or that "mock" channels.

**Comment by jpmens** [comment]
There are two things I'd like to address:

1. Just because something is clear to you does not mean it's clear to me.
2. "OwnTracks app should somehow manage to use" is wishful thinking. Maybe next time, on an open source project, you can politely ask whether a particular feature is planned or whether there is something you can contribute to making it happen.

Thank you.

**Comment by gobftald** [comment]
Perhaps my not native English makes you feel that I have been rude. It was not my intention to be.
However, the response I received was one of resentment.

I was not demanding. I thought that suggesting/reporting a feature/bug here on git hub is not a demand, and maybe even helps developers, and does not provoke derision.

But that's all for now, because I'm getting out of this "community."

**Comment by growse** [comment]
For a self-confessed non-native speaker of English, you seem to be parsing out a large amount of "resentment" and "derision" from what simply appears to be a request for more info.

I'll leave this open to see if anyone else wants to come along with a +1 on this request.

**Comment by gobftald** [comment]
"Maybe next time, on an open source project, you can politely ask whether a particular feature is planned or whether there is something you can contribute to making it happen."

For a "self-confessed non-native English speaker" please explain where I can read that "it simply appears to be a request for more information".

**Comment by growse** [comment]
> "Maybe next time, on an open source project, you can politely ask whether a particular feature is planned or whether there is something you can contribute to making it happen."
> 
> For a "self-confessed non-native English speaker" please explain where I can read that "it simply appears to be a request for more information".

Right here:

> I think you're going to have to explain what exactly you intend to use, what you want to accomplish, and what your expectations are of our Android app.

Now I'm done arguing about tone or style.

Pull requests welcome.

**Comment by kri164** [comment]
What is the core of problem?
Are there some android devices without gps, so the external box must be connected?

**Comment by gobftald** [comment]
Some internal Android GPS is not very accurate. That's why I use e.g. "Columbus P-10 Pro HD GNSS", which is capable of better than 1 meter accuracy. Therefore I have to connect an external GPS receiver via USB and use Android's "mock location" function. First I was planning to do a pull request and find out how to improve the app, since all other apps easily handle both sources (internal and mock/external). But the style of the replies above discouraged me. What I needed was solved in a different way. Therefore, thanks to your question, I no longer need this fix.

**Comment by wir3z** [comment]
I'm with the rest.  Not sure the net goal with this request.  A "cheap phone" gets you 4 meter accuracy easily.  What use case requires 1 meter accuracy for an app like this?

Sorry the world doesn't bow to your requests, asks questions on things that make no sense to them.  Great stance to "take your ball and go home".  Shows your great character <insert sarcasm here> ...

**Comment by gobftald** [comment]
I just wanted to answer the last question to me. And my last words were: "I no longer need this fix."
Your reply were "world doesn't bow to your requests," and "take your ball and go home"

consistent styles of this/your community,

BTW a "cheap phone" cannot get 4 m accuracy "easily", most case at all. It is not about the price of a phone, but the capability of commercial GPS chips (even on SoCs) which are not able to use (enough) independent frequency bands. 

I have a "use case", but I'd like to repeat: I DON'T ASK OR WANT ANYTHING FROM ANYONE.
