### ISSUE TITLE
Can't disable persistent notification

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#1761]
I'm unable to remove the persistent notification with the Report Location and Change Monitoring buttons. I'm guessing this is supposed to be tied to the Ongoing notification -> Last reported location setting in the app, but disabling that doesn't disable the notification. I don't want to disable notifications entirely because I want enter/exiting waypoint notifications. There are also no notification categories so I can't disable it there.

* **App build number**: 2.5.0 420500014
* **Android version**: 14
* **Device**: Samsung Galaxy S22+
* **Installation source**: Google Play

**Comment by growse** [comment]
Can you provide a screenshot? I don't know if you're referring to the service notification or something else.

**Comment by kaysond** [comment]
![image](https://github.com/user-attachments/assets/62f24bd5-7c8b-4250-a2e4-28d196718d43)

**Comment by growse** [comment]
That's just the foreground service notification that android shows, to tell you that there's a foreground notification.

Android <14 you couldn't dismiss these, but you can on Android 14 by swiping.

Are you just trying to make the service notification go away?

**Comment by kaysond** [comment]
> That's just the foreground service notification that android shows, to tell you that there's a foreground notification.
> 
> Android <14 you couldn't dismiss these, but you can on Android 14 by swiping.
> 
> Are you just trying to make the service notification go away?

No I can dismiss the notification just fine. The problem is that it keeps coming back!

**Comment by growse** [comment]
Oh I see! I suspect it comes back every time the app does something with the service, which is pretty regularly.

In the meantime, can you try and disable the "ongoing" notification channel?

![Screenshot_20240721-084205.png](https://github.com/user-attachments/assets/37de9b59-7c2f-4213-b8f5-a6391b0edc74)

**Comment by kaysond** [comment]
> Oh I see! I suspect it comes back every time the app does something with the service, which is pretty regularly.

That does seem to be the case. It roughly corresponds to every time my location gets updated.

> In the meantime, can you try and disable the "ongoing" notification channel?

Aha! I was pretty sure this is what I'd done before, but when I went back in, there were no notification categories to change. I thought it was an issue with the newest version of Owntracks, but turns out that Samsung, in their infinite wisdom, put Notification Categories behind a new toggle and disabled it by default.
