### ISSUE TITLE
Version 2.5.0 on Android not showing list of friends (not even its own device)

### ISSUE THREAD

**Issue by nlanfran** [owntracks/android#1763]
Hello everybody,

since new version 2.5.0, the list of friends is not shown on my app anymore. Not even the device where the app is installed. But position and location are reported correctly (for example inside or outside a region, or to NodeRed).

Thanks for any help on how to fix the problem.

Nick

* **App build number**:  Version 2.5.0, build 420500014
* **Android version**: 12
* **Device**: OnePlus Nord 2
* **Installation source**:  Google play

**Comment by growse** [comment]
Are you using MQTT or HTTP mode?

**Comment by nlanfran** [comment]
Hello,
sorry, I forgot to mention: I am using MQTT, in the specific hivemq.

**Comment by jpmens** [comment]
When a friend publishes their location, do you see that on your device's map?

**Comment by nlanfran** [comment]
No. I have 1 friend on iphone, the iphone can see me and himself on the map and on the friend's list, I can't see her and myself on the android, neither map and friend's list.

**Comment by jpmens** [comment]
That almost sounds as though your Android device isn't subscribed to the correct topic ... 
If you look in preferences, Configuration editor: does `subTopic` contain `owntracks/+/+` ?

**Comment by nlanfran** [comment]
Yes, it is there. 
Maybe I should explain some more. 
It has been running fine for more than a year. My phone and my wife's iphone are the only 2 devices connected to the hivemq broker. Then last Friday I noticed that I was not receiving the iphone updates anymore (this was a problem with iphone killing the app in the background). So I checked my android, and I found that it was not connected to the hivemq anymore, because apparently with the 2.5.0 version it requires the ID client, that was missing in my config. So I added the ID client, and boom, the friend's list and map were populated with my android and the wife iphone. This morning I checked again and no more devices on the map and friend's list.

**Comment by nlanfran** [comment]
Ok, I changed the ID client from '1' to '99', and again everything seems to be normal, I see both devices in the map and friend's list.
Just for my understanding, what is the client ID ?

**Comment by growse** [comment]
From Hive's docs (https://www.hivemq.com/blog/mqtt-essentials-part-3-client-broker-connection-establishment/):

> The ClientId is a unique identifier that distinguishes each MQTT client connecting to a broker and enables the broker to keep track of the client’s current state. To ensure uniqueness, the ClientId should be specific to each client and broker. MQTT 3.1.1 allows for an empty ClientId if no state needs to be maintained by the broker. However, this connection must have the clean session flag set to true, or the broker will reject the connection.

Basically it lets you use multiple devices for the same credentials on a broker. If you connect with a username/password/clientId, the broker *should* disconnect any other device connected with the same tuple.

This feels like a broker permissions issue? Ie you can post to topics, but not read from them....?

**Comment by jpmens** [comment]
> I changed the ID client from '1' to '99', and again everything seems to be normal

it's almost as though HiveMQ isn't behaving correctly ...

I recommend using `<username>-<devicename>` as clientID which, in the OwnTracks context, is likely unique enough. (In case of doubt add a number.)

**Comment by nlanfran** [comment]
ok, thanks for the explanation. (I should have checked myself). My device and my wife's device use different credentials defined inside access management of hivemq, this is also used inside NodeRed. Both credentials have publish and subscribe permissions. This explains why the connection to the broker was rejected without the ID Client. I have now set inside the android app, under the connection, the clean flag at the very bottom (I set ID client to '0', I can't leave it empty). It seems to still have the friend's list and display on the map.

**Comment by jpmens** [comment]
I'd suggest setting clean session = False

From the above docs:

> The CleanSession flag indicates whether the client wants to establish a persistent session with the broker. When CleanSession is set to false (CleanSession = false), considered a persistent session, the broker stores all subscriptions for the client and all missed messages for the client that subscribed with a [Quality of Service (QoS) level 1 or 2](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels).

**Comment by jpmens** [comment]
Glad you got it working.

> again everything seems to be normal

You wrote this earlier, so I'm closing for now.

**Comment by compuguy** [comment]
> Ok, I changed the ID client from '1' to '99', and again everything seems to be normal, I see both devices in the map and friend's list.
> Just for my understanding, what is the client ID ?

I'm using HiveMQ as well and was experiencing the same exact issues. Changing the client ID to something new/unique resolved the issue for me as well.
