### ISSUE TITLE
Trigger "t" (and others) cause Unknown message type on Android

### ISSUE THREAD

**Issue by parkerrsv** [owntracks/android#1768]
I have just setup owntracks on an AWS VPS through lightsail. 
All correct ports are allowed and everything appears to work on the frontend website (positions updated).

Unfortunately on the Android app, the published location of another user(friend) does not show up correctly.
The logs show the following:
`I MessageProcessor: Received incoming message: MessageUnknown on owntracks/tim/iphone`
`W MessageProcessor: Unknown message type received`

I assume everything is set up correctly on the VPS side, as it will occasionally work with manual messages. I've seen the friends location pop up if its manually shared on my android.

I am using all the default settings in the OTRC, generated by the frontend website.

**Comment by parkerrsv** [comment]
> Thank you for the data!
> 
> I can reproduce the error, and I'm a) marking this as a bug and b) moving the issue to our Android issue tracker.
> 
> The problem arises when in the `t` element of the JSON payload a `t` exists. If I replace that by `p`, say, then the message is accepted.
> 
> `t` is a trigger which indicates how a location was reported. Its value may contain `t` in which case it's an iOS timer-based publish in move mode, and our Android app rejects these messages.
> 
> What surprises me very greatly is that nobody's noticed this yet, so congratulations on that! :-)

Great! Good to know I'm not going insane :P

**Comment by ckrey** [comment]
> > Thank you for the data!
> > I can reproduce the error, and I'm a) marking this as a bug and b) moving the issue to our Android issue tracker.
> > The problem arises when in the `t` element of the JSON payload a `t` exists. If I replace that by `p`, say, then the message is accepted.
> > `t` is a trigger which indicates how a location was reported. Its value may contain `t` in which case it's an iOS timer-based publish in move mode, and our Android app rejects these messages.
> > What surprises me very greatly is that nobody's noticed this yet, so congratulations on that! :-)
> 
> Great! Good to know I'm not going insane :P

I can reproduce same behaviour here.

**Comment by parkerrsv** [comment]
Is there any work around to this that I could implement? Right now the app does not work at all with this bug. 
Would it be possible to change the message on the broker side?

**Comment by jpmens** [comment]
The app should be processing other triggers without a problem. If you wanted to work around this you could create a subscriber to your broker which replaced the trigger and re-published as, say, a different "friend". Not quite for the faint of heart, so if you have a bit of patience you could wait for an official fix. :)

**Comment by growse** [comment]
Will be fixed in 2.5.1. Thanks for the bug!

**Comment by parkerrsv** [comment]
Thanks for this. Unfortunetly the 't' trigger seems to be for both 'move' and 'significant', I am rarely seeing positional updates for the people on my server, is there a way around this until the fix is released?

**Comment by jpmens** [comment]
@parkerrsv version 2.5.1 is now hitting the play stores, and we've confirmed the bug is resolved.

**Comment by parkerrsv** [comment]
> @parkerrsv version 2.5.1 is now hitting the play stores, and we've confirmed the bug is resolved.

Thanks for this jpmens!
I can't see the update in the store yet, any eta on that? Assume it's out of your control

**Comment by growse** [comment]
It's a staged rollout. We found some issues so halted, 2.5.2 shortly.

**Comment by killah78** [comment]
I see it's already closed, but not rolled out yet. So a question related to this: I got the "MessageUnknown" also for trigger "v" and "C". This will be solved as well? These are sent from an iphone.

**Comment by jpmens** [comment]
Are you sure that'a a capital `C` ?

**Comment by killah78** [comment]
Yes, it is a capital C

**Comment by ckrey** [comment]
Yes there is a capital `C` trigger value in iOS. It indicates the location update was triggered by entering/leaving the special `+follow` region. Documentation in booklet updated

**Comment by ckrey** [comment]
I think the apps should allow any `t` (trigger) values as long as they don't evaluate them in a special way.

**Comment by killah78** [comment]
So will you reopen this topic, or will take care of it in another way?
