### ISSUE TITLE
[Feature Request] Add Options To Stop Tracking in Airplane and Battery Saver Mode

### ISSUE THREAD

**Issue by TechD123** [owntracks/android#1773]
Dear OwnTracks team,

I'd like to suggest a feature that allows the app to be a bit more respecting of the user's circumstances.

Users may want the app to pause its tracking when their device is either in airplane mode or battery saver has been activated, irrespective of the current tracking mode. There could be two toggles for this in settings under the category Advanced. This feature is already present in [PhoneTrack](https://gitlab.com/eneiluj/phonetrack-android), for example.

Thanks for developing this app!

**Comment by jpmens** [comment]
That's what Quiet mode is for -- the app then no longer tracks.

**Comment by jpmens** [comment]
Possibly using Tasker.

**Comment by growse** [comment]
I'm not particularly keen on building a whole rules engine into OT that can dynamically switch modes based on arbitrary conditions.

Any reason why you can't use a 3rd-party app design for exactly this type of thing, and fire intents at OT that way?

**Comment by jpmens** [comment]
Thanks for the suggestion, @TechD123, but I think we won't add this bit of additional complexity to OwnTracks, particularly as there are third-party mechanisms which can accomplish the task.
