### ISSUE TITLE
Exposing bearing to the location messages

### ISSUE THREAD

**Issue by wir3z** [owntracks/android#1777]
Any thoughts of exposing the bearing in the location update message?  It looks to be created by the GPS position, somehow is shown for each friend when you view them, but doesn't get sent out.

* **App build number**: 2.5.x
* **Android version**: 14
* **Device**: Pixel
* **Installation source**: APK

**Comment by jpmens** [comment]
If it is a value generally obtainable in Android, sure, why not, although I don't think I'd have a use for it.

What would you propose calling the JSON element? I'm not aware of an abbreviation for bearing. Would we call it just that, `bearing`?

**Comment by ckrey** [comment]
do you mean the movement direction „course over ground” which we already report when available as “cog”? Or the orientation of the device?

**Comment by jpmens** [comment]
It sounded familiar ... From the Booklet:

* `cog` Course over ground _(iOS/integer/degree/optional)_

**Comment by wir3z** [comment]
I was thinking "direction" (0-360 degrees).  On iOS, does `cog` return as an angle?  I thought it was direct distance from A->B (without having an iOS device to confirm!)

**Comment by wir3z** [comment]
Awesome, thanks!  Works great!

**Comment by jpmens** [comment]
>Awesome, thanks!  Works great!

thank you for suggesting it; I very much appreciate when Android and iOS get the same features!
