### ISSUE TITLE
Trigger type be returned as NULL on many location updates

### ISSUE THREAD

**Issue by wir3z** [owntracks/android#1798]
I noticed that I'm getting a lot of null trigger types in the received data logs from the app.  Looking at the mobile logs, I'm seeing this on many locations:  publishLocationMessage for Location[fused <...>] triggered by DEFAULT

What is the `DEFAULT` supposed to map to?  It seems to be coming from updates when the phone is moving, so it appears to be a location update `l`.

Thanks!

* **App build number**: 2.5.3
* **Android version**: 14
* **Device**: Google Pixel 7
* **Installation source**: APK

**Comment by jpmens** [comment]
Null trigger type as in `"t" : null` ? That sounds quite wrong.

**Comment by wir3z** [comment]
Sorry, confirmed, when the Android app flags the trigger type as `DEFAULT`, it doesn't populate anything in the outgoing JSON, even though it should have been flagged as a location update.

**Comment by ckrey** [comment]
not sure what docs you are referring to?
There is no `”l”` defined and `”t”` is optional 
https://github.com/owntracks/booklet/blob/master/docs/tech/json.md#_typelocation

**Comment by wir3z** [comment]
Interesting.  There used to be a `l` on that list for location updates.  The Android app is still sending `l` for some normal moving location updates, but others the type field is not returned.

**Comment by wir3z** [comment]
It does appear that using "move mode" is a reliable way of demonstrating that the field is not returned.  Is the assumption now if no type is returned, then it's just a normal location update?

**Comment by jpmens** [comment]
There used to be an `l` for our Greenwich devices — documentation I recently removed.

Other than that I see an `l` only for Android transition events (and I’ve fixed a typo in the word “Location” a moment ago).

**Comment by jpmens** [comment]
I've just checked all historic data received from iOS and Android here.

The only occurrences of `"t":"l"` come from Android and exclusively from `"_type":"transition"` messages, so at least our docs are correct. 😀 

```

$ grep  -r '"l"' jpm/ rec | grep -c  event
196
$ grep  -r '"l"' jpm/  rec | grep -c -v  event
0
```

**Comment by jpmens** [comment]
> Is the assumption now if no type is returned, then it's just a normal location update?

It's not "now" or new. IIRC it's always been that way.

**Comment by wir3z** [comment]
Perhaps too much whiskey in the coffee on my side!  :)

**Comment by jpmens** [comment]
You might find less coffee in the whiskey also works. ;-)
