### ISSUE TITLE
QoS cannot be set in the Android app

### ISSUE THREAD

**Issue by speckenbuettel** [owntracks/android#1801]
Hi,

I would like to change the MQTT QoS for pub to 2, but the change is not saved.

Screenshots:
![Screenshot_20240820_113928_OwnTracks](https://github.com/user-attachments/assets/a5c64494-368b-44f9-b500-4e979465b9da)
![Screenshot_20240820_113946_OwnTracks](https://github.com/user-attachments/assets/199d973f-2a79-4a37-a5ec-704f7fdd88fb)

After saving, nothing happens and the QoS remains 1.

What could be the reason?

Thanks and best regards,
Falk

**Comment by jpmens** [comment]
I confirm the entered value is (not always) saved, and have marked this as a bug.

I was able to configure the value `2` and now I can't revert.

**Comment by growse** [comment]
2 definitely shouldn't work! - Protocol levels are 3 (for 3.1) or 4 for (3.1.1).

Anyhow, found the issue. Just writing a test or two.

**Comment by growse** [comment]
Ah yes - it's actually affecting both, for the same reason.
