### ISSUE TITLE
MultitypeAdapter.java line 108

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#182]
#### in org.owntracks.android.adapter.MultitypeAdapter.getItem

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/554b4e65f505b5ccf0bf0a96](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/554b4e65f505b5ccf0bf0a96)

**Comment by binarybucks** [comment]
MultitypeAdapter will be refactored to RecyclerView in future versions
