### ISSUE TITLE
[FEAT]: Show the same info as frontend

### ISSUE THREAD

**Issue by jiriks74** [owntracks/android#1826]
I've noticed that the web frontend + recorder can show more information than the Android app. Right now I've noticed that WiFi is shown on the frontend but not the app.

* **App build number**: 2.5.0
* **Android version**: 14
* **Device**: Redmi Note 10S (LineageOS)
* **Installation source**: F-Droid

**Comment by jpmens** [comment]
Frontend has access to historic data which the Android app doesn't, so it will never be possible to show the same info as on Frontend.

**Comment by jiriks74** [comment]
Ok, but the info about the WiFi access point is still there, right? I'm not asking about historical stuff. The latest AC is just fine I think.

I don't really need this, it's fine if it's not added, but I thought that it would be nice to show mostly the same stuff on all the places.

**Comment by jpmens** [comment]
I don't really see why the app should show which access point it's using; you can see that on the device proper

**Comment by jiriks74** [comment]
> you can see that on the device proper

I'm thinking about knowing whether my GF is on WiFi or data, not whether my own phone is on WiFi.

**Comment by jpmens** [comment]
Here again, I wouldn't know what to do with the information. FWIW, we don't display that on iOS either.

**Comment by jiriks74** [comment]
Ok. It was only a suggestion, nothing ground breaking.

Would we agree to leave this open for someone else's input?

**Comment by jpmens** [comment]
Closing as not planned.
