### ISSUE TITLE
[BUG]: Battery charging status not working

### ISSUE THREAD

**Issue by jiriks74** [owntracks/android#1827]
I see that this feature has already been added: #841
and I see some screenshots that it's working for people: #1618

However I am unable to see that my battery is charging in the app or the web frontend. I can only see the percentage but not the charging status.

* **App build number**: 2.5.0
* **Android version**: 14
* **Device**: Redmi Note 10S (LineageOS)
* **Installation source**: F-Droid

**Comment by growse** [comment]
Are you using MQTT or HTTP? Do you have an easy way to grab the contents of a location message and post here so i can see what value's being set?

**Comment by jiriks74** [comment]
I'm using MQTT. I'll look into posting the contents (anonymized) here soon.
