### ISSUE TITLE
Android apps doesn't show Friends, but they're visible in web interface

### ISSUE THREAD

**Issue by akorn** [owntracks/android#1866]
* **App build number**: 2.5.3 (420503003) - Google Play
* **Android version**: 14
* **Device**: Google Pixel 6 Pro
* **Installation source**: Google Play

I use the app in HTTP mode (the server side is behind a reverse HTTP proxy).

In the web frontend, users can see each other. In the Android app, the Friends list is empty and there is no obvious way to populate it. In the `ortc` file I give the clients, I have

```
    "subQos": 2,
    "subTopic": "owntracks/+/+ owntracks/+/+/event owntracks/+/+/info owntracks/user/device/cmd",
    "sub": true,
```

I guess not seeing the Friends is a result of using HTTP instead of MQTT, and could be a subset of #774,  but a) the documentation doesn't seem to point this out and b) it still impairs the usability of the app.

**Comment by jpmens** [comment]
You don't say which backend you use, i.e. what the app is POSTing to. 

If you using our OwnTracks Recorder, there is support for Friends, and [this is documented](https://github.com/owntracks/recorder?tab=readme-ov-file#friends-in-http-mode).

**Comment by akorn** [comment]
Oh. I missed that somehow.

I wrote a quick semi-oneliner in zsh to populate the friends database with a full mesh (everyone can see everyone else). Maybe someone else will find it useful:

```zsh
cd /var/lib/owntracks
users=(*.pass)
users=(${users%.pass})
for u in $users; do
	json=()
	for f in $users; do
		[[ $f = $u ]] && continue
		json=($json \"$f/phone\")
	done
	echo "$u-phone [ ${(j:, :)json} ]"
done | sudo -H -u owntracks ocat --load=friends
```

(This assumes everyone has one device and it's called "phone".)
