### ISSUE TITLE
locatorPriority unrecognised in setConfiguration

### ISSUE THREAD

**Issue by JuliusFruitfly** [owntracks/android#1874]
'locatorPriority' is documented as an integer 0..3, but when setting a value with setConfiguration the log contains:-

D [DefaultDispatcher-worker-3] Preferences: Importing configuration key locatorPriority -> 2
I [DefaultDispatcher-worker-3] Preferences: Unknown preference key locatorPriority

and

I [DefaultDispatcher-worker-3] PreferencesStore: Setting default preference value for locatorPriority to null
D [DefaultDispatcher-worker-3] PreferencesStore: Setting preference locatorPriority to null (coerced to null)

Is this parameter no longer supported?

Thanks

* **App build number**: 2.5.3
* **Android version**: 12
* **Device**: Huawei P30 lite
* **Installation source**:  Google Play

**Comment by growse** [comment]
Yep, we took it out. It was not widely used, and causing a bunch of confusion.

**Comment by growse** [comment]
Ok, so the issue is that `locatorPriority` only responded to the value being the name version of the string representation of the enum, not the number (that it used to be). So, a regression.
