### ISSUE TITLE
'Software caused connection abort' appears in notification

### ISSUE THREAD

**Issue by JuliusFruitfly** [owntracks/android#1882]
'Software caused connection abort' appears in notification. Log attached. Thanks

* **App build number**: 2.5.3
* **Android version**:  12
* **Device**: Huawei p30 lite
* **Installation source**: Google Play
* 
[owntracks-log SoftAbt 0910.txt](https://github.com/user-attachments/files/17327739/owntracks-log.SoftAbt.0910.txt)

**Comment by growse** [comment]
This is usually a flakey network that could be causing packet loss (so TCP timeouts), FIN from the remote side, etc.

Mobile devices usually aren't on perfect networks, so this sort of thing is pretty normal.
