### ISSUE TITLE
Unable to configure host URL on Android

### ISSUE THREAD

**Issue by mfurniss** [owntracks/android#1906]
* **App build number**: 2.5.4
* **Android version**: 14
* **Device**: Google
* **Installation source**: Google Play Store

It is not possible to configure the connection endpoint host URL.

After pasting the host URL, the Owntracks app strips the colon and forward slashes from the URL making it invalid.

It is then not possible to edit the URL. The input box is too small and the cursor cannot be moved to the start.

![share_8950310928438470368](https://github.com/user-attachments/assets/fa64c1b4-9a3e-48f7-a484-cbd73bbad58c)
![share_7882078045593989999](https://github.com/user-attachments/assets/306c8b1d-fa4f-453b-be67-b40253cd0da3)

**Comment by jpmens** [comment]
It looks to me as though you're about to configure MQTT which requires a broker address (or hostname), and not a URI.

**Comment by growse** [comment]
Agree with @jpmens .

Are you trying to use MQTT mode or HTTP mode (the fact that it looks like a webhook hints it's http mode).

**Comment by mfurniss** [comment]
HTTP. I switched the mode and can now enter the URL. But the webhook URL provided during installing the HAOS addon responds with 404 Not Found.

**Comment by growse** [comment]
I don't think we'd auto swap the mode, but a clippy-like* "it looks like you're trying to configure an HTTP endpoint" might be feasible.

*Won't actually be clippy.
