### ISSUE TITLE
[FEATURE] Save battery by sending updates less frequently?

### ISSUE THREAD

**Issue by ajpanton** [owntracks/android#1916]
How frequently does Owntracks send location updates? Actually determining the location probably uses the most power, but would it save anything if it stored them locally for a while and then send them in bursts? Would it make sense to have a setting to send updates every x minutes, (or x minutes starting from when the first item is added to the queue), with 0 meaning send it immediately?

**Comment by jpmens** [comment]
Closing as unplanned.
