### ISSUE TITLE
Was working 🤔

### ISSUE THREAD

**Issue by G2740** [owntracks/android#1933]
Version, 2.5.3 using Google play

Was using an S23 Ultra and switched to S24 Ultra. Was working before, may still be working some. TBD 

The message on the pulldown push messages is stuck "initializing".

I've tried rebooting home assistant Green, exiting the app and restart, and fixed it once before doing that for a little while. Force stop and restart.

All known dontkillmyapps are turned off.

It was reporting, I left zones in HA and waypoints in Owntracks. It showed my location at the endpoint after I left today.

Got home, didn't report entering zone at home.

If I zoom in on the Owntracks map, it shows a device moving in the house if I walk around.

I sighed up for Beta, but this version may be most recent release. None to download yet.

Some debug logs data. Not all it's a bunch.
LocationLiveData: Removing previous locationupdate task complete. Success=true Cancelled=false
2024-12-09 12:03:38.670 D [main] LocationLiveData: LocationLiveData location update request completed: Success=true Cancelled=false
2024-12-09 12:03:38.671 D [main] MapFragment$onLocationObserved: Ignoring location with accuracy 100.0 >= 3
2024-12-09 12:03:41.017 D [main] MapFragment$onLocationObserved: Ignoring location with accuracy 7.389 >= 3
2024-12-09 12:03:41.831 D [main] LocationLiveData: LocationLiveData removing location updates completed: Success=true Cancelled=false

Any suggestions or comments appreciated! 👍

**Comment by G2740** [comment]
What I found. I had changed the inaccurate location setting from 0 to 15 yesterday.

Changed it back to zero, it's reporting properly again.🤷

**Comment by growse** [comment]
> What I found. I had changed the inaccurate location setting from 0 to 15 yesterday.

Setting `inaccurateLocations` to 15 will have OT ignore any location with an accuracy worse than 15m. Which might be most of them.

>  2024-12-09 12:03:41.017 D [main] MapFragment$onLocationObserved: Ignoring location with accuracy 7.389 >= 3

This implies you had `inaccurateLocations` set to 3. So it's discarded a GPS fix with 7m accuracy. 

Personally, I set `inaccurateLocations` to about 150.

**Comment by G2740** [comment]
> > What I found. I had changed the inaccurate location setting from 0 to 15 yesterday.
> 
> Setting `inaccurateLocations` to 15 will have OT ignore any location with an accuracy worse than 15m. Which might be most of them.
> 
> >  2024-12-09 12:03:41.017 D [main] MapFragment$onLocationObserved: Ignoring location with accuracy 7.389 >= 3
> 
> This implies you had `inaccurateLocations` set to 3. So it's discarded a GPS fix with 7m accuracy. 
> 
> Personally, I set `inaccurateLocations` to about 150.

Thanks for reply, I did play with 3 and 15, simply because I didn't understand what the heck I was doing. 0, seems to work, I'll test 150 as well.

**Comment by ckrey** [comment]
Meaning of `ignoreInaccurateLocations = 0` clarified [configuration](https://owntracks.org/booklet/tech/json/#_typeconfiguration)

**Comment by growse** [comment]
Let us know if you're still facing an issue,
