### ISSUE TITLE
Report from notification bar has no feedback

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#197]
Swipe down notification bar. Hit up-arrow: there is no vibration or other visual indication that PUB has been done (though it is). Also: time on said bar remains constant.

**Comment by jpmens** [comment]
Published `tst` remains constant as well:

```
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
owntracks/jpmens/nex4 {"_type":"location","tst":1434355442,"acc":30,"t":"u","tid":"x4"}
```

**Comment by jpmens** [comment]
While on Locations page: similar results when pressing Report Now. published `tst`s remain constant although i notice the reverse geocoder blink.

After a few presses, phone vibrates and says "Location reported", and `tst` increases.

**Comment by binarybucks** [comment]
When you report it queries the Google API for the last known location. If you do this many times in a row, the same cached location object is returned from the API. 

The location message includes the tst at which the location was acquired. I can change it to use the time at which the message was send. 

Thinking about it, this is probably also the reason for your reports of duplicate messages in #86

**Comment by jpmens** [comment]
I think current time is more intuitive.
