### ISSUE TITLE
No `desc` in waypoint transition events (waypoint is shared)

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/android#198]
Created a shared waypoint, named `home`. Manually publish my location via the app and see a transition event generated, but no `desc` in the transition publish.

```/owntracks/ben/waypoint {"_type":"waypoint","desc":"home","lat":-43.xxxx,"lon":172.xxxx,"tst":1434355660,"rad":75,"tid":"bj"}
/owntracks/ben/event {"_type":"transition","lat":-43.xxxx,"lon":172.xxxx,"acc":33,"tst":1434359604,"wtst":1434355660,"tid":"bj"}
```

**Comment by sumnerboy12** [comment]
Also, doesn't look like there is any `enter` or `leave` transition type?

**Comment by binarybucks** [comment]
Works fine here. This could happen if a geofence transition occurs but the app cannot find a defined waypoint for the geofence id. As I'm seeing some database errors for you I'd suggest you try with the next version which should correctly setup the databse

**Comment by sumnerboy12** [comment]
Ok - will do - any idea when that next release might be?
