### ISSUE TITLE
Export to Slack crashes app

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/android#199]
Can export to email no problem, but if I attempt to export to Slack the OwnTracks app crashes. Report sent.

**Comment by jpmens** [comment]
Whom did you send the report to? Slack? (Just kidding :-)

**Comment by sumnerboy12** [comment]
Don't know - just clicked `Report` on the exception dialog!

**Comment by binarybucks** [comment]
Funnily, if I export to Slack, OwnTracks lives but Slack crashes :D

**Comment by sumnerboy12** [comment]
Yep - not a big deal this one - once I figured out I could export to email OK I was happy :).

**Comment by binarybucks** [comment]
It crashes Slack but not OwnTracks so it's not our problem.
