### ISSUE TITLE
Add config extention (otrc) to open with app owntracks

### ISSUE THREAD

**Issue by Pimmetje** [owntracks/android#214]
Handle the extention otrc with app. If i now get the file per mail i can't open the file. I have to save it and open it from the explorer using owntracks. Would be nice if this is possible directly from the mail application.

**Comment by binarybucks** [comment]
Works fine here with the latest master channel. When tapping on an .otrc file in Dropbox or the Gmail, Android offers to open the file with OwnTracks. 

Could you specify which app version you are refering to and with which app you are trying to open the .otrc file?

**Comment by Pimmetje** [comment]
0.5.16, tried from gmail & k-9 mail.

Alexander Rust <notifications@github.com> schreef op 1 juli 2015 18:27:30 CEST:
>Works fine here with the latest master channel. When tapping on an
>.otrc file in Dropbox or the Gmail, Android offers to open the file
>with OwnTracks. 
>
>Could you specify which app version you are refering to and with which
>app you are trying to open the .otrc file?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owntracks/android/issues/214#issuecomment-117737909

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by binarybucks** [comment]
Fixed in upcomming 0.5.21. 
Hosted files are exported with application/json MIME type that was previously not associated with the app.
