### ISSUE TITLE
Statistics Page Layout

### ISSUE THREAD

**Issue by stylpen** [owntracks/android#232]
Statistics scroll below menu.
![image](https://cloud.githubusercontent.com/assets/1053870/9156201/b8f52f26-3ed1-11e5-90c3-01853d654fe1.png)
 Android 4.4.4 CM

**Comment by watou** [comment]
I don't see this problem on Android 5.1.1, FWIW.

**Comment by binarybucks** [comment]
It's only for pre 5.x. The page was for debugging purposes only anyway.

On Mon, Aug 10, 2015 at 10:11 AM, John Cocula <notifications@github.com>
wrote:

> I don't see this problem on Android 5.1.1, FWIW.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/android/issues/232#issuecomment-129353578>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust
