### ISSUE TITLE
Vibrate on reports and waypoints both off; vibrates anyway

### ISSUE THREAD

**Issue by watou** [owntracks/android#235]
0.5.20 on Android 5.1.1 Nexus 5.  Seems to report a lot more than 0.5.11 did, so vibrating a lot!

**Comment by jpmens** [comment]
Confirmed: switching Vibrate off has no effect.

**Comment by carlinchisart** [comment]
Hi, i do the change in the configuration to off vibrate, I force to close the aplication and star again,  the report was do without the vibrate.

thanks

**Comment by jpmens** [comment]
Which version are you using? This has been fixed in the latest beta which came out a day or two ago.

**Comment by watou** [comment]
Sorry to ask here, but how to get latest beta?  I still have 0.5.20 in app and 

0.5.20 (520)
## OwnTracks 0.5.20-3
>  Release date 2015-08-08
* [FIX] Setting keystore password

showing in Beta app, refresh does not update.

**Comment by jpmens** [comment]
I responded too quickly :) Latest 0.5.21 is out to beta testers only I think, but we plan on a release around the weekend. Stay tuned please.

**Comment by watou** [comment]
Thanks for quick response.  Looking forward to it!
