### ISSUE TITLE
Unable to connect to private mqtt server with owntracks 0.5.22 for android

### ISSUE THREAD

**Issue by stonith33** [owntracks/android#259]
Hi.

I'm using owntracks for android with a private mosquitto server at home. It used to work, with legacy version, and with beta version until 0.5.22 was released on play store a few days ago.

Since 0.5.22, I always have the message "Disconnected with error", making this new version totally unusable.

It doesn't seem to be related to authentication problem, since i tried to remove authentication requirements and acl on topic. Anyway, according to mosquitto logs, owntracks doesn't even try to post in queue.

Below are some information I gathered while trying to understand if it was a configuration problem or an issue in owntracks. I hope it can help.

1) These are mosquitto server logs when i configure owntracks for anonymous connection, and mosquitto configured to allow anonymous (connack = 5): 
```
Sep 19 11:05:31 cellier mosquitto[25360]: New connection from 192.168.1.12 on port 1883.
Sep 19 11:05:31 cellier mosquitto[25360]: Sending CONNACK to olivier/c6903 (5)
Sep 19 11:05:31 cellier mosquitto[25360]: New connection from 192.168.1.12 on port 1883.
Sep 19 11:05:31 cellier mosquitto[25360]: Sending CONNACK to olivier/c6903 (5)
```

2) These are mosquitto server logs when i configure owntracks for connection with authentication, correct user and password provided, and mosquitto configured to deny anonymous (connack = 5): 
```
Sep 19 11:34:14 cellier mosquitto[28596]: New connection from 192.168.1.12 on port 1883.
Sep 19 11:34:14 cellier mosquitto[28596]: Sending CONNACK to olivier/c6903 (5)
Sep 19 11:34:14 cellier mosquitto[28596]: New connection from 192.168.1.12 on port 1883.
Sep 19 11:34:14 cellier mosquitto[28596]: Sending CONNACK to olivier/c6903 (5)
```

3) These are mosquitto server logs when i use mosquitto_pub to post in owntracks topic and mosquitto configured to allow anonymous (connack = 0): 
```
Sep 19 11:38:37 cellier mosquitto[28652]: New connection from 192.168.1.10 on port 1883.
Sep 19 11:38:37 cellier mosquitto[28652]: New client connected from 192.168.1.10 as mosq_pub_9227_dm3 (c1, k60).
Sep 19 11:38:37 cellier mosquitto[28652]: Sending CONNACK to mosq_pub_9227_dm3 (0)
Sep 19 11:38:37 cellier mosquitto[28652]: Received PUBLISH from mosq_pub_9227_dm3 (d0, q0, r0, m0, 'owntracks/olivier/myphoneid', ... (4 bytes))
Sep 19 11:38:37 cellier mosquitto[28652]: Sending PUBLISH to openhab.1441486947819 (d0, q0, r0, m0, 'owntracks/olivier/myphoneid', ... (4 bytes))
Sep 19 11:38:37 cellier mosquitto[28652]: Received DISCONNECT from mosq_pub_9227_dm3
```

4) These are mosquitto server logs when i use mosquitto_pub to post in owntracks topic and mosquitto configured to deny anonymous, with correct username and password provided (connack = 0):
``` 
Sep 19 11:41:47 cellier mosquitto[28652]: New connection from 192.168.1.10 on port 1883.
Sep 19 11:41:47 cellier mosquitto[28652]: New client connected from 192.168.1.10 as mosq_pub_9279_dm3 (c1, k60, uolivier).
Sep 19 11:41:47 cellier mosquitto[28652]: Sending CONNACK to mosq_pub_9279_dm3 (0)
Sep 19 11:41:47 cellier mosquitto[28652]: Received PUBLISH from mosq_pub_9279_dm3 (d0, q0, r0, m0, 'owntracks/olivier/myphoneid', ... (4 bytes))
Sep 19 11:41:47 cellier mosquitto[28652]: Sending PUBLISH to openhab.1441486947819 (d0, q0, r0, m0, 'owntracks/olivier/myphoneid', ... (4 bytes))
Sep 19 11:41:47 cellier mosquitto[28652]: Received DISCONNECT from mosq_pub_9279_dm3
```

5) These are mosquitto server logs when i use mosquitto_pub to post in owntracks topic but provide bad username/password (connack = 4): 
```
Sep 19 11:41:57 cellier mosquitto[28652]: New connection from 192.168.1.10 on port 1883.
Sep 19 11:41:57 cellier mosquitto[28652]: Sending CONNACK to 192.168.1.10 (4)
```

6) This is what i can capture with wireshark on my server when owntracks tries to connect anonymously (case n°1)
```
.T..MQTT.....
olivier/c6903..owntracks/olivier/c6903. {"_type":"lwt","tst":1442655851} ...
```

7) This is what i can capture with wireshark on my server when mosquitto_pub connects anonymously and publishes a message (case n° 3)
```
....MQIsdp...<..mosq_pub_9673_dm3 ...0(."owntracks/olivier/myphoneidmessage..
```

Steps 1 to 5 seem to show that it is not related to configuration problem on mosquitto side. Since it used to work before version, and since connack value is 0 or 4 with mosquitto client, but always 5 with owntracks 0.5.22, it makes me think of a protocol level problem instead. This is why I tried to dump network trafic.

Steps 6 and 7 seem to confirm a difference in protocol.  First characters are different on the two dumps, and JSON formatted text appear on owntracks dump, but not on pure mosquitto dump.

What has changed with this owntracks 0.5.22 ? 

Thanks for your help, and also thanks for your great job with owntracks.

**Comment by binarybucks** [comment]
Thanks for moving this. 
Could you check if you can connect when you disable Messaging (Preferences, Advanced, Messaging)? 

0.5.2x introduced subs to other topics to receive messages. Maybe these are not included in your ACLs?

**Comment by jpmens** [comment]
This looks like an authorization problem. Please note that 0.5.22 (and future versions) use additional topics as described in our API section of the [Booklet](http://owntracks.org/booklet). Indeed it's probably related to Messaging as binarybucks just said.

**Comment by stonith33** [comment]
Thanks for helping.

I get the same result with messaging enabled or disabled.

However, after your posts I tried to totally disable acl on mosquitto and owntracks could then connect to mosquitto. This is a thing I didn't try since previous version used to work with a single acl to allow posting in the location topic.

I now try to figure out what other acl is required to allow owntracks to connect. I found the API section in the booklet. I will soon let you know if I found something.

**Comment by jpmens** [comment]
I recommend you disable ACLs on Mosquitto side as you suggest. Then launch a `mosquitto_sub -v -t '#'` to see what happens when your client App connects. That should give you a hint of the ACLs you need, and remember please, most of them must be `write`.

**Comment by stonith33** [comment]
I wrote acl in mosquitto according to http://owntracks.org/booklet/tech/json/#topics in order to allow read and write in described topics. 
It now works correctly.
Thanks for your help.

**Comment by jpmens** [comment]
Thanks for the report; glad you got it working!
