### ISSUE TITLE
ignoring waypoints over mqtt ?

### ISSUE THREAD

**Issue by mrizvic** [owntracks/android#264]
I have successfuly connected owntracks 0.5.22 to own mosquitto server. When i create shared waypoint the message gets posted to appropriatet topic (owntracks/username/device/waypoint). I captured the text and posted back the same JSON (waypoint) with tst+1, different name, lat, lon fields. Nothing happened on android app. I doublechecked all the settings inside app. Nothing seems to be wrong. Then I started looking at the code and observed method in src/main/java/org/owntracks/android/services/ServiceApplication.java line 796 (  public void messageArrived(String topic, MqttMessage message) throws Exception ). I followed if (type.equals()) calls and I couldnt find if (type.equals("waypoint")) implementation. Is that the reason why waypoints are ignored? I dont have rooted phone so CatLog doesnt show any other logs than from the CatLog app itself.

**Comment by mrizvic** [comment]
oh nevermind
I just found in booklet:
_type=waypoints (currently iOS only)

**Comment by jpmens** [comment]
Waypoints are not supposed to be published *to* the device. The devices publishes a waypoint when you created it _shared_ to the broker.

**Comment by jpmens** [comment]
Yes, and please do not confuse `waypoint` (singular) with `waypoints` (plural). :-)
