### ISSUE TITLE
Waypoints don't get exported at all

### ISSUE THREAD

**Issue by CWempe** [owntracks/android#279]
I am about to switch to a new phone.

I want to export my config and import it on my new phone.
But it looks like the export function does not export the waypoints any more. :(

The "config.otrc" is 876 byte in size.
I opened it with Notepad++ on my PC and cannot se anything about waypoints.

Last time (https://github.com/owntracks/android/issues/225#event-376167958) waypoints did get exported.
Importing the file works for the rest of the settings, I guess.

old Phone: Nexus 4, Android 5.1.1, Owntracks 0.5.22
new Phone: Galaxy S6, Android 5.1.1, Owntracks 0.5.22

**Comment by binarybucks** [comment]
Good catch. Waypoint export has been a casualty of #230 unless you're using
public mode.
Fixed now for all modes.

On Sat, Oct 10, 2015 at 12:10 AM, Christoph Wempe <notifications@github.com>
wrote:

> I am about to switch to a new phone.
>
> I want to export my config and import it on my new phone.
> But it looks like the export function does not export the waypoints any
> more. :(
>
> The "config.otrc" is 876 byte in size.
> I opened it with Notepad++ on my PC and cannot se anything about waypoints.
>
> Last time (#225 (comment)
> <https://github.com/owntracks/android/issues/225#event-376167958>)
> waypoints did get exported.
> Importing the file works for the rest of the settings, I guess.
>
> old Phone: Nexus 4, Android 5.1.1, Owntracks 0.5.22
> new Phone: Galaxy S6, Android 5.1.1, Owntracks 0.5.22
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/android/issues/279>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust

**Comment by binarybucks** [comment]
Could you test if this has been fixed in 0.5.23 beta?

**Comment by CWempe** [comment]
Is there an apk I can download?
I dont see an update via Play Store yet.
I already opted in as a beta user.

**Comment by jpmens** [comment]
If you are a beta user, launch Beta, click Refresh, and you should see this new version.

**Comment by CWempe** [comment]
Looks like I am beta tester for the old app.
Referenced here: http://owntracks.org/booklet/features/android/

Now, I will follow these steps:
https://community.owntracks.org/topic/41/public-beta-test-of-our-android-app

**Comment by CWempe** [comment]
Ok.
Importing the waypoints now works!

**Comment by jpmens** [comment]
You write 'importing', but you originally reported an issue on 'exporting'. Do both work for you?

**Comment by CWempe** [comment]
Sorry, yes.

Exporting works.
And to verify, I imported the config on my new phone as well.
Both running Owntracks 0.5.23

Issue is fixed for me.
