### ISSUE TITLE
Messages are not received

### ISSUE THREAD

**Issue by hoalex** [owntracks/android#281]
Hi there,

I wanted to try the messaging functionality as explained in the Owntracks [booklet](http://owntracks.org/booklet/features/msg/).
I issued the following command on my server:
```
mosquitto_pub -h localhost -l -q 2 -t owntracks/<myUser>/<myDevice>/msg
{"_type":"msg","prio":0,"title":"Library","desc":"Don't forget to return War and Peace","icon":"fa-book","tst":1435017442}
```
I can see via ``mosquitto_sub`` that the message is correctly received on the MQTT broker -- unfortunately, the Owntracks Android app does not seem to receive those messages. (Messaging functionality is activated under Preferences --> Advanced.)

Tested using version 0.5.23 under Android 5.1.1.

Regards
Alex

**Comment by binarybucks** [comment]
Could you try if messages are received at `/msg` instead?

**Comment by hoalex** [comment]
Sending messages to ``/msg``is working fine :+1:

**Comment by binarybucks** [comment]
Good, I just noticed there's a little issue with the direct message topic subscriptions. That's why you're not receiving them. Will be fixed in the next release. Thanks for noticing :+1:

**Comment by hoalex** [comment]
Perfect, thanks! :-)

**Comment by vrampal** [comment]
Hello, same here, I spent 2 hours trying to debug my MQTT system and understand why I never see the messages.
Then I realized it's the documentation that is wrong and not in line with the android app.
Can we re-open this issue until documentation and app are aligned ?
Thanks

**Comment by graugans** [comment]
Same here I can not get messaging working. The docs describe that the app subscribes to 

```
    owntracks/user/device/cmd if remote commands are enabled
    owntracks/+/+ for seeing other user's locations, depending on broker ACL
    owntracks/+/+/event (singular) for transition messages (enter/leave)
    owntracks/+/+/waypoint (singular) for Waypoint definitions/modifications
    owntracks/+/+/info for obtaining cards.
```

From this I tried to send messages to ``owntracks/chris/fp2/cmd`` a few commands work but no message is displayed.

```
mosquitto_pub -h xxxx -u xxx -P xxx  -p 8883 --capath /etc/ssl/certs/ -t owntracks/chris/fp2/cmd -l -q 2
{"_type":"cmd","action":"action","content":"Backend maintenance scheduled for tonight\n\nhttp://support.owntracks.org"}
```

**Comment by binarybucks** [comment]
This feature has been removed since a long time.
