### ISSUE TITLE
Re-publish all Waypoints via MQTT

### ISSUE THREAD

**Issue by hakan42** [owntracks/android#287]
I am working on a new OpenHAB binding, where a "configure all my waypoints" discovery step would be tremendously more user friendly if the user could be sure that the waypoint list of openhab and that of the client would be identical.

This is assuming that either the user might have configured waypoints that did not make it to the MQTT server (no connection, was connected to somewhere else, etc.) or the MQTT server forgot some of the messages because of misconfiguration on the user side (no persistent storage for example).

**Comment by jpmens** [comment]
Origin: [Community posting](https://community.owntracks.org/topic/77/re-publish-all-waypoints-via-mqtt)

**Comment by powermik** [comment]
While you are at it: Please add an option for sending the waypoints "retained"

**Comment by binarybucks** [comment]
as discussed previously we won't do that, as you would only receive the last waypoint when subscribing to the waypoints topic and not all waypoints that have been published. 

We don't see a reason, why you would be interested in the last published waypoint.

**Comment by hakan42** [comment]
> as discussed previously we won't do that

@binarybucks , is this comment an answer to me or to @powermik ?

**Comment by binarybucks** [comment]
that was a comment to @powermik 
Republish all will be added ;)
Ticket was closed because I hit the wrong button btw.

**Comment by powermik** [comment]
oh, seems that i misunterstood the documentation. i thought that the waypoints get published under 
waypoints/timestamp/
