### ISSUE TITLE
Create Tasker / Locale plugin to automatically switch reporting

### ISSUE THREAD

**Issue by hakan42** [owntracks/android#288]
While the automatic location reporting is nice, there might be cases where one wants to switch that off. And, so one does not forget to do so, have it done automatically. Use cases:

* I am leaving the office, but where I go next is my private information and should not be reported to the office server
* I am visiting some shopping places for surprise presents but don't want people at home to know of it prematurely
* insert-your-reason here

I can think of many other use cases where one might want to stop automatic reporting or maybe even switch reporting from the office MQTT to the private MQTT at home.

**Comment by jpmens** [comment]
We will accept that as a contribution.

**Comment by hakan42** [comment]
Of course :)

As soon as I am done with the openhab integration and switch back to android programming...
