### ISSUE TITLE
Go back from THANKS Menu

### ISSUE THREAD

**Issue by PedroLourenco** [owntracks/android#289]
It is not being possible to go back from THANKS Menu using actionBar icon.

**Comment by joshproehl** [comment]
@binarybucks Can this be closed with the closing of #290?

**Comment by binarybucks** [comment]
yes

On 04 Dec 2015, at 00:41, Josh Proehl <notifications@github.com> wrote:

@binarybucks <https://github.com/binarybucks> Can this be closed with the
closing of #290 <https://github.com/owntracks/android/pull/290>?

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/289#issuecomment-161825699>.
