### ISSUE TITLE
LocationMessage.java line 97

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#291]
#### in org.owntracks.android.messages.LocationMessage.toJSONObject

* Number of crashes: 33
* Impacted devices: 33

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/55fe7ad0f5d3a7f76b2be74a](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/55fe7ad0f5d3a7f76b2be74a)

**Comment by mrigankdembla** [comment]
Hey can you provide the authentication for fabric to open the above link and see the crash cause?
I want to contribute to the project and resolve the issues.

**Comment by binarybucks** [comment]
The Master branch has  a completely rewritten message serialization and deserialization which doesn't have the above issue. Thanks for your help, there'll be more issues to work on soon ;)
