### ISSUE TITLE
Android app doesn't suscribe right topic for Messages

### ISSUE THREAD

**Issue by clinique** [owntracks/android#294]
No message is received on the android app with the topic as described in the documentation. Instead, it works with /cmd. Found that after unsuccessfull trials and looked into code :

In ServiceBroker.java #442 :

if (Preferences.getDirectMessageEnable() && !Preferences.isModePublic())
topics.add(subTopicBase + Preferences.getPubTopicCommandsPart());

and in Preferences.java #595 : 
public static String getPubTopicCommandsPart() {
return "/cmd";
}

**Comment by binarybucks** [comment]
Thanks, fixed.
