### ISSUE TITLE
Can not see geo-fences on the map, but family/friends receive enter/leave events.

### ISSUE THREAD

**Issue by DuckY1987** [owntracks/android#296]
I don't see published and private waypoints on any of my test devices. Family-Members can see enter and leave events when i'm moving out from home or entering.

According to some documentation you should see the geo-fence on the owntracks/map where i can see only my devices but the private and published zones are missing.

I implemented the auth-plugin and i'm working with acl's but i've the super admin flag additionally so i should be able to see everything.

My used devices: Samsung galaxy s4 active, Samsung galaxy s5, One Plus Two. All up-to-date.

Did i forget smth or is that a known issue

**Comment by binarybucks** [comment]
Geofences are only displayed in the iOS version. On Android events are send
when you transition a fence, they are just not shown on the map.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 19 Dec 2015, at 21:13, DuckY1987 <notifications@github.com> wrote:

I don't see published and private waypoints on any of my test devices
Family-Members can see enter and leave events when i'm moving out from home
or entering

According to some documentation you should see the geo-fence on the
owntracks/map where i can see only my devices but the private and published
zones are missing

I implemented the auth-plugin and i'm working with acl's but i've the super
admin flag additionally so i should be able to see everything

Did i forget smth or is that a known issue

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/296>.

**Comment by DuckY1987** [comment]
thanks for the clear answer, is the implementation planed or is it kind of "work as designed" thing?

**Comment by jpmens** [comment]
If somebody is willing to contribute showing geofences on the Android map we would probably take it. As it stands we haven't planned adding this at the moment.

**Comment by binarybucks** [comment]
Indeed. That being said, it's not difficult to implement but we've many
more important things to do before.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 20 Dec 2015, at 10:24, JP Mens <notifications@github.com> wrote:

If somebody is willing to contribute showing geofences on the Android map
we would probably take it. As it stands we haven't planned adding this at
the moment.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/296#issuecomment-166095056>.
