### ISSUE TITLE
Add simple API so other apps can publish related topics

### ISSUE THREAD

**Issue by watou** [owntracks/android#300]
An openHAB user [asked about a way to track his car's metrics via a Bluetooth OBDII device](https://community.openhab.org/t/connected-car/6682) when he's driving around, so not only is OwnTracks doing its job, but he can also see other metrics from his vehicle.  

I suggested that he fork this project, add the Bluetooth bits and off he goes.  But thinking more about it, if OwnTracks had a simple API through which other Android apps could provide a stream of MQTT subtopics and metrics into OwnTracks, then he could write just the Bluetooth OBDII app, and just use OwnTrack's existing broker connection and infrastructure to publish the additional data alongside the topics that OwnTracks already publishes.  The "plugin" app's data could also be rendered in OwnTracks's UI, so the plugin app wouldn't even need a UI.

A simple API would help avoid the negatives of forking and diverging, and opens up other kinds of companion applications where specific devices could augment the picture that OwnTracks provides without OwnTracks having to care anything about these external devices.

**Comment by jpmens** [comment]
This sounds pretty far fetched, and it is quite out of scope for OwnTracks. If at all, and this would have to be really well thought out, we _might_ consider a contribution for such an API if it where _publish-only_ (we will not do additional subscriptions), i.e. your API could publish through Android to the broker. We will not, however, spend any time on this.
