### ISSUE TITLE
MikePenz Library Problem

### ISSUE THREAD

**Issue by brok85** [owntracks/android#303]
Dear OwnTracks Developers,
I am implementing a hang-bug detection tool and I am analyzing OwnTracks with it (master version). I found that the main thread of OwnTracks frequently calls

**android.graphics.BitmapFactory.decodeStream**

every time a user location is opened. In particular, the above API is called as consequence of using a MikePenz library function as follows:

**...
org.owntracks.android.support.DrawerFactory.buildDrawerV2(DrawerFactory.java:123)
com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:803),
 com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79),
android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:72),
...
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)**

at the very end. The Android documentation states, the decode* functions should not be executed on the UI thread. As a result, moving the execution of the BitmapFactory.decodeStream(...); off the main thread leads to higher responsiveness (smoothness) of the app. 

Do you think that the smoothness of the app would improve by executing the library function AccountHeaderBuilder.build in a background thread rather than on the main thread? Do you think it is possible to do so or that function MUST be called from the main thread?

Thanks for any information,
I hope I can help improve OwnTracks

**Comment by binarybucks** [comment]
That's an interesting find and will certainly help. 
Could you give me a complete stacktrace for the method in question?  I assume that you refer to the Contacts list with "every time a user location is opened" ? 
It's probably  an issue with the drawer library which tries to decode a user image even though none is used.

**Comment by brok85** [comment]
Hi,
glad to help. Yes I mean that when i click on a contact the map is opened with the position of the contact. The hang described in the previous message happens whenever I click on a contact to check its location:

```
android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
 android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
 android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
 android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
 android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
 android.content.res.Resources.loadDrawable(Resources.java:2540)
 android.content.res.Resources.getDrawable(Resources.java:806)
 android.content.Context.getDrawable(Context.java:458)
 android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
 android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
 android.support.v7.widget.TintManager.getDrawable(TintManager.java:175)
 android.support.v7.widget.TintManager.getDrawable(TintManager.java:168)
 android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:51)
 android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:72)
 com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
 com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:171)
 com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:803)
 org.owntracks.android.support.DrawerFactory.buildDrawerV2(DrawerFactory.java:123)
 org.owntracks.android.activities.ActivityMain.onCreate(ActivityMain.java:102)
 android.app.Activity.performCreate(Activity.java:6251)
 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
 android.app.ActivityThread.-wrap11(ActivityThread.java)
 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
 android.os.Handler.dispatchMessage(Handler.java:102)
 android.os.Looper.loop(Looper.java:148)
 android.app.ActivityThread.main(ActivityThread.java:5417)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by binarybucks** [comment]
Ok, the cause was the background image of the navigation drawer header. This really is an issue with the library which decodes the bitmap on the UI thread. 

I've temporarily removed the header in the latest commit. Could you check if the problem still occurs? 

Also, did you you find any other issues? 
I'm intrigued by your hang-bug detection tool, can you tell me more about it?
