### ISSUE TITLE
iBeacon from imported waypoints file does not shop up in waypoints list

### ISSUE THREAD

**Issue by hoalex** [owntracks/android#307]
Hi there,

I wanted to add an iBeacon to my waypoints lists. I followed the guide in the [booklet](http://owntracks.org/booklet/features/beacons/) and sent the following file (with a _.otrw_ file ending) to myself:

> {
  "waypoints" : [
    {
      "tst" : 1432817332,
      "lat" : 52.0,
      "_type" : "waypoint",
      "lon" : 6.0,
      "rad" : 0,
      "desc" : "Wohnung:E2C56DB5-1234-48D2-B060-D0F5A71096E0"
    }
  ],
  "_type" : "waypoints"
}

I then:

1. opened the file on my device
2. Owntracks displays a preview of the file
3. Select the checkmark symbol to accept the import
4. Owntracks displays a message that it needs to restart
5. I select "restart"

After restarting I do not see the waypoint in my waypoints list. Consequently, no waypoint events for this iBeacon are being sent.

I tried exporting my config in the preferences menu -- it does not show up there, either. I do have two other waypoints configured manually (georegion, no iBeacon), which work and also show up in the app just fine.

If I can be of any help in debugging this please let me know! :+1: 

## Device
- Sony Xperia Z3
- Android 5.1.1
- Owntracks 0.5.23

**Comment by jpmens** [comment]
iBeacons are not (yet) supported in our Android version; we're working on that.

**Comment by hoalex** [comment]
Whoops, well that explains it, doesn't it :-)
I think a short notice in the booklet would be useful, as it is not really clear from the explanation that the Android app does not yet support iBeacons. Or maybe show an error when importing such a waypoint file in the Android app.

Either way, now that I know that it's not implemented yet, I will try to get it running with my iOS device :-)

**Comment by binarybucks** [comment]
If we add warnings for all the features we do not support on android, we
would have even less time to add those :D

That being said, beacon support will arrive soonish.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 16 Feb 2016, at 18:42, hoalex <notifications@github.com> wrote:

Whoops, well that explains it, doesn't it :-)
I think a short notice in the booklet would be useful, as it is not really
clear from the explanation that the Android app does not yet support
iBeacons. Or maybe show an error when importing such a waypoint file in the
Android app.

Either way, now that I know that it's not implemented yet, I will try to
get it running with my iOS device :-)

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/307#issuecomment-184793681>.

**Comment by hoalex** [comment]
Well, you have a point ;-) Looking forward to beacon support! Keep up the awesome work :) :+1:

**Comment by jpmens** [comment]
@hoalex you are quite right: the Booklet should mention that. I will add a note right now.
