### ISSUE TITLE
Delete Waypoints by long holding

### ISSUE THREAD

**Issue by NiJen** [owntracks/android#316]
It will be more intuitiv to delete a Waypoint by holding it long and a context menu.

**Comment by skorokithakis** [comment]
Agreed, sliding is an iOS interaction and almost unknown to Android users. I didn't know how to delete waypoints for a long time until I stumbled upon swiping. A trash bin on the top right of the edit menu (next to the location button) would do as well.

**Comment by travisghansen** [comment]
Wow, yeah I couldn't figure out how to delete them until I read this (for either iOS or Android).

**Comment by binarybucks** [comment]
Next version implements the long press actionmode for deletion
