### ISSUE TITLE
random points with same tst after network is connected

### ISSUE THREAD

**Issue by eschava** [owntracks/android#317]
I have owntracks android application installed at the car and it works all the time but networking is enabled only after ignition is on
And it reports many random points right after network is connected.
Mqtt messages look like (note same tst value)
{"_type":"location","lon":35.0083256,"tid":"so","acc":1038,"tst":1456816609,"lat":48.4241701}
{"_type":"location","lon":35.00635,"tid":"so","acc":22,"tst":1456816609,"lat":48.4196566}
{"_type":"location","lon":35.001365,"tid":"so","acc":18,"tst":1456816609,"lat":48.427945}
{"_type":"location","lon":35.0072733,"tid":"so","acc":18,"tst":1456816609,"lat":48.4198333}
{"_type":"location","lon":35.0024183,"tid":"so","acc":10,"tst":1456816609,"lat":48.4248116}
{"_type":"location","lon":35.006985,"tid":"so","acc":10,"tst":1456816609,"lat":48.4204583}
{"_type":"location","lon":35.0022716,"tid":"so","acc":26,"tst":1456816609,"lat":48.4286249}
{"_type":"location","lon":35.0065449,"tid":"so","acc":12,"tst":1456816609,"lat":48.4207116}
{"_type":"location","lon":35.0018866,"tid":"so","acc":24,"tst":1456816609,"lat":48.42573}
{"_type":"location","lon":35.0065266,"tid":"so","acc":11,"tst":1456816609,"lat":48.4207966}

and track (recorded by recorder) like below:
http://dl.dropbox.com/u/450959/screenshots/screen160303-101415.png

**Comment by jpmens** [comment]
This looks quite normal to me; it is due to varying reports (GPS, WiFi), and we see this kind of behavior also with GPS-only devices.

**Comment by eschava** [comment]
It can  be acceptable if these messages have correct timestamp (tst field). But now it's same for all of them!

**Comment by jpmens** [comment]
Indeed; sorry: I hadn't noticed that.
I'm marking this as a bug.

**Comment by binarybucks** [comment]
That's strange. I could understand it if the tst values were different. In
that case they could be queued message.
The next version includes a completely new message backend so I'd suggest
you report back if the error persists when the new version is out in beta
(soonish).

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 03 Mar 2016, at 09:15, Eugene Schava <notifications@github.com> wrote:

I have owntracks android application installed at the car and it works all
the time but networking is enabled only after ignition is on
And it reports many random points right after network is connected.
Mqtt messages look like (note same tst value)
{"_type":"location","lon":35.0083256,"tid":"so","acc":1038,"tst":1456816609,"lat":48.4241701}
{"_type":"location","lon":35.00635,"tid":"so","acc":22,"tst":1456816609,"lat":48.4196566}
{"_type":"location","lon":35.001365,"tid":"so","acc":18,"tst":1456816609,"lat":48.427945}
{"_type":"location","lon":35.0072733,"tid":"so","acc":18,"tst":1456816609,"lat":48.4198333}
{"_type":"location","lon":35.0024183,"tid":"so","acc":10,"tst":1456816609,"lat":48.4248116}
{"_type":"location","lon":35.006985,"tid":"so","acc":10,"tst":1456816609,"lat":48.4204583}
{"_type":"location","lon":35.0022716,"tid":"so","acc":26,"tst":1456816609,"lat":48.4286249}
{"_type":"location","lon":35.0065449,"tid":"so","acc":12,"tst":1456816609,"lat":48.4207116}
{"_type":"location","lon":35.0018866,"tid":"so","acc":24,"tst":1456816609,"lat":48.42573}
{"_type":"location","lon":35.0065266,"tid":"so","acc":11,"tst":1456816609,"lat":48.4207966}

and track (recorded by recorder) like below:
http://dl.dropbox.com/u/450959/screenshots/screen160303-101415.png

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/317>.
