### ISSUE TITLE
Preferences import can not be unset from preferences window

### ISSUE THREAD

**Issue by sethwoodworth** [owntracks/android#319]
I exported my preferences from the owntracks android app and emailed it to a friend.  He installed the app, opened the preferences and was able to publish to our MQTT server (hooray!).  BUT, he has changed his identification in the app settings and is still publishing to the MQTT server as my user name and device name.

I am still able to change my user name and device names to whatever.  He has changed his user and device names in settings, but they have no effect.

**Comment by jpmens** [comment]
I hope you've learned you should have changed the `.otrc` file before sending it to your friend? (Sorry, couldn't resist :-) 

Please ask your friend to explicitly disconnect from within the app and then reconnect. Does that solve the issue? Also, have you ensured you're both using a *different* clientID? MQTT brokers will kick duplicate clientIDs automatically.

**Comment by sethwoodworth** [comment]
Explicitly disconnecting and reconnecting did not change what the device was reporting as. Neither did rebooting the device strangely enough.
Uninstalling the app and entering credentials manually worked.

Of course, editing the `.otrc` file in the first place should also have worked ;)
