### ISSUE TITLE
061: notification of transition on device

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#326]
Currently we see "Username has entered/left a location". Can we `s/a location/name of location/`, i.e. _Username has entered Home_ ?

**Comment by binarybucks** [comment]
Is the waypoint shared?

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 11 Mar 2016, at 20:52, JP Mens <notifications@github.com> wrote:

Currently we see "Username has entered/left a location". Can we s/a
location/name of location/, i.e. *Username has entered Home* ?

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/326>.

**Comment by jpmens** [comment]
Yes, but see #322
