### ISSUE TITLE
Shared regions do not add to other devices

### ISSUE THREAD

**Issue by travisghansen** [owntracks/android#346]
I may misunderstand this feature but my understanding of 'share' is that the waypoint should be published (which it is) but the clients don't seem to pick it up.

I've also noticed that the published waypoint format is different on iOS vs Android giving me more confusion.

Any thing I'm missing here?

**Comment by jpmens** [comment]
When a waypoint is shared it's not picked up by other devices connected to the same broker. What those devices _would_ see, however, (MQTT broker permissions permitting), are the _transition_ events your device caused, e.g. `JP has entered his favorite Indian restaurant`.

**Comment by travisghansen** [comment]
The doc is confusing to me then

```
If a description is entered and the share flag set, the location is published to the MQTT broker as a waypoint once. Waypoints shared by other users are displayed on the map and are visible in the Friends/Locations table.
```
I disabled sharing (on the Android specifically) and still saw enter/leave events going to the broker (and my other device).

I guess I'm still unclear if 'share' is meant for sharing the *waypoint* or the *events* or *both*

**Comment by jpmens** [comment]
On a non-shared Waypoint you should have seen something along the lines of "username enters (or leaves) a location", without "location" being specified. If the waypoint had been shared you should have seen the specific location being specified.

**Comment by jpmens** [comment]
> I've also noticed that the published waypoint format is different on iOS vs Android giving me more confusion.

Can you show us an example of each (xx for lat/lon is fine of course)?

**Comment by jpmens** [comment]
I don't see a difference:

### Android

```json
{"_type":"waypoint","desc":"andoroid","lat":88.3,"lon":22.0,"rad":500,"tst":1459152559}
```

### iOS

```json
{"_type":"waypoint","tst":1459152801,"lat":88.3,"lon":22.0,"rad":500,"desc":"ios"}
```

**Comment by travisghansen** [comment]
OK I'll jot that behavior down in my notes.

So publishing the waypoints have no effect in the iOS and Android clients directly (I'm sure they could be used by other subscribers however)?

I wasn't super clear about the differences in waypoints.  Specifically iBeacons.

iOS
```{"_type":"waypoint","tst":1459096125,"lat":XX,"lon":YY,"rad":-1,"desc":"-Home:e2c66db5-dffb-48d2-b060-d0f5a71096e0"}```

Android
```{"_type":"waypoint","desc":"-Home","lat":0.0,"lon":0.0,"tst":1459092888,"uuid":"e2c66db5-dffb-48d2-b060-d0f5a71096e0"}```

I've also noticed I can't use the ```-``` sign for radius on Android to force a publish of the lat/lon with the event.  I'll open a separate issue for that however.

**Comment by travisghansen** [comment]
This language is confusing as well regarding the 'share' functionality per my original understanding.

```Setting the radius to a negative value (e.g. -1), the app will update the location coordinates of the waypoint on each enter/leave event. This update will be transmitted to the broker when the share option is on and will be reflected on your map screen. You may use this to keep track of moveable items as luggage or your car.```

The doc leads one to believe that enter/leave *events* are not published is share is unselected.  Mostly just and FYI than anything as I understand the behavior now.

Thanks!

**Comment by binarybucks** [comment]
iOS alowed to input the UUID via the `desc` attribute in earlier versions. It should now also suppot the `uuid`, `major` and `minor` attributes to specify the beacon details. 

On export the format should probably be updated as well in iOS.

**Comment by binarybucks** [comment]
As mentioned in #348, the negative radius is not supported in Android.

**Comment by travisghansen** [comment]
@binarybucks that was entered on the most recent iOS version *not* using the desc field.
