### ISSUE TITLE
unable to set contacts to tracked devices/friends

### ISSUE THREAD

**Issue by dannykruitbosch** [owntracks/android#351]
Hi,

Since the latest (0.6.9) android version, I cannot set the contact anymore for a tracked device. Is this functionality removed? Or is this a bug?

Thanks,

Danny

**Comment by binarybucks** [comment]
This functionality was removed. You can provide contact details via [card messages](http://owntracks.org/booklet/features/card/) now.

**Comment by jpmens** [comment]
We removed the functionality in order to lower the permissions required by the app on the device; many people complained that "allow access to addressbook" was frightening.

**Comment by dannykruitbosch** [comment]
Would it be an idea to allow users to publish their own card to the broker? So fill in your friendly name somewhere, select your avatar and publish it to the broker?

Danny

**Comment by jpmens** [comment]
@dannykruitbosch You can do that from "outside" already, so we won't be adding that.

**Comment by jpmens** [comment]
@dannykruitbosch to clarify, by "outside" I mean from, say, a Python or similar program (curl does it too). Please check the linked Booklet section on cards.
