### ISSUE TITLE
Appcrash when picking "not available" friends

### ISSUE THREAD

**Issue by gummigroda** [owntracks/android#355]
Hi and thanks for a great app/service.

I think I found two "bugs" in Android Owntracks v.0.6.14

1) When clicking on a friend in the friendslist that doesn't have a retained location, the app craches. Status of the friend is set to "Not Available"

2) In the old versions it was possible to enter the app via the notification bar. Now when "clicked" nothing happens. I've to start the app via the app drawer.

This all on a Samsung S6 with Andriod 5.1.1

**Comment by binarybucks** [comment]
Thanks for reporting these. Both are confirmed and actually easy to fix. 
Am I right that for 1) you send a card message to create a contact that doesn't have a location yet?

**Comment by gummigroda** [comment]
1) Exactly!
