### ISSUE TITLE
Possible to set iBeacon scan interval?

### ISSUE THREAD

**Issue by travisghansen** [owntracks/android#357]
I'm looking for a real-time solution for scanning iBeacons.  Something similar to: http://wiki.aprbrother.com/wiki/Wireless_iBeacon_Receiver

In any case there seems to be a delay (and looking at the code I think it's 30 seconds in the foreground) for scans.  The easiest solution for me would be to plug in an android device and have it scan real-time, otherwise I'll be hunting for a solution with an RPi or similar.

Any tips or chance of making the scan interval configurable?

If no, has there been any thought to making a desktop owntracks client (specifically linux)? if so is any of the code here reusable for something like that?

Thanks!

**Comment by binarybucks** [comment]
The current version uses the always-on low-power background scanning on Andorid 5 and above.
