### ISSUE TITLE
Crash if no internal sdcard

### ISSUE THREAD

**Issue by johnjore** [owntracks/android#365]
If internal sdcard is missing / not available, app will crash after going through the 4? step intro and trying to launch GUI. (On Android 6.0.1 / Samsung S2 i9100) 

Seen with version 0.6.14. 

Bug report filed April 19th, around 10pm'ish. Can't reproduce as I've added back the internal sdcard. 

JJ

**Comment by binarybucks** [comment]
This is a bug in the Google Maps SDK which doesn't handle missing SD cards too well. 
See https://code.google.com/p/gmaps-api-issues/issues/detail?id=9021. Besides installing a SD card, there currently is no workaround until a new version of the Google Play services is available, sorry.
