### ISSUE TITLE
Friends GUI Update Error

### ISSUE THREAD

**Issue by johnjore** [owntracks/android#371]
Hi!

Looks like there is an intermittend error when enumerating Friends:

<img width="270" alt="screenshot_2016-04-27-10-57-27" src="https://cloud.githubusercontent.com/assets/12951842/14920197/380ff882-0e24-11e6-805b-b12c7d3386cb.png">

Friend 1 and 3 is actually the same device. The GUI has them both with the same ID and Address (the blacked out parts). Normally only one instance of the friend is shown, but occasionally, I see duplicates, as per the image above.

JJ

**Comment by binarybucks** [comment]
Maybe fixed.
