### ISSUE TITLE
transition trigger key not showing up in json as expected

### ISSUE THREAD

**Issue by pancho-villa** [owntracks/android#372]
[Per the docs for _type=transition](http://owntracks.org/booklet/tech/json/#_typetransition) the JSON payload has a `'t'` key. I'm running version 0.6.14 and my payload has a `'trigger'` key instead of the `'t'` key.

`{"_type":"transition",
"acc":18.349,
"desc":"my waypoint",
"event":"enter",
"lat":11.11,
"lon":22.22,
"tid":"6p",
"trigger":"c",
"tst":1462535691,
"wtst":1462534036}`

Is that expected? Does the `'t'` key only show up when it's a beacon triggered event?

**Comment by binarybucks** [comment]
Will be fixed in the next release, thanks.
