### ISSUE TITLE
No custom picture for friends

### ISSUE THREAD

**Issue by johnjore** [owntracks/android#373]
Hi!

I've tried to add custom icons to friends, but not successfull:

Contact on phone (w/picture associated and IM configured):
<img width="270" alt="screenshot_2016-05-06-15-41-19" src="https://cloud.githubusercontent.com/assets/12951842/15076828/7eaeee5e-13a3-11e6-9c58-edc92251d075.png">

Friend topic is the same:
<img width="270" alt="screenshot_2016-05-06-15-46-57" src="https://cloud.githubusercontent.com/assets/12951842/15076827/7eaa745a-13a3-11e6-825f-a3e24eaa6092.png">

Icon / for the friend remains a colored circle with the initials. Is this a known bug / problem with the android 0.6.14 client?

JJ

**Comment by jpmens** [comment]
What are  you actually trying to show us with all those black spaces? Those screenshots are pretty useless imo.

What did you do to add a friend? Tell us the steps you took.

**Comment by johnjore** [comment]
Black spots are there as I'm not interested in sharing too much private information. If you actually look at them you see the first is a contact with an IM defined and the topic. 2nd picture has the same topic for a friend. Icon does not update, even after restarting phone.

**Comment by jpmens** [comment]
Not sharing private information is more than fine for us; just omit. ;-)

Friends has changed in Android (and on iOS); please see [Cards in the Booklet](http://owntracks.org/booklet/features/card/).

**Comment by johnjore** [comment]
Its a screenshot of the phone. The area in black is the part thats omitted...

If http://owntracks.org/booklet/features/friends/ is no longer valid (on Android), then maybe it should be removed?

> "Add an instant-messaging ( IM ) entry to the contact you want to associate with a particular MQTT topic name. The tag of the  IM  should be " OwnTracks " (case independent), and the value is the topic name."

**Comment by jpmens** [comment]
Done.

**Comment by johnjore** [comment]
Not a bug as functionality had been removed. Documentation updated to reflect change in functionality. Closed.

**Comment by johnjore** [comment]
Btw, the documenation for "card" implies the functionality is still there:

From http://owntracks.org/booklet/features/card/

> but you can associate an address book entry to that friend in order to see a friendly face (if you have you friend's photo in your device's address book) and/or a friendly name.
