### ISSUE TITLE
OTRC import doesn't honour tid

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#374]
OTRC imported with `"tid":"xx"` in it, but device publishes a TID consisting of the last two characters of the `topic`

**Comment by binarybucks** [comment]
The key is `trackerId` per http://owntracks.org/booklet/tech/json/#_typeconfiguration, isn't it?

**Comment by jpmens** [comment]
This has slipped past many an eye ... We have tid in the export on iOS.
I've looked at an old export from Android, and you're right.

Would it be ok to ask you to revert to "tid", and I change the docs? ;-)

**Comment by binarybucks** [comment]
Chande in next release 0.7.3
