### ISSUE TITLE
Not getting region transitions with overlapping / concentric regions

### ISSUE THREAD

**Issue by haunma** [owntracks/android#376]
I came back to try Android Owntracks again (0.6.14) after not having much luck with it last year.  Part of the problem was probably my extensive battery-saving hacks on Kitkat.  Now I am using Cyanogenmod 13 (Marshmallow) and it seems to be working much better.  But I think I have identified a bug.

After verifying that comms with my MQTT server were working, I created a first region around my home with a large radius (10 km).  This worked great, and I was reliably getting transition events.  Then I added a second region with the same center point but a much smaller radius (100 m).  I need both because there are home-automation things I want to do when I am approaching my house (HVAC) and other things when I am very close (disarming an alarm system).  But what I have found is that I am now getting transition events only on the new, smaller region.  Since adding it, no more transitions have occurred on the original, large region.

Expected behavior would be for all regions to behave independently, even if they are exact duplicates of one another.

**Comment by binarybucks** [comment]
After some debugging, it seems that existing regions are removed when an additional one with the coordinates is loaded. I'll try to work around this

**Comment by haunma** [comment]
Could I work around this by moving one of the region centers slightly so the two don't exactly coincide?  The large-radius region doesn't have to be exactly centered.

**Comment by haunma** [comment]
FYI, today I tried adding a third region at my workplace, which does not intersect with the other two circles (the big and little circle around my house).

Result:  I now get transitions on the new "work" region, and no transitions on either of the two "home" regions.  So the issue may involve more than coinciding centers.

**Comment by binarybucks** [comment]
Indeed, it's a general problem that existing regions are removed once you add a new one 
Could you try to setup two or more regions and force close the app ? 
When the app is newly started, all regions should be requested in an orderly fashion.

**Comment by haunma** [comment]
I force-closed and restarted the app, and was almost ready to declare victory... but...

So I have three regions:  One big and one small around home, and one more around work (no overlap with the other regions).  After restarting the app, both home regions, big and small, are seeing regular transitions.  The work region, which is the third one in the list, has stopped working (no pun intended :)

I can't find a pattern here :|

**Comment by binarybucks** [comment]
Could you please drop me a mail to support@owntracks.org? 
I'd like to add you to the alpha testers list so you can test a possible fix for this issue. 
If you're interested, you can also join or semi-public Slack channel.

**Comment by haunma** [comment]
Email sent, thanks.

**Comment by hamfoo** [comment]
I am experiencing the same issue. I only get transition events published for the latest created region. Also using version 0.6.14.

Is there a solution on the way? and Also: is this also an issue on iOS?

**Comment by binarybucks** [comment]
yes, they do not work correctly on 0.6.x. 
A solution is on the way. 

This is not an issue on iOS as far as I know.
