### ISSUE TITLE
Feature request: action to update friend location on map

### ISSUE THREAD

**Issue by gadget1999** [owntracks/android#382]
Currently when click the friend icon on map, you can see details about this friend about his/her location, update time and etc. There is also an action at the bottom to navigate to the location.

It would be convenient if can also add an action to update the friend's location (if he/she allows remote command). This should not have privacy concern since it can only work when remote command is allowed, which could be disabled if the user wants.

This will be helpful for a group of friends who want to know the most up-to-date location information of each other without reporting too frequently (thus save battery).

**Comment by binarybucks** [comment]
This feature has been removed because the reliable/timely delivery of the reportLocation cmd cannot be guaranteed which lead to many questions from our users. Moreover, it is not supported in HTTP mode anyway.
