### ISSUE TITLE
Friends are not removed

### ISSUE THREAD

**Issue by avanc** [owntracks/android#383]
As I configured the owntracks app wrong on first setup, some data were publish to my MQTT broker with different phone name. I removed the retained data in mosquitto using mosquitto_pub and a zero length message as described in the documentation.
However, the item is still in my friends list. How I can remove it?

In addition, I published a CARD at the wrong topic. So I also have this in my friends list as _not available_, as location data for this topic was never published. I removed also this topic as decribed above, but owntracks did not recognize this (on two devices the same behaviour).

**Comment by binarybucks** [comment]
Confirm that they are removed by running mosquitto_sub.

If they are removed, force close the app and start it again.

**Comment by avanc** [comment]
Before, I closed the Owntracks app by swipe the app out of the tasks list.
Now I forced the daemon to stop and now the undesired friends are gone. Thanks.
But the behavior is not very intuitive.

However, the CARD information for my other friends are also missing. I still can see their positions, but no image nor name.

**Comment by avanc** [comment]
My mistake, I didn't configured persistence in mosquitto, so every retained message got lost after a restart of the broker.

But still, the client should remove friends, if it gets a zero-sized messages. Or does the broker does not publish such messages?

**Comment by protist** [comment]
> I removed the retained data in mosquitto using mosquitto_pub and a zero length message as described in the documentation.

Could someone please point me in the right direction for this documentation? I have the same problem with persistent "old" IDs in the the Android app. I had a look in the OwnTracks Booklet, but couldn't find anything.

**Comment by avanc** [comment]
@protist You have to restart the owntracks daemon. On Android, go to Settings -> Apps -> Select Owntracks -> Click "Stop application" (or something similar, "Beenden erzwingen" in German)

**Comment by protist** [comment]
Thanks @avanc, but that didn't seem to work. I tried killing it as you suggest, and holding the back button (which kills it in Cyanogenmod). I even tried restarting the phone. The device is still shown.

To clarify, I originally configured my phone with the wrong identifier. I then changed the identifier. However, I can still see a device with the original identifier, last updated three weeks ago, in addition to my new identifier.

**Comment by binarybucks** [comment]
You have to publish a retained null payload to the topic that you want
to clear before restarting the app.

**Comment by avanc** [comment]
Using mosquitto you can do the following:

    mosquitto_pub -t owntracks/<user>/<device> -r -n -h >yourmqttbroker> -p <portnumber>

**Comment by protist** [comment]
Thank you both. @avanc those instructions worked perfectly. Cheers.

**Comment by binarybucks** [comment]
GUI support has been added
