### ISSUE TITLE
Icon position on map does not correspond to received data

### ISSUE THREAD

**Issue by avanc** [owntracks/android#384]
When opening the app (after it was in the background), the position of firends icons are at a wrong place. If I select a friend from the GUI (where the new location is written already), the map jumps to the correct position. It seems that the map is only updated if a friend is selected, but not on arrival of a new MQTT message.

In additions, sometimes the map jumps to the right position, but no icon is shown.

This might be related to the comment https://github.com/owntracks/android/issues/367#issuecomment-229810735, but I created a new ticket, as this problem seems not related to network switches.

**Comment by binarybucks** [comment]
you're right. I think the problem will be fixed in the next version that I'm currently working on.
