### ISSUE TITLE
Private HTTP support

### ISSUE THREAD

**Issue by mrdon2** [owntracks/android#386]
The android client should support connecting via private HTTP.  

See https://github.com/owntracks/android/pull/385 for the PR.

**Comment by binarybucks** [comment]
Well, the current feature-android-n branch supports HTTP mode. It's just not finished yet ;)

**Comment by mrdon2** [comment]
Sure, and my PR is based off that branch, adding in a few other things.

**Comment by binarybucks** [comment]
The PR is based on the http-mode branch which is quite some commits behind ;) 
I'll incorporate the changes nevertheless.

**Comment by mrdon2** [comment]
Great thanks.  We've been running a locally-built apk with this PR for the last few days and it has been working fine.  I'm anxious to get an official app store release though for us and any other sandstorm folks.

**Comment by binarybucks** [comment]
One question, you added preferences fields for deviceId and trackerId in HTTP mode. 
However, those preferences values are not used in http mode yet, as everything is supplied in the POST url. What is the purpose of those two new fields?

**Comment by binarybucks** [comment]
I suggest we take the same identification view as for private MQTT mode. 

Authentication => Switch
Username  => sent as `X-Limit-User` header. If authentication is enabled, additionally used for HTTP basic auth. 
Password => If authentication is enabled, used for HTTP basic auth. 
DeviceId => sent as `X-Limit-Device` header 
TrackerId  => included in JSON message payload 

It is additionally possible to provide a URL in the format `http(s)://user:password@host:port?u=USERNAME&d=DEVICEID`. 
If both are specified, I suggest the URL parameters for HTTP auth are preferred. The username and deviceid parameters are sent anyway. It is then up to the application to prefer one over the other. 

What do you think?

**Comment by mrdon2** [comment]
The reason I added the device and tracker id is it would pick a device name that was the same as the display user name (in sandstorm at least).  This meant that the user name was "don brown" and device id was "don brown" with the tracker id derived from those.  The space screwed up the friends configuration, generally made it more clumsy, and made the display tracker id really confusing.  Once I added a way to set the tracker id, I got the expected ID.  

That said, for some reason, the device id was still the user name.  I haven't looked into why that wasn't taking.

**Comment by mrdon2** [comment]
As for allowing user/pass in http mode, that's fine with me - less code and more flexible.

**Comment by mrdon2** [comment]
So looking more, I think the tracker id is sent in the HTTP message, but the device ID isn't, which explains what I was seeing.  Looks like device ID gets set on the server somehow?

**Comment by binarybucks** [comment]
The device id isn't meant for showing the user name. It is for separation
of different devices from the same user and stems from the MQTT origins of
OwnTracks. Please don't misuse it and use the tracker ID instead ;)

Am 14.08.2016 6:51 nachm. schrieb "mrdon2" <notifications@github.com>:

**Comment by mrdon2** [comment]
Oh, I know.  I think it was the Sandstorm backend that was creating a device id that was the user name, which caused problems due to that space character.  By adding a field for it in the mobile app, I was hoping to override that and use it for a device identifier again.

The reason device id even matters is for the friend configuration.  Without that (because you can't do * matches on topics in HTTP mode), there is no way to see other people's location.

**Comment by binarybucks** [comment]
I'm not familar with what Sandstorm is tbh, but our Recoder supports HTTP just fine with those fields ;)

**Comment by strugee** [comment]
Re: Sandstorm - see https://apps.sandstorm.io/app/cjv3p2a970vrm729x9x0v54k0nff6x6s2xcgwvgpuzhgk56wum5h. Tl;dr: selfhosted freedom-respecting webapps made as easy as an app store.

**Comment by surge919** [comment]
@mrdon2 
Do you have instructions for building the APK locally or have you posted your version anywhere?

While the world awaits the official version, I'd like to use my private HTTP server.

thanks.

**Comment by compuguy** [comment]
@binarybucks so how do you use the currently posted owntracks app with https host?

**Comment by compuguy** [comment]
I don't know why this is closed @friesenkiwi with the official posted version on google play not supporting this...

**Comment by binarybucks** [comment]
We're on the final steps of testing things before there will be a public version.

**Comment by binarybucks** [comment]
@compuguy also, thanks for leaving a 1 star rating in the store, really encourages me to continue development. 
Im sorry that I've not added all the features you wish while investing my free time.

**Comment by jberger** [comment]
@binarybucks I'm sorry other people are jerks. I've just stumbled over this project and I'm chomping at the bit to try it! I'm a core developer of Mojolicious, a Perl-based non-blocking web framework (think node.js for Perl) and I would LOVE to have HTTP support on android. I got to the point of injesting data when I realized that Android doesn't have HTTP yet. 

Thanks you SO MUCH for taking your spare time and building a better/safer way to track phones in the privacy of our own hosted services! Cheers!

**Comment by compuguy** [comment]
@binarybucks I was annoyed at the time, because the sandstorm version of owntracks doesn't support the traditional MQTT configuration. I understand you do this in your spare time, but you should have this upcoming feature listing the upcoming features.
