### ISSUE TITLE
Barcode scanning for private HTTP url input

### ISSUE THREAD

**Issue by mrdon2** [owntracks/android#389]
It would be nice to support barcode scanning for private HTTP host URL input.  It would be particularly nice for Sandstorm configuration, where the URL can be quite long.

**Comment by mrdon2** [comment]
I added the comment to PR https://github.com/owntracks/android/pull/385

**Comment by binarybucks** [comment]
There's already a very solid config import system and adding a QR code import is on the todo list for a long time now. Would you be willing to add that instead so other users may also profit from it? 

I'll merge my changes into the master branch and resolve some errors so we're talking about the same code base and don't have to resolve a ton of conflicts.

**Comment by binarybucks** [comment]
Could you check if you can add QR import of `configuration` messages to the `Export` menu in the Preferences? 
Should work similarly to the import of messages for which code is already present, as long as the QR library supports `startActivityForResult`.

**Comment by mrdon2** [comment]
What about both?  Being able to import a URL is handy with a chrome or firefox extension that let's you turn any URL into a qrcode.  Once we merge the mqtt and and http configuration screen, both would benefit.  BTW, am I doing that merge or are you?

To do the export, I'll have to bring in more code to add qrcode generation, but it shouldn't be difficult.

**Comment by binarybucks** [comment]
MQTT mode doesn't have any URLs to import hence I'm not too keen to merge
the commit in its current form.

Adding a generic QR import benefits all modes instead. Additionally, it
will allow you to provide many more settings to the user or distribute the
config in other fotms.

Am 14.08.2016 7:18 nachm. schrieb "mrdon2" <notifications@github.com>:

**Comment by mrdon2** [comment]
Ah right, we are merging the identification screen, not the host one.  Well still, I'd like to keep the barcode reading for the host form as it makes it a bunch easier to import an arbitrary URL with no backend changes required.

I'm working on the barcode export/import now.

**Comment by binarybucks** [comment]
Ok, good point.

I'll merge the host barcode form and identification form manually into
master. Please  submit a new PR for the general import on the master branch
if you're done.
If you need any help, open a new issue please.

Am 14.08.2016 7:29 nachm. schrieb "mrdon2" <notifications@github.com>:

**Comment by binarybucks** [comment]
Added scanner with commit c31676e27c14d51ea951422271ea623ed898f061. 
I've replaced the button with a long press listener on the url field. 

Also, added the identification preferences.

**Comment by binarybucks** [comment]
@mrdon2 could you drop me a mail to support@owntracks.org? 
I'd like to invite you to the Google Play alpha release channel and our semi-public Slack channel if you like.
