### ISSUE TITLE
Shows my device at old location

### ISSUE THREAD

**Issue by watou** [owntracks/android#392]
OwnTracks is always showing my device location as my old home address, a location that my device has not been to since the end of last month (over two weeks ago).  When I then open Google Maps, it briefly shows me at that incorrect location, and then quickly updates to my actual location.  Then, when switch back to OwnTracks, it updates to show my correct location as Google Maps does.  This scenario happens consistently.

1. What could possibly have either my device or OwnTracks "remember" a location, repeatedly, to which neither I nor my device has been to for two weeks?
1. Why does opening Google Maps correct the problem, and running only OwnTracks does not?

I am using OwnTracks 0.6.14 on a Nexus 5 running 6.0.1.  Thank you.

**Comment by binarybucks** [comment]
Is the current location indicator (blue dot) at the wrong location or a
reported location (your marker when you click in the item in the friends
list?

We're getting locations from Android. So when even Google Maps shortly
shows you at your old location, there likely is an old location stuck
somewhere in the location API. I suggest you try to restart your device and
disable/enable the location services.

What might also happen, if you moved and took your WIFI router with you,
Android/Google might have cached the old SSID location which now confuses
the location service. This has actually happened to me some time ago when I
noved. It took several weeks until the SSID location automatically got
upxated. You might try to rename your SSID though if that is an option for
you.

**Comment by watou** [comment]
> if you moved and took your WIFI router with you,
Android/Google might have cached the old SSID location which now confuses
the location service. This has actually happened to me some time ago when I
noved. It took several weeks until the SSID location automatically got
upxated.

That has to be the explanation. Thank you very much for that insight and experience.
