### ISSUE TITLE
Ignore _old_ location pubs

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/android#401]
Ignore any retained location pubs that are older than *n* days (configurable?). Means spurious retained pubs that are left lying around by old devices/users don't pollute the app (without having to clear those topics).

**Comment by binarybucks** [comment]
That's actually a really great idea and also quite easy to implement. 
Defaults to on and 7 days?

**Comment by sumnerboy12** [comment]
Yeah I guess 7 days is sensible - @jpmens was thinking 10 or 30 - what are your thoughts on a hidden config option (set via `.otrc`)? Seems like something that someone is going to want to extend or disable? Don't need any UI so simpler to implement?

**Comment by jpmens** [comment]
[more comments](https://github.com/owntracks/ios/issues/410)
