### ISSUE TITLE
WiFi enabled / Roaming Not Enabled - Remains Disconnected

### ISSUE THREAD

**Issue by johnjore** [owntracks/android#405]
Hi!

When travelling abroad I dont have data roaming enabled, but rely on hotel / guest WiFi connections. I noticed that OwnTracks remains in Disconnected state, see screenshot, even after several hours. E.g. next morning, OwnTracks was still in disconnected state. If manually pressing the right buttons (force disconnect / connect), OwnTracks would connect. This happened throughout the journey, OwnTracks would not re-connect when WiFi become available without manual intervention.

<img width="270" alt="screenshot_2016-09-02-16-10-54" src="https://cloud.githubusercontent.com/assets/12951842/18413107/08ad2f1a-7797-11e6-8360-ff6f1e1ad2ba.png">

Hopefully this can be fixed.

JJ

(PS: I think this is different from my other issue as its not error (re-) connecting, but OwnTracks (incorrectly) stating that there is no data connection.)

**Comment by binarybucks** [comment]
The underlying cause is the same as the other issues. You may close that
one for now.

**Comment by johnjore** [comment]
Closing as duplicate of previous issue.
