### ISSUE TITLE
Battery drain when using with Home Assistant

### ISSUE THREAD

**Issue by sgauche** [owntracks/android#407]
I'm using owntracks with Home Assistant over a private MQTT broker (mosquitto).  I recently saw this in my Home Assistant log.  It seems like OwnTracks did a bunch of rapid reports with very low accuracy and managed to drain the battery on the phone by 3% in 2 seconds.  Is there anything that would cause OwnTracks to act like this?  I have Home Assistant publish a location request update every 15 minutes.
```
    topic: "owntracks/sgauche/nexus5x/cmd"
    payload_template: '{"_type":"cmd","action":"reportLocation"}'
```

I edited the GPS coordinates for privacy, but the first 4 and the last report were all the same coordinates and then the 2nd and 3rd from last reports were the same and only about 1500 ft from the other 5 reports.
```
16-09-21 13:47:31 homeassistant.components.device_tracker.owntracks: Ignoring location update because expected GPS accuracy 100.0 is not met: {"_type":"location","acc":2000,"batt":91,"lat":41,"lon":-84,"tid":"kl","tst":1474469172}
16-09-21 13:47:31 homeassistant.components.device_tracker.owntracks: Ignoring location update because expected GPS accuracy 100.0 is not met: {"_type":"location","acc":2000,"batt":91,"lat":41,"lon":-84,"tid":"kl","tst":1474470985}
16-09-21 13:47:31 homeassistant.components.device_tracker.owntracks: Ignoring location update because expected GPS accuracy 100.0 is not met: {"_type":"location","acc":2000,"batt":90,"lat":41,"lon":-84,"tid":"kl","tst":1474472798}
16-09-21 13:47:31 homeassistant.components.device_tracker.owntracks: Ignoring location update because expected GPS accuracy 100.0 is not met: {"_type":"location","acc":2000,"batt":90,"lat":41,"lon":-84,"tid":"kl","tst":1474474611}
16-09-21 13:47:32 homeassistant.components.device_tracker.owntracks: Ignoring location update because expected GPS accuracy 100.0 is not met: {"_type":"location","acc":1900,"batt":90,"lat":42,"lon":-85,"tid":"kl","tst":1474476424}
16-09-21 13:47:32 homeassistant.components.device_tracker.owntracks: Ignoring location update because expected GPS accuracy 100.0 is not met: {"_type":"location","acc":1900,"batt":89,"lat":42,"lon":-85,"tid":"kl","tst":1474478237}
16-09-21 13:47:32 homeassistant.components.device_tracker.owntracks: Ignoring location update because expected GPS accuracy 100.0 is not met: {"_type":"location","acc":2000,"batt":88,"lat":41,"lon":-84,"tid":"kl","tst":1474480050}
```

**Comment by binarybucks** [comment]
Draining the battery by 3% in 2 seconds is unlikely caused by OwnTracks (unless you charged the phone to 100% after which it suddenly dropped to 97%). 

Rapidly publishing messages will drain the battery rapidly, but it will not drain the phone from 100% to 0 in ~60 seconds. From 3% drain it's hard to tell what caused this. Maybe you simply experienced a glitch in the battery calculation. 

Is the behavior reproducible?

**Comment by sgauche** [comment]
I will watch for it to happen again.  I'm not sure what triggered it so it's hard to reproduce.

**Comment by binarybucks** [comment]
Please reopen this issue if you can reproduce it.

**Comment by jfarcher** [comment]
For me it wasn't just the draining of the battery, but the impact on performance of the device. Slowing it down to be almost unusable.

**Comment by binarybucks** [comment]
This seems to be an issue with Home Assistant. 
I'm not familiar with that that software beyond it's name so I suggest you help me out and explain how it works and what it does. If possible, capture the output of mosquitto_sub for all topics of the device that is seeing the battery issues. I suggest a wildcard subscription to check if there are misbehaving cmd messages being send by Home Assistant. 

What you could also do is check if your background location accuracy is set to high. In that case the app will try to immediately publish locations that come in from the GPS which might hit the device with several updates per second.

**Comment by binarybucks** [comment]
@jfarcher, could you also post an export of your configuration here (minus sensitive information of course)

**Comment by jfarcher** [comment]
I'll grab relevant detail now.

**Comment by jfarcher** [comment]
Configuration export

[config.txt](https://github.com/owntracks/android/files/491158/config.txt)

**Comment by binarybucks** [comment]
nothing wrong with that configuration as far as I can tell. 
I suspect, that Home Assistant is sending too many commands or there is a message loop somehow. 
Could you verify this by collecting mosquitto_sub output from your broker please?

**Comment by jfarcher** [comment]
I've just re-installed and configured it again, (device id should have been jonphone in that config so home assistant recognises is)
just running a sub now to get output, home assistant doesn't send commands that I know of.

**Comment by binarybucks** [comment]
As I mentioned, I have no clue how that software works. 
@sgauche mentioned that "I have Home Assistant publish a location request update every 15 minutes"

**Comment by binarybucks** [comment]
Could you please explain your setup and the involed components a bit?

**Comment by jfarcher** [comment]
As far as Home assistant is concerned it's a consumer of owntracks data. It takes the location and based upon zones specified within Home Assistant it can display on the interface (or a map) whether known devices are home or away, other zones can be configured i.e. work for tidy looking status. 

So far I've never seen a message go to the broker to request location - I'm constantly monitoring the wildcard to see what goes in.

**Comment by jfarcher** [comment]
My setup is a broker running mosquitto - websockets enabled and thats how the owntracks app connects. Home assistant runs on a seperate server, its a python application which subscribes to owntracks data (and other data) via mqtt for various home automation tasks (Similar to OpenHAB)

**Comment by jfarcher** [comment]
And so far since we've been talking I've only seen 4 owntracks messages come into mqtt.
owntracks/jon/phone {"_type":"location","acc":114,"batt":63,"lat":53.6897125,"lon":-2.2991867,"tid":"JA","tst":1474728066}

**Comment by binarybucks** [comment]
May I add you to our alpha build just to make sure it's not a bug that is already fixed? 
If so, please send me the email address of your Google account to support@owntracks.org so I can approve the update for you.

**Comment by jfarcher** [comment]
Of course!
I'll monitor this over the next day or so.

**Comment by pancho-villa** [comment]
I'm also running home-assistant and mosquitto and I don't see any log entries out of the ordinary. Looking at the logs shows 5 entries for me over 24 hours.

**Comment by jfarcher** [comment]
@pancho-villa are you seeing perfomance issues or battery drain also?

**Comment by binarybucks** [comment]
@jfarcher could you try with the latest alpha versions? Besides monitoring mosquitto_sub, checking the broker logs for irregular MQTT messages (many subs, reconnects, TLS errors, etc.) could also be helpful.

@pancho-villa would help if you also stated your problem ;)

**Comment by pancho-villa** [comment]
@jfarcher Not that I can tell. What indicates Owntracks is related to the battery drain issue?

@binarybucks Apologies, I don't have any issues, I was simply commenting that I run the same environment and was trying to get more information on the issue as it may be occurring on my system without my knowledge.

**Comment by jfarcher** [comment]
@binarybucks I installed the Alpha, although I was finding poor performance on the phone yesterday and uninstalled as I needed to use it. I will be testing more throughout the week and will install the latest alpha.
@pancho-villa battery drain issue is shown by 2 things, massive drain when installed compared to not installed also when drain occurs it shows up as top battery user in battery settings detail.
I was seeing phone drain completely in half the time it would normally.

**Comment by binarybucks** [comment]
You'd do me a great favor, if you could collect your devices LogCat output when you encounter this issue. If you've got ADB installed on Windows you can plug in the device and collect the output through `adb -d logcat org.owntracks.android:V`. Alternatively, there are some apps that allow you to view it on the device.

**Comment by sgauche** [comment]
The battery drain didn't seem to show this time, but the repetitive updates happened again.
![image](https://cloud.githubusercontent.com/assets/8250717/18994004/ea1b439a-86f3-11e6-8c9b-285ed8f287ad.png)

**Comment by binarybucks** [comment]
which version?  
You could try to play with larger fences or suppress messages with low accuracy with the new config parameter. Besides that, there's not much we can do against hyperactive geofences.

**Comment by sgauche** [comment]
0.6.14

I have a 350 meter radius on the region, but I will try increasing it.

**Comment by sgauche** [comment]
@binarybucks What is the "new config parameter"?

**Comment by binarybucks** [comment]
See https://community.owntracks.org/topic/225/android-v-1-1-2-beta. 
You need to install the beta first though. It also contains some changes to geofences that should minimize the occurences of your problem.

**Comment by binarybucks** [comment]
Please reopen, if there is any new input on this issue
