### ISSUE TITLE
tremendous battery drain and performance issues

### ISSUE THREAD

**Issue by jfarcher** [owntracks/android#408]
As reported via play store, I revisited Owntracks yesterday and found that my battery drained rapidly.

To answer your question from Play store, yes I'm using home assistant.

I find that having the application installed severely impacts the performance of the device, slowing down the phone so much that general usage is difficult.

I'm using the Moto X Play device, but also found exactly the same symptoms on a brand new Moto G4 device.

**Comment by binarybucks** [comment]
Thanks for reporting back, as you're using Home Assistant, I'm closing this issue in favor of a previously reported one, please head over to #407
