### ISSUE TITLE
Beta 0.6.14 doesn't show error message for MQTT error

### ISSUE THREAD

**Issue by kvoit** [owntracks/android#412]
Today, I failed to renew my Letsencrypt cert, resulting in a connection error. My Beta client only gave "Error" below "Connection" in setting. My wifes stable version gave a detailed error report that pointed me to the problem. 
This has been helpful multiple times and should be added again.

**Comment by binarybucks** [comment]
Fixed with 205ebba913f31ce387148c15d8ff27bf18ab8dae
