### ISSUE TITLE
Timestamps in Status view are wrong

### ISSUE THREAD

**Issue by nbartels** [owntracks/android#419]
In the status view, there ar timestamps for "Location service last background update", "App started" and "Background service started".

I see dates in the future, the Year is greater than 40000 :smile: . Perhaps seconds are expected but milliseconds used or something. 

Version is 1.1.3

**Comment by binarybucks** [comment]
Yes indeed :D

**Comment by binarybucks** [comment]
Fixed in 1.1.4 (available shortly)
