### ISSUE TITLE
Support hardware pedometer

### ISSUE THREAD

**Issue by myfreeweb** [owntracks/android#422]
Hi!

OwnTracks [supports the pedometer only on iOS](http://owntracks.org/booklet/features/pedometer/). I couldn't find *anything* about step counting on Android, no issues, no discussions, nothing.

Seems like you missed that [step detector and step counter sensors became supported in Android 4.4](http://blog.bawa.com/2013/11/create-your-own-simple-pedometer.html). The [Pedometer app](https://github.com/j4velin/Pedometer) works great on my Nexus 5X without Google services.

**Comment by binarybucks** [comment]
I didn't exactly miss that they became available but there were other things that had a higher priority. 

If you are willing to work on that feature I'll accept a pull request.

**Comment by NLNetWolf** [comment]
It would really be nice if Owncloud for Android would get this too :)

Trail sense can do this: https://github.com/kylecorry31/Trail-Sense

Maybe the code from their project could be reused?
