### ISSUE TITLE
Crash when exiting Android 7.0 split screen mode

### ISSUE THREAD

**Issue by juzam** [owntracks/android#427]
I have managed to crash the app when exiting split screen mode, dragging the slider in order to restore Owntracks in full screen.

I didn't have time to catch the subimt crash dialog, nor i've been able to reproduce it so far.

**Comment by jpmens** [comment]
@juzam if you cannot reproduce, can we close this?

**Comment by juzam** [comment]
Yes,  no problem. I'll reopen it if needed.

Il mer 14 dic 2016, 22:16 JP Mens <notifications@github.com> ha scritto:
