### ISSUE TITLE
Map view is "flaky" in terms of touch responsiveness in 1.1.5 (11501)

### ISSUE THREAD

**Issue by nivekmai** [owntracks/android#428]
The issue is only reproducible in 1.1.5 (11501), in 1.1.4 (11402) I can't reproduce.

Picture is worth 1000 words, what's a video worth?
https://www.youtube.com/watch?v=H9X_CICY67Q

TL;DW: The map doesn't respond to touches well. It seems to "stick" when trying to drag, and it's all but impossible to change the zoom level using a pinch gesture. Double tapping to zoom works fine, and other apps (WhatsApp, Maps, Yelp, Chargepoint) tested work fine in the map view, so far only able to reproduce in owntracks map view.

Attempted remedies:
 - uninstall/reinstall
 - reboot

Owntracks version: 1.1.5 (11501)
Device: LG V20 (LG-US996)
OS: 7.0
Build number: NRD90M
Kernel version: 3.18.31
Software version: US99610

**Comment by nivekmai** [comment]
Hmm, just built from sources and it works fine. Seems that whatever build got uploaded to google play is broken. 

Note that when I was building, it wasn't building because [ba004ee](https://github.com/owntracks/android/commit/ba004ee1f6e588339633f9b2830e9affc336016c) doesn't import AppBarLayout and CoordinatorLayout, I let Android Studio automatically fix that and it built and worked fine.

**Comment by binarybucks** [comment]
A fix for this was provided via https://github.com/owntracks/android/pull/426 (which didn't include the AppBarLayout). A new version with the fix will be available shortly.

**Comment by binarybucks** [comment]
Done
