### ISSUE TITLE
GSM RSSI

### ISSUE THREAD

**Issue by nibelungen** [owntracks/android#429]
Hey,

as it is my first question i want to start with a thanks for this great piece of software.

I dint find anything in android or ios client code to publish the gsm signal strength (rssi) to the broker.
Is there a way to do this? Maybe a way for multiple providers f.e. telekom, vodafone - even if the device is just registred in one network?
If it is not planned or even not possible, does someone know a way how to publish these values via mqtt??

Thanks an best regards,

-Andreas

**Comment by jpmens** [comment]
This is not possible with OwnTracks. 

It probably is possible with a bit of code which obtains the value and publishes it, but we haven't forseen doing this in OwnTracks.

**Comment by nibelungen** [comment]
Thank you for the really fast reply!

So at first i will have to find out how this could be done within android.
This issue could be closed - or leave it open if someone else is interested in it.
