### ISSUE TITLE
Websockets communication after applying configuration but never after

### ISSUE THREAD

**Issue by openhab-5iver** [owntracks/android#430]
Private MQTT server through a websocket reverse proxy with SSL. We are both on 1.1.5 (11503), but she is not on the beta and only just started having the issue after upgrading recently to the current production release (same hardware version, OS, etc.). The behavior is the same when the client is configured to go directly to the backend server (not through reverse proxy) using web sockets, with and without SSL. Without websockets it works with and without SSL. Mosquitto will show initial connect after saving configuration in client, but never succeeds in connecting again. Status page in client shows 'Endpoint state message' as 'Not available'. I do not have a development environment setup for Owntracks to investigate further. Are there some client logs that could help someone else troubleshoot? Anyone else reporting issues with websockets?

**Comment by binarybucks** [comment]
> Without websockets it works with and without SSL
So do you have the problem when websockets are enabled only or is this a general problem?

**Comment by openhab-5iver** [comment]
The issue occurs when using websockets, either through the reverse proxy or directly. When not using websockets, there is no issue except that it restricts it's use to within our local network. We need websockets to use the reverse proxy.

**Comment by binarybucks** [comment]
1) the initial connect through websockets work, but afterwards it does not connect again? 
2) What happens if you manually hit the connect button in the connection preferences? 
3) Does it connect again if you force close the app and start it again?

**Comment by openhab-5iver** [comment]
1. Correct. But the "Endpoint state' says "Connected'. 'Endpoint state message' shows 'Not available' (I'm not sure what this means). And the 'Location service last background update' seems to be changing on schedule. Seems like the client thinks it is communicating even if it fails.

2. Same as initial connect. Mosquitto shows a successful connection. Here is the log (security info redacted):
`1481273213: New client connected from <REVERSE PROXY IP ADDRESS> as <ACCOUNT/DEVICE ID> (c1, k3600, u'<ACCOUNT>').
1481273213: Sending CONNACK to <ACCOUNT/DEVICE ID> (0, 0)
1481273214: Received SUBSCRIBE from <ACCOUNT/DEVICE ID>
1481273214:     owntracks/+/+ (QoS 2)
1481273214: Sending PUBLISH to <ACCOUNT/DEVICE ID> (d0, q1, r1, m1, 'owntracks/<ACCOUNT/ WIFE'S DEVICE ID>', ... (134 bytes))
1481273214: Sending PUBLISH to <ACCOUNT/DEVICE ID> (d0, q1, r1, m2, 'owntracks/<ACCOUNT/DEVICE ID>', ... (126 bytes))
1481273214: <ACCOUNT/DEVICE ID> 2 owntracks/+/+
1481273214:     owntracks/+/+/info (QoS 2)
1481273214: <ACCOUNT/DEVICE ID> 2 owntracks/+/+/info
1481273214:     owntracks/<ACCOUNT/DEVICE ID>/cmd (QoS 2)
1481273214: <ACCOUNT/DEVICE ID> 2 owntracks/<ACCOUNT/DEVICE ID>/cmd
1481273214:     owntracks/+/+/event (QoS 2)
1481273214: <ACCOUNT/DEVICE ID> 2 owntracks/+/+/event
1481273214:     owntracks/+/+/waypoint (QoS 2)
1481273214: <ACCOUNT/DEVICE ID> 2 owntracks/+/+/waypoint
1481273214: Sending SUBACK to <ACCOUNT/DEVICE ID>
1481273214: Received PUBACK from <ACCOUNT/DEVICE ID> (Mid: 1)
1481273214: Received PUBACK from <ACCOUNT/DEVICE ID> (Mid: 2)
1481273215: Socket error on client <ACCOUNT/DEVICE ID>, disconnecting.
1481273215: Sending PUBLISH to root.1481206160759 (d0, q0, r0, m0, 'owntracks/<ACCOUNT/DEVICE ID>', ... (32 bytes))
`
If you manually report location, 'message queued' pops up but nothing is logged in mosquitto or the reverse proxy. Status shows 'Endpoint queue' as 0.

3. No. Not even after a restart of the phone.

Is there any logging that can be enabled in the client that would show connection status/success/failures? Thank you for your help!

**Comment by binarybucks** [comment]
Not available means that there is no detailed error message available for the connection. This does indicate that there isn't any dedicated exception thrown. 

If the device disconnects, what is logged in the mosquitto log? 

There isn't any dedicated logging. If any errors would occur, you would see it in the endpoint state. 
More detailed logs can only be gathered through ADB.

**Comment by openhab-5iver** [comment]
The only messages in the mosquitto log are similar to what I posted. The only reference to a disconnect is in the line...

Socket error on client <ACCOUNT/DEVICE ID>, disconnecting.

And I think I remember that line/error occurring when my wife's phone was on the previous version where websockets was working. Would it be helpful for you if I could pull logs? I have ADB setup on my Openhab box for turning on/off dashboards with motion. I assume it would be something like adb logcat -d > filename.txt?

**Comment by binarybucks** [comment]
Yes, this would help immensely

**Comment by openhab-5iver** [comment]
Pulled my hair out for a quite a while to get Fedora to see my phone, then swapped the USB cable for a new one and it showed right up. Sigh. After manually sending location, here is what turns up...

V/ServiceMessage( 7276): onMessageQueued()- messageId:1481340974343, queueLength:193
V/ServiceMessageMqtt( 7276): publishMessage: org.owntracks.android.messages.MessageLocation@189c3ddd, q size: 0
V/ServiceMessageMqtt( 7276): publishing message org.owntracks.android.messages.MessageLocation@189c3ddd to topic owntracks/<ACCOUNT/DEVICE ID>
E/ServiceMessageMqtt( 7276): processIncomingMessage: MqttException. null 32104 Client is not connected
W/System.err( 7276): Client is not connected (32104)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:177)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1126)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1103)
W/System.err( 7276): 	at org.owntracks.android.services.ServiceMessageMqtt.publishMessage(ServiceMessageMqtt.java:245)
W/System.err( 7276): 	at org.owntracks.android.services.ServiceMessageMqtt.processOutgoingMessage(ServiceMessageMqtt.java:122)
W/System.err( 7276): 	at org.owntracks.android.messages.MessageLocation.processOutgoingMessage(MessageLocation.java:142)
W/System.err( 7276): 	at org.owntracks.android.messages.MessageBase.run(MessageBase.java:121)
W/System.err( 7276): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 7276): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 7276): 	at java.lang.Thread.run(Thread.java:818)

**Comment by openhab-5iver** [comment]
Here is after clicking connect check mark in Connection Preferences, and then manually sending location...

--------- beginning of main
V/PingHandler( 7276): stop org.owntracks.android.services.ServiceMessageMqtt$PingHandler@1452c4b6
D/PingHandler( 7276): Release lock underlock or null (org.owntracks.android.wakelock.broker.ping):1481342279357
I/SurfaceFlinger(  264): FPS: 19
V/ServiceMessageMqtt( 7276): running thread
V/ServiceMessageMqtt( 7276): handleStart: force:true
V/ServiceMessageMqtt( 7276): handleStart: isDisconnected:true
V/ServiceMessageMqtt( 7276): connect() mode: 0
V/ServiceMessageMqtt( 7276): init() mode: 0
V/ServiceMessageMqtt( 7276): init() client id: webproxyuser/scott
V/ServiceMessageMqtt( 7276): init() connect string: wss://mosquitto.rushworth.us:85
V/ActivityPreferencesCon( 7276): onEventMainThread Events.EndpointStateChanged -> DISCONNECTED cached CONNECTED
V/PingHandler( 7276): stop org.owntracks.android.services.ServiceMessageMqtt$PingHandler@1452c4b6
D/PingHandler( 7276): Release lock underlock or null (org.owntracks.android.wakelock.broker.ping):1481342279384
V/PingHandler( 7276): init org.owntracks.android.services.ServiceMessageMqtt$PingHandler@1cfba80d
V/org.owntracks.android.support.SocketFactory@b68b3c2( 7276): initializing CustomSocketFactory
V/org.owntracks.android.support.SocketFactory@b68b3c2( 7276): options.hasCaCrt(): true
V/ActivityPreferencesCon( 7276): onEventMainThread Events.EndpointStateChanged -> DISCONNECTED cached DISCONNECTED
V/org.owntracks.android.support.SocketFactory@b68b3c2( 7276): CA Keystore content: 
V/org.owntracks.android.support.SocketFactory@b68b3c2( 7276): options.hasClientP12Crt(): true
V/ActivityPreferencesCon( 7276): onEventMainThread Events.EndpointStateChanged -> CONNECTING cached DISCONNECTED
V/org.owntracks.android.support.SocketFactory@b68b3c2( 7276): Client .p12 Keystore content: 
V/org.owntracks.android.support.SocketFactory@b68b3c2( 7276): Alias: Scott's key
--------- beginning of system
D/FrameworkListener(  281): arg[0] = 'getaddrinfo'
D/FrameworkListener(  281): arg[1] = 'mosquitto.rushworth.us'
D/FrameworkListener(  281): arg[2] = '^'
D/FrameworkListener(  281): arg[3] = '1024'
D/FrameworkListener(  281): arg[4] = '0'
D/FrameworkListener(  281): arg[5] = '1'
D/FrameworkListener(  281): arg[6] = '0'
D/FrameworkListener(  281): arg[7] = '0'
D/FrameworkListener(  281): will free arg[0] = 'getaddrinfo'
D/FrameworkListener(  281): will free arg[1] = 'mosquitto.rushworth.us'
D/FrameworkListener(  281): will free arg[2] = '^'
D/FrameworkListener(  281): will free arg[3] = '1024'
D/FrameworkListener(  281): will free arg[4] = '0'
D/FrameworkListener(  281): will free arg[5] = '1'
D/FrameworkListener(  281): will free arg[6] = '0'
D/FrameworkListener(  281): will free arg[7] = '0'
V/PingHandler( 7276): start org.owntracks.android.services.ServiceMessageMqtt$PingHandler@1cfba80d
V/PingHandler( 7276): scheduled ping at tst 1481345880359 (current: 1481342280361 /3600000)
V/ReconnectHandler( 7276): stopping reconnect handler
V/ServiceMessageMqtt( 7276): subscribe() - Will subscribe to: owntracks/+/+
V/ServiceMessageMqtt( 7276): subscribe() - Will subscribe to: owntracks/+/+/info
V/ServiceMessageMqtt( 7276): subscribe() - Will subscribe to: owntracks/webproxyuser/scott/cmd
V/ServiceMessageMqtt( 7276): subscribe() - Will subscribe to: owntracks/+/+/event
V/ServiceMessageMqtt( 7276): subscribe() - Will subscribe to: owntracks/+/+/waypoint
V/ActivityPreferencesCon( 7276): onEventMainThread Events.EndpointStateChanged -> CONNECTED cached CONNECTING
V/PingHandler( 7276): stop org.owntracks.android.services.ServiceMessageMqtt$PingHandler@1cfba80d
D/PingHandler( 7276): Release lock underlock or null (org.owntracks.android.wakelock.broker.ping):1481342281663
V/ConnectionPReferences( 7276): handleBack. ModeChange: false
D/Perf-Track( 7276): activity.onResume: cmp = ComponentInfo{org.owntracks.android/org.owntracks.android.activities.ActivityPreferences}, time = 0ms
I/Timeline( 7276): Timeline: Activity_idle id: android.os.BinderProxy@3d542a38 time:39077138
D/Perf-Track( 7276): activityNewIntent : NewIntentData{intents=[Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.owntracks.android/.ui.map.MapActivity }] token=android.os.BinderProxy@6c70701}
D/Perf-Track( 7276): activity.onResume: cmp = ComponentInfo{org.owntracks.android/org.owntracks.android.ui.map.MapActivity}, time = 9ms
I/Timeline( 7276): Timeline: Activity_idle id: android.os.BinderProxy@6c70701 time:39078156
V/ReceiverProxy( 7276): onReceive
V/ServiceProxy( 7276): deliverIntentToService getServiceForIntent:org.owntracks.android.services.ServiceLocator@15e2d4b8
V/ServiceMessage( 7276): onMessageQueued()- messageId:1481342284019, queueLength:206
V/ServiceMessageMqtt( 7276): publishMessage: org.owntracks.android.messages.MessageLocation@351be628, q size: 0
V/ServiceMessageMqtt( 7276): publishing message org.owntracks.android.messages.MessageLocation@351be628 to topic owntracks/webproxyuser/scott
E/ServiceMessageMqtt( 7276): processIncomingMessage: MqttException. null 32104 Client is not connected
W/System.err( 7276): Client is not connected (32104)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:177)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1126)
W/System.err( 7276): 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1103)
W/System.err( 7276): 	at org.owntracks.android.services.ServiceMessageMqtt.publishMessage(ServiceMessageMqtt.java:245)
W/System.err( 7276): 	at org.owntracks.android.services.ServiceMessageMqtt.processOutgoingMessage(ServiceMessageMqtt.java:122)
W/System.err( 7276): 	at org.owntracks.android.messages.MessageLocation.processOutgoingMessage(MessageLocation.java:142)
W/System.err( 7276): 	at org.owntracks.android.messages.MessageBase.run(MessageBase.java:121)
W/System.err( 7276): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 7276): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 7276): 	at java.lang.Thread.run(Thread.java:818)
I/ViewRootImpl( 7276): CPU Rendering VSync enable = true

**Comment by binarybucks** [comment]
That was indeed help. The app thinks it is still connected but the MQTT library is not. 

I'll investigate why this happens.

**Comment by binarybucks** [comment]
@openhab-5iver @dib0 what Android Version are you using?

**Comment by dib0** [comment]
5.1 with patch level 5 november 2016

**Comment by binarybucks** [comment]
Could you join the beta release stream? I'd like to push a new version to you just to test something.

**Comment by binarybucks** [comment]
Also, of you drop me your Google account address to support@owntracks.org I can invite you to our alpha testers list.

**Comment by openhab-5iver** [comment]
We are 5.1.1, and I'm already beta. Sending email for alpha.

**Comment by openhab-5iver** [comment]
1.1.6 (11601) has same results. Although I haven't done any logging to confirm.

**Comment by dib0** [comment]
Ok, I joined the beta and sent you an email

**Comment by binarybucks** [comment]
5.1.1?

Am 11.12.2016 um 02:49 schrieb openhab-5iver <notifications@github.com>:

We are 5.1.1, and I'm already beta. Sending email for alpha.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/430#issuecomment-266255121>,
or mute the thread

**Comment by openhab-5iver** [comment]
Our phones are running Android version: 5.1.1, Kernel version: android-bld@aclgcl-ubnt #1, Build number: D6UUPU0. It is a stock build from our carrier and unrooted.

**Comment by Kernald** [comment]
I've got the same issue, on a 5.1 (CyanogenMod) Sony Z3 Compact. Already on the beta channel, I can test if that can help.

**Comment by dib0** [comment]
Did you receive my e-mail for aplha testing? Last weekend I did some more testing on 1.1.6 that seems to work for a while, but then stops working. Now I'm back in 1.1.4, but I would love to do some testing for you. Please let me know if there is anything I can do to help!

**Comment by pbanasik** [comment]
I'm getting the same error as @openhab-5iver , using app version 1.1.6 (11601). The error appears when I'm not connected to my home wifi, i.e. when using the mobile data connection. The behaviour is the same regardless of using web sockets or not. 

The messages are published when connected to the home wifi, even though as mentioned in the first post, the Status page in client shows 'Endpoint state message' as 'Not available'

The exception is as follows ('Połączenie z klientem nie jest nawiązane' is 'Client is not connected' in Polish):

```
processIncomingMessage: MqttException. null 32104 Połączenie z klientem nie jest nawiązane

W/System.err( 5837): Połączenie z klientem nie jest nawiązane (32104)
W/System.err( 5837): 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
W/System.err( 5837): 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:170)
W/System.err( 5837): 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1019)
W/System.err( 5837): 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:997)
W/System.err( 5837): 	at org.owntracks.android.services.ServiceMessageMqtt.publishMessage(ServiceMessageMqtt.java:245)
V/ServiceMessage( 5837): onMessageQueued()- messageId:1482489120953, queueLength:68
W/System.err( 5837): 	at org.owntracks.android.services.ServiceMessageMqtt.processOutgoingMessage(ServiceMessageMqtt.java:122)
W/System.err( 5837): 	at org.owntracks.android.messages.MessageLocation.processOutgoingMessage(MessageLocation.java:142)
W/System.err( 5837): 	at org.owntracks.android.messages.MessageBase.run(MessageBase.java:121)
W/System.err( 5837): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 5837): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 5837): 	at java.lang.Thread.run(Thread.java:841)
```

The iPhone app works in all cases with the same MQTT server and setup (connected to wifi or not, with web sockets enabled or not).

**Comment by binarybucks** [comment]
@dib0 found your mail, sorry. You're added to the alpha testers list. Please check 11602. 

@Kernald please send your Google account address to support@owntracks.org so I can subscribe you to the alpha builds.

**Comment by dib0** [comment]
@binarybucks Love to test it. Is there a link to the alpha build? It's not showing up in google play (maybe I'm too quick) and I can't find any other alpha builds.

**Comment by binarybucks** [comment]
It will arrive as a normal update through Google Play.

**Comment by dib0** [comment]
Ok, cool. Thought so, but wasn't sure. Thanks!

**Comment by dib0** [comment]
Version 11602 seems to be working fine up to now. The problem with the previous version occurred much sooner. I'll keep an eye on it for the next couple of days, but I'm quite positive that this version solves this problem.

**Comment by dib0** [comment]
Hi! This version still works as it should. Great!

One thing I noticed is that the map that is shown by OwnTracks has less details. Did you use a different zoom level? I'm missing a lot of streets. If that is by choice, maybe it's a good idea to make the zoom level configurable?

**Comment by binarybucks** [comment]
No but Google changed some aspects of the map design on the server side. I don't like it either but there is nothing I can do about that.

**Comment by dib0** [comment]
Ok, thanks, I understand. Maybe OpenStreetMap will provide an alternative, but I don't know enough specifics to really determine that.

**Comment by ekw** [comment]
How does one join the beta release stream? I'm seeing this issue as well on v1.1.6 (11601) and Android v4.4.4, though I'm not using WebSockets, just MQTT.

**Comment by binarybucks** [comment]
@ekw https://play.google.com/apps/testing/org.owntracks.android 

@dib0 is it still working well?

**Comment by dib0** [comment]
Hi! Yes, works like a charm.

I installed this version on my wife's phone and it works well there too. I still have a problem with the map, after removing and reinstalling owntracks I now have no map at all. But on the phone of my wife this seems all to work fine, it's probably a problem on my phone (just don't know what).

But the app works well!

**Comment by binarybucks** [comment]
Build with the fix is now in beta

**Comment by bastshoes** [comment]
Connection issues with MQTT disappeared. Now it works like charm. But map is blank.

**Comment by dib0** [comment]
I have the same problem. Thought it was a problem on my phone. I created a new issue for this problem:
https://github.com/owntracks/android/issues/437

**Comment by binarybucks** [comment]
11604 is now available as a normal update. The map issue has also been fixed.
