### ISSUE TITLE
Server Name extension not sent when using Websockets over TLS

### ISSUE THREAD

**Issue by KingJ** [owntracks/android#432]
Hi,

My Moqsuitto broker is behind a nginx reverse proxy, which handles the TLS connection and passes it on to mosquitto's non-TLS'd websocket interface. However, when I attempt to connect to the broker, I receive a `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.` error.

A bit of troubleshooting later, it seems that the certificate being returned is the default self-signed certificate that is used when none of the proxy's host directives are met, hence the certificate error.  Looking at the TLS Client Hello sent by Owntracks, no `server_name` extension is sent and hence the proxy serves the request using the default backend with the self-signed cert.

If I use another MQTT client such as MQTTLens, I am able to successfully connect to the broker and publish/subscribe to messages.

I am running Owntracks 1.1.6 on an Android 6.0.1 device.

**Comment by binarybucks** [comment]
That seems strange because I was able to connect through my reverse proxy. It might very well be a bug in the MQTT library. The Websocket implements is rather new. 

Could you please post your Nginx config?

**Comment by KingJ** [comment]
Sorry for the delay, here's my nginx configuration for the MQTT proxy. It was generated by a Kubernetes Ingress resource, hence the extra bits for LetsEncrypt and the overall verbose nature of the config!

I know the timeouts are a little bit low (60sec), but this shouldn't affect the initial connection should it?

```
    server {
        server_name mqtt.kingj.net;
        listen 80;
        listen 443  ssl spdy http2;

        ssl_certificate /etc/nginx-ssl/default-mosquitto-tls.pem;
        ssl_certificate_key /etc/nginx-ssl/default-mosquitto-tls.pem;

        more_set_headers                            "Strict-Transport-Security: max-age=15724800; includeSubDomains; preload";

        vhost_traffic_status_filter_by_set_key $geoip_country_code country::$server_name;

        location /.well-known/acme-challenge {






            proxy_set_header Host                   $host;

            # Pass Real IP
            proxy_set_header X-Real-IP              $remote_addr;

            # Allow websocket connections
            proxy_set_header                        Upgrade           $http_upgrade;
            proxy_set_header                        Connection        $connection_upgrade;

            proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host       $host;
            proxy_set_header X-Forwarded-Port       $server_port;
            proxy_set_header X-Forwarded-Proto      $pass_access_scheme;

            # mitigate HTTPoxy Vulnerability
            # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
            proxy_set_header Proxy                  "";

            proxy_connect_timeout                   5s;
            proxy_send_timeout                      60s;
            proxy_read_timeout                      60s;

            proxy_redirect                          off;
            proxy_buffering                         off;

            proxy_http_version                      1.1;


            proxy_pass http://kube-lego-kube-lego-nginx-8080;
        }


        location / {
            # enforce ssl on server side
            if ($scheme = http) {
                return 301 https://$host$request_uri;
            }





            proxy_set_header Host                   $host;

            # Pass Real IP
            proxy_set_header X-Real-IP              $remote_addr;

            # Allow websocket connections
            proxy_set_header                        Upgrade           $http_upgrade;
            proxy_set_header                        Connection        $connection_upgrade;

            proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host       $host;
            proxy_set_header X-Forwarded-Port       $server_port;
            proxy_set_header X-Forwarded-Proto      $pass_access_scheme;

            # mitigate HTTPoxy Vulnerability
            # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
            proxy_set_header Proxy                  "";

            proxy_connect_timeout                   5s;
            proxy_send_timeout                      60s;
            proxy_read_timeout                      60s;

            proxy_redirect                          off;
            proxy_buffering                         off;

            proxy_http_version                      1.1;


            proxy_pass http://default-mosquitto-svc-9883;
        }






    }
```

**Comment by binarybucks** [comment]
I'm trying to test this but with the latest Mosquitto build WS connections don't stay connected. 
Even without TLS, connections are closed right after the connect with a socket error and no further messages. 
Any ideas?

**Comment by KingJ** [comment]
I'm going to close this in favour of #448. I recently upgraded to Android 7.0 and wiped my phone clean. Now, I get the exact error that issue #448 lists - if I monitor the status screen I very breifly see Owntracks flip to connected before disconnecting with the exception `java.lang.Exception: Connection lost (32109) - java.io.EOFException`.

**Comment by speedst3r** [comment]
These are two separate issues though? The problem in #448 is with websockets closing connection, the opener states it occurs without TLS or auth.

The issue here is when using TLS with websockets, the server_name is not sent in the TLS client hello.

**Comment by binarybucks** [comment]
Yes, but as Paho Websocket support is broken anyway, this issue is mood ;)
