### ISSUE TITLE
Add Track History Capability

### ISSUE THREAD

**Issue by seesemichaelj** [owntracks/android#433]
The iOS app has the ability to show track history by clicking multiple times on a track. It doesn't appear to be possible to do this on the Android application.

**Comment by binarybucks** [comment]
Please use https://github.com/owntracks/recorder on the backend to record your tracks.

**Comment by jpmens** [comment]
@seesemichaelj in particular use Recorder b/c the track that iOS shows you is just a few points in the past.

**Comment by seesemichaelj** [comment]
I do use the recorder, but it is not a mobile friendly interface. This is a nice to have feature that most commercial tracking apps have.

This capability does not need to have the entire track, but it would be nice to have some history within the app.
