### ISSUE TITLE
IllegalArgumentException on Logon to Cloudmqtt

### ISSUE THREAD

**Issue by derrapf** [owntracks/android#434]
Hi
Can anybody help me?
I own two mobiles: Samsung Galaxy Note4 and Samsung Galaxy Note2 (Android 4.4.2).
I used the same configuration for Owtracks to log on to www.cloudmqtt.com. 
It works flawlessly on the Note4. But the Note2 gives me an:

Endpoint state:
   java.lang.IllegalArgumentException: tcp://m11.cloudmqtt.com : 18383  
Endpoint state message: 0

in its status messages

Regards Ralf

**Comment by binarybucks** [comment]
Post your configuration here please (minus credentials)

**Comment by derrapf** [comment]
Hi
Thanks for your quick reply.
Here are some screenshots of the configuration.
Is there somewhere a logfile i could upload?


![owntracks](https://cloud.githubusercontent.com/assets/11745094/21720550/1e28d094-d424-11e6-8af5-d0124588237b.jpg)

Ralf

**Comment by binarybucks** [comment]
Please export the settings to a file and upload the content here

**Comment by derrapf** [comment]
Ok
Here it is:
[config_Note2.zip](https://github.com/owntracks/android/files/690113/config_Note2.zip)

**Comment by binarybucks** [comment]
Your host configuration constains some newline characters and spaces 
```
"host":"\nm11.cloudmqtt.com\n\n    "
```

I would suggest to empty the field and enter the host by hand again. 
Alternatively, edit your config and import it again. 

**And please change your cloudmqtt password, it was sent in the config file.**

**Comment by derrapf** [comment]
I just saw that. Why is it exported non encrypted???
Just let me try if deleting the whitespaces work.
If that's the reason: Would'nt it be a good idea to cut trailig an leading whitespaces in thse fields?
Ralf

**Comment by derrapf** [comment]
Issue Solved!
Thank you very much for that really super-quick help!!!
By the way: Before I updated owntracks it said "connected" after I pressed the check-button the confguration. Now it does not say anything. You have to check it in the status screen to find out.

**Comment by binarybucks** [comment]
Yes, the status moved to its own screen now. 
The previous way was very fragile code.

**Comment by derrapf** [comment]
Ok. 
But I stll would recomment to delete whitespaces. 
A common user (like me) does not recognize such errors.
Ciao Ralf
