### ISSUE TITLE
AWS IoT

### ISSUE THREAD

**Issue by mortommy** [owntracks/android#435]
I don't now if this is the right place where to ask this questions, but I'm wondering if it is possible to use AWS Iot as broker, I'm trying to set up the app with no success.
Thank you.
Regards.

**Comment by jpmens** [comment]
"with no success" is not really something we can work with. Care to specify some details?

**Comment by mortommy** [comment]
Yes, sorry, you are right.

The AWS IoT support TLS v1.2 with certificate authentication. I got from AWS the CA certificate (PEM format), the client certificate and a pair of private/public key for my device.
My setting on Android App v0.6.14:

Host: my AWS Iot Endpoint, port 8883
Identification: disabled
Security: CA Certificate the [root certificate](https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem), that I also tried to convert to a crt certificate using openssl x509; as Client certificate a pk12 package I created via openssl pk12 using the client certificate and the private key I got from Amazon.
I receive the error: "error: null"
I think it is an authentication issue, because in the AWS Iot Watchlogs I can see the connection tentatives failed.

**Comment by ckrey** [comment]
@mortommy you will have to modify the default settings (via .otrc file, see http://owntracks.org/booklet) to make OwnTracks work with AWS.

This is because AWS does not support full MQTT 3.1.1 (http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html)

Change
- `pubRetain`to `false`
- `cleanSession`to `true`
- `pubQos`to `1`

**Comment by mortommy** [comment]
Thank you @ckrey ,
I connected owntracks to AWS IoT! 
But I can see only messages type "lwt" published because owntracks get disconnected after that message.

When I exported my configuration I didn't have the option cleanSession, I added it manually with the value True.

**Comment by ckrey** [comment]
please try again with a JSON `true` (lowercase t)


Von meinem iPhone gesendet

**Comment by mortommy** [comment]
yes. it is already lowercase. I changed it also from the app: back to false I get again the error "error:null",  on true the behavior described above.

**Comment by ckrey** [comment]
can you please check the `subQos`? It must not be =2 either

**Comment by mortommy** [comment]
tried with 
"subQos":1
but still encountering the same issue.

The Cloudwatch on AWS is showing errors of type: PublishIn.ClientError
In the [documentations](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/iot-metricscollected.html) the error has the description:

_AWS IoT rejected a publish request from a client because the MQTT message did not meet the requirements defined in AWS IoT Limits._

The limits are defined [here](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot)

I have the option include extended data in location reporting set false, but anyway I think limits are not so restrictive.

**Comment by ckrey** [comment]
I thing the `keepAlive` in Android might be too high. Try setting it to e.g. `300`, within AWS limits.


Von meinem iPhone gesendet

**Comment by mortommy** [comment]
Some news here, but no good news.
I changed the cloudwatch log level to Info. The early entries showed an error message:

EVENT:Unsupported keep-alive requested in MQTT CONNECT request. MESSAGE:An unsupported MQTT keep-alive value was requested from the server. AWS IoT supports keep-alive values between 5 and 1200. The connection will be handled with the supported value closest to the request value.

I changed the keepalive option as the @ckrey suggestion to 300. The message above is not logged anymore but anyway owntracks keeps to be disconnected after the message (lwt) published;

now I see:

2017-01-09 16:13:02.624  [INFO] EVENT:MQTT Client Connect MESSAGE:Connect Status: SUCCESS
2017-01-09 16:13:02.716 [INFO] EVENT:MQTTClient Subscribe TOPICNAME:owntracks/+/+,owntracks/+/+/info,owntracks/tommy/motox/cmd,owntracks/+/+/event,owntracks/+/+/waypoint MESSAGE:Subscribe Status: SUCCESS
2017-01-09 16:13:02.765  [INFO] EVENT:PublishEvent TOPICNAME:owntracks/tommy/motox MESSAGE:PublishIn Status: CLIENT_ERROR
2017-01-09 16:13:02.861 [INFO] EVENT:PublishOut TOPICNAME:owntracks/tommy/motox MESSAGE:PublishOut Status: SUCCESS

Unfortunately the error entry shows no more info.

**Comment by ckrey** [comment]
Please try
`pubQos` set to `0`.

**Comment by mortommy** [comment]
Hi,
tried pubQos to 0, unfortunately no luck.

**Comment by binarybucks** [comment]
subQos is not supported with the current version. Added it with c1c31ef73fd835d41516db5803f75f91fe8dd05c.

**Comment by magnusheino** [comment]
Did anyone get owntracks working with amazon iot mqtt?

**Comment by binarybucks** [comment]
AWS IOT is not supported and does not work
