### ISSUE TITLE
OwnTracks not sending messages to MQTT broker

### ISSUE THREAD

**Issue by VitaliFrolov** [owntracks/android#436]
I just installed owntracks on 3 different Samsung phones. Set up Mosquitto on Raspberry Pi3 and also OwnTracks Recorder. Tested it for 3 days. It looks like owntracks is not sending messages to the broker. 

If I go to the map view and push on the manual update button (up arrow) the broker is not receiving anything. But if I use MQTT publishing app on the same phone to publish test messages to the same broker  they go through immediately.

Same problem is happening to the background updates, they only happen a few times per day, maybe 2 - 3 times.

Owntracks shows my location accurately at all times on the map, but the messages are not sent.

I am sure that the settings for the broker are correct because occasionally messages do go through to the broker.

I am using owntracks 1.6.1 (11601). And 3 different phones:

Samsung GT-I9295, Android 5.0.1
Samsung GT-I9505, Android 5.0.1
Samsung J1

**Comment by VitaliFrolov** [comment]
I dont think the problem is with the settings. Because aoutomatic background location updates are sent by owntracks and received by the broker. The problem is owntracks has sent only about 2 - 7 single location messages in the last 12h on all 3 phones. But all of them were moving all day long.

**Comment by jpmens** [comment]
You are going to have to make up your mind; you said:

> It looks like owntracks is not sending messages to the broker

what is it then? Is it or is it not sending messages to the broker?

**Comment by VitaliFrolov** [comment]
It is sending messages. But not as frequently as it should. As I understand it should send a message every time when the phone is moving. But that is not happening, for the last 12 h there was only 7 updates. And I was moving around town all day and network was connected at all times. Also when pressing the manual update button on one of the phones nothing happens. But using the same button on the other 2 phones I get an immediate update on the broker. All phones have identical setups.

**Comment by jpmens** [comment]
All phones have identical setups? The clientid must be different, andvthe
device name or username should be different. Please check the clientids.

**Comment by VitaliFrolov** [comment]
All phones have same user and password for the MQTT and different Device ID and Tracker ID.

I solved the problem with one of the phones not updating via manual update button. I had the notifications turned off in the status bar.So I turned it on now and noticed that it was saying "No connection", I tried opening web pages in chrome and internet was working. I restarted the phone and now it says connected. And manual update button also works.

Looks like the problem is with the internet connection. Seems the app is loosing internet connection at times. Because if the problem was with MQTT settings I would not be getting any updates at all.

**Comment by binarybucks** [comment]
If you disable the notification, Android will stop the app and you will not get reports in the background.

**Comment by binarybucks** [comment]
Also it will say no connection until the next automatic reconnect attempt.

**Comment by VitaliFrolov** [comment]
OK, so looks like problem solved. That actually didn't occur to me. I thought that the reporting section was responsible for the automatic location updates. And notifications were only for convenience.

It's a pity that it has to be always on as it taking up space in the status bar. 

I will enable notifications on all the phones and check it out.

It is strange though that I was still getting some location updates even with notifications turned off.

**Comment by binarybucks** [comment]
Android might resume the app sporadically, hence you might get some updates.

**Comment by VitaliFrolov** [comment]
Thank you for your help guys!

Maybe worth changing the description in notification options to be more clear. Something like: If you disable this you will not get any background updates."

Or maybe make it possible to have it run in the background without the status bar message.

**Comment by binarybucks** [comment]
This is an OS limitation. No background service without ongoing notification. 

Also, if I'm not mistaken, the notification setting states "display a notification to keep running".
