### ISSUE TITLE
Blank map

### ISSUE THREAD

**Issue by dib0** [owntracks/android#437]
"Connection issues with MQTT disappeared. Now it works like charm. But map is blank." (see https://github.com/owntracks/android/issues/430#issuecomment-271511762) - I created a new issues for this problem.

Same problem here, a blank map. At first I had some map (not much detail) that seems to come from the cache. After I installed this version on my wife's phone and saw that the map works perfectly there I deinstalled and reinstalled OwnTracks on my phone and reconfigure by hand. Ever since then the map is blank.

This is in version 11602.

**Comment by jpmens** [comment]
I believe a private report was given about exactly this same issue. Would you please attempt to uninstall and then re-install the app?

**Comment by dib0** [comment]
Hi, that's true. I was under the assumption that it was a problem with just my phone. Since some else reported the same problem (see #430) I thought it was best to open a new issue.

I just deinstalled and reinstalled the app. And reconfigured by hand, but still no map.

**Comment by bastshoes** [comment]
I've reinstall the app. Still no map.

**Comment by binarybucks** [comment]
Please test with 11604 from the beta channel.

**Comment by dib0** [comment]
Thanks! 11604 brought the map back! Will test tonight and tomorrow with multiple locations, since I have to travel.

**Comment by bastshoes** [comment]
Great! Map is back. Will test tomorrow while traveling to office.

**Comment by binarybucks** [comment]
Version with a fix is now available as a normal update for all users
