### ISSUE TITLE
Owntracks Android sporadically stops sending beacon based region updates

### ISSUE THREAD

**Issue by yajrendrag** [owntracks/android#440]
I have a galaxy s7 (android 6.01 - & OS availability controlled by mobile carrier) configured with waypoints several of which are beacon regions inside my house (corresponding to individual rooms) - my house  is one of the waypoints.  Most of the time, things work as expected.  

Periodically - the transition events based on the beacons just stop for no apparent reason.  (in fact - it may be more than just transition events that stop - overnight last night, no new messages for 6 hours - phone was stationary).

What seems to start it all back up again is deleting the cache and memory content from the applications settings in android and then deleting the app and reinstalling the app.  the config remains intact (i would have thought deleting the cache and memory would have wiped it out, but it doesn't).

after that procedure, beacon regions begin updating again and i get transition events.  if i don't do this, i fail to get any transmissions from this device.

i do also have an ios device configured with owntracks that has the same house and beacon waypoints defined (i imported the waypoint config from the android device to the ipad).

any thoughts on why this is stopping or suggestions on what to check?  I do also have other android devices (gps waypoint only) and other MQTT devices using the same broker and MQTT is operable and messages are exchanged just fine (between the other androids and the ipad and MQTT) when the android in question stops working.

**Comment by binarybucks** [comment]
Which version are you using (post the full build number please)? 
If transition events stop, do message arrive at the broker when you manually publish a location?

**Comment by yajrendrag** [comment]
Version 1.1.6 (11601).
yes, if i understand what you are asking -  if i go into owntracks app to the map screen - it does seem to cause a location to be published - don't even have to press the publish button (up arrow).

**Comment by binarybucks** [comment]
Issue is #430
