### ISSUE TITLE
java.lang.illegalargumentexception

### ISSUE THREAD

**Issue by eghetto** [owntracks/android#441]
Endpoint state message. Version 11604.

**Comment by binarybucks** [comment]
You couldn't have included any less details, could you?

**Comment by eghetto** [comment]
Sorry - used my phone to create the issue. It's not very convenient on the device.

However, after the update to 11604 I'm no longer able to connect. 

Status Screen  Shows: "Error / Endpoint state".

Endpoint state message: "java.lang.illegalargumentexception: myserver.com:8883:mqtt"

Is there a way to provide you with more debug information?

I'm wondering whether I'm the only one having this issue...

**Comment by binarybucks** [comment]
As the error says, you've entered an invalid hostname.  For websocket connections the new version automatically appends "/mqtt" to the connect uri. Could you double check what you set as hostname int he preferences?

**Comment by eghetto** [comment]
Ah thanks! - "java.lang.illegalargumentexception" is not very self-explanatory...
Well, actually I did not modify my settings/preferences. 
My hostname is set as: "myserver.com"
Port is not set.
I'm not using websockets.

**Comment by imtiajmeah** [comment]
Same issue after update of the app..

**Comment by peterlozano** [comment]
Same issue here. No websockers. No TLS.

java.lang.IllegalArgumentException: tcp://X.cloudmqtt:17606/mqtt

(X = my server instance)

The mqtt instance is working correctly since I'm able to connect with a different app.

**Comment by nbartels** [comment]
Without changing anything the new version of owntracks is not able to connect to the mqtt broker. Append the `mqtt` should be optional ...

**Comment by binarybucks** [comment]
A fix has been submitted to Google Play, it will be available shortly. Sorry for any inconvenience.

**Comment by imtiajmeah** [comment]
I can confirm issue resolved. Thanks for the speedy fix.

**Comment by peterlozano** [comment]
Confirmed. It works.

**Comment by eghetto** [comment]
Agree, issue solved! Thank you!
