### ISSUE TITLE
Support for BT Device tracking similar to how iBeacon's work.

### ISSUE THREAD

**Issue by r4** [owntracks/android#442]
I have a car that has a BT Handsfree unit. I'd love to use this to track the location of my car instead of using an iBeacon (BTLE).

This could also generally be used for BT devices as well.

**Comment by binarybucks** [comment]
BLE beacons and paired devices are funamentally different. There are currently no plans to support tracking of normal paired devices due to the fragile nature of the Android Bluetooth APIs.
