### ISSUE TITLE
msg and cmd support in Android

### ISSUE THREAD

**Issue by akkord64** [owntracks/android#444]
Does msg and cmd command processing function in the Android client as of 1/19/17? I see references to msg feature support was removed and I am unable to get it to process. Just confirming with developers it is intended not to work, or if my problem is local.

**Comment by binarybucks** [comment]
cmd works, msg has been removed long ago

**Comment by akkord64** [comment]
Thanks for the reply. Just confirming then that the intent to display notifications to users via the push/msg function can be accomplished via the cmd actions?

Such as:
{"_type":"cmd","action":"action","content":"Backend maintenance scheduled for tonight\n\nhttp://support.owntracks.org"}
{"_type":"cmd","action":"action","content":"<a href='http://support.owntracks.org'>Backend Maintenance tonight</a>"}
{"_type":"cmd","action":"action","url":"http://support.owntracks.org"}

**Comment by binarybucks** [comment]
It cannot. Cmd messages are generally supported on Android, just not the `action` command. 
The documentation seems to be a bit lacking.

**Comment by binarybucks** [comment]
Android supports the following cmd messages only
```
{"_type":"cmd","action":"reportLocation"}
{"_type":"cmd","action":"waypoints"}
{"_type":"cmd","action":"setWaypoints","payload":{"_type":"waypoints","waypoints":[...]}
{"_type":"cmd","action":"setConfiguration","payload":{"_type":"configuration",...}
```

**Comment by akkord64** [comment]
Thank you for the confirmation. Great product, just with it had feature parity with ios. Is there an open Enhancement, or is the feature not going to be available on the Android platform? Thanks again.

**Comment by binarybucks** [comment]
There are no plans to add it currently

**Comment by Intellium** [comment]
> Android supports the following cmd messages only
{"_type":"cmd","action":"reportLocation"}
{"_type":"cmd","action":"waypoints"}
{"_type":"cmd","action":"setWaypoints","payload":{"_type":"waypoints","waypoints":[...]}
 {"_type":"cmd","action":"setConfiguration","payload":{"_type":"configuration",...}

I've just been testing and from what I can gather, the 'setConfiguration' action is not working on Android. I can list the device's waypoints just fine, but trying to set a config never results in the device actually setting the configured settings. 

I've tried a few basic settings, like to locatorInterval, and even did a full config export of the device and tried to set that with one minor change, but nothing works in this regard. 

This is on app version 1.1.2 (11212).

**Comment by binarybucks** [comment]
1.1.2 is rather old, please update. 
Also, have you enabled remote commands in the advanced preferences?

**Comment by Intellium** [comment]
Ouch, somehow my Owntracks wasn't updating... my bad. I've now updated it to the latest version (1.1.6) and rebooted my device.

Now, it's a different issue, as the app crashes as soon as I respond with a configuration command.
I'm using HTTP mode and a sample output which the device get's when it pushes it's location is the following:

```
{"_type":"cmd","action":"setConfiguration","payload":{"_type":"configuration","locatorInterval":666}}
```

I've tried with above simple setting, as well as an entire dump of the config of the device. It always results in an app crash and consequently, no settings are set. Is there something wrong in the JSON line above?

**Comment by binarybucks** [comment]
Nobody tried to do cmd messages through http before but it should work nevertlesless. 

I got the crash report and will have a look in the following days.

**Comment by Intellium** [comment]
Thanks.
I've been testing with all sorts of JSON arrays, to see if I could pinpoint something, but it always crashes. 
Sending invalid JSON however, seems to not do anything, but also not crash the app 😄

**Comment by binarybucks** [comment]
Invalid JSON is ignored, valid JSON can crash things ;)

Am 22.01.2017 um 23:19 schrieb Intellium <notifications@github.com>:

Thanks.
I've been testing with all sorts of JSON arrays, to see if I could pinpoint
something, but it always crashes.
Sending invalid JSON however, seems to not do anything, but also not crash
the app 😄

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/444#issuecomment-274364506>,
or mute the thread

**Comment by binarybucks** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.owntracks.android.messages.MessageConfiguration.containsKey(java.lang.String)' on a null object reference
	at org.owntracks.android.support.Preferences.importFromMessage(Preferences.java:303)
	at org.owntracks.android.services.ServiceMessage.processIncomingMessage(ServiceMessage.java:283)
	at org.owntracks.android.messages.MessageCmd.processIncomingMessage(MessageCmd.java:87)
	at org.owntracks.android.messages.MessageBase.run(MessageBase.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by binarybucks** [comment]
This is probably a combination of two errors. One is that a missing configuration object is not expected, hence the crash. 

The second is, that the payload attribute isn't implemented as documented. Could you try if the following message works? 
`{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration","locatorInterval":666}}`

**Comment by Intellium** [comment]
Just tried with:

> {"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration","locatorInterval":666}}

No crash, and seems to have set the interval correctly!
I will try a more elaborate config setting and see if that will also work...

**Comment by ckrey** [comment]
Sorry, we have a slightly different implementation in iOS and Android regarding the payload for setConfiguration and setWaypoints.

We will update the documentation in http://owntracks.org/booklet/tech/json/#_typecmd and the iOS app.

**Comment by Intellium** [comment]
Just tried with a bigger configuration object and all settings seem to apply just fine. Good to know it's simply an error in the documentation. 

Thanks for looking into this.
