### ISSUE TITLE
Owntracks Android sporadically stops sending updates - Reopen #440

### ISSUE THREAD

**Issue by yajrendrag** [owntracks/android#445]
This problem still persists for me...

I have a galaxy s7 (android 6.01 - & OS availability controlled by mobile carrier) configured with waypoints several of which are beacon regions inside my house (corresponding to individual rooms) - my house is one of the waypoints. Most of the time, things work as expected.

Periodically - the transition events based on the beacons just stop for no apparent reason. (in fact - it may be more than just transition events that stop - overnight last night, no new messages for 6 hours - phone was stationary).

What seems to start it all back up again is deleting the cache and memory content from the applications settings in android and then deleting the app and reinstalling the app. the config remains intact (i would have thought deleting the cache and memory would have wiped it out, but it doesn't).

after that procedure, beacon regions begin updating again and i get transition events. if i don't do this, i fail to get any transmissions from this device.

**Comment by binarybucks** [comment]
If you remove the app or clear the application storage, the config should be removed as well. This is very strange but might be a Samsung thing. They tend to do things differently. 

1. Which version do you have installed (build number)?
2. Do you have the ongoing notification enabled? 
3. Could you check if only beacon event transmission stops or if the app stops sending messages completely?
4. If you no longer receive beacon events, does the app send a message when you manually hit the report button? 
5. Are you using MQTT or HTTP mode? 
6. If you are using MQTT mode, do the broker logs indicate anything? 

Last but not least, BLE support on Android 6 (and above) is a bit sketchy. 
My nexus 4 phone required every other day for beacons to work. Otherwise the bluetooth scanning stopped returning anything.

**Comment by binarybucks** [comment]
Might also be the issue fixed with #443. It will be included with the next update.

**Comment by yajrendrag** [comment]
1. thanks, version 1.1.6 (11605) - and have been running this since sometime in the last week when it came out.
2. yes, ongoing notifications enabled
3. seems to vary - but last night for example, i returned from a trip, came home, it worked for a brief period of time, then after 2am, no updates at all until i deleted re-installed.
4.  yes, if i manually hit the report button it sends a location update (but not a transition message).
5. MQTT mode
6. the only thing i notice is occasional socket errors on various clients: 
`Socket error on client jays7/galaxys7, disconnecting`
get these on ipad client too, but the ipad uipdates keep going after the client reconnects.  I haven't checked until you suggested looking at this log, so will spend some more time on it, but there is one of these client disconnect messages last night when the updates from the samsung stopped around 2am... but i do see these messages also during periods when MQTT updates continue to occur...

**Comment by tleegaard** [comment]
I seem to have the same issue. My phone (Nexus 5x) has stopped to recognize the beacon at home. I'm also at 11605.

[
![screenshot](https://cloud.githubusercontent.com/assets/5439041/22374010/89ad9210-e4a4-11e6-97be-62cd5208db07.png)
](url)

**Comment by roothorick** [comment]
Observing the same problem on a Blackberry Priv and 1st gen Moto g. So we've very definitely ruled out any vendor customizations causing issues, and the g having the issue as well shows it's not related to changes in Marshmallow. (And I wonder if the issues you've observed are N4 specific... the Priv is on 6.0.1 and picks up my Vive base stations every time I open the Bluetooth settings.)

Both are running 1.1.6 11605.

As best I can tell, they just weren't reporting at all for quite a while... I didn't catch when it started unfortunately.

App continues to send messages with GPS data only.

Hitting report manually generates a GPS only message.

Private MQTT mode.

Mosquitto logs look very business-as-usual.

Exporting config, deleting app data (not just cache), and re-importing config seems to have fixed it... for now.

**Comment by binarybucks** [comment]
Updated AltBeacon version in f0da8afbf917d9a39f65405cbc6709bc7a7fe182. Will be included in the next release

**Comment by binarybucks** [comment]
Please test the 1.1.7 release

**Comment by tleegaard** [comment]
Beacons are working for me again! :-)

**Comment by syssi** [comment]
It's possible to test the new release without build the apk on my own?

**Comment by binarybucks** [comment]
Install the update from the play store

**Comment by syssi** [comment]
Okay. It did now show up yet (for me).

**Comment by syssi** [comment]
I've updated to 1.1.7. Beacons are recognized again on my nexus 5. Thanks a lot!
