### ISSUE TITLE
MqttException (0) - java.net.SocketException: Permission denied

### ISSUE THREAD

**Issue by Crupuk** [owntracks/android#447]
I have this issue when my phone is connected to the WiFi at home.

My Mqtt is self hosted on the same network.

If i disable the WiFi on Android, owntracks show me "Connected" on the Status menu.
If my smartphone is connected i have this error  : 

![screenshot_20170123-095429](https://cloud.githubusercontent.com/assets/670728/22197407/2a04f628-e152-11e6-8f1b-51b7b1f636b3.png)

When i'm test with mosquitto_sub with my laptop ( connected on the WiFi ) it works .

It's seems it's related with this : http://stackoverflow.com/a/13698307

I don't know if it's more a Android issue or a Owntracks permission issue.

Thanks for your help

**Comment by samarthgupta29** [comment]
Downgrade JDK

**Comment by binarybucks** [comment]
Downgrade the JDK on Android? 
The issue occurs when the network permission is denied which OwnTracks correctly requests.

**Comment by binarybucks** [comment]
@Crupuk which Android/ROM version are you using?

**Comment by Crupuk** [comment]
@binarybucks I'm on a Nexus 6 running Android N 7.0 

I'm think is related with to different kind of permission : 
- One for querying on a distant location
- One for quering on a local destination ( nat loopback throught the router ).

My girlfriend as the same issue with her Iphone 7 ( No data send when connected to the WiFi )

**Comment by binarybucks** [comment]
I can assure you that the error you posted is entirely unrelated to the NAT issue you have. 

Try enabling NAT reflection/ hairpin NAT on your router for the NAT problems.

**Comment by Crupuk** [comment]
I don't undestand why this issue is now closed ?

I have many application that connect directly to my local server using the domain name ( and not the local IP ).

News reader -> FreshRss
LabCoat -> Gitlab
Remote transmission -> Transmission
Chrome -> apache

Each of this app use a sub domain and Works perfectly .

Owntrack work great outside of my network. 

Like i said in my first post, when i'm usinf mosquitto_sub on my laptop ( connected to the WiFi , using the domaine name instead of IP ) it works ...

**Comment by Crupuk** [comment]
Could you please review this issue again ?

**Comment by binarybucks** [comment]
There's not much I can do here as Owntracks works well with many kinds of NAT setups. 
Unfortunately, I'm not able to reproduce this issue. 

The app requests network permission and that's it. 
There is no other permission that can be requested. 

As you also have the error on another device it looks like a firewall/router issue which e.g. denies the connect to the MQTT port (even though the error message is a bit strange for this).

**Comment by pmorange** [comment]
Hi,
Same issue here. Just tried to use certificate for TLS but same error.
When I'm connected to my Wifi, the endpoint queue grows with messages accumulating. Then I remove Wifi to connect to 4G, and suddenly all messages are sent.

I'm using Owntracks beta program latest release (2.1.3 21302).
Android is a little old : 5.0.2
