### ISSUE TITLE
Owntracks unexpectedly closes websocket connection

### ISSUE THREAD

**Issue by herm** [owntracks/android#448]
Trying to connect owntracks to mosquitto via websocket is not possible. The connection is always closed before sending useful information. This is also reported as a comment in #432. I'm not using TLS or authentication for this test. Normal MQTT works fine.

I tried to debug the problem. The difference between the two methods seems to be that for Websocket-MQTT mosquitto sends the PUBLISH for the retained message before sending the SUBACK. Owntracks seems to process the publication anyways (sends PUBACK) but closes the connection after the PUBACK packet. It does not send a DISCONNECT command.
Mosquitto reports this as "Socket error on client owntrackstest/testdevice, disconnecting."

tcp_dump (decoded)
-----

```
-> Client to server
<- Server to client

-> CONNECT
<- CONNACK
-> SUBSCRIBE (multiple topics)
<- PUBLISH (QOS=2, retain=1)
<- SUBACK
-> PUBACK 
-> Websocket close (Status: 12592, Reason: 0)
<- Websocket close (Status: 12592, Reason: 0)
```
Mosquitto debug messages
---------

Connection via plain MQTT:
```mqtt_1           | 1486079775: New connection from 192.168.0.54 on port 1883.
mqtt_1           | 1486079775: Client owntrackstest/testdevice disconnected.
mqtt_1           | 1486079775: New client connected from 192.168.0.54 as owntrackstest/testdevice (c0, k3600).
mqtt_1           | 1486079775: Sending CONNACK to owntrackstest/testdevice (1, 0)
mqtt_1           | 1486079775: Received SUBSCRIBE from owntrackstest/testdevice
mqtt_1           | 1486079775: 	owntracks/+/+ (QoS 2)
mqtt_1           | 1486079775: owntrackstest/testdevice 2 owntracks/+/+
mqtt_1           | 1486079775: 	owntracks/+/+/info (QoS 2)
mqtt_1           | 1486079775: owntrackstest/testdevice 2 owntracks/+/+/info
mqtt_1           | 1486079775: 	owntracks/owntrackstest/testdevice/cmd (QoS 2)
mqtt_1           | 1486079775: owntrackstest/testdevice 2 owntracks/owntrackstest/testdevice/cmd
mqtt_1           | 1486079775: 	owntracks/+/+/event (QoS 2)
mqtt_1           | 1486079775: owntrackstest/testdevice 2 owntracks/+/+/event
mqtt_1           | 1486079775: 	owntracks/+/+/waypoint (QoS 2)
mqtt_1           | 1486079775: owntrackstest/testdevice 2 owntracks/+/+/waypoint
mqtt_1           | 1486079775: Sending SUBACK to owntrackstest/testdevice
mqtt_1           | 1486079775: Sending PUBLISH to owntrackstest/testdevice (d0, q1, r1, m58, 'owntracks/owntrackstest/testdevice', ... (133 bytes))
mqtt_1           | 1486079775: Received PUBACK from owntrackstest/testdevice (Mid: 58)
```

Connection via Websocket-MQTT:
```
mqtt_1           | 1486079894: Received DISCONNECT from owntrackstest/testdevice
mqtt_1           | 1486079894: Client owntrackstest/testdevice disconnected.
mqtt_1           | 1486079894: Client owntrackstest/testdevice disconnected.
mqtt_1           | 1486079894: New client connected from 192.168.0.54 as owntrackstest/testdevice (c0, k3600).
mqtt_1           | 1486079894: Sending CONNACK to owntrackstest/testdevice (1, 0)
mqtt_1           | 1486079895: Received SUBSCRIBE from owntrackstest/testdevice
mqtt_1           | 1486079895: 	owntracks/+/+ (QoS 2)
mqtt_1           | 1486079895: Sending PUBLISH to owntrackstest/testdevice (d0, q1, r1, m59, 'owntracks/owntrackstest/testdevice', ... (133 bytes))
mqtt_1           | 1486079895: owntrackstest/testdevice 2 owntracks/+/+
mqtt_1           | 1486079895: 	owntracks/+/+/info (QoS 2)
mqtt_1           | 1486079895: owntrackstest/testdevice 2 owntracks/+/+/info
mqtt_1           | 1486079895: 	owntracks/owntrackstest/testdevice/cmd (QoS 2)
mqtt_1           | 1486079895: owntrackstest/testdevice 2 owntracks/owntrackstest/testdevice/cmd
mqtt_1           | 1486079895: 	owntracks/+/+/event (QoS 2)
mqtt_1           | 1486079895: owntrackstest/testdevice 2 owntracks/+/+/event
mqtt_1           | 1486079895: 	owntracks/+/+/waypoint (QoS 2)
mqtt_1           | 1486079895: owntrackstest/testdevice 2 owntracks/+/+/waypoint
mqtt_1           | 1486079895: Sending SUBACK to owntrackstest/testdevice
mqtt_1           | 1486079895: Received PUBACK from owntrackstest/testdevice (Mid: 59)
mqtt_1           | 1486079896: Socket error on client owntrackstest/testdevice, disconnecting.
```

**Comment by kylerw** [comment]
Just chiming in to say I'm seeing this same thing.

**Comment by binarybucks** [comment]
The issue doesn't seem to be related to subscriptions or published messages. 
I've removed all related code to test only the bare connection and even then the socket error occurs. 

Paho library stacktrace
```
02-17 21:53:39.432 19990-20600/org.owntracks.android.debug W/System.err: Connection lost (32109) - java.io.EOFException
02-17 21:53:39.432 19990-20600/org.owntracks.android.debug W/System.err:     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:155)
02-17 21:53:39.432 19990-20600/org.owntracks.android.debug W/System.err:     at java.lang.Thread.run(Thread.java:761)
02-17 21:53:39.432 19990-20600/org.owntracks.android.debug W/System.err: Caused by: java.io.EOFException
02-17 21:53:39.432 19990-20600/org.owntracks.android.debug W/System.err:     at java.io.DataInputStream.readByte(DataInputStream.java:270)
02-17 21:53:39.432 19990-20600/org.owntracks.android.debug W/System.err:     at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
02-17 21:53:39.432 19990-20600/org.owntracks.android.debug W/System.err:     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:113)
02-17 21:53:39.433 19990-20600/org.owntracks.android.debug W/System.err: 	... 1 more
```

Mosquitto log
```
Feb 17 21:56:25 srv01 mosquitto[10226]: New client connected from 192.168.1.99 as alexander/5x (c1, k3600, u'alexander').
Feb 17 21:56:25 srv01 mosquitto[10226]: Sending CONNACK to alexander/5x (0, 0)
Feb 17 21:56:26 srv01 mosquitto[10226]: Socket error on client alexander/5x, disconnecting.
```

**Comment by GravHub** [comment]
Owntracks with Websocket stopped working for me since October. I've checked this again by using version **0.6.14**  where I do not get socket errors whereas I do get them with newer versions of owntracks.

I don't know if this information is of use.

**Comment by zgilburd** [comment]
+1, affecting latest version of Android installs. Clients are immediately disconnected from WebSocket connections, citing 32109.  That error code is supposedly reserved for server-forced disconnects so it seems this bug also raises the wrong disconnect code.  Fortunately for iOS users, their Owntracks application is still handling WebSocket connections just fine.

**Comment by binarybucks** [comment]
This is likely an issue in the Paho Java library. I will try with the recently released stable version.

**Comment by nordicblue** [comment]
Subscribing to thread, experiencing the same issue:

Latest Android app running on Android 7.0 (did a fresh install, after my upgrade from 6)
ngnix proxy with websockets and basic authentication
Mosquitto 1.44.11

I recently upgraded my phone to 7.0 and this issue became more evident at that time, although it did happen before. Since my Android upgrade, the mosquitto logs will show thousands of these connection errors. 

Also, since the upgrade, I have had my Mosquitto crash on me 2 days in a row now. Not 100% sure yet on if they are related. Before then, however, my Mosquitto had been running flawlessly for at least 3 months.

**Comment by Cadair** [comment]
I am seeing the 32109 error but I am still getting successful location updates back to my broker. I have disabled updates to the android app so that I can still use it with my websockets setup.

**Comment by dc297** [comment]
Hey try using the paho client version 1.1.0 to build. Websockets works with that version.

**Comment by zgilburd** [comment]
Would you please try to pull the latest paho and recompile and push?  It's a real pain to use Owntracks without good websocket support.

**Comment by zgilburd** [comment]
Would you please consider pulling the just-slightly-older 1.1.0 version of paho until their master/stable is fixed? @binarybucks 

I'm sure many users would appreciate this. Owntracks on Android without websockets has proven rather unreliable for me.

**Comment by binarybucks** [comment]
I've pushed a new version with the 1.1.0 Paho version to the beta channel. 
I'm still getting the EOF error but this might also be caused by the VPN connection. 

Could you please test 1.1.8 (11801) from the Google Play Store beta channel?

**Comment by zgilburd** [comment]
Websockets in the beta channel are working great for me.

**Comment by zgilburd** [comment]
Websockets in the beta channel, on Owntracks version 1.1.8 (11801), are working great for me.  FWIW, I'm using Mosquitto as my broker.

**Comment by nordicblue** [comment]
How do I get the beta version? I went to the beta tab and it says no beta versions available. Android  7 on Galaxy S7 edge. Thanks!

**Comment by Cadair** [comment]
The beta version is working well for me. It's maintaining a "connected" endpoint state which is the first time I have seen that using websockets.

**Comment by KingJ** [comment]
Can also confirm that the beta version is working here - I am now able to connect without issue using Websockets.

**Comment by mrueger42** [comment]
I know this has been closed for a while, but I think I might have a fix for the problem in
https://github.com/mrueger42/paho.mqtt.java/tree/issue501
The underlying problem is that not all WebSocket frame types were handled, especially continuation. Some servers seem to (occasionally) send zero length ones. The WebSocket implementation is still very incomplete though.
