### ISSUE TITLE
Adafruit.io

### ISSUE THREAD

**Issue by geckohouse** [owntracks/android#450]
I am attempting to connect to adafruit.io but having no luck - 
In owntracks: preferences i have connection set to private mqtt.

host - adafruit.io
port 8883
websockets is currently off but i have tried it with it on.
My username is my 'adafruit username'
my password is my 'aio key'
device id = the same as my <feed name>
tracker id = us

TLS is off

What is wrong with this picture?

**Comment by jpmens** [comment]
No idea; we're not familiar with that service. (The reason we're not familiar with it is that we strongly recommend not using pubilc services; set up your own broker for privacy.) That said, there could be any amount of imposed limitations, including topics to which you may publish to/subscribe from. Check their documentation and adapt our apps using an OTRC configuration as described in our Booklet.

**Comment by binarybucks** [comment]
@geckohouse what error do you get? It's hard to help you without any details ;)

**Comment by binarybucks** [comment]
Closing due to lack of any response

**Comment by bartman121** [comment]
i managed to publish to adafruit.io

You have to

**Comment by Joshy-2010** [comment]
I tried it again today. Not sure what I did differently. Now it works perfectly. I can upload data from owntracks to adafruit io and I can also manually add datasets which when get shown in owntracks. If I find out what made it work, I'll post it here.
