### ISSUE TITLE
command executed on all devices when published to bad topic

### ISSUE THREAD

**Issue by capulo** [owntracks/android#451]
i accidentaly published cmd for reporting location to bad topic and i got reply from all devices :)
in booklet is definition: owntracks/user/device/cmd with _type=cmd for remote commands
but when i  sent message this way:
mosquitto_pub -t owntracks/anything/cmd -m '{"_type":"cmd","action":"reportLocation"}'
i got reply from all devices attached to my local mosquitto server
'anything' could be really anything you want
i don't think this is some secret feature :) so probably a bug

**Comment by jpmens** [comment]
You are saying that a publish to `owntracks/BLURB278/cmd` is responded to by all devices? Show us.

**Comment by capulo** [comment]
check screenshot from mqtt-spy
![virtualbox_debian64_2_20_02_2017_09_02_24](https://cloud.githubusercontent.com/assets/25885970/23116605/a7a4d260-f74b-11e6-9f97-e91316f83230.png)

**Comment by jpmens** [comment]
Can you please export the configuration of the two devices and show us `subTopic` from the JSON output? If necessary, you can send these configs to support@owntracks.org

**Comment by capulo** [comment]
here are configs
i'm just removed host IPs


[capo.otrc.txt](https://github.com/owntracks/android/files/787197/capo.otrc.txt)
[kika.otrc.txt](https://github.com/owntracks/android/files/787198/kika.otrc.txt)

**Comment by jpmens** [comment]
Thank you for the data. I note the configuration specifies a `subTopic` of `owntracks/+/+`, and this should be "seeing" but not processing `cmd`. I am marking this as a bug.

**Comment by binarybucks** [comment]
Fix is in master
