### ISSUE TITLE
Connection Setting: Socks5 Proxy

### ISSUE THREAD

**Issue by foertel** [owntracks/android#452]
Hey,

as we motivate more and more people to use Tor on their mobie phones, as well as to host their own IoT instead of relying on third party vendors, it would be great to have owntracks connect to my home automation / mqtt via Tor / hidden service.

Orbot runs the Tor client on Android and offers a SOCKS5 proxy for all apps. If I could configure a SOCKS proxy (localhost:9050) in orbot, it could communicate over Tor without rooting the phone.

At the moment I rooted my phone and made owntracks talk to my mqtt via the Orbot firewall. But it would be great to not have root in the first place.

**Comment by binarybucks** [comment]
We currently do not have plans to implement this feature. If your current setup is working with root, I suggest you continue using this.
