### ISSUE TITLE
Can't build project in Android Studio v2.3

### ISSUE THREAD

**Issue by petkov** [owntracks/android#453]
Hello,

I have difficulties building the project in the Android Studio v2.3 (the latest one, installed it today).

One I do "Sync Project With Gradle Files" I get a warning saying:
Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.

If I then try to build the project I get errors similar to below one:
/Users/avyatchanin/projects/owntrack/android/project/app/src/main/java/org/owntracks/android/model/FusedContact.java
Error:(16, 29) error: cannot find symbol class BR

Looks like the android-apt has been deprecated in the latest version of Android Studio: http://stackoverflow.com/questions/42632662/android-studio-warning-using-incompatible-plugins-for-the-annotation-processing

I've tried several options but still don't know how this problem can be fixed.
Will really appreciate your help.

Regards,
Alexey

**Comment by binarybucks** [comment]
You are correct. APT is deprecated in v2.3. 
Currently the EventBus library has some problems with the new preprocessor format, hence all the build errors.

**Comment by binarybucks** [comment]
Can you please try if you can build the project with https://github.com/owntracks/android/commit/2f0c539d72f7814033db3d6f95549377b31d6470?

**Comment by petkov** [comment]
That works! Thank you so much for a quick response!
