### ISSUE TITLE
some fields are missing

### ISSUE THREAD

**Issue by Vorms** [owntracks/android#454]
Hello, on my smart phone, some fields a re missing, for example altitude.
I enabled extra data....

here is a json message:
{"_type":"location","tid":"01","acc":20,"batt":82,"conn":"w","doze":false,"lat":46.2251267,"lon":6.100105,"tst":1488961085}
Thanks for your help.
Best regards

**Comment by jpmens** [comment]
Altitude doesn't exist on Android; we're updating the documentation now.
