### ISSUE TITLE
Issue with ibeacons on android

### ISSUE THREAD

**Issue by chriscolden** [owntracks/android#455]
I am having issues with ibeacons on android. Owntracks doesn't always pick up the beacons even though other apps are able to see them just fine. Then when it does work usually after a force close and start again, it will trigger event for entering multiple beacons.

I have 4 beacons setup. the phone is able to see them all at all times, but one will be closer than the others. The entry leave events should only trigger for the closest one. This will allow for room detection.

edit: All beacons share the same uuid, and major number is always 1, the minor is different for them all 1-4.

Regards
Chris

**Comment by tleegaard** [comment]
Maybe this is the same issue as https://github.com/owntracks/android/issues/445#issuecomment-280917035

**Comment by binarybucks** [comment]
It probably is, see #445.
