### ISSUE TITLE
Friends are not updated

### ISSUE THREAD

**Issue by RDCH106** [owntracks/android#458]
I am using HTTP mode to track a couple of Android devices.

The data of the last location of each device is resturned  for each post request.  Both devices are located in the first time, but the location is never updated again. The status notice the good parsing in the response.

The locations are only updated if I stop completely the Owntracks app and I restart it again.

Is it a bug? Or must I return with the response some extra data? The current response is:

```
$response = array(array('_type' => 'location', 'tid' => $data1['tid'], 'lat' => $data1['lat'], 'lon' => $data1['lon']),
                    array('_type' => 'location', 'tid' => $data2['tid'], 'lat' => $data2['lat'], 'lon' => $data2['lon']));

print json_encode($response);
```

Thanks in advance for your help!

**Comment by RDCH106** [comment]
Can someone help me with this?

**Comment by binarybucks** [comment]
Your response doesn't include a `tst` attribute. Please return a timestamp of the location and check if the locations are updated.

**Comment by binarybucks** [comment]
Closing for lack of response

**Comment by RDCH106** [comment]
That was the problem.
Thanks!
