### ISSUE TITLE
Android Notifications

### ISSUE THREAD

**Issue by mk1113** [owntracks/android#459]
When I receive a notification when someone enters/leaves a region on my device, the notification I receive just says "Event" and no notification sound. Is there something I haven't setup correctly or is this expected behaviour? I'm currently using a Samsung Galaxy Note 4 device.

**Comment by binarybucks** [comment]
Can you please post some more information (OS version, Event JSON, Waypoint JSON) and possibly a screenshot?

**Comment by mk1113** [comment]
Android Version: 6.0.1
Event JSON: 
2017-04-05T10:43:08Z	event             	{"t":"c","tst":1491388988,"acc":10,"_type":"transition","event":"enter","lon":<LONGITUDE HERE>,"lat":<LATITUDE HERE>,"wtst":1491387439,"tid":"KK","desc":"KK-Work"}
Waypoint JSON:
2017-04-05T10:17:19Z	waypoint          	{"_type":"waypoint","tst":1491387439,"lat":<LATITUDE HERE>,"lon":<LONGITUDE HERE>,"rad":250,"desc":"KK-Work"}
Screenshot:
I don't have one right now but it literally is just a notification bar with the OwnTracks Icon and the word "Event"

**Comment by mk1113** [comment]
See attached screenshots. Interestingly it appears to work fine on my Samsung Gear S2. However, even with  the Gear S2, I don't get a vibrate on the arrival of the notification.
![screenshot_2017-04-05-18-33-43](https://cloud.githubusercontent.com/assets/26929534/24732690/6fe0c196-1a40-11e7-9f00-9c2f38b73616.png)
![20170405_183406](https://cloud.githubusercontent.com/assets/26929534/24732694/757036aa-1a40-11e7-9f14-3db5b8b3a705.jpg)

**Comment by binarybucks** [comment]
There is no vibrate for the notifications.
The events notification looks a bit broken. The Samsung launcher probably doesn't handle the notification group correctly. You cannot swipe down the notification to expand it, can you?

**Comment by mk1113** [comment]
No I tried to swipe down and hold it, nothing more displays. When you select it, it just takes you to the Owntracks map and doesn't indicate what the event actually is.

**Comment by mk1113** [comment]
I tried swiping down again today and it appears to display the alerts. It would be nice if it showed in the notification itself, much like Life360 does.

**Comment by johnjore** [comment]
I have a variation of this issue. In my case I've turned off all notifications, but I still get the "Events" notification (with no details).  If you need this as a separate issue let me know?

JJ

**Comment by binarybucks** [comment]
That's interesting. I'll look into it.

**Comment by johnjore** [comment]
Thanks. As an FYI, I'm on 1.1.7 (11701).

**Comment by binarybucks** [comment]
2.0 version will have a rewritten notification code. Please report back if it works better once it is released.
