### ISSUE TITLE
The following "Remote management" ops are not working on android clients

### ISSUE THREAD

**Issue by tclarsson** [owntracks/android#462]
{"_type":"cmd","action":"dump"}
{"_type":"cmd","action":"action","url":"http://support.owntracks.org"}
{"_type":"cmd","action":"reportSteps"}
{"_type":"cmd","action":"action","content":"Backend maintenance scheduled for tonight\n\nhttp://support.owntracks.org"}
{"_type":"cmd","action":"action","content":"<a href='http://support.owntracks.org'>Backend Maintenance tonight</a>"}

**Comment by binarybucks** [comment]
Those are not supported on Android and there are currently no plans to change that. 

The documentation will be updated accordingly soon.
