### ISSUE TITLE
Can't connect to Losant broker. 

### ISSUE THREAD

**Issue by skbobade** [owntracks/android#464]
Losant.com provides infrastructure for IoT applications. It uses access key and secret pair which is to be used as username and password. When used with Owntracks, connection results I  "not authorised to connect". I am able to connect generic MQTT application MQTT Dash without problems. 

It maybe possible that part of username or password is getting truncated, resulting in authentication failure.

**Comment by binarybucks** [comment]
There isn't any code that explicity truncates credentials. 

Did you set the correct client ID? The documentation states "client id must be set to a valid device ID that is already registered with the Losant platform"

**Comment by skbobade** [comment]
I did. To verify it, I used MQTT Dash app to connect to Losant and it worked.

**Comment by binarybucks** [comment]
Did you set "mqttProtocolLevel=4, pubRetain=false,pubQos=0,cleanSession=true" as mentioned in the review?

**Comment by skbobade** [comment]
I believe among the settings you mentioned, only Clean Session = true can be set in Owntracks. I do not know how to set others.

I can share device id and key pair for my device, to you in private message. So if you use it I can verify when it connects. Below is an expired keypair 
Device ID: 58f38d8bca2ee50001687605
Username: 1f5186e6-71da-4d02-ac6b-5c1de78fc91b
Pass: c31b19bda2a140604d9e162a261ba498d8226506f95d70cba331b9a72e9fb17d

**Comment by jpmens** [comment]
Other settings are configured via a `.otrc` file as described in the [Booklet](http://owntracks.org/booklet/features/remoteconfig/)

**Comment by binarybucks** [comment]
If I recomment you to set some keys, you can believe me that they exist ;) 
See the link JP posted to create a .otrc file that can be used to set many advanced settings.

**Comment by binarybucks** [comment]
Important is (amongst others) mqttProtocolLevel=4. With the default 3 your device ID will get truncated to 23 digits.

**Comment by skbobade** [comment]
Okay :) I tried with following json, but ended with same results. Probably I need to read it more c carefully and try again. 
{
    "_type": "configuration",
    "mqttProtocolLevel": 4,
    "pubRetain": false,
    "pubQos": 0,
    "cleanSession": true
}

**Comment by binarybucks** [comment]
I'm able to connect just fine with the following config
```
"_type": "configuration",
"mode":0,
"mqttProtocolLevel": 4,
"host":"broker.losant.com",
"port":8883,
"tls":true,
"pubRetain": false,
"pubQos": 0,
"cleanSession": true,
"clientId":"CLIENT_ID",
"auth":true,
"username":"ACCESS_KEY",
"password":"ACCESS_SECRET"
}
```

**Comment by binarybucks** [comment]
Documented under http://owntracks.org/booklet/tech/mqtt/

**Comment by skbobade** [comment]
Thanks Alexander, 
I tried with the settings and able to connect now.

**Comment by binarybucks** [comment]
Great. If you could update your Play Store review accordingly, that would be great.

**Comment by skbobade** [comment]
Done.

:)
Thanks for help.

**Comment by binarybucks** [comment]
You wrote that the UI could be made simpler and more user friendly. What would you suggest?

**Comment by skbobade** [comment]
1. There could be a wizard for noobs to set things up the first time. Which
will walk through broker settings and geofensing.

2. Preferences menu is all the way down in left bottom corner, but there is
a white space after regions and status that could be used. (maybe I'm not
using all features of the app to make things show up there.)

3. Setting up topics for pub and sub, QoS and maybe some other options can
be added as in UI for setting in "advanced"? Maybe all! (at the risk of
over cluttered UI) or most used settings be added in UI instead of config
file.)

4. Some of the reviews of the app were because of people not being able to
connect due to wrong configuration. However without reading documentation
there was no way to know a configuration file exists. I read first few
pages of documentation and didn't reach to the config file part, as I was
travelling and doing all this on my phone and was anxious to try out. There
can be a message as such?

5. Import configuration settings menu is buried in Export menu.

6. Left pane can show a menu, indicating name of broker and an green or red
indication suggesting status.

- Just some thoughts off my head.

**Comment by ckrey** [comment]
Losant is not an MQTT-3.1.1 compliant broker

https://docs.losant.com/mqtt/overview/

<img width="509" alt="bildschirmfoto 2017-04-18 um 18 42 48" src="https://cloud.githubusercontent.com/assets/4027289/25142447/28aa640e-2467-11e7-9e86-9a817d496cdd.png">

**Comment by skbobade** [comment]
@ckrey, the issue has been resolved with correct configuration file.
