### ISSUE TITLE
Owntracks Android iBeacon waypoints kill wifi speed

### ISSUE THREAD

**Issue by chriscolden** [owntracks/android#465]
Hi,

With own tracks running and scanning for ibeacons  the wifi speeds drop to 1-2mbps.

If I turn bluetooth off on the device the speed returns.

If I turn bluetooth back on speed drops again.

If I then force stop owntracks but leave bluetooth on, wifi speeds return.

I will need to test deleting my regions which use ibeacons and see if running owntracks  with wifi and bluetooth turned on has the same issue.

Let me know if you need more information

Chris

**Comment by syssi** [comment]
I hit the same issue. The beacon has an interval of 100ms. I'm using a nexus 5. The documentation of owntracks has a paragraph about this topic. It's a bug or bad hardware design?

**Comment by binarybucks** [comment]
This might be a known hardware/software issue. Beacon scanning on Android might range from completely broken to working pretty well depending on the hardware. Unfortunately, Google devices are no exception to this. 

From one of the beacon library maintainers: "some mobile devices including the Moto G, Moto X, Nexus 4 and Nexus 7, the combined Bluetooth/WiFi chip prevents simultaneous operation of both radios. Scanning for beacons can make WiFi unreliable and using WiFi can make beacon detections get dropped."

Currently, the app scans for beacons every 30s (foreground) or 120s (background) for 1.1s unless it is using the new Android L background scanning mode. You could try to to alleviate the issue by setting scanning to legacy mode: `beaconMode=1` if you're on Android L or higher. 

If you don't have any BLE regions, scanning should not be enabled. If you want to disable it without removing regions, set `beaconMode=2`.

**Comment by chriscolden** [comment]
Apologies for asking, but how do I set beaconMode=1 on the device?

**Comment by binarybucks** [comment]
Import a .otrc configuration file with that key and import it to the app. See http://owntracks.org/booklet/features/remoteconfig/ for more details.

**Comment by alex-ter** [comment]
I've once had a device, which practically stalled wifi 2.4Ghz traffic with active BT scanning going on.

However switching it to 5Ghz resolved that and I was able to use both wifi and BT without any problems. So, if that's an option and nothing else helps - give it a try.

**Comment by binarybucks** [comment]
No response
