### ISSUE TITLE
OwnTracks has stopped responding to remote commands

### ISSUE THREAD

**Issue by jburgin** [owntracks/android#466]
I have been using OwnTracks for quite awhile, but recently it has stopped responding to remote commands in background or foreground. I am running Android 7.1.2 and OwnTracks 1.1.7. I have uninstalled and reinstalled the app several times. I have tried using a different user to authenticate to my private MQTT server, and I have even factory reset my phone and I still have the issue. It is connected to my MQTT and will send updates when I am moving around. I recently tried sending other commands but the app doesn't respond to those either. I really like the app and hope to get this resolved instead of finding a new solution.

**Comment by binarybucks** [comment]
Please check to which topic you are sending the commands. Previous versions had a bug that accepted commands on the wrong topics. 

It should be `owntracks/user/device/cmd` . 
I will verify if it works with my device later.

**Comment by binarybucks** [comment]
Can you do me a favor and import the configuration below by saving it to an .otrc file and opening it with the OwnTracks app?

```
{
    "_type": "configuration",
    "cmd": true
}
```

**Comment by jburgin** [comment]
I imported the file and restarted the app but it still fails to respond to remote commands.

**Comment by jburgin** [comment]
I exported my current config so you could see if there is anything that looks like it could be causing issues
```
{
   "_type":"configuration",
   "waypoints":[

   ],
   "deviceId":"jeff",
   "notificationHigherPriority":false,
   "pubQos":1,
   "ws":false,
   "beaconMode":0,
   "cleanSession":false,
   "sub":true,
   "pubExtendedData":true,
   "remoteConfiguration":true,
   "locatorAccuracyForeground":1,
   "ranging":false,
   "port":1883,
   "notificationLocation":true,
   "pub":true,
   "ignoreStaleLocations":0,
   "ignoreInaccurateLocations":0,
   "keepalive":3600,
   "beaconLayout":"m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24",
   "subTopic":"owntracks/+/+",
   "password":"**************************",
   "host":"**************************",
   "cmd":true,
   "subQos":2,
   "pubRetain":true,
   "playOverride":false,
   "locatorInterval":450,
   "mqttProtocolLevel":3,
   "autostartOnBoot":true,
   "locatorAccuracyBackground":1,
   "tls":false,
   "notification":true,
   "username":"jeff",
   "locatorDisplacement":250,
   "mode":0,
   "tid":"6p",
   "beaconBackgroundScanPeriod":30,
   "auth":true,
   "beaconForegroundScanPeriod":0
}
```

**Comment by binarybucks** [comment]
I found the issue. The fix will be in the next release.
