### ISSUE TITLE
Offline tracking (enhancemet)

### ISSUE THREAD

**Issue by szimszon** [owntracks/android#467]
Hi,

I just found this app and it is awesome.

I just wondering if would be possible to have some length of message queue to store location data until the connection to the server is available again and then send the stored data to the server?

Br,

**Comment by binarybucks** [comment]
The apps already store messages until a connection can be established. 
Messages are queued in memory so once the app is quit, the queue is cleared. All messages are also removed if you change the mode or the endpoint.
