### ISSUE TITLE
javax.net.ssl.SSLException: I/O error during system call

### ISSUE THREAD

**Issue by daniel-stoneuk** [owntracks/android#469]
After running in the background, status shows the following exception:

![Image](http://i.imgur.com/XPiqZWc.png)

After the app is opened and refreshed it shows this:

![Image](http://i.imgur.com/vlZMYNg.png)

Therefore I don't think its an issue with my private MQTT broker. 

Had a little search around and haven't seen a recent issue posted. I'm using version 11701 of the app on a Nexus 6P 7.1.2 Resurrection Remix. Locater background accuracy is set to low power if that should make any difference.

Any clues?

**Comment by daniel-stoneuk** [comment]
I should add I've only been on LTE which might make a difference now that I think about it. Maybe it would be possible to catch the exception and try again?

**Comment by binarybucks** [comment]
This should be a fairly normal behavior. The app lost the connection to the broker which is nothing to be concerned about. The app tries to connect in regular intervals which might or might not work depending on how much Android interfers. 

Note that with more recent Android versions it is becoming more difficult to maintain a long running TCP connection. If the issue bothers you, you might consider switching to HTTP mode. This mode is stateless and optimized for background usage on newer Android versions (6 and 7, 8 not yet)
