### ISSUE TITLE
1.1.8 publishes transitions events to the wrong topic 

### ISSUE THREAD

**Issue by juzam** [owntracks/android#470]
1.1.8 publishes `_type=transition` events to topic `owntracks/user/device`, not `owntracks/user/device/event`  as it should be.

mosquitto_sub output when subscribing to `owntracks/juzam/#`:

```
owntracks/juzam/nexus5x {"_type":"transition","tid":"5x","acc":18.623,"desc":"Home","event":"enter","lat":nn.nnnn,"lon":nn.nnnn,"tst":1493964722,"wtst":1458916925,"t":"c"}
```

**Comment by binarybucks** [comment]
Interesting, I didn't change anything there :D 
I'll look into it.

**Comment by juzam** [comment]
I'm still seeing the same behaviour with yesterday 1.2.1 (12101) is there anything else I can check?

**Comment by binarybucks** [comment]
Closed by accident. It's the next thing on my todo list.

**Comment by binarybucks** [comment]
I'll get back to you when I need further input.

**Comment by binarybucks** [comment]
Found the issue, thanks for catching it

**Comment by juzam** [comment]
You are doing the hard work, so I should thank you, not the other way around :)
