### ISSUE TITLE
EndPointState.Error with STS MQTT broker

### ISSUE THREAD

**Issue by CubeSS-Bert** [owntracks/android#472]
It seems that there is a confusing between 'Owntracks/Sensetecnic', about username and deviceID.

Not able to publish a message on STS MQTT broker of sensetecnic.
(subTopic changed in configuration file: "subTopic":" users/<username.sensetecnic>/owntracks/")

**Comment by binarybucks** [comment]
Could you please elaborate your problem? 
I don't really understand what you are trying to report.

**Comment by CubeSS-Bert** [comment]
When I look in the Owntracks booklet:

**_type=configuration**
auth => Use username and password for endpoint authentication (iOS,Android/boolean)
deviceId => MQTT client ID (iOS,Android/string)

**Configuration file**
"host":"mqtt.sensetecnic.com",
"port":1883,
"auth":true,
"username":"<clientID.broker>",
"password":"xyzxyz",
"deviceId":"<username.broker>",
"tid":"xy",

![image](https://cloud.githubusercontent.com/assets/28361869/25775074/04d6c286-329d-11e7-842a-6485b675b55b.png)

The only way to get no ClientID failure on side of the broker is to put the <clientID.broker> in the username field of owntracks.

**Comment by binarybucks** [comment]
I verified that the clientId and username are correctly send. There probably is some other broker related issue that causes the message you see. 

Please let  me know if there is anything else that we can help you with.

**Comment by binarybucks** [comment]
No reponse

**Comment by CubeSS-Bert** [comment]
Alexander,

I think I know the reason for the problem.
(#472)

I'm using a mqtt broker of 'FRED.Sensetecnic'-platform. There are some
restrictions to make a valid deviceID.
[image: Inline afbeelding 1]
When I look at the device ID at 'Owntracks'-app, there seems to be always a
slash '/' in the (half automatic generated) deviceID.
(Even when you leave it empty you'll get '<username>/hammerhead'!)

In the configfile, I do not find a way to gif a deviceID without the prefix
<username>/.

Can you have a look at this?
Thanks,

Greetings Bert.




2017-05-13 12:58 GMT+02:00 Alexander Rust <notifications@github.com>:

**Comment by jpmens** [comment]
We are [aware of this issue](https://github.com/owntracks/android/issues/487) and it'll be addressed soon.

**Comment by binarybucks** [comment]
In the meantime, can you not just put your own clientId into the field or use the configuration editor to set your own value that does not include the slash? 

The precomputed one is just meant as a placeholder when no one is set. It's comprised of the username and the device manufacturer name.

**Comment by CubeSS-Bert** [comment]
Alexander,

No it doesn't work because owntracks always puts a / in the result of
clientID.
When I put 'test' in the 'Owntracks' configuration menu, it generates
<username>/test.


Bert.

2017-05-31 20:46 GMT+02:00 Alexander Rust <notifications@github.com>:

**Comment by binarybucks** [comment]
Interesting, it shouldn't do that. 
I'll get that fixed.

**Comment by binarybucks** [comment]
If you set the clientId value through the confirmation management activity, it should not prepend anything. This should only happen if you set the deviceId through the normal connect settings. 
Could you please double check?

**Comment by ckrey** [comment]
see #487

**Comment by CubeSS-Bert** [comment]
Alexander,

It works fine when I put the 'clientID'-value through the confirmation
management.



Thanks.
(Great app, support is even better!)

Bert.

2017-06-01 11:16 GMT+02:00 Alexander Rust <notifications@github.com>:

**Comment by binarybucks** [comment]
Client ID generation is fixed in ff9d626be75e60a4bfd655f4f3de8e02a2cd63b8
