### ISSUE TITLE
report location does not work

### ISSUE THREAD

**Issue by capulo** [owntracks/android#473]
in latest version, after fixing my reported issue https://github.com/owntracks/android/issues/451, report location does not work
i can do for example client.publish("owntracks/capo/sony/cmd", '{"_type":"cmd","action":"reportLocation"}'), but no location is received from device... it works in previous version

**Comment by jtornero** [comment]
Hello,

I can confirm the issue. Just updated a couple hours ago. Notwithstanding, manual report still works.

**Comment by binarybucks** [comment]
To which version did you update?

**Comment by jtornero** [comment]
@binarybucks Updated to 1.1.7(11701) on android 4.4.2 kernel 3.4.67 compilation 1.5.3_20150618-1313

My config

{"_type":"configuration","waypoints":[],"port":########,"beaconForegroundScanPeriod":0,"sub":true,"locatorInterval":60,"ignoreInaccurateLocations":0,"pubQos":1,"locatorDisplacement":20,"beaconBackgroundScanPeriod":30,"password":"########","mode":0,"ranging":false,"username":"######","notificationLocation":true,"notification":false,"keepalive":60,"deviceId":"bq","beaconMode":0,"subQos":2,"host":"#######","tls":false,"ws":false,"pubRetain":true,"pub":false,"remoteConfiguration":true,"autostartOnBoot":true,"cmd":true,"ignoreStaleLocations":0,"beaconLayout":"m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24","playOverride":false,"notificationHigherPriority":false,"subTopic":"owntracks/+/+","locatorAccuracyForeground":2,"locatorAccuracyBackground":2,"mqttProtocolLevel":3,"pubExtendedData":true,"auth":true,"cleanSession":true}

**Comment by capulo** [comment]
On my side version 1.1.7 with android 4.4.4

**Comment by binarybucks** [comment]
Verified to work in 1.2.3
