### ISSUE TITLE
bluetooth handsfree device could not find phone

### ISSUE THREAD

**Issue by capulo** [owntracks/android#474]
in latest version, ibeacons starts working, but i have problem with handsfree in car. it could not detect my phone until i restart bluetooth or kill owntracks. i think it is heavily using bluetooth what blocks car bluetooth connect to phone

i'm not sure if this is bug, or only feature after ibeacons support :)

**Comment by binarybucks** [comment]
Try setting beaconMode to 1 if you're using Andorid 6 or later. The default Andorid 6+ beacon scanning code is known to cause problems. This is, however, more a hardware/driver issue.

**Comment by binarybucks** [comment]
No response
