### ISSUE TITLE
When assigning custom "pubTopicBase" the "username" and "deviceid" is not added to the published topic

### ISSUE THREAD

**Issue by Grovkillen** [owntracks/android#475]
Please fix so that we don't need to manually add these, and if we export the settings the hard coded values would persist.

**Comment by binarybucks** [comment]
Will do as discussed through email. 

Currently the default replacement is owntracks/%s/%s. Could I just expose the same replacement pattern in which the first placeholder is replaced with the username and the second one with the deviceid?

**Comment by jpmens** [comment]
Sounds sensible to a techie ;-)

**Comment by Grovkillen** [comment]
Works for me. If it is documented it is not a big issue to understand.

Den 13 maj 2017 17:50 skrev "JP Mens" <notifications@github.com>:

**Comment by binarybucks** [comment]
Availabel in version 1.2.3
Added placeholder support for %u (username) and (%d) device. 
Export value for pubTopicBase now also is the placeholder string instead of the formated string.

**Comment by Grovkillen** [comment]
Works just great!

Den 14 maj 2017 12:17 skrev "Alexander Rust" <notifications@github.com>:
