### ISSUE TITLE
Offline map

### ISSUE THREAD

**Issue by audunbrekke** [owntracks/android#480]
It should be possible to cache / download maps in the app. I use an private owntracks mqtt broker on a local network. Sometimes without internet connection. It should then be possible to cache or save maps in the app ot locate the items on the map without internet connection.

**Comment by jpmens** [comment]
I won't ask what the use of a tracking app via MQTT is on a local network.

Be that as it may, as [said here to you already](https://github.com/owntracks/recorder/issues/194#issuecomment-302310793) none of our apps support that, though we will of course entertain a pull-request to make that happen.
