### ISSUE TITLE
Minimum update interval.

### ISSUE THREAD

**Issue by mikecardwell** [owntracks/android#482]
Running this with my own private MQTT server. If I don't move, I don't get any updates. Which is how it is supposed to work from what I've read. *However*, I feel like it should still be possible to configure a minimum update interval even if you don't move. Otherwise, I can't tell if the updates have stopped because the phone isn't moving, or because my phone has run out of battery or because there is a network issue etc.

I'm trying to automate some stuff, and I don't want to make decisions based on location data that is potentially "stale".

**Comment by jpmens** [comment]
Indeed we don't seem to do that in our Android version (contrary to iOS where we do with a `t:p` (ping) in the JSON payload). 

I'm tentatively marking this as a feature request.

**Comment by binarybucks** [comment]
Reporting in regular intervals is not implemented on Android. It also will not be implemented. Background jobs are already broken enough, so there's no need for yet another one. Contrary to popular belief, it also does not give more detailed location results. 

If you want to check if the app is still alive, you can send regular reportLocation commands from the backend. This will mostly do what you want.

**Comment by mikecardwell** [comment]
Can you advise how I go about doing that please? I've tried running the following on the backend but the client doesn't respond to it:

```sh
mosquitto_pub -u mike -P mypassword -t 'owntracks/mike/phone/cmd' -m \
'{"_type":"cmd","action":"reportLocation"}'
```

Have I fundamentally misunderstood something, or should the above work? I have "Remote commands" enabled on Owntracks on my phone. I only found out about this software and MQTT yesterday so I'm a raw newbie.

**Comment by binarybucks** [comment]
It should work if you temporarily use the 1.2.3 beta version. 
1.1.7 has a known issue and does not respond to the command.
