### ISSUE TITLE
reportLocation ignored

### ISSUE THREAD

**Issue by mikecardwell** [owntracks/android#483]
Sending a reportLocation does not trigger the Android client to send any updates to the MQTT server.

I'm running the command:

```bash
mosquitto_pub -u mike -P mypassword -t 'owntracks/mike/phone/cmd' -m \
'{"_type":"cmd","action":"reportLocation"}'
```

Whilst subscribed to everything:

```bash
mosquitto_sub -u mike -P mypassword -v -t '#'
```

I see `{"_type":"cmd","action":"reportLocation"}` in the terminal running the subscription, but no other follow up messages from my Android ownTracks client.

This issue was triggered by my comments in https://github.com/owntracks/android/issues/482

I ran reportLocation commands on a 15 minute interval for the past 11 hours and my phone did not send a single message in that time (it had not moved). The second I open the app on my phone, it reports its location.

**Comment by binarybucks** [comment]
which version (full build) are you using?

**Comment by jpmens** [comment]
@mikecardwell we've just tested with `1.2.3 (12302)` and the location is reported instantaneously if remote commands are enabled. (You had said you've enabled them.)

**Comment by mikecardwell** [comment]
I'm running the latest version available to my phone on the Google Play store (1.1.7)

**Comment by binarybucks** [comment]
Sorry for your issues then. This is probably a problem  that slipped during beta testing. 
I think I have fixed it already in the current beta version. 

Could you temporarily sign up for the beta version 1.2.3 at https://play.google.com/apps/testing/org.owntracks.android and install that version as a regular Play Store update?

**Comment by mikecardwell** [comment]
Version 1.2.3 fixes it. Thank you for your quick responses, and for developing such a great app.

**Comment by binarybucks** [comment]
You're welcome. I'm glad that this fixed it for you.
