### ISSUE TITLE
setWaypoints remotely not working

### ISSUE THREAD

**Issue by przemas75** [owntracks/android#484]
`mosquitto_pub -t owntracks/user/device/cmd -h hostname -p 1883 -u username-m '{"_type": "cmd","action": "setWaypoints","payload": {"waypoints": [{"desc": "waypointname","rad": 200,"lon": yy.yyyyy,"lat": xx,xxxxx,"tst": 1437552714,"_type": "waypoint"}],"_type": "waypoints"}}' -P pass`
Doing this command, im not able to set a new waypoint remotely.
Checked with owntrack ver 1.2.3 (test ver) from https://github.com/owntracks/android/issues/483
but it does not work.

**Comment by jpmens** [comment]
Have you verified that you've allowed remote commands?

Which version of Mosquitto clients are you using? There was a bug in a slightly older version which truncated payloads longer than NNN octets (I don't recall the length of NNN). Could you verify please by subscribing to the same topic and check whether you see the full payload you publish?

Please also publish with qos=2 in order that the broker has a chance to actually transmit this message to the client.

**Comment by binarybucks** [comment]
The attribute is called `waypoints` and not `payload`. 
However, the Android app also did not behave according to the documentation. 
I've changed the behavior in build 1233. It now is a bit more verbose, but you can now easily reuse the output of the waypoints export. 

```
{"_type":"cmd","action":"setWaypoints","waypoints":{"_type":"waypoints","waypoints":[...]}
```

**Comment by przemas75** [comment]
OK, thank you!
However i took the attr from documentatiation:
http://owntracks.org/booklet/features/remoteconfig/#setwaypoints

**Comment by jpmens** [comment]
@przemas75 documentation fixed; sorry about that.
