### ISSUE TITLE
Beacon transitions wobbly when app not in foreground

### ISSUE THREAD

**Issue by AnassSaikouk** [owntracks/android#486]
Hi, i ve tested the application, it work very well when the screen is on, but when i use another application or when the screen is off, i can't receive the transition event, hence when i unlock the screen i receive all the event, i belive it's not the case for all of you?

**Comment by binarybucks** [comment]
Have you enabled the ongoing notification?

**Comment by AnassSaikouk** [comment]
@binarybucks yes already done, 
![18902683_10206875945576464_1193748871_n](https://cloud.githubusercontent.com/assets/27215248/26756227/bec1d440-489d-11e7-822d-d032e4cfdf63.jpg)

**Comment by binarybucks** [comment]
What do you mean that you receive the messages when you turn the screen on? 
What do you expect to happen when the screen is off? 

Currently, transition events are only shown in the drawer but the screen does not turn on for them.

**Comment by AnassSaikouk** [comment]
for example when the screen is off and the phone approaches to a beacon i should have an enter message in MQTTlens but the problem is that i can receive this messages of enter/leave just in the case when i'm navigating on the application. (if the screen is off or if i'm navigating on another app i don't receive the message so that's not good because the person has passed near and leaved without receiving any message transition ... )

and what i meant by : receive the messages when i turn the screen on : 
all the messages i didn't receive in real time i receive them after entering on the app.(and logically i can't navigate all the time on the app), was the app developped this way ?

**Comment by jpmens** [comment]
@AnassSaikouk are you referring to notification messages on your device's *screen*, or are you referring to MQTT messages as received by your *broker*?

**Comment by AnassSaikouk** [comment]
@jpmens I will give an example :
1) Imagine i ve added a pharmacy beacon in the application in my phone then i gived the phone to my grand parent.
2) on the MQTTlens, i can receive the enter message for example (type : transition, desc: Pharmacy Beacon, event: enter....)
**When my grand parent approaches to this beacon i should receive an enter message in my broker whatever is the screen (on or off) so the problem i told u is that i can receive this message in my broker side just if i navigate on the app.

**Comment by jpmens** [comment]
We know that on Android the Beacon messages are a little wonky, but there's not much we can do about it at the moment. It appears the library is being rewritten by its authors so maybe future versions will be better, but I cannot say when that'll be. 

Indeed when the app is open in foreground the processing of Beacon events seems more stable than when the app is in the background.

**Comment by AnassSaikouk** [comment]
Ok, Thank you mr @binarybucks  & mr @jpmens  for your  answers.
