### ISSUE TITLE
Restrict clientId to minimum MQTT 3.1.1 requirements

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#487]
as with [iOS](https://github.com/owntracks/ios/issues/450#issuecomment-305114172)

**Comment by ckrey** [comment]
owntracks/ios#450

**Comment by binarybucks** [comment]
Fixed in ff9d626be75e60a4bfd655f4f3de8e02a2cd63b8

**Comment by jcollie** [comment]
Has a new version been pushed to the Play Store? I'm running into this issue and version 1.2.3 of the client is what's available to me from the Store.
