### ISSUE TITLE
'configuration incomplete'

### ISSUE THREAD

**Issue by consolacion** [owntracks/android#490]
android app  tells me 'configuration incomplete' without telling me what. Tried to fill out any field i came across.  Nothing.
I have a functioning MQTT server that I try to connect to. No owntracks/#  messages published at all.
owntracks sees my location, but thats it

**Comment by binarybucks** [comment]
App version?

**Comment by consolacion** [comment]
latest, just downloaded from playstore

**Comment by binarybucks** [comment]
There is an alpha, beta and the production version and different rollout stages on the Play Store. 
Please post the full build number that is shown in the app.

**Comment by consolacion** [comment]
Where in the app?

**Comment by consolacion** [comment]
ah it says 1.2.3(12304)

**Comment by binarybucks** [comment]
Did you set a username in the connection preferences?
If so, please send a configuration export to support@owntracks.org.

**Comment by consolacion** [comment]
yes i did. Where do i find a config export?

**Comment by binarybucks** [comment]
Preferences, Configuration management, _three circles menu_, Export.

**Comment by consolacion** [comment]
yes, found it already. Tnx for yr quick, ultra quick reaction here  :-)

**Comment by binarybucks** [comment]
It seems that you enabled authentication for the broker but did not provide a password. 
Please check Preferences, Connection, Identification, Password. 

After changing anything in the connection preferences, you have to connect again by hitting the single arrow button.

**Comment by consolacion** [comment]
I did not set any authentication myself. just left it as is. there is no authentication on my broker.
So I now switched off TLS (being the only security parameter i could find).
But still 'incomplete'

**Comment by binarybucks** [comment]
Then don't switch on authentication.

**Comment by binarybucks** [comment]
Don't switch of TLS, switch of authentication.

**Comment by consolacion** [comment]
switched that off now. still incomplete,  restarted.  pressed the up arrow. no difference

**Comment by consolacion** [comment]
TLS ON authentication off is what I have

**Comment by consolacion** [comment]
OK fresh restart, now I get "Error"

**Comment by consolacion** [comment]
but I am on th eright track I guess as I now get 'queued messages' :-)

**Comment by binarybucks** [comment]
Probably because you enabled TLS but did not configure TLS on your broker. 
What is shown on the status page (navigation drawer) under _Endpoint state message_?

**Comment by consolacion** [comment]
javax.net.ssl.SSLHandshakeException:SSL handshake aborted:ssl ox bunch of nrs: I/O error during systemcall, Connection reset by peer

**Comment by consolacion** [comment]
ok, switched off TLS. seems to be working now.
Thanks for your great assietnce

**Comment by binarybucks** [comment]
Glad it is working now. 
You might want to look at our [booklet](https://github.com/owntracks/booklet) for some background information before continuing though.

**Comment by consolacion** [comment]
yes I had before I raised issue. Thanks again ;-) perfect for OpenHab

**Comment by consolacion** [comment]
yes I had before I raised issue. Thanks again ;-)

Presence detection in OpenHab: Perfect!!

**Comment by JsBergbau** [comment]
I have the same issue. I have a local broker without any authentification. I've setup host ip address and port, Websockets is off. But still it says configuration incomplete. I can't find any auth off switch. Version 2.1.3 (21302)

**Comment by jpmens** [comment]
You are commenting on a 3yo ticket ...

Have you set username and device name?

**Comment by JsBergbau** [comment]
Yeah, Google finds this as first result when you search for "owntracks konfiguration unvollständig"

Found out how to manage: You have to go the manual configuration editor and set auth to false
Then you still have to configure a user and a device name. Sorry thats really complicated, cost me over 30 minutes to get this to work.

**Comment by jpmens** [comment]
Username and Device are set in Connection/Identification. I think if you don't set a password we don't use one.

**Comment by JsBergbau** [comment]
You need one and its very hidden https://owntracks.org/booklet/features/android/#setup

**Comment by growse** [comment]
> 
> 
> I have the same issue. I have a local broker without any authentification. I've setup host ip address and port, Websockets is off. But still it says configuration incomplete. I can't find any auth off switch. Version 2.1.3 (21302)

This is one of the things we're hoping will be sorted in the 2.2.0 version, as the UI could be a lot better here.
