### ISSUE TITLE
no altitude reported?

### ISSUE THREAD

**Issue by zavorra** [owntracks/android#494]
I would like to receive altitude informations from the android app. 
After a quick look in MessageLocation.java seems that it is never delivered. Is there a reason to it?

**Comment by binarybucks** [comment]
Altitude reporting is only supported on the iOS version.

**Comment by jpmens** [comment]
This is documented in the Booklet.

**Comment by zavorra** [comment]
Ok, thanks, i must have missed it in the booklet. 

Is there a reason to not report altitude on android?

**Comment by jpmens** [comment]
The value's not available.

**Comment by binarybucks** [comment]
Oh it might be on some devices. There just were other features that were required more urgently.
