### ISSUE TITLE
Is altitude available generally now?

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#495]
We should check whether `alt`itude is now generally available on Android devices and bring this up to par with our iOS app. 

(/[via](https://github.com/owntracks/android/issues/494#issuecomment-307628361)

**Comment by binarybucks** [comment]
Of course it's not generally available. It's fragmented like everything else.

**Comment by jpmens** [comment]
By which I meant, if we can do something like

```
if (we have altitude reports on this version of Android and this specific model) {
  jsonAdd(location, "alt", nnn)
}
```

;-)

**Comment by zavorra** [comment]
I am no way an android developer, so sorry for the obviously naive question, just out of curiosity. How could the altitude data be unavailable? 
There are (always been) lot of apps providing altitude information.

**Comment by jpmens** [comment]
IIRC when we started with OwnTracks on Android there were deficiencies in the API which didn't enable us to reliably obtain altitude on all devices. At the time (this is now several years back) we decided to drop the attempt.

With this issue, we will, time permitting, re-investigate, but at low priority; there's still lots of other things ahead of this in the queue. :-)

**Comment by jpmens** [comment]
@zavorra be advised: our next Android version will carry the `alt` attribute; if a particular platform/device doesn't report it, it'll be zero. 

The next version will become available when it is ready.

**Comment by zavorra** [comment]
Great, thanks

BTW, since -1 is a valid value, I would suggest to simply not send the (optional) alt attribute when not available

**Comment by zavorra** [comment]
Sorry, I meant "since 0 isa a valid value..."

**Comment by binarybucks** [comment]
Added in 2.x

**Comment by zavorra** [comment]
Great! Thanks

Is this version going to appear on the play store or is it something I need to build?

**Comment by jpmens** [comment]
@zavorra It will be on the Play Store when it's ready.
