### ISSUE TITLE
Keep the app running?

### ISSUE THREAD

**Issue by Diaoul** [owntracks/android#498]
Is there a way to have the app always running like a background service even when the said app is closed?
I find myself too often closing owntracks with other apps by (bad) habit...

**Comment by binarybucks** [comment]
If you enable the ongoing notification, the app will keep running, even if you close the app in the app switcher.

**Comment by Diaoul** [comment]
I guess this means that currently there is no other way to achieve the same without the ongoing notification right? Would you consider this as a feature request?

**Comment by binarybucks** [comment]
No, because there is no way to work around this without rooting. '
The OS will kill the app if it doesn't have a ongoing notification.

**Comment by Diaoul** [comment]
Ok, thanks for the clear answer :+1:
