### ISSUE TITLE
Dateformat and bold characters in notifications

### ISSUE THREAD

**Issue by gummigroda** [owntracks/android#499]
Hi.

![20170622_074001](https://user-images.githubusercontent.com/15022172/27419505-9328734c-5721-11e7-845d-fd4300403970.jpg)

* The dateformat does not follow the regional settings of the phone, it seem to default to US?
* The first 6 characters of the username is bold, the rest is not.

All this on a Samsung S6, with Android 6.

**Comment by binarybucks** [comment]
Which version are you using (build number?

The date format is handled by Android itself (the app just sets the Unix timestamp of the notification and the OS converts that). 

The bold text is interesting, I'll look into it.

**Comment by gummigroda** [comment]
Ok.
Running version 1.2.3 (12304)
