### ISSUE TITLE
1.2.6 Open Map

### ISSUE THREAD

**Issue by jkvalence** [owntracks/android#501]
Upgraded to 1.2.6 overnight.  When I launch the front end, the map is blank.  No matter how much time passes, the map stays blank.  If I go to friends and click a friend, then the map populates.  I closed the front end completely and opened it twice with same result.

**Comment by lovethat** [comment]
Does the blank map still show the 'Google' at the bottom left? If so,  try and zoom out and move around in it.  It may be that a location is loaded such that it is zoomed in on a grey, blank-looking area.

**Comment by binarybucks** [comment]
Are you using Android 6?

**Comment by jkvalence** [comment]
@binarybucks Android 7.0.

@love that the Google icon is there and I tried what you suggested but no change on the map.

**Comment by gareth-ellis** [comment]
I see the same on Android 7.1.1

**Comment by binarybucks** [comment]
The issue is likely caused by a too thourough workaround for crashes on Android 6. 
The map is not initialized correctly. I will upload a fixed version shortly.

**Comment by gareth-ellis** [comment]
One more thing I've noticed, is that previously in the notification bar it would have the geolocated location, now it just has the long/lat

**Comment by binarybucks** [comment]
Thanks, I'll have a look
