### ISSUE TITLE
F droid compatibility / google play services dependency

### ISSUE THREAD

**Issue by ouinouin** [owntracks/android#503]
Hi, 
according to the documentation, your software looks great, but seems to rely on google play services, wich isnt compatible to all of my android devices (im using lineageos roms with my phone without google plays services for privacy purpose).
So i managed to install it but cant use it.

is your code tightly tied to google play services, or can it run or be replaced easily with the NLP services that are to my understanding more generic than the google location provider services.
here are the nlp backends available for location, not depending on google play services : 
https://github.com/microg/android_packages_apps_UnifiedNlp
Would this switch to an app depending only of fully open parts be part of your plan in a mid term /long term ?
Thanks again for all the efforts put in this apps.

**Comment by binarybucks** [comment]
This has been discussed over and over again. 
Owntracks depends on Google Play Services. 
There is no plan to change this.
