### ISSUE TITLE
Internal and external host address

### ISSUE THREAD

**Issue by seeknowevil** [owntracks/android#504]
**App build number**:  1.2.7
* **Android version**:  7.1
* **Device**:  ZTE AXON 7

I've been using owntracks and am having an issue with not being able to access the mosquitto from inside the home network due to using a ddns. My modem router doesn't support Nat loopback so it just gives an error. 

It would be handy to have the ability to supply both an internal and external host address and a WiFi name which tells owntracks when it should use either. Have a look at the nzb360 app for an example.

**Comment by binarybucks** [comment]
There are no plans to implement this.

**Comment by seeknowevil** [comment]
Maybe the should be

**Comment by binarybucks** [comment]
You're free to submit a pull request.

**Comment by jpmens** [comment]
@seeknowevil I do this using my own internal DNS server (eg. _dnsmasq_) which simply provides a different address when I'm in $HOME lan. We do not think there is the need for what you suggest.
