### ISSUE TITLE
Owntracks isn't sending location reports.

### ISSUE THREAD

**Issue by pservais** [owntracks/android#505]
I've noticed that my home automation systeem didn't see me leaving home.
The app does not send any location reports, not automatic nor manual.
In Status it says that the app is connected to my MQTT broker.
When publishing the waypoints from the app, the messages arrives at my broker.
So the MQTT part is working.
What's weird is that if I press the manual update icon, no 'Message queued' message is displayed.
I've tried to reinstall the app, but sadly with the same results.
My wife has the same issue with her phone.

Can someone please help us?

* **App build number**: 1.2.7 (12701)
* **Android version**: 6.0.1   
* **Device**: HTC M8s

**Comment by binarybucks** [comment]
Did you enable the ongoing notification?
Did you choose balanced locator accuracy? If so, did you enable wifi and enable wifi on during sleep in the wifi preferences?
Did you create any broker ACLs?
Please post logs from your broker

**Comment by pservais** [comment]
Hi Alexander,

The ongoing notification is enabled
Wifi is enabled and on during sleep.
No ACL's are made.
In fact, nothing has changed in my setup.
The only thing that happend is that my ddns provider has gone awol :)
So I changed that to another and modified it in the app.
There are no errors or strange message in Mosquitto log.
Attached is my config.

2017-07-28 21:03 GMT+02:00 Alexander Rust <notifications@github.com>:

**Comment by parnu2000** [comment]
It had happened to me too when my owntrack automatically updated to 1.2.7. It did not send my location. But my wife still use 1.2.6. It still work properly. So I uninstall 1.2.7 and downgraded to 1.2.6 that i copied from my wife phone. Now it works for me.

**Comment by skimpax** [comment]
I have just installed the latest version (1.2.7). This is my first install.
Configured in private HTTP mode, w/o authentication: user is simply 'chris' on my device 'd855'
Pushed my location, but data displayable on webgui.

I think the divice part in missing **(X-Limit-D)** in the data send by the android app.
here below is a tcpdump content on data received at server side (ot-recorder) : 
(my server address and long/lat are masked)
	0x0010:  ...].*..3F.z....
	0x0020:  ...Y........m.c
	0x0030:  ....POST./.HTTP/
	0x0040:  1.1..X-Limit-U:.
	0x0050:  chris..Content-T
	0x0060:  ype:.application
	0x0070:  /json;.charset=u
	0x0080:  tf-8..Content-Le
	0x0090:  ngth:.120..Host:
	0x00a0:  .tracks.xxxxxxxx
	0x00b0:  .net:8083..Conne
	0x00c0:  ction:.Keep-Aliv
	0x00d0:  e..Accept-Encodi
	0x00e0:  ng:.gzip..User-A
	0x00f0:  gent:.okhttp/3.8
	0x0100:  .0....{"_type":"
	0x0110:  location","tid":
	0x0120:  "55","acc":17,"b
	0x0130:  att":78,"conn":"
	0x0140:  w","lat":99.9999
	0x0150:  999,"lon":-8.888
	0x0160:  8888,"t":"u","ts
	0x0170:  t":1504960773}

alternatively this worked ok:
curl --data '{"_type":"location","tid":"55","acc":17,"batt":78,"conn":"w","lat":99.9999999,"lon":-8.8888888,"t":"u","tst":1504960191}' 'http://tracks.xxxxxxx.net:8083/pub?u=chris&d=d855
