### ISSUE TITLE
APK file is missing in releases for quite a while

### ISSUE THREAD

**Issue by IzzySoft** [owntracks/android#506]
Could you please continue attaching the `.apk` to the `releases/` – or is there a specific reason you removed them from that place?

**Comment by binarybucks** [comment]
The app is available on the Play Store. Why do you need the APK?

**Comment by IzzySoft** [comment]
Because I don't use Playstore? There are Android users who either cannot ("big firewall") or do not want (privacy, tracking-prevention) use Google Apps incl. Playstore. For those an alternative source is very welcome. Especially with open source apps, there's F-Droid – and for those apps not fully meeting their strong criteria (in case of Owntracks, due to the use of GMS), there's also [my F-Droid repo](https://apt.izzysoft.de/fdroid/) to give them a chance to use those apps. You can [find your app in it](http://apt.izzysoft.de/fdroid/index/apk/org.owntracks.android), but – for reasons now obvious – not up-to-date :wink:

**Comment by binarybucks** [comment]
This has been discussed countless times. OwnTracks relies on Google Play Services and is distributed through the Play Store. It does not meet F-Droid requirements and there are no plans to change that. 

In the past we uploaded our APK to Github and users mirrored it to other places. The result was that users didn't get updates and complained to us about issues that were fixed since a long time. 
Hence we will not upload a APK. The app can be build from the master branch at any time if you require an APK.

**Comment by IzzySoft** [comment]
I see. Then, while my repo usually has the updates fetched automatically within 24h, this cannot be done anymore (due to lack of the source) – and I shall remove it from there? If I have no source to keep it up-to-date (and note I cannot compile myself), that's the logical next step I'd have to go – to avoid exactly the complaints you just mentioned.

Note that not all users are capable of building the `.apk` themselves (I'm one of those). So my repo is a good compromise for apps which, because of dependencies, cannot be included with the official repo – like in your case. It can be used with the F-Droid client, and even gets recommended by some F-Droid staff members for exactly this case.

Of course I'll respect your decision. But for an open source app it's strange to be available for "normal users" via proprietary sources only :wink:

**Comment by IzzySoft** [comment]
@binarybucks no reply? Shall I remove it from my repo then? Would be a pity.

**Comment by jpmens** [comment]
This has already been answered above.

**Comment by IzzySoft** [comment]
@jpmens No, it has not. Don't confuse presence on the official F-Droid repo with availability of the APK. It is correct that F-Droid won't accept the package in its main repo – but as I wrote, it would e.g. be acceptable in mine. As I don't build APKs myself, I'd need the developers support for that part. @binarybucks needs to build the APK anyhow (to upload it to Playstore), so all that's left is to also upload it here and attach it to the corresponding release – which is what I'm asking about.

**Comment by jpmens** [comment]
This has been answered above:

> OwnTracks relies on Google Play Services and is distributed through the Play Store. It does not meet F-Droid requirements and there are no plans to change that.

We are not interested in F-Droid and the only method we distribute the app is via the Play store.

**Comment by IzzySoft** [comment]
@jpmens no offense meant, but I see neither an owner, a member or even contributor tag next to your comment – so I'm not sure how much weight your opinion has in this context and how to read the "we" (unfortunately, the member list is not public – so my apologies ahead in case you *are* a member of the project and it's just not reflected by the site's design). The quote doesn't say "we are not interested in F-Droid" – but that the app doesn't meet the criteria set by F-Droid. Nor did I ask those requirements to be met. But an open-source project refusing any open-source distribution channel – even if offered on a "silver plate" – but insists on only using a walled-garden proprietary one simply sounds somewhat confusing to me.

So you'll forgive me if I prefer a more official statement – i.e. one from a project member.

**Comment by IzzySoft** [comment]
On the other hand: Seeing the last commit declaring the project dead (which again contradicts your "we distribute" – as what do you distribute if there's nothing build anymore?) and no "official response" for almost half a year, I don't know why I even bother with it. I'll simply kick it out of my repo and strike it from my recommendations list.

@binarybucks In case things change, be welcome to contact me again. No bad feelings towards the project / team :wink:

**Comment by jpmens** [comment]
@IzzySoft OwnTracks was my idea.

**Comment by IzzySoft** [comment]
Good I included forward-apologies, @jpmens – but see for yourself:

![screenshot](https://i.imgur.com/0Oy1Luq.png)

That's what I see. Do you see "owner" there somewhere? I see "Original Poster" next to my entries, and "Contributor" next to comments made by binarybucks – but nothing next to yours (maybe a GH speciality if team members are not public). So sorry again if I sounded a bit harsh – but to me it looked like some over-engaged user pretending to speak for the team.

And yeah, I very much liked the idea: tracking myself without others tracking my data. That's why I was so insisting. A pity – and I really mean it.

**Comment by binarybucks** [comment]
@IzzySoft sorry for the long radio silence. I've been very busy with personal things lately. 
Our previous stance was that the app is distributed through Google Play only. The reson behind this was that many users sideloaded the .apk, never updated it again and then complained about long fixed bugs. 

I've now attached the 1.2.7 .apk to the Github release for those interested in case the Google Play listing is not available in the future.

**Comment by IzzySoft** [comment]
@binarybucks Thanks for your response! Yeah, there's that project called "real life", sometimes very demanding. I know what you speak of. So I'm especially glad you finally found time for this!

Yes, I'm aware of that sideload-and-forget issue. That was one of the main reasons I've setup my repo. Though people can still simply grab the APK and sideload it that way, they could also use the F-Droid client and be notified of updates. So if they still sideload despite of that – well, all their fault then :wink:

The reason I finally removed it yesterday was that it seemed it won't ever be updated. The last commit was to the readme, declaring this project "stopped" – and JP made it very clear he wanted it "playstore only". I'll gladly add it back to my repo, now that an updated version is available (just done, sync in progress). Shall I include a note that it is *currently* unmaintained? And, understanding gaps and not expecting it to happen "daily": will you continue adding the APK whenever there *is* one? I just want to avoid above confusion coming up again. And I refer to you as you are listed the app's author :wink:

**Comment by IzzySoft** [comment]
@binarybucks could you please do the same also for the latest release, now v2.1.3? Thanks in advance!

**Comment by binarybucks** [comment]
The 2.1.3 Tag was just for testing. Latest build on Play is 2.1.2

**Comment by IzzySoft** [comment]
@binarybucks I see, thanks. Maybe adding a comment to it before the next one asks?

**Comment by binarybucks** [comment]
I removed the tag, it was not needed anyway. 
Thanks for pointing that out

**Comment by IzzySoft** [comment]
Thanks for complete clarification :smile:

**Comment by IzzySoft** [comment]
@binarybucks tag is back, again without APK?

**Comment by IzzySoft** [comment]
Will the APK itself return to the tag where it's missing from – the newest one?
