### ISSUE TITLE
Automatic reporting turns off automatically

### ISSUE THREAD

**Issue by rajeevn1** [owntracks/android#508]
I am using v1.2.7 on Nexus 5x running Android-8 (upcoming).  I am running a private mqtt server used by a few people.  Everything works great except on my phone automatic location reporting automatically turns off.

Another person has the exact same setup and is not facing the issue.

What can I try to narrow the root cause. This happens even when Remote commands is disabled.

**Comment by rajeevn1** [comment]
I found the issue.  The app was missing the storage permission.

I think it is a bug.  It should request the permission.

**Comment by binarybucks** [comment]
The storage permission has nothing to do with it. It isn't requested because it is just needed as a workaround for configuration imports with file management apps that don't implement a content provider.

Can you please verify if setting the permission really fixes it?

**Comment by rajeevn1** [comment]
you are right. It does not fix it. I was running the app without notification, but with battery optimization off.

As a workaround I am running the app with notification, till I can learn more.

**Comment by rajeevn1** [comment]
what i learned is that it happens less often with notification on.  Also the auto notification seems to turn off when the app is swapped out (heavy load). 

Are there any conditions, that are coded, when the auto reporting is turned off by the program.

**Comment by rajeevn1** [comment]
i see the following often in the log:

08-17 15:02:08.259   766  2093 W ActivityManager: Scheduling restart of crashed service org.owntracks.android/.services.ServiceProxy in 1000ms

**Comment by rajeevn1** [comment]
Is there a reason why "pub" auto reporting key is not listed on configuration management json screen. The system does not allow adding it either.

**Comment by CiquattroFPV** [comment]
I have a similar problem.. I'm using a private mqtt.. when I'm pushing the report button in  owntracks app (android) the app seems don't send the data of my gps locantion and  I cant see my updated location in the mqtt server.. but I modify something in the connection settings and save the app send the correct data to the mqtt server.

**Comment by LINKIWI** [comment]
Was there ever a user-facing resolution to this problem? This still happens very frequently on my device.

Symptom: turn on automatic reporting, close app, wait a few hours, open app again, notice that automatic reporting has turned itself off.

**Comment by rajeevn1** [comment]
i switched to https://play.google.com/store/apps/details?id=com.mendhak.gpslogger&hl=en which has support for http logging. I invoke mosquitto_pub from cgi.

**Comment by triplepoint** [comment]
I'm not sure if it helps anyone, but my wife and I just tracked down one cause of this behavior.

Android N and later has a Data Saver feature that will restrict background network activity.  If this feature is on and restricts OwnTracks from reporting, OwnTracks will apparently turn off further reporting (showing the "Reporting" switch in preferences as disabled).

You can either disable Data Saver on the affected phone, or there's a app whitelisting feature where you can allow OwnTracks to be excepted.

**Comment by binarybucks** [comment]
While the data saver can certainly cause a lack of reporting, it will not turn of the reporting switch in the app. 
Whitelisting the app certainly is a good idea however.

**Comment by triplepoint** [comment]
Then I'm at a loss to explain why my wife's phone was turning off the Owntracks "reporting" switch multiple times a day before we whitelisted the app in her Data Saver config, and hasn't done so since.  Any ideas?

**Comment by Kanga-Who** [comment]
I have the same issue constantly for myself and my Wife. I have disabled data saver altogether, this has not helped to fix the problem.

I'm not sure why this thread has been marked closed when the issue is still present?

**Comment by declankenny** [comment]
I am facing the same problem.

**Comment by bosscyril** [comment]
Same behaviour here. It feels quite random to me. It may stay several days with reporting on, then it eventually turns off.

App is configured in Private HTTP mode. I'm running Android 7.1.1

Just guessing... could it be caused by multiple consecutive timeouts to the server??

**Comment by binarybucks** [comment]
No guessing required, it’s caused by a the navigation drawer switch that sets the preference to off when loading the button. It has been removed in the latest beta release.

**Comment by rikki78** [comment]
Is there a workaround for this or when is a new version without this issue?

**Comment by nelsonblaha** [comment]
Why is this issue closed? I'm very much affected on a Pixel XL

**Comment by binarybucks** [comment]
The issue has been resolved in 2.x
