### ISSUE TITLE
Messages sent to device are not displayed

### ISSUE THREAD

**Issue by openhab-5iver** [owntracks/android#509]
This may just be an issue in the documentation. [The Booklet](http://owntracks.org/booklet/features/msg/) states:

> If messaging in OwnTracks is enabled, the apps subscribe to owntracks/user/device/msg to receive messages which you publish to that topic from an application.

But the [JSON API](http://owntracks.org/booklet/tech/json/) does not list owntracks/user/device/msg as something the apps subscribe to. Also, when I publish to this topic, mosquitto shows that it received the publish, but does not show that it is sending the publish to any of our devices running Owntracks (which do have notifications enabled). I've also tried publishing to owntracks/user/device, but they do not get displayed in the app. My test messages look like this (current time is used for tst):

`{"_type":"msg","prio":0,"title":"MQTT test","desc":"Testing messages.","tst":"1502900278"}`

Is my formatting incorrect? Or are messages not supported in the Android app? I was testing this for displaying notifications from openHAB.

* **App build number**: 1.2.7 (12701)
* **Android version**: 5.1.1   
* **Device**: Alcatel Fierce XL

**Comment by jpmens** [comment]
We apologize: you have chanced upon a page which doesn't actually exist in the documentation any more ... Something old got cached; I will look at it immediately.

Messaging *was* a feature, but we removed it quite some time ago.

**Comment by openhab-5iver** [comment]
LOL! This was one of the first things I added to my backlog when first setting up openHAB a couple years ago and I finally found some time to test it before implementing. [This is where reached that page in the Booklet.](https://www.google.com/search?q=owntracks+messages&oq=owntracks+notifications) Guess I need to setup [openHAB Cloud](https://github.com/openhab/openhab-cloud/blob/master/README.md).

**Comment by jpmens** [comment]
Once again: I'm sorry. That shouldn't have happened, but it's one of those things... (There _was_ another page there which shouldn't have been there, so thank for the heads up!)

Maybe only a small consolation, but: if you have an iOS device look at [featured](http://owntracks.org/booklet/features/featured/) and [here's an article using it with openHAB](http://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/). I know you did say Android above ... :-)

**Comment by openhab-5iver** [comment]
[Exactly... this is the article that I had noted and planned to implement!](http://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/) I do not use iOS, but had hoped that it would eventually be possible with Android. No need to apologize... I'm glad the docs could get cleaned up for others!
