### ISSUE TITLE
Phone flapping enter, exit  home 

### ISSUE THREAD

**Issue by rajil** [owntracks/android#511]
I have a Samsung Note 4 and have setup and ibeacon+gps region. Unfortunately, the device leaves the region even when the phone is resting. I suspect that it is because of ibeacon. Any idea how to solve this? I have set beaconmode to 1.
* **App build number**: 1.2.7 (12701)
* **Android version**:6.0.1
* **Device**: Samsung note 4

**Comment by rajil** [comment]
This is what i get using Samsung N910T phone and a Sanwo ibeacon
```
9:30:36 AM | ON to OFF
9:30:36 AM | OFF to ON
9:31:07 AM | ON to OFF
9:31:08 AM | OFF to ON
9:31:39 AM | ON to OFF
9:31:39 AM | OFF to ON
9:32:10 AM | ON to OFF
9:32:10 AM | OFF to ON
9:32:41 AM | ON to OFF
9:32:41 AM | OFF to ON
9:33:12 AM | ON to OFF
9:33:12 AM | OFF to ON
9:33:43 AM | ON to OFF
9:33:43 AM | OFF to ON
9:34:14 AM | ON to OFF
9:34:14 AM | OFF to ON
9:34:45 AM | ON to OFF
9:34:45 AM | OFF to ON
```

**Comment by binarybucks** [comment]
Beacon reporting is unreliable and will probably never work good on Android.
