### ISSUE TITLE
topic not reported in http mode

### ISSUE THREAD

**Issue by thomasdelaet** [owntracks/android#512]
* **App build number**:  1.2.7
* **Android version**: 7.0
* **Device**: Google  Pixel C

Hey, first of all thanks for this fantastic app!

I'm writing an HTTP  interface for OwnTracks to work with home assistant. When testing this in HTTP mode, the iPhone version of the client app includes topic name in the JSON body of the POST request but the Android version doesn't. Is this a bug or something I'm doing wrong?

Thanks.

**Comment by jpmens** [comment]
This is not a bug; we chose to not add that for the time being, other things being more pressing. You can construct a pseudo-topic from the `tid` if you need something.

**Comment by thomasdelaet** [comment]
Clear. Thanks

**Comment by balloob** [comment]
As an easy workaround, for Home Assistant we're going to make the url be `/api/owntracks/<user>/<device>`.

**Comment by realjax** [comment]
> we chose to not add that for the time being
Is this still the case?   I'm not seeing it either..

**Comment by jpmens** [comment]
That is still the case.

**Comment by realjax** [comment]
Ah, I see. Shame there's still nothing mentioned in the docs then.  I did see my username end up as a x-limit-d header so I supposed I can get it that way... any way I can get to the device id ?

**Comment by realjax** [comment]
Ah wait it IS mentioned :) I stand corrected :)
