### ISSUE TITLE
Data connection not available

### ISSUE THREAD

**Issue by fredronnv** [owntracks/android#513]
Owntracks doesn't seem to work at all. I've got a private mosquitto server, however location updates don't work at all. Whenever I open the app and look at status it gives me the information "Data connection not available" for Endpoint state. There's nothing wrong with my data connection, I use streaming media all the time on 4g/WiFi and never have issues, so I suspect that's not the issue. There are no restrictions on background data.
![screenshot_20170829-073308](https://user-images.githubusercontent.com/5538536/29807733-82f444c0-8c95-11e7-8e4e-b1568a937620.png)

* **App build number**: 1.2.7 (12701)
* **Android version**: 7.0
* **Device**: Moto X Force

**Comment by jkvalence** [comment]
Hey Fredronnv,

Its not just you.  I am running similar build and android version on a LG G6 and have the exact same problem on my phone.  My wife however has the same setup and is not having the issue.  I find that the issue can be temporarily corrwcted by going into Preferences, Connection, and clicking the check mark.  It works after that for a period of time.  Then goes back to data connection not available.

Justin

**Comment by Draghtnod** [comment]
Exact same issue here. Clicking the check mark reestablishes the connection and it works until the next disconnect occurs. If it is disconnected, it stays disconnected and says "Data connection not available".
I have this problem in a Samsung S7 and Samsung A5, both on version 1.2.7 (12701).

The reconnect routine should be triggered every 10 Minutes. Thas seems not to work for some reason.

**Comment by moallemi** [comment]
I have the same issue on Pixel Xl android 8.0

**Comment by Draghtnod** [comment]
I noticed that there are similar issues with DavDroid, CardDav-Sync and CalDav-Sync since Android 7. All these cease to work if not opened regularly. It is like the app standby mechanism is disabling them after a while, despite i explicitly disabled this for these apps.
Maybe this is related and an issue of Android, not Owntracks? Or the app has to be optimized to work properly with Doze and App Standby?
https://developer.android.com/training/monitoring-device-state/doze-standby.html

**Comment by zglurb** [comment]
I had the same issue. It's caused by the Android battery saving feature. You can disable this functionality for a specific app in the battery settings.

**Comment by Draghtnod** [comment]
As i said, that won't help. Not for my two devices.
