### ISSUE TITLE
ios11 iphone 7 no location settings available

### ISSUE THREAD

**Issue by ianjenn** [owntracks/android#515]
9.7.1:
ios11:   
iphone 7: 
Since installing ios11 and the latest owntracks update I cannot get it to enable location services. It appears to be enabled but as soon as I open owntracks it says can't get access to location services. I have reset privacy settings to no avail. I have updated ios to 11.01 but still no good. I have re-installed owntracks but still no good.

My wife has the same version on an iphone 6 and it works without problem. Must be something specific to iphone7 but it is very frustrating. need a fix asap if anyone has any ides

**Comment by ckrey** [comment]
This *iOS* issue is tracked here owntracks/ios#483. The problem is known, fixed, and delivered to the app store waiting for review.
