### ISSUE TITLE
Negative accuracy

### ISSUE THREAD

**Issue by kylegordon** [owntracks/android#519]
I just received a massively position report with massively negative accuracy from my phone, whilst it's sitting here on the table where it's been for the past few hours. Home Assistant immediately assumed I was out the house!

owntracks/bagpuss/a0001 {"_type":"location","tid":"01","acc":-2147473,"batt":26,"conn":"w","lat":redacted,"lon":redacted,"tst":1507837685,"_cp":true}

Should a negative accuracy even be possible?  I tried to get a manual fix, but it was always reporting what's visible in the attached screenshot. The only way to get the phone to be more accurate (at this point it's locking on to the local cell tower) was to open up a GPS test app, and after a few seconds it locked on to 7 satellites and updated the location. Owntracks immediately reported correctly at this point too.

The lack of a lock might be a phone problem, but I'm not sure the -2147473 accuracy and 1970 datestamp is :-)

![screenshot_20171012-205507](https://user-images.githubusercontent.com/231528/31517044-8d755202-af92-11e7-81c4-8e03ad0d6fe5.png)

* **App build number**: 1.2.7 (12701)
* **Android version**: 6.0.1   
* **Device**: Oneplus One

**Comment by binarybucks** [comment]
The data is literally just copied from the Google location API. Looks like your device screwed up a fix and reported a tst of 0 and an invalid accuracy.

**Comment by kylegordon** [comment]
What's your thoughts on filtering out bogus data like the invalid accuracy? Happy to close this if you want to leave it as is.
