### ISSUE TITLE
Unmaintained

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#520]
Owntracks for Android is not maintained at the moment. 
Bugs and issues can be reported but do not expect a swift fix.

**Comment by neekz0r** [comment]
What happened? :-/

**Comment by jpmens** [comment]
We're searching for a new maintainer.

**Comment by neelanshsahai** [comment]
@jpmens can you please fill me in about this.
I would like to contribute in this repo

**Comment by binarybucks** [comment]
@neekz0r I‘m no longer using any Android devices for quite some time. Hence I cannot dedicate any time towards this project. 

@neelanshsahai how may I help you?

**Comment by neelanshsahai** [comment]
@binarybucks for the new maintainer stuff as mentioned by @jpmens.
Actually I find it interesting. :smile:

**Comment by IzzySoft** [comment]
Could you please at least attach the `.apk` to the latest release meanwhile? I've just noticed it was missing for quite a while, so the version offered via my repo is hopelessly outdated already.

**Comment by Diaoul** [comment]
I was about to open an issue and just learned this :cry: 
It's too bad, the android app seems to be the most stared github repo.

**Comment by shymega** [comment]
Sorry to hear this. I would be interested in helping out with keeping the Android OT app going. I can be reached via email, or on IRC - Freenode is the best one to reach me on - as `shymega` :smiley:

@IzzySoft By the looks of it, the Owntracks app published in the play store is v1.2.7 - not sure about F-Droid, but I hope that helps solve your issue.. unless its already solved..?

**Comment by IzzySoft** [comment]
@shymega thanks for the hint. I'm not using the app myself, but it's in [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid), which takes APKs from the resp. projects here at Github. I don't want to interfere with Playstore for that. So I was hoping e.g. @binarybucks (or whoever has access to that) could attach the file to its corresponding release here at Github.

**Comment by jpmens** [comment]
If you need the current version of the app, you can either install from Google Play Store or build it yourselves from source. We aren’t providing apk files here.

**Comment by jpmens** [comment]
@neelanshsahai @shymega if you’re willing to contribute, the best way to do that is to get very familiar with the code in its current form and then attempt to bring life into it on newest Android versions.

**Comment by neelanshsahai** [comment]
sure :+1: 
thanks

**Comment by shymega** [comment]
@jpmens Thanks - I'll probably work on it on a local repo for now - what's the min API version we should target?

**Comment by binarybucks** [comment]
@shymega there's the f_background_scheduler that targets Android 8 and contains many improvements to work around the background restriction limits. It needs some little improvements to target API 26.

**Comment by tungmeister** [comment]
@shymega have you picked this up? I'd be very interested in proper Oreo support, I've just upgraded to the pixel 2 XL and have only just discovered the app is no longer my maintained.

**Comment by SomeFixItDude** [comment]
Any update on someone picking this up? I really like being in charge of my own data. The app works pretty good as is, but could use some love.

**Comment by jpmens** [comment]
We're very sad that so far nobody has taken it upon themsevles to help us.

**Comment by shymega** [comment]
@tungmeister I apologise for the late reply.. it has, sadly become the time of year where life overtakes other things that I like doing. I'm also in the process of applying to University for Sept 2018. I've added this issue to my todo list, and I'll take a look ASAP. I notice however that some commits have been made to the `f_background_scheduler` branch. AFAIK, this is for Android 8, but from my POV, it would be good to support _at least_ Android 5.0... I wouldn't like to drop support for older version of Android.. unless I have got the wrong end of the stick. If so, I apologise preemptively in advance! :smile:

**Comment by shymega** [comment]
Am looking around the Android app code - few questions for the maintainers:

- Is there any code guidelines?
- Any particular branch to work on first of all? I'm guessing `f_background_scheduler` first?
- Any comments on my comment above about minimum API level to support? Is there a position official on this?

Thanks!

**Comment by binarybucks** [comment]
There are no particular coding guidelines as long as the code is functional. There are bonus points if you make Travis happy and if you provide Unit tests ;) 

@growse is currently investing time and effort in fixing the remaining issues in the Android-2.0 branch (former f_background_scheduler). Work on this branch will benefit all API levels because it contains a completely rewritten background code that‘s optimized for the new Android background restrictions that got increasingly more restrictive from 5.0 to 8.0. 
Current minimum API level is 21 (5.0) with target and compile SDK set to latest. 

If you‘d like to join us two, I can invite you to our semi-public Slack channel. If you‘re interested, please drop me a line at support@owntracks.org.

**Comment by shymega** [comment]
Hi,

Alexander Rust <notifications@github.com> writes:

> There are no particular coding guidelines as long as the code is
> functional. There are bonus points if you make Travis happy and if
> you provide Unit tests ;)

Noted, fair enough.

> @growse is currently investing time and effort in fixing the
> remaining issues in the Android-2.0 branch (former
> f_background_scheduler). Work on this branch will benefit all API
> levels because it contains a completely rewritten background code
> that‘s optimized for the new Android background restrictions that
> got increasingly more restrictive from 5.0 to 8.0.

Yes, I've been going through the Android docs, it does seem that it
*is* more restrictive now. It has quite a noticeable effect.

> Current minimum API level is 21 (5.0) with target and compile SDK
> set to latest.

Minimum API level sounds good to me :)

> If you‘d like to join us two, I can invite you to our semi-public
> Slack channel. If you‘re interested, please drop me a line at
> support@owntracks.org.

Sure, I'll send you an email, would be good to get involved.

--
Best regards,
Dom Rodriguez (shymega / dzr).
