### ISSUE TITLE
Reconnect faster

### ISSUE THREAD

**Issue by Diaoul** [owntracks/android#521]
* **App build number**: 12701
* **Android version**: 7
* **Device**: Honor 8 / Nexus 5

I find OwnTracks is quite slow to reconnect in general, is there a way to make it reconnect faster through configuration?
This is usually a problem for me as when network change this is usually next to a Geofence and the devices switches from network to another. This causes the Geofence to not trigger properly.
I think when a Geofence is entered or exited, OwnTracks should be more aggressive on retrying to reconnect and send the data.

I have no experience in developing Android app but I can try, if you have any pointers it would be helpful.

**Comment by shymega** [comment]
@Diaoul I do get this problem as well - I'm not sure if you're aware of this, but according to #520 .. Owntracks for Android *is* no longer maintained.

I'm sorry to be the bearer of bad news, however. I only just found out yesterday myself.

I hope your problem gets solved. :smile:

**Comment by shymega** [comment]
Ah.. sorry about that @Diaoul .. didn't see your comment in that issue.

Apologies! :smiley:

**Comment by kvoit** [comment]
I don't find the app reconnecting at all in some situation. When I restart my MQTT server, the "Publish" switch in the side menu switches to off and does not seem to reenable.

**Comment by binarybucks** [comment]
Publish switch issue should be fixed in the latest beta. 
Also reconnecting works completely different now.
