### ISSUE TITLE
Lots of enter/exits of a region

### ISSUE THREAD

**Issue by markrennie71** [owntracks/android#525]
Hello, in my android phone I have lots of event stating I have either entered or exited a region when I haven't. I am using GPS with ibeacons and I have 2 of them with the same UUID for better coverage. Any reason why this would be happening please?

Cheers
Mark

**Comment by binarybucks** [comment]
That’s a normal behavior because Android Beacon support is a broken mess.

**Comment by markrennie71** [comment]
yeah that is such a pity as I love OwnTracks with the added bonus of iBeacons it works so well for automation's. Saying that I get the events listed in Home assistant logs and on my android phones, but it doesn't appear to cause any issues (yet) :)

Thanks
