### ISSUE TITLE
no update

### ISSUE THREAD

**Issue by speedymk1** [owntracks/android#527]
* **App build number**: 1.2.7 from google app store
* **Android version**: 7.0
* **Device**:  Huawei 10P Lite / Huawei 9P Lite

Hi,
I hope someone could help me.
I installed OT on two mobile phones, a mosquitto broker on a PI and everything works fine if I do an update manually.
But I get no updates automatically.
The configuration is following:
{
	"_type": "configuration",
	"waypoints": [{
			"_type": "waypoint",
			"desc": "xxxx",
			"lat": xxxx,
			"lon": xxxx,
			"rad": 50,
			"tst": 1515149419
		}
	],
	"auth": true,
	"autostartOnBoot": true,
	"beaconBackgroundScanPeriod": 30,
	"beaconForegroundScanPeriod": 0,
	"beaconLayout": "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24",
	"beaconMode": 0,
	"cleanSession": true,
	"clientId": "xxxx",
	"cmd": false,
	"cp": false,
	"deviceId": "android",
	"host": "mcspeedy.ddns.net",
	"ignoreInaccurateLocations": 0,
	"ignoreStaleLocations": 0,
	"keepalive": 3600,
	"locatorAccuracyBackground": 2,
	"locatorAccuracyForeground": 2,
	"locatorDisplacement": 500,
	"locatorInterval": 900,
	"mode": 0,
	"mqttProtocolLevel": 3,
	"notification": true,
	"notificationHigherPriority": false,
	"notificationLocation": true,
	"password": "hpsw",
	"playOverride": false,
	"port": 1883,
	"pub": true,
	"pubExtendedData": true,
	"pubQos": 1,
	"pubRetain": true,
	"pubTopicBase": "owntracks/%u/%d",
	"ranging": false,
	"remoteConfiguration": true,
	"sub": true,
	"subQos": 2,
	"subTopic": "owntracks/+/+",
	"tid": "xxxx",
	"tls": false,
	"username": "xxxx",
	"ws": true
}

**Comment by wardcraigj** [comment]
I'm also seeing similar behaviour on the google Pixel.

**Comment by binarybucks** [comment]
Background updates should work more reliable in the Android 2.0 beta. 
On Huawei phones the app needs to be explicity whitelisted to run in the background.
