### ISSUE TITLE
Friends list minor requests...

### ISSUE THREAD

**Issue by nothingmn** [owntracks/android#532]
App Build Number:
2.0.0  (20018)

Just a couple, hopefully minor requests, for the friends list.

1. Show the last date/time (or just time) when the client received a message for that device.  iOS has this, and its pretty handy.  Maybe show time since (think momentjs).

2. Be able to delete/remove a friend from the list.

Thanks for the great app!

**Comment by binarybucks** [comment]
I think we had the data in there in the past. I'm not sure why it was removed but I will see if I can add it again. 

Deleting a friend is only possible in MQTT mode. Tap on a friend in the list. Then tap the sheet at the bottom and hit the three menu dots. 
In HTTP mode, the backend would have to clear the message or it would reappear with every report. This is currently not supported.
