### ISSUE TITLE
Mqtt publish topics

### ISSUE THREAD

**Issue by esthoril** [owntracks/android#534]
Hi,

first off, thanks for the nice app. I'd like to send data over private mqtt to my own endpoint, but I fail to find which topics the (Android) app uses to publish on. Is there a list somewhere of used topics or topic structure? Or can I define my own topics for certain data (such as location, ...). Thanks.

**Comment by binarybucks** [comment]
See http://owntracks.org/booklet/tech/json/

**Comment by esthoril** [comment]
Guess I didn't search enough. My bad. Thanks for the quick reply!
