### ISSUE TITLE
Owntracks and ThingsBoard.io

### ISSUE THREAD

**Issue by Gastondamian** [owntracks/android#535]
Cant configure owstracks to be used with thingsboard.io, any steps?

**Comment by jpmens** [comment]
What is ThingsBoard.io?
Have you read their documentation?
Have you read our documentation? 
What steps have you tried?
What were the results?
Did you see any error messages and if so which?

**Comment by CloCkWeRX** [comment]
https://thingsboard.io/docs/reference/mqtt-api/ is your best bet. But worth shifting over to https://github.com/thingsboard/thingsboard/issues/639

**Comment by jpmens** [comment]
Thanks @CloCkWeRX. Closing here now.
