### ISSUE TITLE
Background updates stop working while in buildings

### ISSUE THREAD

**Issue by haimiko** [owntracks/android#540]
I've noticed if I'm at home, the background updates cease so long as I don't open the app.  This may be by design but it would be nice if the "Locator background interval" preference setting actually controlled the background reporting even if no new GPS location was detected or movement made. 

Better yet, a new preference setting which controlled background reporting when no movement is detected so to conserve power.

Version: 1.2.7 (12701)
Android 7.1.1
S Note 8

**Comment by jpmens** [comment]
This is definitely not by design, on the contrary. What I assume you're seeing is some inability to switch to your home WiFi or such?

**Comment by haimiko** [comment]
Don't think so.  If that were the case then it would continue to automatically report the location after manually running the report.  My whole family has this problem.  My son is using the iPhone version, wife is on a OnePlus 3 running 7.0.1 and I am on a Note 8.


[config.otrc.txt](https://github.com/owntracks/android/files/1845543/config.otrc.txt)

**Comment by tleegaard** [comment]
I'm getting no updates while stationary as well. Background update interval set to 300.

Version: 2.0 (20022)
Android 8.1

**Comment by binarybucks** [comment]
The background interval isn’t for what you think it is. 

Updates won’t be pushed while stationary. It’s when the device moved backgroundDisplacement meters at least every backgroundInterval. The interval is a max so you might receive updates more often if you moved a certain amount. 

If you want regular updates, try setting the ping parameter. You will not get new locations but it will repeat the last known location every ping interval minutes.
