### ISSUE TITLE
Certificates won't refresh when mosquitto updates

### ISSUE THREAD

**Issue by cpw** [owntracks/android#543]
* **App build number**: 12701
* **Android version**: 8.0.0 (Oxygen 5.0.1)
* **Device**: One plus 3

My MQTT certificates are let's encrypt issued certs, and update every couple of months. Mosquitto does an automated restart, but Owntracks doesn't notice the new certificate until the phone is restarted.

**Comment by jpmens** [comment]
The Let's Encrypt root CA certificate ought to be part of your phone's OS, so it's not likely to be an OwnTracks issue, unless you've manually configured your broker certificate in OwnTracks. In that case there's not much we can do about it.

Please indicate which fields you've configured in OwnTracks on Android in terms of TLS and their values (excepting sensitive data of course)
