### ISSUE TITLE
[Feature Request] Use OpenStreetMap instead of Google Maps

### ISSUE THREAD

**Issue by mbirth** [owntracks/android#544]
OpenStreetMap provides far more detailed maps than Google does. Also with e.g. a mapsforge-compatible library, we could even use offline maps to save mobile data.

(This is just a request for the map display. You can continue to use Google's Geocoder API.)

**Comment by jpmens** [comment]
Wow: that's nice that we can continue to use Google's Geocoder API.  
Thanks for permitting us to do that.

We will entertain the thought of accepting your pull request to 
implement the feature you think we should have.

**Comment by mbirth** [comment]
Y u so bitchy?

That wasn't about permission, that was merely to not have this request confused with #88 . I don't care about Google dependencies, I'd just like to see a better map display.

Also, if I was an Android dev, I wouldn't have opened this FR.

**Comment by binarybucks** [comment]
We will focus on using the native map libraries for now. This might change in the future though.
