### ISSUE TITLE
Crash when tapping notification

### ISSUE THREAD

**Issue by mbirth** [owntracks/android#545]
Tapping on the notification makes Owntracks crash most of the times on a Pixel XL with Android 8.1.

Steps to reproduce:
1. While Owntracks is opened, put in in background by using the phone's "back" button until you're on the home screen
2. Open the notification drawer and tap the Owntracks notification.
3. In 3 of 5 cases Owntracks will crash here.

![7276854816050398298](https://user-images.githubusercontent.com/130302/39326322-e4e528a4-4994-11e8-89b2-71723df51321.png)

* **App build number**: 2.0.0 (20022)
* **Android version**: 8.1.0
* **Device**: Google Pixel XL

On a BlackBerry KEYone with Android 7.1.1, I had occasional crashes as well (yesterday) but not a single one today.

**Comment by growse** [comment]
Looks like the same issue that #537 looks to solve.
