### ISSUE TITLE
Mobile Beacons on Android

### ISSUE THREAD

**Issue by stefbigbay** [owntracks/android#547]
Last update I saw on Mobile beacons was a year ago - has there been any change? Specifically, I'm hoping to get lat/lon updates to ibeacon regions from my phones location. Setting radius to -1 as on the iOS app doesn't seem to be supported.

**Comment by binarybucks** [comment]
Beacon support on Android is a mess and there won't be any changes to the features as even normal beacons don't work realiably. 
If we change anything at all it is to remove the beacon support alltogether on Android.

**Comment by jpmens** [comment]
For the record: we have decided to remove support for Beacons in our Android app, and the Booklet has already been edited to reflect that change.
