### ISSUE TITLE
Unable to use client certificate

### ISSUE THREAD

**Issue by lnovara** [owntracks/android#552]
* **App build number**: 1.2.7 (12701)
* **Android version**: 4.2.2
* **Device**: Fairphone FP1U

If I try to use a client certificate I get this error from the app:

![image](https://user-images.githubusercontent.com/26872940/40535631-ef7f3198-6009-11e8-8b8e-5e59419581d1.png)

whith Mosquitto logging the following error:
``
OpenSSL Error: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate
``

The same client certificate is working fine with `mosquitto_pub/mosquitto_sub`. Can you help me unsterstand the issue? Thanks.

**Comment by binarybucks** [comment]
Did you provide a password for the client cert? 
The app can only use client certificates with a password.

**Comment by lnovara** [comment]
Yes, I exported the certifcate + key using a password following the instructions in the [booklet](http://owntracks.org/booklet/features/tlscert/).

**Comment by jpmens** [comment]
@lnovara have you been able to solve the problem?

**Comment by 317713** [comment]
No

**Comment by lnovara** [comment]
Hi @jpmens,

  I got it working using password authentication but I woul really like to use client certificates. Are there missing informations that could help clarify the issue?

**Comment by jpmens** [comment]
Please show us exactly the steps you took, and please also explain where you got the client certificate from.

**Comment by binarybucks** [comment]
Closing for lack of reponse. Please reopen with steps to reproduce.
