### ISSUE TITLE
CONNACK (0,5) to broker

### ISSUE THREAD

**Issue by sarmbruster** [owntracks/android#553]
* **App build number**: 1.2.7 (12701)
* **Android version**: 7.1.2
* **Device**: OnePlus One running LineageOS (NB: the phone is rooted)

I do have locally a mosquitto server installed - requiring authentication, TLS switched off (for now). Port 1883 is opened in my router. 
I've verified that mosquitto itself works using `mosquitto_sub`/`mosquitto_pub` tools.
I've configured a MQTT private connection to the same host, port and credentials like my mosquitto_pub command was using.

When trying to publish my location I do see in `mosquitto.log`:

```
Jun 21 18:16:58 openHABianPi mosquitto[13470]: Sending CONNACK to xxx.yyy.zzz.zzz (0, 5)
```

In the app's status view I get:
* Endpoint state: Fehler (english: error)
* Endpoint state message: Keine Berechtigung für Verbindung (5) (english: no permission for connection)

Any hints how to get more debug info and how to fix it?

**Comment by jpmens** [comment]
Double, no, triple-check the credentials your app is using. The message is rather self-explanatory: "Keine Berechtigung".

**Comment by jpmens** [comment]
@sarmbruster have you been able to solve the problem?

**Comment by 317713** [comment]
A little bit. It still is disconnecting allot

**Comment by sarmbruster** [comment]
@jpmens I've temporarely switched off authentication - this works. Just to make sure I'm using the correct credentials I've copy&pasted them on the Android side to rule out typing errors. 
Still I'm getting `CONNACK (0,5)` with auth re-enabled. Need to check my mosquitto permissions - maybe the user can authenticate successful but is not allow to push the location status update.

**Comment by sarmbruster** [comment]
Just wanted to make sure that "MQTT private" with websocket disabled is the right way to use it in conjuction with mosquitto?

**Comment by jpmens** [comment]
An MQTT publish wouldn't return CONNACK even if the Mosquitto ACL prohibits it, and yes, "MQTT private" without Websockets is the correct method. Please make sure your Android app is talking to the correct MQTT TCP port on your broker (1883 without and 8883 with TLS per default)

**Comment by sarmbruster** [comment]
Thanks again. I've run it successfully without authentication. After some time I've re-enabled auth and finally it works.
