### ISSUE TITLE
Unable to remove ongoing notification

### ISSUE THREAD

**Issue by CheeseySandal** [owntracks/android#555]
* **App build number**: 2.0.0 (20026)
* **Android version**: 8.1.0   
* **Device**: Google Pixel

I understand the fact that android can kill apps to manage memory, and having a persistent notification can negate this, however after upgrading to 2.0.0 I simply can't get rid of the ongoing notification.

Enabling the "Last reported location" option I get the expected address in my notification tray, but when I disable this setting, I simply get an ongoing "Connected" notification.

I've used the previous version for a good year and have never had trouble running it without an ongoing notification.

Would it be possible to update the new version with an "At your own risk" kind of option to remove all persistent notifications?

Thank you.

**Comment by binarybucks** [comment]
The notification is required by the background service due to OS restrictions. Many users forgot it and complained that the app did no longer work , hence we removed the option. 

You can however hide the notification in the channel settings. Long press the launcher icon, app  Info, notifications, uncheck ongoing.

**Comment by CheeseySandal** [comment]
I totally understand the fact that it's required, hence the "At your own risk" kind of option.

Unfortunately, on Android 8, hiding the notification simply replaces it with an ongoing Android notification stating that Owntracks is using battery and data.

Do you know if there's a download available for previous versions?

**Comment by binarybucks** [comment]
The service is started differently (and correctly) now which requires the notification. It’s not as easy as just don’t showing it. The app will be force quit after 5 seconds when no notification is shown.

The system provided „is using battery and data“ is there to uncover misbehaving apps. You can however swipe it right, hit the gear icon and also disable it.

**Comment by CheeseySandal** [comment]
Ok fair enough. I'll close this issue and open a new one if it's misbehaving. 

Thanks.
