### ISSUE TITLE
Regions nothing visible.

### ISSUE THREAD

**Issue by Smarti15** [owntracks/android#558]
Hello I put on regions, but they are on the time then nothing visible.

* **App build number**: 2.0.0 (20025)
* **Android version**: Oreo 8.0.0
* **Device**: Samsung Galaxy S8+

**Comment by binarybucks** [comment]
What do you mean by they are „on the time then not visible“?

**Comment by Smarti15** [comment]
The regions are not visible on the map. Besides, you do not always see a friend on the map. Often the point is not visible. Although you get the location with address displayed but the location point is not visible. you rarely see him

**Comment by binarybucks** [comment]
Regions are not displayed on the map. This is only done in the iOS version. 

For the other issue, please post a scteeenshot.

**Comment by pacive** [comment]
Is there a reason they are not visible? I was planning on creating an "in town" region, but it's hard to just guess a radius without being able to see the result.

**Comment by binarybucks** [comment]
We just haven’t come around to implement that feature. I just use the legend on Google Maps to estimate the radius. It’s not accurate to the meter anyway.

**Comment by pacive** [comment]
Ok, thanks for the tip. I hope I didn't appear rude, I know how OSS works, so put the effort where you believe it's needed! But it's a feature I would like to see implemented at some point :)

**Comment by binarybucks** [comment]
No offense taken.
Any steps to reproduce the issue were the friend is not shown on the map?

**Comment by binarybucks** [comment]
Friends not showing is fixed in recent builds
