### ISSUE TITLE
LetsEncrypt cert causing CertPathValidatorException for HTTP private mode?

### ISSUE THREAD

**Issue by sibbl** [owntracks/android#559]
I'm currently trying to set up this app with home assistant behind an nginx reverse proxy, which uses a wildcard cert from LetsEncrypt. I've never had troubles with other apps accessing HA on my phone, but OwnTracks  v1.2.7 shows the following error when using HTTP private connection mode:

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

I've not specified a server CA and honestly don't want to - my phone should already trust it. Any ideas how this can be fixed? Thanks in advance!

(btw, using a Google Pixel with latest Android 9 beta)

**Comment by sibbl** [comment]
I've now manually selected Lets Encrypt's CA, but why is this necessary at all?

**Comment by binarybucks** [comment]
Good question. If the phone trusts the LE CA chain it should work like you mentioned. I’ve my own root CA and subordinate CA added to the Android store and it works like a charm. 

I’ll add a LE certificate and check for any issues.

**Comment by sibbl** [comment]
Just for testing purposes, I set the host directly to https://sibbl.net and the same error occurs (even though there's no server-side logic behind, but it doesn't even establish the connection). Does this work on your side as well? Maybe it's Android 9 related then...

**Comment by binarybucks** [comment]
If the TLS setup is broken, it doesn't matter if there's server side logic behind or not. The connection will never come this far. 

Obviously I cannot test with your domain but it works fine if I use one of mine. Have you tried with the above Caddyfile? It will auto fetch and setup the LE certificates and return a valid chain. If that doesn't work as well, it's probably an Android 9 issue.

**Comment by sibbl** [comment]
Fun fact: I renewed my cert via acme.sh and suddenly it works without the client CA with the same OS and OwnTracks version... it probably was a server side issue then, so sorry for wasting your time and thanks for the support :)
