### ISSUE TITLE
Android not processing remoteConfiguration in HTTP mode

### ISSUE THREAD

**Issue by Intellium** [owntracks/android#561]
In reference to #444 in which I had the same issue.

Running owntracks v1.2.7 on Android in HTTP mode.
When the app publishes it's location, it receives the following output:
```
{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration","locatorInterval":666}}
```
Nothing is processed however. The locatorInterval isn't updated as the app still shows it's current setting (900). I've tried restarting the device, but nothing seems to get Owntracks to process the configuration.

Remote commands are enabled.

**Comment by Intellium** [comment]
Issue is the same on v2.0.0

**Comment by binarybucks** [comment]
Fixed in recent builds
