### ISSUE TITLE
enormous battery drain Android 8.0

### ISSUE THREAD

**Issue by leandresz** [owntracks/android#562]
Me and my wife are using owntracks both for presence detection with our home automation software. Since I replaced my previous smartphone (Samsung Galaxy S6 (SM-G920F) the battery usage increased dramatically. Owntracks uses approximate 20% of the device battery in a full charge cycle. 

I noticed on my new device I run an older owntracks version comparing to my wife's older device. Maybe this battery issue will be resolved if this newer of newest(?) version become available for Android 8.0 devices?

Acceptable battery usage:
* **App build number**: 2.0.0 (20022)
* **Android version**: 7.00 
* **Device**: Samsung Galaxy S6 Edge (SM-G925F)

Battery drain:
* **App build number**: 1.2.7 (12701)
* **Android version**: 8.00 
* **Device**: Samsung Galaxy S9 (SM-G960F)

![screenshot_20180811-153041_settings](https://user-images.githubusercontent.com/17427976/43992612-4b873d00-9d81-11e8-83d3-e84a44892014.jpg)

**Comment by leandresz** [comment]
We installed owntracks using the Google playstore. So we do not have any influence about the version the playstore provides right? Or what I'm I missing here.

**Comment by binarybucks** [comment]
Please report back if the issue persists in the 2.1 build
