### ISSUE TITLE
OwnTracks won't connect to mqtt on local WLAN

### ISSUE THREAD

**Issue by RudolfRendier** [owntracks/android#563]
OwnTracks does not connect when the phone is connected to (local?) WLAN.
Mobile networks is not an issue, but when connected to my wi-fi OwnTracks stays 'Connecting'

It **does** work when I change the host to the LAN-IP.
Sounds like a routing issue, but my configuration was working before and is still working with OwnTracks 1.2.7. Please advise on how I can gather more logging on this issue.

App is whitelisted from battery optimization, but issue also present when phone is awake.

(doesn't connect properly from WLAN using external-IP, does connect from WAN, and connects from WLAN using internal-IP)
* **App build number**: 2.0.0 (20026)
* **Android version**: 8.0.0
* **Device**: Xiaomi Mi A1

Other phone in this household does not have this issue (still on 1.2.7) 
(connects properly from WAN & WLAN using external-IP)

* **App build number**: 1.2.7 (12701)
* **Android version**: 8.0.0
* **Device**: Oneplus 3T

**Comment by RudolfRendier** [comment]
Nevermind, it was a routing issue.

**Comment by 4994james** [comment]
Hi.  Is it possible to outline the solution you found for this as I have the same problem and am not sure how to fix it
  Thanks.

**Comment by binarybucks** [comment]
Enabling NAT Reflection in your router might help

**Comment by RudolfRendier** [comment]
My problem was that I routed traffic from my phone onto a VPN.
Unsure why I can't access local services when I do that, but it was not related to OwnTracks.
