### ISSUE TITLE
plain vanilla Private Mosquitto MQTT and only LWT msg from OwnTracks

### ISSUE THREAD

**Issue by ppontre** [owntracks/android#564]
* **App build number**: 20016
* **Android version**: 8.0.0   
* **Device**: Samsung Galaxy S7
Hello, 
I am running a private Mosquitto (no TLS, No Websockets) on port 1883.
(other apps are using it as a broker, without any issue)
I can't see incoming messages from Android apart from an initial LWT.
Log says there's a TLS error and there is a reconnection to broker
Has someone already experienced this ?

**Comment by ppontre** [comment]
Hello,
here is the message, starting ot-recorder manually (in Debian) server:

/usr/sbin/ot-recorder
ot-recorder[18792]: version 0.7.6 starting with STORAGEDIR=/media/usb-drive/owntracks/recorder/store
ot-recorder[18792]: gcache_open: mdb_dbi_open for `topic2tid': MDB_NOTFOUND: No matching key/data pair found
ot-recorder[18792]: gcache_open: mdb_dbi_open for `keys': MDB_NOTFOUND: No matching key/data pair found
ot-recorder[18792]: gcache_open: mdb_dbi_open for `friends': MDB_NOTFOUND: No matching key/data pair found
ot-recorder[18792]: connecting to MQTT on localhost:1883 as clientID otr without TLS
ot-recorder[18792]: HTTP listener started on 192.168.1.211:8085
ot-recorder[18792]: Using storage at /media/usb-drive/owntracks/recorder/store with precision 7
ot-recorder[18792]: Subscribing to owntracks/+/+ (qos=2)

On Android device Status Page, i Get:
Connected – Enpoint state
Not available – Endpoint state message
0 – endpoint queue
14:09 – location service last background update
….
….

Is it what you asted for ?
Thanks for yr support

Paolo
---------------------------------------------------
Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Alexander Rust <notifications@github.com>
Inviato: Wednesday, August 15, 2018 1:22:48 PM
A: owntracks/android
Cc: ppontre; Author
Oggetto: Re: [owntracks/android] plain vanilla Private Mosquitto MQTT and only LWT msg from OwnTracks (#564)


What is the TLS error in the log and what is the connection message on the app‘s status page?

**Comment by jpmens** [comment]
You have opened this issue in our Android tracker, and we're not quite sure what your problem is.

The messages you show above are from our Recorder which appears not to have been installed correctly; please see the documentation for the `--initialize` option to set up the internal database.

What you'll then need to do is point your Android OwnTracks app to your broker, and the Recorder should then be able to see your location and store it.

**Comment by ppontre** [comment]
Hi and Thx JP,
actually it was 2 different issues….

  1.  Solved with –initialize
  2.  I am monitoring incoming owntracks messages and receive only LWT:

I issue:

mosquitto_sub -t owntracks/+/+



The only incoming msg from onadroid device is (at device starup):

{"_type":"lwt","tst":1534336207}

Thanks for help……

Paolo
--------------------------------------------

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: JP Mens <notifications@github.com>
Inviato: Wednesday, August 15, 2018 2:17:17 PM
A: owntracks/android
Cc: ppontre; Author
Oggetto: Re: [owntracks/android] plain vanilla Private Mosquitto MQTT and only LWT msg from OwnTracks (#564)


You have opened this issue in our Android tracker, and we're not quite sure what your problem is.

The messages you show above are from our Recorder which appears not to have been installed correctly; please see the documentation for the --initialize option to set up the internal database.

What you'll then need to do is point your Android OwnTracks app to your broker, and the Recorder should then be able to see your location and store it.

**Comment by jpmens** [comment]
If you're seeing an `lwt` that means at least that the device is speaking to your MQTT broker which is good. Are you quite sure you have no ACLs? Can you tell us how you've configured the Android app?

**Comment by binarybucks** [comment]
Do you see messages when you manually hit the report location button?

**Comment by ppontre** [comment]
No, I don’t see any msg, neither in background nor pushing the “report” button
I attach config file….


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Alexander Rust <notifications@github.com>
Inviato: Wednesday, August 15, 2018 2:45:57 PM
A: owntracks/android
Cc: ppontre; Author
Oggetto: Re: [owntracks/android] plain vanilla Private Mosquitto MQTT and only LWT msg from OwnTracks (#564)


Do you see messages when you manually hit the report location button?

**Comment by jpmens** [comment]
Files attached to mails don't make it in to Github issues; you'll have to visit this page here to do that.

**Comment by binarybucks** [comment]
Please report back if the issue persists in 2.1.x
