### ISSUE TITLE
iBeacons not working in Android

### ISSUE THREAD

**Issue by bartnaaijkens** [owntracks/android#566]
Hi,

I'm trying to set-up iBeacons with OwnTracks on Android but I'm not able to have OwnTracks recognize my iBeacons.

The iBeacon I'm using is made by Wellcore and set-up as an iBeacon. If I use Beacon scanner I scan see it's being picked up. See this screenshot;
![screenshot_20180818-095325](https://user-images.githubusercontent.com/11751532/44297162-3706fb80-a2cd-11e8-959e-e1c2c62fbd9e.jpg)

In OwnTracks I tried various settings. With major/minor left empty, with them set too 1000/101 (as configured and confirmed in Beacon Scanner) and with major/minor set to 0. Also I tried the UUID with and without caps and with and without dashes. 

![screenshot_20180818-095344](https://user-images.githubusercontent.com/11751532/44297160-340c0b00-a2cd-11e8-994d-50290407f539.jpg)

No to the iBeacon relevant output is appearing via MQTT or in the app. Normal GPS mode is functioning and visible via MQTT.

How can I help to further troubleshoot this issue and to get it fixed?

Kind regards,
Bart

* **App build number**: 1.2.7 (12701)
* **Android version**: Android 8.0.0, patch level July 1 2018, OxygenOS version 5.0.4  
* **Device**: Oneplus 3

**Comment by jpmens** [comment]
It's not worth your while experimenting with this: in the next iteration of our Android app we've removed support for Beacons completely as they're not reliable in Android, sorry.

**Comment by bartnaaijkens** [comment]
That's a shame to hear but good to know before putting in more time. Thanks.
