### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by samsk** [owntracks/android#567]
* **App build number**: 2.0.0
* **Android version**: 8.0
* **Device**: Galaxy S7

Owntracks app displays in notification area, 'Connected' or 'Error'. The problem is the 'Error' state can be connection problems (very often), but it might be also 'Not authorized' or smth. similar.
IMHO, the app should not report 'usual' connection problems, unless they persist for a longer time, but it should immediately highlight possible configuration errors like 'Not authorized to connect'.

This UX problem manifested itself, after I've changed my password and I've forgotten to change it on one device.

Btw. thanks for developing this app ;-)

**Comment by binarybucks** [comment]
The commit improves error reporting a bit but e.g. showing HTTP error codes or MQTT authorization issues in the notification. Not perfect yet but I hope it is more useful.
