### ISSUE TITLE
Android App not consistently downloading from MQTT Server

### ISSUE THREAD

**Issue by begleysm** [owntracks/android#568]
* **App build number**: 12701
* **Android version**: 8.0.0
* **Device**: LG G6

I have Owntracks installed on two LG G6 phones running Android 8.0.0.  I have a Mosquito Server setup at my home.  I also have MQTT Snooper installed on one of my phones.

With MQTT Snooper subscribed to the topics "owntracks/user/device1" and "owntracks/user/device2" I see new messages published to the server at expected intervals.  However the display within Owntracks rarely updates the location of my "friends" (device1 and device2).  Often the last update is 10 minutes old with a dos dozen new published messages in the interim.

Since MQTT Snooper sees plenty of published messages I surmise that Owntracks, for some reason, isn't choosing or isn't able to download some of the messages that are on topics it is subscribed to.

**Comment by jpmens** [comment]
Our app doesn't "download" messages. With MQTT, the app subscribes to the MQTT broker and listens for the broker to send it data. This is apparently working correctly for your "snoop" app.

Can you show us logs of your MQTT broker when our Android app is connecting and as you publish a message from device2? There's bound to be a very simple explanation ...

Also please say which platform your broker is running on, which software version, and which broker / version, and if possible show us broker configuration (without passwords of course)

**Comment by begleysm** [comment]
Hi @jpmens, thanks for the reply.

FYI:
- device1 = SB = sean
- device2 = JB = jackie
- "loc" is the common user that both of our phones log in as.
- I've got HTTPS setup on the MQTT Broker server.  And the "loc" user has a password.

**BROKER**
OS: Debian 9
PLATFORM: running as a LXC Container on a Proxmox Server (Proxmox 5.2-2)
MQTT BROKER: Mosquitto 1.4.10-3+deb9u1
MOSQUITTO.CONF
`# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
`
CONF.D/DEFAULT.CONF:
`allow_anonymous false

password_file /etc/mosquitto/passwd

listener 1883 localhost

listener 8883
certfile /etc/letsencrypt/scp/steamforge.net/cert.pem
cafile /etc/letsencrypt/scp/steamforge.net/chain.pem
keyfile /etc/letsencrypt/scp/steamforge.net/privkey.pem

persistence_file mosquitto.db

log_dest syslog
log_dest stdout
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
`
LOGFILE: attached: [mosquitto.log](https://github.com/owntracks/android/files/2367335/mosquitto.log)

MQTT Snooper (running on my phone) Screen Capture (today): 
![mqtt_snooper](https://user-images.githubusercontent.com/1275999/45308665-0000c000-b4f0-11e8-9ee9-7e3c48254e13.png)

Owntracks (running on my phone) Screen Capture (today) showing my location.  Notice that it hasn't been updated since 9/1 even though MQTT Snooper shows multiple updates today since activiating the Snooper: 
![owntracks-sb](https://user-images.githubusercontent.com/1275999/45308739-2b83aa80-b4f0-11e8-86d4-c4ae5f6ac8d0.png)

Owntracks (running on my phone) Screen Capture (today) showing my wife's location.  It updates a lot more reliably (but still not quite as frequently as I'd expect): 
![owntracks-jb](https://user-images.githubusercontent.com/1275999/45308807-5241e100-b4f0-11e8-8920-a8cfa5cc43a3.png)

Thanks,
begleysm

**Comment by binarybucks** [comment]
from the mosquitto logs it looks like you‘re reusing the same MQTT clientid for both devices. Try setting the clientid to something unique please

**Comment by begleysm** [comment]
Thanks.  On my phone I have the following parameters setup under Preferences -> Connection -> Identification.

![owntracks-sb-settings](https://user-images.githubusercontent.com/1275999/45311739-05fa9f00-b4f8-11e8-975c-6558e20a954c.png)

On my wife's phone the settings are:
Username: loc
Password: ********
Device ID: jackie
Tracker ID: JB

I'm not sure how clientid is set but, looking at my Configuration, my clientid "locsean".  Hers is "locjackie" which should be verified by the log file.  Search and "locjackie", there are 1691 occurrences.  See attached [config.otrc.txt](https://github.com/owntracks/android/files/2367623/config.otrc.txt) (with password removed) showing clientID as "locsean".

As far as I can tell, we have unique clientId's.

**Comment by jpmens** [comment]
Some client on  your network (at 192.168.1.1) is kicking your MQTT connection off due to duplicate client IDs:

```
$ grep 'New client.*locsean' mosquitto.log
1533085631: New client connected from 192.168.1.1 as locsean (c0, k3600, u'loc').
1533087605: New client connected from 192.168.1.1 as locsean (c0, k3600, u'loc').
1533117902: New client connected from 99.203.4.201 as locsean (c0, k3600, u'loc').
1533120132: New client connected from 99.203.5.81 as locsean (c0, k3600, u'loc').
1533120215: New client connected from 99.203.4.145 as locsean (c0, k3600, u'loc').
1533120706: New client connected from 128.61.22.83 as locsean (c0, k3600, u'loc').
1533124357: New client connected from 99.203.4.55 as locsean (c0, k3600, u'loc').
....
```

**Comment by begleysm** [comment]
Until this afternoon I had no updates to "my" location on my phone since Sept 1st.  Around 5pm my app displayed my location from approx 10:30am.  Checking again now (at 10:04pm) it is showing my location from 3:40pm.

**Comment by binarybucks** [comment]
The issue should no longer appear in 2.1.0 which has hit the public beta channel on Google Play. 
Could you please try that verison and report back to #569 if the issue persists?

**Comment by begleysm** [comment]
Unfortunately I think this is still an issue.  I commented on the current behavior in #569.
