### ISSUE TITLE
Cant work in private HTTP mode

### ISSUE THREAD

**Issue by evanrich** [owntracks/android#570]
* **App build number**: 2.0.0(20026)
* **Android version**: 9
* **Device**: Pixel

I'm trying to get owntracks to talk to home assistant via HTTPS, but it's not working, specifically I get an error:

> javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

My cert is from Comodo:
![image](https://user-images.githubusercontent.com/518320/44893528-655ae280-aca0-11e8-94ee-a100e47ca93a.png)

and I've validated that the first CA in that image (COMODO_RSA_Certification_authority_wixCert_1) exists on my android device.   I'm running home assistant on a kubernetes cluster, with a ingress controller in front, but If I look at the cert in Chrome and on my Android device, it uses the Comodo cert chain.  If I run openssl client on one of the kubernetes nodes, i get a fake kubernetes cert, but I believe that's just the path it's taking internally.    I've tried every thing I can think of to make this work, but I can't get around this issue (including saving the domain validation cert and loading that as well).

Any ideas?

**Comment by binarybucks** [comment]
Hi, 

the way Owntracks uses the system CAs isn’t exactly rocked science. Either the system knows the CAs and the server setup is correct or it doesn’t work. This doesn’t appear to be a problem with Owntracks but more with your TLS  setup. 

Running an Owntracks backend on Kubernetes also isn’t exactly the easiest to troubleshoot. May I suggest a more simple setup with less rope to shoot yourself in the foot? 

Have you tried a simple Caddy setup or checked from an external host if the correct cert chain is returned? Also, is the intermediate CA correct?

**Comment by binarybucks** [comment]
Closing for lack of response
