### ISSUE TITLE
Can owntracks be used as an application, not as device?

### ISSUE THREAD

**Issue by mbsysd00** [owntracks/android#571]
Can owntracks be used as an application (displaying gps device data sent from the cloud) instead of the device itself? Thanks.

**Comment by jpmens** [comment]
If you provide the data in our OwnTracks JSON format via the MQTT broker the app connects to or via the HTTP endpoint the app connects to, then that would be possible as a "friend". We document this quite extensively in our Booklet.

You might care to elaborate on what you're trying to accomplish?

**Comment by mbsysd00** [comment]
Thank you for point out.

I have sent GPS data from Android-Smartwatch (as Device) to Cloud using the SMTT protocol. GPS data already appears on the event log from the Cloud (I use IBM Cloud)

I want the GPS data from the Cloud to appear on Owntracks's map (as Application). Are the steps as follows:
1. Subcribe to Cloud to retrieve data from Clouds.
2. Show data to owntracks map.

Thank You.

Best Regards,
mbsysd

**Comment by jpmens** [comment]
I do not know what "SMTT" is, but that doesn't matter. I've explained how you can accomplish what you're asking for, and yes, those are basically the steps you need to take.

Good luck.

**Comment by mbsysd00** [comment]
Sorry, mistype. Thanks.

**Comment by jpmens** [comment]
You will have to create an MQTT subscriber which reads from your "cloud", converts to [OwnTracks JSON](https://owntracks.org/booklet/tech/json/) and republishes such that our app subscribes to it. Your data will then appear on the map of the OwnTracks app.

**Comment by mbsysd00** [comment]
Thank you for point out.
