### ISSUE TITLE
Improve documentation for the app

### ISSUE THREAD

**Issue by nbeernink** [owntracks/android#587]
Hi, 

I read [the booklet](https://owntracks.org/booklet) but couldn't figure out what the "copy" option does in the Android app. Can anyone explain?

None of the options in android app seem to have an explanation, maybe it's a good idea to document them all? I can try to help out...

* **App build number**: 12701
* **Android version**: 8.0.0
* **Device**: Oneplus 3T

**Comment by jpmens** [comment]
The _copy_ option you still see is no longer available in newer releases, which is why we've removed the documentation for it. If you're curious, it adds a `_cp` tag to the outgoing payload. But as I said, we've removed it because it turns out nobody used it.

**Comment by nbeernink** [comment]
Thanks for the explanation @jpmens!
