### ISSUE TITLE
Host with subdirectory

### ISSUE THREAD

**Issue by AnthonyVH** [owntracks/android#592]
I have an MQTT broker running behind a reverse proxy (Traefik). This is set up to redirect websockets traffic to the broker. If I configure it to redirect all traffic from the root domain (e.g. www.example.com) to the broker, everything works, i.e. OwnTracks connects to it just fine. 

However, if I redirect only when accesses are to a certain subfolder (e.g. www.example.com/mqtt) then OwnTracks can't connect any longer.

Is there a certain way I have to setup the hosts field for this to work, or is such a configuration not supported? I went through the documentation multiple times, but couldn't find anything related to this.

The reason I'm using subdirectories over subdomains is because they makes it much easier for me to add services/"entry points". With subdomains I have to add port forwarding in multiple routers and add a separate DNS A domain for each service. None of that is required when using subdirectories.

* **App build number**: 1.2.7 (12701)
* **Android version**: 7.1.2 (LineageOS 14.1-20170728-NIGHTLY-titan)
* **Device**: Motorola MotoG 2014

**Comment by jpmens** [comment]
I don't think we support this type of configuration.

**Comment by binarybucks** [comment]
I tried the same thing some time ago but do never got it to work. From my experience the websocket support of the Paho MQTT library is rather rudimentary so I didn’t look into it any further. 

If it is a huge issue for you, I suggest to migrate to HTTP mode which of course works perfectly with subdirectories.

**Comment by jpmens** [comment]
Just to clarify @binarybucks' response: our HTTP mode is exactly that: we then expect an HTTP endpoint (no Websockets) and no longer an MQTT broker.

**Comment by AnthonyVH** [comment]
I did a quick test with an HTTP-to-MQTT bridge I found online (https://github.com/petkov/http_to_mqtt), but that doesn't quite work. I'm assuming this is because there's not really an MQTT-over-HTTP standard and the code is expecting JSON with a slightly different format (e.g. containing the MQTT topic in a "topic" field).

Am I correct that the most likely way to get this to work is by setting up OwnTracks Recorder?

**Comment by jpmens** [comment]
I don't really know what you mean by getting _this_ to work ...

Using our Android app you have three possibilities:

1. Websockets (which you've ruled out because of the path not working)
2. HTTP
3. MQTT

The OwnTracks Recorder will work in the latter two scenarios, but as I say, I don't know what you're attempting to accomplish.

**Comment by AnthonyVH** [comment]
Right, I now see that wasn't very clear. With "this" I mean setting up a receiver (be it HTTP, MQTT or Websockets) which bridges received data to another MQTT broker on the internal network. As far as I can see, this should be possible using OwnTracks Recorder and some LUA hooks. (Or write my own lightweight script, I guess).

**Comment by binarybucks** [comment]
Yes, in facts that's what I'm mainly using. 
As a bonus, you bypass most firewalls that block MQTT and you get some nice features from ot-recorder for free ;)

**Comment by AnthonyVH** [comment]
Would you mind sharing your setup/hooks you're using? I've searched Google, but found no examples, so was preparing myself to dig in.

Related to this, how are you securing your setup? It seems there's no way to lock down the HTTP access in Recorder itself. For now, I've made sure that only requests to the /put subdir go through, but maybe I'm missing an obvious, better solution.

**Comment by jpmens** [comment]
The Recorder should **definitely not** be accessible publicly; we reccomend placing it behind an nginx or Apache proxy (there's an example for nginx in the Recorder's documentation).

**Comment by pjv** [comment]
seconding the request for some sample code for the lua hooks to echo http updates to the recorder into its associated MQTT. For now I have android devices posting to an external MQTT server on a VPS which my internal (home) MQTT is subscribed to. But if I could post updates via HTTP from the android app, get all the ot-recorder goodies, and also still end up with the updates on my local MQTT, that would be awesome. I just don't have the time right now to absorb all of the documentation I'd need to write the lua code from scratch.

**Comment by binarybucks** [comment]
I'm using these LUA functions
```
alexander@li:/var/docker/hass$ cat /etc/ot-recorder/ot-recorder.lua
JSON = (loadfile "/etc/ot-recorder/JSON.lua")()

function otr_init()
end

function otr_exit()
end

function otr_hook(topic, _type, data)
    otr.log("DEBUG_PUB:" .. topic .. " " .. JSON:encode(data))
    if(data['_http'] == true) then
        if(data['_repub'] == true) then
           return
        end
        data['_repub'] = true
        local payload = JSON:encode(data)
        otr.publish(topic, payload, 1, 1)
    end
end

function otr_putrec(u, d, s)
        j = JSON:decode(s)
        if (j['_repub'] == true) then
                return 1
        end
end
```
