### ISSUE TITLE
Cannot import waypoints

### ISSUE THREAD

**Issue by Ruebezahl11** [owntracks/android#596]
* 1.2.7*: 
* 4.4.2:    
* Wiko Rainbow: 

Hi,

I have copied the sample file from the booklet (and just changed lat/lon). I use totalcommander ftp to download the file. TC offers to import configuration, but I get import error.
I already tried to use "payload" instead of "waypoints" in the file, but that does not work either.
Is there any way to get a more detailed error message?

**Comment by jpmens** [comment]
Are you quite sure you are importing valid JSON? Since you are working with the example file as you say, woud you show us the result of your conversion? (Please paste here between two lines of three backticks each)

**Comment by jpmens** [comment]
Could you kindly also point out which sample file from the Booklet you've used? I'm not quite sure what you're using.

**Comment by binarybucks** [comment]
Try 
```
{
  "_type": "configuration",
    "waypoints": [
      {
        "desc": "Home - outer range",
        "rad": 500,
        "lon": 12.1923383,
        "lat": 48.6834467,
        "tst": 1539662468,
        "_type": "waypoint"
      },
      {
        "desc": "Home - inner range",
        "rad": 100,
        "lon": 12.1923383,
        "lat": 48.6834467,
        "tst": 1539662467,
        "_type": "waypoint"
      }
    ]
}```

The setWaypoints is for remote commands and not for .otrc imports

**Comment by jpmens** [comment]
The example you found, is one for a remote command. In order to import waypoints from what we call an `.otrw` file, you must please format your JSON this way:

```json
{
  "_type": "waypoints",
  "waypoints": [
    {
      "desc": "Home - outer range",
      "rad": 500,
      "lon": 12.1923383,
      "lat": 48.6834467,
      "tst": 1539662468,
      "_type": "waypoint"
    }
  ]
}
```

I hope that helps.

**Comment by Ruebezahl11** [comment]
Hi,

unfortunately no luck either

**Comment by binarybucks** [comment]
Fixed in 2.x
