### ISSUE TITLE
S7 running Android 8.0.0 not being offered owntracks v2

### ISSUE THREAD

**Issue by grheard** [owntracks/android#597]
* **App build number**: 1.2.7 (12701)
* **Android version**: 8.0.0   
* **Device**: Samsung SM-G930A
* **Play Version**: 12.1.18-all [0] [PR] 216263519

Not sure if this is the right place to post this, but I'm stumped as to what I can do to resolve the situation. I own 3 devices. Two S6's running Android 7 and the one S7 running Android 8. The two S6s were offered and updated to version 2 of owntracks, but the S7 is only offered the now out of date 1.2.7 on Google Play. All the devices are using the same version of Google Play (see above).

Any ideas?

**Comment by binarybucks** [comment]
Please wait a bit. Rollout of 2.x is halted until 2.1 is available due to some bugs.
