### ISSUE TITLE
[Feature Request] Disable Notifications when on WiFi

### ISSUE THREAD

**Issue by mpemberton5** [owntracks/android#605]
My guess is it would save some battery life if there was an option to not send out notifications when currently connected to a WiFi.  May not always work for everyone, but for my configuration, each WiFi I connect to I establish a Region.

Thanks!

**Comment by growse** [comment]
This seems like a somewhat niche request. Is the only reason for disabling by Wifi because you have tied regions to wifi networks? 

I wonder if the open PR we have on hiding notifications for your own region events (#584) would help you achieve what you need?

**Comment by binarybucks** [comment]
The app cannot act on changes in WiFi networks because that is now prohibited by Android. Adding this kind of feature to regions would become very confusing if there e.g. are overlapping regions. 

What would be the indended use case here? Supress event notifications if you're connected to the home network?

**Comment by mpemberton5** [comment]
Use Case: When I connect to a WiFi (say I come home and connect to my home network) it doesn't make sense to continue to try and find my GPS location.  Benefit would be reduced battery usage.  Once I drop the WiFi connection from my home (aka leave home), location monitoring should pick back up.

As an alternative, have the ability to externally request OwnTracks to stop/start monitoring (i.e. using Tasker or IFTTT).

**Comment by binarybucks** [comment]
2.1 has different monitoring modes (low power, significant location changes, high power) which can be switched with an external intent e.g. from tasker. You should be able to set it to low power mode (cell tower location, uses nearly no battery) when at home. 
I'd be happy to hear from you if it works like expected once it's in beta in the next days.

**Comment by mpemberton5** [comment]
Sounds great!!  Be glad to test it out.

**Comment by binarybucks** [comment]
2.1 is available now. You can toggle the monitoring mode by sending an intent with action `org.owntracks.android.CHANGE_MONITORING` to Owntracks. 
The mode can be specified by adding ang `int` extra named `monitoring` with values between `-1` and `3`

**Comment by digimystigi** [comment]
To those reading binarybucks instructions, when using Tasker, leave "Cat" as None, set the value (-1, 0, 1, 2 or 3) in the first "Extra" field and change the Target from "Broadcast Receiver" to "Service" and it will work.
