### ISSUE TITLE
Configuration incomplete

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#609]
I'm trying to get the anrdoid app set up on Android 8, but I get a message saying the configuration is incomplete with no information as to why... I have an ssl cert from letsencrypt, which I'd like to use for connection security, but I don't care about authentication or payload encryption. What do I need to fix?

My config is

```
{
  "_type": "configuration",
  "waypoints": [],
  "auth": false,
  "autostartOnBoot": true,
  "beaconBackgroundScanPeriod": 30,
  "beaconForegroundScanPeriod": 0,
  "beaconLayout": "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24",
  "beaconMode": 0,
  "cleanSession": false,
  "clientId": "hwbla",
  "cmd": true,
  "cp": false,
  "deviceId": "hwbla",
  "host": "iamnub.com",
  "ignoreInaccurateLocations": 0,
  "ignoreStaleLocations": 0,
  "keepalive": 3600,
  "locatorAccuracyBackground": 1,
  "locatorAccuracyForeground": 0,
  "locatorDisplacement": 500,
  "locatorInterval": 900,
  "mode": 0,
  "mqttProtocolLevel": 3,
  "notification": true,
  "notificationHigherPriority": false,
  "notificationLocation": true,
  "playOverride": false,
  "port": 8883,
  "pub": true,
  "pubExtendedData": true,
  "pubQos": 1,
  "pubRetain": true,
  "pubTopicBase": "owntracks/%u/%d",
  "ranging": false,
  "remoteConfiguration": true,
  "sub": true,
  "subQos": 2,
  "subTopic": "owntracks/+/+",
  "tls": false,
  "ws": false
}
```

**Comment by binarybucks** [comment]
First of, running without authentication is a very bad idea. It allows anyone to read your location data and services like Shodan already Index Owntracks users. 

In any case, set a username and the configuration should be complete.

**Comment by kaysond** [comment]
Ah I just caught that in the documentation. Thanks! And yes it did just occur to me that without user authentication, anyone can subscribe. I was just thinking about publishing. Oops!

**Comment by binarybucks** [comment]
Good that we cought that. The next version no longer has a direct UI for setting up unauthenticated connections to provide secure defaults.

**Comment by kaysond** [comment]
@binarybucks Alright I got things set up with ssl and authentication, thanks.

Do you happen to know why I can't get `mosquitto_pub` to work? I get a TLS error, but I'm using `--cafile` and pointing it to the same location as the `cafile` option in `mosquitto.conf`. Owntracks works just fine though...

**Comment by kaysond** [comment]
Nvm got it! Thanks for the help

**Comment by kaysond** [comment]
@binarybucks actually - random question: what does the "copy" toggle do in the app?
