### ISSUE TITLE
Tracker ID doesn't update until app is restarted

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#610]
I've noticed that if I change the tracker ID and then manually push a message, it still uses the old tracker ID. Seems that I have to kill the app in the app switcher then restart it which took me a while to figure out.

* **App build number**: 1.2.7 (12701)
* **Android version**: 8   
* **Device**: Huawei MAte 10 Pro

**Comment by binarybucks** [comment]
The tracker ID is read from preferences for every new outgoing message. Could it be that the old tracker IDs you see are from queued messages?

**Comment by kaysond** [comment]
So it looks like the issue is just the display of the default icon in the app.

Suppose my old ID was `AA` and I change it to `BB`. Before the settings change, the tid sent to the broker is `AA`, the icon on the map shows `AA`, and the text says `Device-AA`.

After changing it to `BB`, the tid sent to the broker is `BB`, the text says `Device-BB`, but the icon on the map still shows `AA`. Even after several manual pushes. Killing the app and restarting it presumably re-draws the icon with the correct tid

**Comment by binarybucks** [comment]
Good point, that’s indeed an edge case I didn’t think about. The contact images are cached and not correctly invalidated when the tid changes. 
I’ll look into it.
