### ISSUE TITLE
Does not update location when reach home

### ISSUE THREAD

**Issue by 4994james** [owntracks/android#615]
This seems like a bug but happy to be corrected.  When tracking location I find when I get back home (say) that the notified location stays out of date and shows a location i would have passed on the way but not where I am now.  When I launch the app it immediately corrects itself so the issue isn't with gps.  the problem is this stops geofencing working properly i.e. it doesn't know i am in the home geofence until it corrects itself when launching the app.

* **App build number**: 2.00 20026
* **Android version**: 5.1
* **Device**: motorola moto g xt1039

**Comment by RomRider** [comment]
Same issue here with the 2.1.0 version.
In `significant changes mode`, the last location update was like 200m from my home and stays like this forever (even after 1 day of not moving from my home) unless I put owntracks in `move monitoring mode` it stays 200m away even if Google maps report my correct position.

**Comment by binarybucks** [comment]
Hi @RomRider, 

it's probably the same as explained in #367:  With signifficant location mode, the app only updates depending on locator displacement and interval. This means an location update is received every interval (or faster) when the device moved. If you arrive at a location and don't move much, the app won't publish a location update.

If you change the mode, a new location request with other parameters is created, hence you will immediately receive a new location. Same goes for opening Google maps which uses a new location request that could possible be reused by Owntracks. 

Signifficant changes mode uses the BALANCED_POWER request type for location requests which mainly relies on Cell Tower paired with Wifi network location. If the network location is lightly wrong, it might have you stuck in a slightly wrong location. I had this when I moved and took my router with me for example. 

Does the app send the "200m away location" when you hit the report button or does it not send things at all?

**Comment by binarybucks** [comment]
@RomRider can you set Locator Displacement to `0` in the advanced preferences please and let me know if things work better?

**Comment by 4994james** [comment]
Hi.  Many thanks for the responses.  I have amended as you suggest and will report back.  Are these options documented anywhere?  I can guess that "locator background displacement" means that it will only report a new location once you have moved that distance from the last location.  I cannot see a "significant changes mode" unless that is the same thing.

**Comment by binarybucks** [comment]
It's in the beta release channel

**Comment by binarybucks** [comment]
Please report back if the issue persists in 2.1.x
