### ISSUE TITLE
Copy mode?

### ISSUE THREAD

**Issue by hex4d617474** [owntracks/android#617]
In owntracks, what does "copy" do? There was a reference to "copy mode" on the owntracks website, but it was a dead link. I haven't been able to find anything else from a quick internet search.
<img width="540" alt="owntracks" src="https://user-images.githubusercontent.com/17362096/48308829-3b445d00-e53a-11e8-8e55-1150ded6ab5f.png">

**Comment by binarybucks** [comment]
Ignore that feature. It has been removed in the next version
