### ISSUE TITLE
Owntracks does not update since Android 9 

### ISSUE THREAD

**Issue by ajfriesen** [owntracks/android#625]
Hardware and Software:

- OnePlus 6
- Android 9
- 1. November 3018

Latest owntracks app setup with http to home assistant.
The setup in general works. It actually worked great for more than a year now.

I think since the android 9 update (I am not 100% sure) owntracks does not update my location.

Battery optimization for owntracks is off.

When I start the app manually it will update my location almost immediately.
I also can see the notification after the start. But some hours later the notification is gone and owntracks needs a manuel start.

If you need logs or further help let me know.

**Comment by AuspeXeu** [comment]
Same problem here

**Comment by binarybucks** [comment]
Version 2.1.0 with many fixes for Android >=8 is available new. Please reopen the issue with steps to reproduce if the problems persist.
