### ISSUE TITLE
Wrong data types in _location json payload

### ISSUE THREAD

**Issue by morenstrat** [owntracks/android#629]
* **App build number**: 2.1.0 (21004)
* **Android version**: 9
* **Device**: Google Pixel 2

Some data types do not conform to the API anymore. "alt" and "vel" should be integers (according to https://owntracks.org/booklet/tech/json/#_typelocation) but they are float with version 2.1.0 of the app:

`{"_type":"location","acc":66,"alt":167.10000610351562,"batt":9,"conn":"w","lat":XXX,"lon":XXX,"tid":"px","tst":1544227351,"vac":2,"vel":0.0}`

**Comment by jpmens** [comment]
Good catch, thank you

**Comment by morenstrat** [comment]
Wow, that was quick. Thank you!
