### ISSUE TITLE
Add various protocol handlers for easier setup

### ISSUE THREAD

**Issue by CloCkWeRX** [owntracks/android#63]
Like: http://snipplr.com/view/49930/android-open-an-activity-when-a-custom-protocol-is-clicked-in-the-browser/

Flow: Setup
 * User clicks on an MQTT link: mqtt://blah:blah@m10.cloudmqtt.com:13858
 * Application opens prompts user to see if they want to open this with Owntracks
 * User has a pre-populated 'connection' dialog
 * Normal 'create connection' flow takes over

Flow: Replace connection
 * User clicks on an MQTT link: mqtt://blah:blah@m10.cloudmqtt.com:13858
 * Application opens prompts user to see if they want to open this with Owntracks
 * User already has a connection, but is asked if they wish to replace it
 * They select yes
 * User has a pre-populated 'connection' dialog
 * Normal 'create connection' flow takes over

Quite similar to https://github.com/owntracks/owntracks/wiki/RemoteConfig ; but aimed more at the "I just found a new broker I want to use or share with my friends".

This *also* makes it easy for self hosted owntracks services to publish mobile friendly links in a variety of media; ie:

![qrcode 22718421](https://cloud.githubusercontent.com/assets/365751/3183485/d174a6bc-ec6b-11e3-934d-0c116196033c.png)

**Comment by jpmens** [comment]
We're doing this in iOS now with QR codes (>= app version 8.0.35, currently alpha testers). [See documentation](http://owntracks.org/booklet/tech/qr/)
