### ISSUE TITLE
Can't get out of intro menu

### ISSUE THREAD

**Issue by ljmerza** [owntracks/android#630]
* **App build number**: 2.1.1
* **Android version**: 8.0.0
* **Device**: Samsung s8

Installed owntracks app and I can't get past the second intro screen about restrictions. I can click on the learn more button but I can't go to the third intro menu. The right arrow does nothing.

**Comment by binarybucks** [comment]
We're looking into a little issue with the intro screen flow. Could you attach a screenshot please?

**Comment by ljmerza** [comment]
![image](https://user-images.githubusercontent.com/4085765/49700163-35798000-fba9-11e8-90f7-165c9cc45d40.png)

**Comment by binarybucks** [comment]
Thanks, I can reproduce it in the emulator. Give me a second.

**Comment by binarybucks** [comment]
2.1.1 (build 2) will be available as an update in a couple of minutes. Could you please report back if you can now get past the restrictions screen?

**Comment by Stinkfut** [comment]
I am also experiencing this exact issue.  I'm on Android 8, app build 2.1.1, device is Moto Z2.

**Comment by binarybucks** [comment]
Are you using build 21101 or 21102?

**Comment by Stinkfut** [comment]
App details only tells me 2.1.1.  I just reinstalled from the Play Store to be sure I have the latest.  Where do I see if 21101 or 21102?

**Comment by binarybucks** [comment]
Apparently the Play Store release took quite some time to process the new version. There should be an update that shows 21102 in the update notes now.

**Comment by Stinkfut** [comment]
I reinstalled today, everything is working.  Thank you!

**Comment by Stinkfut** [comment]
I reinstalled from the Play Store and everything is working now.  Thank you Alexander for the quick fix.  I'm looking forward to integrating OwnTracks into my Home Assistant for presence tracking.
