### ISSUE TITLE
Update "storm" after latest update

### ISSUE THREAD

**Issue by lsowen** [owntracks/android#632]
I have two android phones connecting to a private MQTT server.  One is running 2.1.0, and after updating the second one to 2.1.1 there is a "storm" of updates, causing the notifications on both phones (without regard to the monitoring mode) to cycle between "connected", the monitoring mode", and "disconnected".  No changes were made to the configs or to the server.

As far as I can tell, each phone is connecting, publishing an update, and then disconnecting once a second.  It sort of feels like the update published by one phone is triggering the other phone to loop, which causes the first phone to loop, ad infinitum.

Phone 1:
Pixel 2
Android 9
Owntracks 2.1.1

Phone 2:
Nexux 6p
Android 8.1.0
Owntracks 2.1.0

Let me know what other information I can supply.  When I get a chance I'll pull logs from the MQTT server and the phones.

**Comment by binarybucks** [comment]
Yes, broker logs would be very appreciated

**Comment by lsowen** [comment]
Finally tracked down the issue.  The configuration from one phone had been used to as a template to create the configuration for the other phone (a long time ago, >6 months), and while the "Connection -> Identification" information had been updated (including the `deviceId`), the `clientId` had not been changed either via "Configuration Management" or automatically when the "Connection -> Identification" had been updated.

This was causing some sort of logic loop to be fired, which hadn't existed in the previous version.  So, a bug in the configuration file has triggering new behavior.

Definitely user error, so I'll close this.  But when/how should the `deviceId` be regenerated (if ever)?
