### ISSUE TITLE
Can't connect to Beebutte

### ISSUE THREAD

**Issue by qwertangel** [owntracks/android#637]
* **2.1.2(21201)**: 
* **9**:    
* **Pixel 2 XL**: 

Can't connect to Beebutte (beebutte.com) mqtt broker no matter what i try.
1) beebutte uses only username (no password) . but owntracks insists on having a password
2) beebutte only supports channel/resource , but owntracks insists on having channel/resource/device 

I was able to edit (2) using config editor to use channel/resource but don't know how to get around (1). I tried putting junk value and value of username in password field, but it still can't connect.

Since beebutte provides generous amount of free messages and a rest endpoint, it is one of very useful servers to support. Please help.

**Comment by jpmens** [comment]
We strongly recommend using a service you provide yourself, in particular one in which you configure transport security and authentication which is why we now insist on username/password. You can change that by creating an `.otrc` configuration file and that is described in our Booklet. We will not help you do that though for reasons I've just mentioned.

**Comment by qwertangel** [comment]
hi jpmens, i understand how risky it looks without a password. however beebutte actually uses a randomly generated token  (which is  revokable) since most of mqtt requires username/password, they instruct to put that token in username. Security of using that token is no less secure than a using a password.

**Comment by jpmens** [comment]
@qwertangel yes, we understand that, thank you. FYI, we've been talking about this internally, and have decided to probably support not specifying a password (at least via our `.otrc` configuration, possibly via UI).

https://github.com/owntracks/ios/issues/559

**Comment by binarybucks** [comment]
The new parameter will be in the next android release too. It’s rather easy to add. It will be available through the configuration management editor.

**Comment by qwertangel** [comment]
Awesome ! Allowing this functionality through manual edit of config file balances out needs of both - advance users who need advance configurations and casual users who might miss entering password.
Thanks @jpmens and @binarybucks ! Appreciate your quick response.

**Comment by binarybucks** [comment]
Code is commited with https://github.com/owntracks/android/commit/133745885a12a15c195063270af6d5c91cea0d52 and will be in the next release. 
To enable it, go to the configuration editor in the preferences, set `usePassword` to `false` and reconnect to the broker.

**Comment by qwertangel** [comment]
apologies for typo.. correct site is beebotte.com

**Comment by binarybucks** [comment]
Fix will be in next version.
