### ISSUE TITLE
reportLocation available in significant move only

### ISSUE THREAD

**Issue by mdelpire** [owntracks/android#660]
* **App build number**: 2.1.2
* **Android version**: 8.0.0
* **Device**: Samsung S8

Hi,

I discovered owntracks and wanted to integrate within my automation system. I realized that that che command "reportLocation" is only available in significant move mode. Secondly, I noticed that this command returns in fact the last known location but doesn't trigger a new location request.

Is this normal? Would it be possible to get a new location request when calling reportLocation? And by doing so also make this command available in any mode?

Thanks a lot for your answer.

Maxime

**Comment by binarybucks** [comment]
It should be available in move mode too. 
The other modes disable it because only user triggered reports are allowed. 

It is correct that it only reports the last known location. That could be changed but might require some rewriting. It’s not planned to change this behavior at the moment. PRs are welcome though.

**Comment by grheard** [comment]
I think this needs to be re-thought. In my kids use-case, I want reportLocation to work regardless of how my kid has decided to set the app.

I also feel it should force a location update and not just parrot the last known, but I understand if that causes a significant re-write and may be unfeasible.

**Comment by jpmens** [comment]
We do not intend to change this behavior at this time, but as @binarybucks already said, we welcome code contributions to do so.

It's grand that people think _this needs to be re-thought_, and it's interesting to hear that people _want reportLocation to work regardless .._, but that's not how open source works, at least not this small project.

We welcome constructive ideas, and we've also taken many of those an have implemented them, but not, if you'll pardon me saying so, when we're expected to fulfill demands. That just doesn't work that way.

**Comment by grheard** [comment]
Funny, I thought I was simply voicing support for an idea. I know I wasn't demanding the feature, but rather keeping the idea alive and providing a possibly overlooked use-case. I'm sorry if my post was interpreted as more than that.

**Comment by binarybucks** [comment]
The term “want” might have triggered some red flags here. Additionally Owntracks is quite focused on user privacy hence it’s a double edged sword to be able to request location reports in case $kid has chosen to switch the app to manual mode. After all that’s the whole point why the modes were added. 

If the device has remote configuration enabled, it would however be possible to temporarily switch modes and also automatically get a new location fix.

**Comment by binarybucks** [comment]
`reportLocation` cmds now trigger a new fix. Will be shipped with the next version.
