### ISSUE TITLE
beacon support

### ISSUE THREAD

**Issue by canatella** [owntracks/android#662]
Hello, I understand that beacon support in Android is not perfect ATM, but I could not find more precise information on the actual reason for removal. Is there some info that I might have missed about that ? Are there plan to put them back if things get better on that front ? The Android beacon library is at 2.15.2 now so things might have changed. It would be nice to have the feature back at least for tinkering and check what the actual status is.

Also, thanks for your work and time on this application.

**Comment by binarybucks** [comment]
The beacon code was causing around 90% of all crashes in the app and even affected users that were not actively using that feature. 

Additionally “not perfect” is a completely understatement of the BLE state of Android in general. Horrible broken and severely impaired by screwed up hardware, drivers, software or a mix of all three is probably more precise

Things might have changed but I’m not very optimistic about that. Looking at the open issues reveals similar issues that lead to its removal from our app. 

As we’ve very little resources that we can dedicate towards the development and maintenance of the app, I will not implement beacon support again at the moment. Instead we’d like to focus on general stability improvements.
