### ISSUE TITLE
mqtt topics

### ISSUE THREAD

**Issue by johnmcdnz** [owntracks/android#665]
Using version 2.1.2 (21201) on Android

I'd like to know if the mqtt subTopic can be set to "owntracks" and use the JSON "topic" to identify the required channel.

My purpose is that I'm using pubnub.com to publish data via http to an associated mqtt server.  Pubnub can only publish to the top level channel/topic and can't subscribe to subtopics.  i.e. to a topic 'owntracks' only

I've been testing the mqtt message by adding a JSON topic parameter and sending this to the top level owntracks mqtt topic, but it seems that the app is insisting on using the mqtt channel to display the data.

I've also edited the config management parameters to change the subTopic to 'owntracks' or '/' instead of 'owntracks/+/+' but neither of these helps.

**Comment by binarybucks** [comment]
I'm not sure I understand your question or the problem. Could you elaborate?

**Comment by johnmcdnz** [comment]
Pubnub has a relatively simple method of sending and listening on a top level mqtt channel.  But it's difficult to subscribe to a topic path.  I can arrange to put the required topic path in the json message as per the topic: parameter.   It seems that this only works with post message types though, not mqtt.  So there's an almost solution, if owntracks could also accept topic parameter for mqtt messages. 

Thanks for considering.

**Comment by dustin** [comment]
I think it'd be quite useful if, instead of having a single topic owntracks is publishing to with different message types and different meanings, each message type could be a subtopic.

e.g., 

    owntracks/me/dev/location
    owntracks/me/dev/transition
    owntracks/me/dev/lwt

etc...

I've got tooling around this, but all of the tools I use consider a single topic to represent a single type of message.  Opening the message contents and parsing them to determine which message is being sent is more complicated than just telling the broker to send the subset of interest.

**Comment by johnmcdnz** [comment]
As I think about my request I realise the complexity.  The pubnub broker is
not sophisticated to handle multiple topics.  So I'm wondering if the mqtt
messages can be in a single topic, ie /owntracks. But the json message has
the actual required topic.

Probably ought to implement the interface at pubnub better.

Best Regards,
John McDermott

mob: 0274 100 079
tel(voip): +64 (0)955 33227

**Comment by dustin** [comment]
Perhaps augmenting `pubTopicBase` with a mechanism allowing the publishing patterns to be specified along with an extra `%` variable for message type would solve both problems?  You could smash all publishing down into a single message and differentiate by contents, and I could separate them out into separate topics and subscribe to the interesting ones.

**Comment by jpmens** [comment]
Thank you for your suggestions. 

We've discussed this internally, and have decided we are not interested in investing effort in developing, testing, and maintaining this feature simply for this particular broker implementation. We just don't have the resources to do so, nor do we see a benefit in doing it.

It may be worth your while to invent a "republisher" which takes our JSON payloads and formats them in the way you need them.

**Comment by johnmcdnz** [comment]
Yep. I understand. The problem is at the other end of not having a good
mqtt integration.

Keep up the good work.

Best Regards,
John McDermott

mob: 0274 100 079
tel(voip): +64 (0)955 33227
