### ISSUE TITLE
Cannot edit config/client not responding to remote commands

### ISSUE THREAD

**Issue by shfan91** [owntracks/android#666]
Hello all, 

I recently got started down the deep deep hole that is home automation and recently implemented a cloud based MQTT server that's been bridged back home and encrypted with TLS v1.2.

I'm able to publish location updates from my Android phone as expected. Things become more of an issue when I look at trying to edit my config to enable remote commands.

I tried first editing the setting in Preferences >> Advanced >> Enable Remote Commands, no luck after change.

After checking the booklet, I tried to add the "allowRemoteLocation" key in my config, first by using the editor in the app, no luck, then by exporting the config and manually editing via Notepad++ and importing. The app looks like it imports, even goes as far as saying it was successful and recommends a restart, but after a reboot I'm able to see that nothing has changed.

Here is the default config I have in my phone (private info redacted)

`{"_type":"configuration",
"waypoints":[
{"_type":"waypoint",
"desc":"Home",
"lat":<latitude>,
"lon":<longitude>,
"rad":200,
"tst":1547862351}
],
"_build":21201,
"auth":true,
"autostartOnBoot":true,
"cleanSession":false,
"clientId":"user1galaxyuser",
"cmd":true,
"deviceId":"user1galaxy",
"fusedRegionDetection":true,
"host":"mycloudmqtt.duckdns.org",
"ignoreInaccurateLocations":0,
"ignoreStaleLocations":0,
"keepalive":3600,
"locatorDisplacement":50,
"locatorInterval":50,
"mode":0,
"mqttProtocolLevel":3,
"notificationHigherPriority":false,
"notificationLocation":true,
"password":"password goes here",
"ping":30,
"port":8883,
"pubExtendedData":true,
"pubQos":1,
"pubRetain":true,
"pubTopicBase":"owntracks/%u/%d",
"remoteConfiguration":true,
"allowRemoteLocation":true,
"sub":true,
"subQos":2,
"subTopic":"owntracks/+/+",
"tid":"ZF",
"tls":true,
"tlsCaCrt":"ca.crt",
"tlsClientCrt":"client1.pfx",
"username":"user1",
"ws":false}`

App version 2.1.2 (21201)
Android version 8.0.0
Samsung Galaxy S9+

**Comment by binarybucks** [comment]
What exactly is not working? The attached config is showing that all cmd related settings are enabled.

**Comment by shfan91** [comment]
After not touching this for a few months, I took another look at this and realized that I had not set up MQTT topic bridging correctly. Working now!
