### ISSUE TITLE
Movement modes don't seem to match the documenation

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#669]
Maybe this has already been addressed in the master branch, but the page in the documentation for Android location data (https://owntracks.org/booklet/features/location/#android) indicates that there aren't really any selectable modes for location updating. However, the app itself has the button just as the iOS does, which suggests that I can choose between different modes like significant changes vs move mode.

Is there really only one mode? Do the locator displacement and locator interval control updates regardless of what the "mode" button is set to?

I ask because my mother's location updates aren't coming as expected. For example, she drove about 10 miles in 15min or so, and there was no location update whatsoever.

**Comment by binarybucks** [comment]
The documentation isn’t up to date yet, thank you for pointing that out. 

Locator setting only influence significant mode but their UI settings will be removed in the next version due to all the confusion they cause.

**Comment by binarybucks** [comment]
Of course

**Comment by kaysond** [comment]
Thanks! I can create another issue if you'd like, but I also noticed that if you long-press the "mode" button, it has the same hover text as the publish button. It would be nice if it showed what the current mode is. Also, I think it used to give me toasts as I changed mode, but that doesn't seem to happen anymore.

**Comment by binarybucks** [comment]
Oh yes, good catch. Feel free to create an extra issue for that
