### ISSUE TITLE
False transition events in move mode

### ISSUE THREAD

**Issue by Andrew718** [owntracks/android#670]
Version 2.1.2 (21201)
* **Android version**: 8.0
* **Samsung Galaxy S9+**

Hello,
I am using the android app in move mode. When I am sitting at my desk, phone asleep, not even picked up, it will intermittently report a transition exit, and then enter event for the region I am in.

The events are not specific to one region, and typically happen between 10s and 30s apart.

When I am in significant changes mode, there are no false transitions, but the time delay is too long for my use case.

I believe this is probably something to do with the GPS going to sleep or not connecting quickly enough.

Can you suggest any ways I could try to debug this issue?

Thank you!

**Comment by grheard** [comment]
@Andrew718 I found this was the case with my S6 edge as well. I found that setting the 'Preferences->Advanced->Inacurate locations' to around 50 meters quieted the bouncing locations. Depending on the number of satellites in view, the accuracy of the gps on my phone bounces around quite a bit especially in doors.

**Comment by Andrew718** [comment]
Thank you so much, I didnt even see this as an option. I have set it to 50m and will update here with results.

Cheers

**Comment by Andrew718** [comment]
Thank you, this fixed my issues. Inaccurate locations set to 50m in advanced settings.
