### ISSUE TITLE
Long press of reporting mode UI button shows wrong text

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#671]
If you long press the mode button, it says "Report" rather than the current mode (or something similary)

**Comment by darianf01** [comment]
agree, and i could not find anywhere else guide for Android to tell what mode each icon represents: play, pause, stop, pause&play. 

maybe it was working in the past and users are already familiar with the meaning of icons... but not me, and maybe others as well...

guessing, i think the play is move mode?
pause&play - Significant location change mode? (it also activates the location icon in the notification bar)
stop - manual
pause - quiet?

Maybe somebody can help correcting my guessing...

**Comment by kaysond** [comment]
You should get a toast at the bottom of the screen each time you press the button that tells you what it is. If you don't, I'd file a separate issue.

- Play: significant changes mode
- PausePlay: move monitoring mode
- Stop: quiet monitoring mode
- Pause: manual monitoring mode

It would also be nice if this was documented better in the documentation and in the app. I always have a hard time remembering how each works.

**Comment by growse** [comment]
I think this may have already been fixed. I see the bug on the latest play store version, but if I run the HEAD of master in the emulator, it behaves correctly.

**Comment by binarybucks** [comment]
Documentation is updated anda available at https://owntracks.org/booklet/features/location/

**Comment by kaysond** [comment]
Thank you! This is great
