### ISSUE TITLE
Phantom friend with http connection

### ISSUE THREAD

**Issue by m4rky-m4rk** [owntracks/android#693]
* **App build number**: 
* **Android version**:    
* **Device**:

**Comment by m4rky-m4rk** [comment]
Hi,

 I am using  app v2.1.2 on a Galaxy Note 8 Android v8. I am using the app to send gps data to Openhab cloud with http connection. Recently I changed my tacker ID and now the old tracker ID appears as a 'friend'

I can't find a way to remove the spurious friend. There is no delete option I can see in the app. Am I missing something or this a bug? The manual only talks about mqtt.

Thanks, Mark

**Comment by binarybucks** [comment]
You probably need to change something on the Openhab side so that it no longer returns the old tracker ID. After you made sure that this is the case, restart the app.

**Comment by m4rky-m4rk** [comment]
I don't know what the something on Openhab could be. I already updated everwhere where the ID was used. Anyway, I restarted the app after clearing out the cached files and my phantom friend gone.. so thanks for the hint.

 Is there instructions somehwere on how to use the friends feature for http connection?

**Comment by binarybucks** [comment]
What kind of instructions are you looking for?

**Comment by m4rky-m4rk** [comment]
The usual. What to expect from the feature. How it works. How to add and remove friends. Securirty etc.

**Comment by binarybucks** [comment]
Have you had a look at https://owntracks.org/booklet/features/friends/?

**Comment by m4rky-m4rk** [comment]
Thanks. Yes I have read it but it only talks about MQTT connection and not http.

**Comment by jpmens** [comment]
There are some notes on Friends in HTTP mode [here](https://owntracks.org/booklet/tech/http/).
