### ISSUE TITLE
Enabling websockets sends requests over port 80 regardless of what port is selected

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#697]
* **App build number**: 2.1.2(21201)
* **Android version**: 9   
* **Device**: Huawei Mate 10 Pro

I've set up an Apache 2.7 reverse proxy to access my mosquitto broker over websockets via port 443. I've set up owntracks with the right hostname, the port is set to 443, and TLS is enabled. However, owntracks keeps sending `"GET /mqtt HTTP/1.1` requests over port 80, and it took me a while to figure out why things weren't working. So for now I've set my reverse proxy to listen on 80 and 443, but this behavior was unexpected. Maybe this is part of the spec or something?

**Comment by growse** [comment]
Could you enable debug logging as per the booklet (https://owntracks.org/booklet/features/android/#debug-log) and post that here? There should be a line prefixed with "connect string" that should show the url it's trying to message (including the port).

**Comment by kaysond** [comment]
https://pastebin.com/ueZwctqh
Changed domain to my domain.com. Interestingly, it only shows things for port 443. And yet, my access log shows:
```
[10/Mar/2019:11:01:24 -0700] 192.168.1.1 mosquitto.mydomain.com:80 "GET /mqtt HTTP/1.1" "-" "-" TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 200 8552
[10/Mar/2019:11:01:24 -0700] 192.168.1.1 mosquitto.mydomain.com:80 "GET /mqtt HTTP/1.1" "-" "-" TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 200 26738
[10/Mar/2019:11:01:53 -0700] 192.168.1.1 mosquitto.mydomain.com:80 "GET /mqtt HTTP/1.1" "-" "-" TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 200 5574
[10/Mar/2019:11:02:12 -0700] 192.168.1.1 mosquitto.mydomain.com:80 "GET /mqtt HTTP/1.1" "-" "-" TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 200 5878
```

**Comment by binarybucks** [comment]
Downgraded library in ae12f77. Please report back if it works better now in the next release.

**Comment by kaysond** [comment]
Can you upload the apk for the 2.1.3 release? I don't have a build environment set up, but could do so if necessary.

**Comment by kaysond** [comment]
@binarybucks I'm currently running build 21302 via play store beta and I still see server log entries for port 80.

**Comment by growse** [comment]
Latest version definitely sends WS over the specified port now. Closing.
