### ISSUE TITLE
Request location data in Android doesnt seem to work

### ISSUE THREAD

**Issue by ksathara** [owntracks/android#701]
Hi, I am using owntracks app in couple of Android phones in my family and use node-red to show the locations in a worldmap. As of MQTT broker I use maqiatto.com. I can get the location messages ok. 

The problem I have is when I try to get a response to '{"_type":"cmd","action":"reportLocation"}'. Due to requirement of my MQTT broker, I have to use my email as the username. So I changed my 'pubTopicBase' to '%u/owntracks/kaushalya/%d'. %u is my email (in the form abc@xyz.com) and %d is device ID. Now location info published due to automatic/manual updates work perfectly, but not remote request.

Now based on owntracks documentation, I think to get a location message I should publish a {"_type":"cmd","action":"reportLocation"} to '%u/owntracks/kaushalya/%d/cmd'. Am I correct?

I have tried sending this message to both  '%u/owntracks/kaushalya/%d/cmd' as well as '%u/owntracks/kaushalya/%d' but I didnt get the location back.

Is there a way to observe the messages received by owntracks app?

Thanks,
Kaushalya

**Comment by binarybucks** [comment]
Moved from talk to android repo

**Comment by binarybucks** [comment]
Can you check if the app is signifficant or move mode? 
Other modes do not respond to reportLocation cmds.

**Comment by ksathara** [comment]
Hi, Yes thanks that solved the problem.

Cheers,
Kay

------ Original Message ------
