### ISSUE TITLE
Can't import config.otrc

### ISSUE THREAD

**Issue by skarotech** [owntracks/android#704]
I am trying to import a config file into the Android app, and I keep getting an 'Import failed' error.

I have a very simple config (named config.ortc) file to start with

{
    "_type": "configuration",
    "cmd": true
}

What am i missing ?

* **App build number**: 2.1.2 (21201)
* **Android version**: 8.0.0   
* **Device**: Galaxy S7

**Comment by jpmens** [comment]
Please configure your app, produce a full configuration (export) and modify that for import. The configuration you are trying to import is incomplete.

**Comment by boogymantoo** [comment]
See also issue #818 - although i do not know whether that issue was present in build 21201.

**Comment by growse** [comment]
I think we possibly need to be a bit clearer when the configuration is incomplete. It's not obvious that a configuration being imported needs to have a minimum set of keys set.

**Comment by growse** [comment]
This config import works on the current version now.
