### ISSUE TITLE
Exit app

### ISSUE THREAD

**Issue by lazarberbakov** [owntracks/android#708]
Hello,
Is it possible to exit the application and kill background service?
Basically, If I don't want to send my location anymore.
I was not able to find this option...

**Comment by growse** [comment]
If you want to turn off location sending, would putting it into "Quiet" mode not suffice? If not, then you can stop the service using the "Force Stop" functionality that Android provides to any application.

**Comment by lazarberbakov** [comment]
The Force stop looks like a workaround. In my opinion, an UI element which would allow user to stop the app completely is necessary. Not all users want to be tracked all the time.

**Comment by jpmens** [comment]
The app has a quiet mode which does just that: it stops location publishes.

**Comment by lazarberbakov** [comment]
Ok. Does this mean that the service is still running in background even though it is not publishing location updates?

**Comment by jpmens** [comment]
Indeed, yes.

**Comment by lazarberbakov** [comment]
Do you plan to add a feature where a user will be able to completely exit the app and stop the background service, so that no service is running in the background anymore?

**Comment by joardar-aditya** [comment]
updating the onStop() function might work , right?

**Comment by growse** [comment]
You can do this from within the Android settings itself, so why duplicate the functionality?

What problem would it be solving?

**Comment by joardar-aditya** [comment]
i guess most users won't like to take the extra burden for setting off the location tracking after shutting the app. It should be managed by the app itself

**Comment by growse** [comment]
As above, if uesrs want to turn off tracking, they can do that by setting the mode to manual in the app.
