### ISSUE TITLE
Screen activiating when sending position report

### ISSUE THREAD

**Issue by joshproehl** [owntracks/android#709]
* **App build number**: 2.1.2 (21201)
* **Android version**: 9
* **Device**: Essential PH-1

On one of my devices it appears that the screen activates every time Owntracks sends a position report. On a second device with exactly the same hardware/operating system this does not appear to happen.

Is this an expected behavior?

**Comment by binarybucks** [comment]
Can you check if the Android notification settings/priorities are the same on both devices

**Comment by joshproehl** [comment]
I discovered that the device which was **not** activating the screen on position update had the notification settings set to not display the OwnTracks notification at all on the lock screen.

Changing this setting on the other device causes the phone screen to stay off while the phone is in motion and updating it's position. It has the side effect of not being able to change monitoring mode or manually report position from the lock screen, but it does appear to solve the screen activation issue.

**Comment by growse** [comment]
I think I ended up fixing this a while back, as it was annoying me as well.
