### ISSUE TITLE
Inside/Outside Network

### ISSUE THREAD

**Issue by darvvin** [owntracks/android#710]
Owntracks works fine outside of my network using my public IP and domain name, but when I'm home and my phone is on the same network as the mqtt server the external IP doesn't work, but the internal one does(10.x.x.x).  Is there a way to put multiple mqtt hosts into owntracks?

I'm sure there is a way to configure DNS to make this work, but my knowledge in that area is minimal and I was hoping there was a way to deal with the issue in the Owntracks app.

Thank You
chris

**Comment by binarybucks** [comment]
It's not possible to put in mutiple hosts. I suggest to look into configuring NAT Reflection / NAT Loopback on the Router to allow the external adress to work internally. 
As you mentioned, split DNS is also an option.

**Comment by darvvin** [comment]
Thank you for your quick response.  I will look into that suggestion.
This might be a bit clunky, but would this work?
I'm using Node-Red with the MQTT server.
Could I use Node-Red to push a config to the app with the internal IP when the Enter Home event fired?
Then push a config with the external IP when Leaving Home?

**Comment by binarybucks** [comment]
How would it receive the config if it cannot connect when at home? ;) 
NAT Reflection / Split DNS is the proper solution here.
