### ISSUE TITLE
Location information way out on 21302

### ISSUE THREAD

**Issue by mf-social** [owntracks/android#711]
* **App build number**: 21302
* **Android version**: Pie
* **Device**: Pixel 2

Hi,

I'm on 21302 after upgrading to see if it would fix the issue from #700 - which so far (touch wood) seems to have done the trick, but now I have a bigger problem that wasn't present before.

My location is sometimes miles out.

There doesn't seem to be any rhyme or reason around when it happens, but just now I'm sat at home but owntracks is showing me 3 miles away as of 7 minutes ago. 

The centre button and the send button are both greyed out in the toolbar, and it seems to think it's fairly accurate because the blue circle around the dot on the map is a reasonable size. 

I've taken screenshots of owntracks and Google Maps taken seconds apart to show that Google maps is showing the correct location but owntracks isn't, but as I said I'm at home now so I'm not going to post them publicly here, but can email to a dev if needed.

Thoughts?

**Comment by mf-social** [comment]
Also, just to mention, I very rarely go in to the owntracks app itself and just leave it running in the background to update homeassistant with my location, so I only really notice these sort of issues if I'm looking at a notification from the status bar pull-down and I spot that the location is wrong in the little permanent-notification thingy. But I can safely say that it's not happening loads because it would cause havoc with my homeassistant automations.

I've maybe noticed it 3 times since I upgraded 13 days ago, could possibly have happened several times more than that, but it's not going to be a 'constant' problem.

**Comment by mf-social** [comment]
... And as a further update, I'm now showing back at home as of 4 minutes ago, so the location jump lasted about 20 minutes I guess.

Also, now it has me in the correct place, the centre and send buttons are back to white. 

Hope all of this means something to someone 🙂

**Comment by growse** [comment]
We did a load of work sorting out the blue dot on OT for 2.3, so hoping this has solved the problem. Please re-open if you're still seeing it on 2.4.
