### ISSUE TITLE
Issue Pushing Information to Home Assistant

### ISSUE THREAD

**Issue by mwhitmore15** [owntracks/android#714]
I am setting up owntracks to use with Home Assistant using this tutorial: https://www.youtube.com/watch?v=UieAQ8sC6GY

I follow it correctly until 2:50 into the video where you are supposed to push information to Home Assistant.

After I do this, the owntracks app shows an error:

"java.net.SocketTimeoutException: failed to connect to xxx.duckdns.org/xx.xx.xxx.xxx (port 8123) from/xxx.xxx.x.xxx (port 48380) after 15000ms"

I've repeated the process a few times, and receive the same error each time. I have also tried this on 4G and on a separate WiFi network away from my main network.

Any help is appreciated.

* **App build number**: 2.1.2 (21201)
* **Android version**: 9   
* **Device**: Google Pixel 2

**Comment by jpmens** [comment]
Thanks for your report. I don't think we're interested in watching a video with a tutorial we didn't make to access a system we're not familiar with. Please contact the people who created the tutorial for help.

Alternatively try and configure OwnTracks on your Android device using our documentation: we spent a lot of effort in our [Booklet](https://owntracks.org/booklet/). If you think that's not sufficient we will entertain proposals on how to improve upon it.

**Comment by jpmens** [comment]
Oh, and one more thing: you chose to attempt to hide actual values in your error message so it's impossible for anybody to actually help you diagnose the issue. `xxx.duckdns.org/xx.xx.xxx.xxx (port 8123) `

(I say "attempt", because xxx.duckdns.org actually has an IP address)

**Comment by mwhitmore15** [comment]
Okay, I apologize, I thought it was a common interface with Home Assistant.

I will try to get more information from the HA folks. Thank you for your time.
