### ISSUE TITLE
I can't erase owntrack users on home assistant device

### ISSUE THREAD

**Issue by Drwood73** [owntracks/android#716]
Good morning,

I apologize for my bad English and I thank you in advance for the help you give me.

I have this problem, I have installed and configured a server with Home Assistant and mosquitto, so I configured my own Android phone in my private mode MQTT everything works correctly, but my problem is that every time I change the username configuration, DFevice ID and Tracker ID, I find them systematically on Home Assistace between the devices even if I change them from the Android App. Who can tell me how can I delete them from the app? I have already tried to uninstall and reinstall it from my smartphone.

I thank everyone for their help.

**Comment by jpmens** [comment]
I think you'll have to ask the home assistant people ... but if you want to remove an entry from OwnTracks on Android you can do so by swiping it in the Friends list. However, if you're still subscribed to the broker and it has a retained message, you'll get it back immediately. Hence please consult the home assistant documentation.

**Comment by Drwood73** [comment]
Thanks for the reply.
In fact I found friends to remove in the list, what is the operation to do to do it? I believe this is the problem.
Thank you so much for the help

**Comment by jpmens** [comment]
To remove a friend from the MQTT broker, publish a retained null value to the particular topic. For example

```
mosquitto_pub -h broker-address -p port .... -t owntracks/username/devicename -r -n
```

You'll likely need specific options/values for TLS and authentication; consult the home assistant documentation, please.

**Comment by Drwood73** [comment]
Thank you so much, I solved by cleaning the mosquitto entries with the command you gave me.

Thanks again very much.
