### ISSUE TITLE
JsonParseException Endpoint Errors

### ISSUE THREAD

**Issue by nickm324** [owntracks/android#717]
* **App build number**: 2.1.2
* **Android version**: 7.0  
* **Device**: Samsung Galaxy S6 Edge Plus

After setting the host URL I get  HTTP 200, JsonParseException in the Endpoint state message.

**Comment by binarybucks** [comment]
Your endpoint is returning an invalid JSON response

**Comment by nickm324** [comment]
Its a fresh install of HASSIO. Any idea where  to start looking as I see nothing in the logs that indicates it is having an issue on the HA side.

**Comment by binarybucks** [comment]
I suggest asking the HASS folks. They need to return a correct response.

**Comment by binarybucks** [comment]
You can also use CURL to manually POST a location message to your endpoint to see what it returns.

**Comment by nickm324** [comment]
Could my HASS being setup to use SSL/TLS cause any kind of issue?

**Comment by binarybucks** [comment]
If there were any TLS issues you would receive a certificate exception.

**Comment by nickm324** [comment]
Ok, thanks. I will investigate on the HASS side.

**Comment by nickm324** [comment]
One other question, I see on here release 2.1.13 is available, is that version available in the play store under some other name? I installed the version from play store but its version 2.1.12

**Comment by binarybucks** [comment]
You can join the beta to receive pre release versions

**Comment by nickm324** [comment]
> You can join the beta to receive pre release versions

How do I do that?

**Comment by binarybucks** [comment]
https://play.google.com/apps/testing/org.owntracks.android

**Comment by nickm324** [comment]
> https://play.google.com/apps/testing/org.owntracks.android

Cool, thanks.

**Comment by nickm324** [comment]
> You can also use CURL to manually POST a location message to your endpoint to see what it returns.

Could you give me an example of doing this?

**Comment by binarybucks** [comment]
Sure I could. 
What steps have you tried so far to find out yourself?

**Comment by nickm324** [comment]
Well, I tried deleting and reconfiguring OwnTracks in HASS numerious times, reviewed all the HASS logs nothing there. In the android app I have reconfigured the end point numerouse times, rentered the encytption key multiple times. Enabled debugging and downloaded the logs  hoping to get some kind of clue from that but honestly I dont know what I am looking for other than all the JsonParseErrors in the log.

**Comment by nickm324** [comment]
I figured it out. I took the url from the logs pasted that into a browser and seen what I got, which was not what I expected because it was trying to hit port 443 which is use by something else on my network. So I went back to the android app and added the port HASS is on and refreshed and it worked.
