### ISSUE TITLE
Ibeacons old tech? Any other BLE work with Owntracks ?

### ISSUE THREAD

**Issue by Bacon-Ranch** [owntracks/android#719]
Hello,

new to home automation and Hassio, just started with Owntracks and I see they state they no loner "support" Ibeacons, by support do they actually mean no longer compatible at all? If yes, are there  any suggestions for other BLE beacons that I can use with Owntracks and Hassio??

**Comment by jpmens** [comment]
The Android version of OwnTracks no longer contains support for any type of beacons; that means they won't do anything. Our iOS version still supports iBeacons, if that's a consolation.
