### ISSUE TITLE
Locator interval text is incorrect

### ISSUE THREAD

**Issue by metal450** [owntracks/android#720]
* **App build number**: 2.1.2 (21201)
* **Android version**: 9
* **Device**: Samsung Galaxy S9

In Preferences->Advanced, the text for Locator interval says "Distance in meters between location updates."  This is incorrect - this option controls the max time between new location fixes.  It looks like it just duplicated the same text as for "Locator displacement."

**Comment by binarybucks** [comment]
Preferences have been reduced, issue is no longer relevant.
