### ISSUE TITLE
Error: Endpoint State Changed

### ISSUE THREAD

**Issue by Strizz02** [owntracks/android#723]
Hello,

I try to connect Owntracks to Cloudmqtt. Unfortunately this does not work. In the logfile of owntracks I get an error message: 'endpoint state error. Message: null'. I am (rather) sure that all my input is correct. What does this error message mean and how can I avoid this?

App build number is: 2.1.2(21201)
Android version: 9
Device: Huawei P20pro

Kind regards
Strizz

**Comment by growse** [comment]
Would you be able to generate and attach a debug log (instructions in the booklet: https://owntracks.org/booklet/features/android/#debug-log). That will help get to the bottom of the issue.

I agree that a "null" error message isn't very useful, so will look to try and catch / improve that anyhow.

**Comment by Strizz02** [comment]
Hello,
hope this will help you. 
[27-05-2019.log](https://github.com/owntracks/android/files/3268321/27-05-2019.log)
Strizz
