### ISSUE TITLE
MQTT connections are constantly recreated

### ISSUE THREAD

**Issue by kaysond** [owntracks/android#725]
My mosquitto logs are full of errors like:
`Client ****** already connected, closing old connection.`
It appears to happen up to several times a minute. I guess owntracks is for some reason creating a new MQTT connection every time? I'm not sure if this is standard practice or a logging issue on mosquitto's end, but it drowns out everything in my server error logs...

* **App build number**: 2.1.2
* **Android version**: 9   
* **Device**: Galaxy S10+

**Comment by binarybucks** [comment]
Check if you have another client that uses the same client ID.

**Comment by kaysond** [comment]
I don't. Also, this happens with all of my clients.

**Comment by jpmens** [comment]
Which version of Mosquitto?

**Comment by kaysond** [comment]
```
mosquitto version 1.4.15 (build date Wed, 13 Feb 2019 00:27:01 +0000)

mosquitto is an MQTT v3.1.1/v3.1 broker.
```

**Comment by jpmens** [comment]
That sounds ok.

If you look at some of those `Client ****** already connected, closing old connection` lines in the log, can you identify whether they're being emitted by one client's IP address only?

I agree with @binarybucks: typically this message is issued when two or more clients use the same clientID; MQTT brokers are then supposed to kick off the second client which often results in them fighting for a connection :)

**Comment by kaysond** [comment]
Ah. It's because the client is jumping back and forth between a cellular IP and a wifi IP. Guess I'll move him to the websocket reverse proxy to avoid this. thanks!
