### ISSUE TITLE
Use app in read-only mode without location access

### ISSUE THREAD

**Issue by makubi** [owntracks/android#726]
Hi,

it would be great if the app could be used in read-only mode without the need for location access.

Thanks

**Comment by binarybucks** [comment]
Can you not just set it to manual mode so it will not publish your location automatically?

**Comment by makubi** [comment]
Sure this works, but I think it is more convenient to allow users to set up and use the app without location access if you do not need it.

**Comment by growse** [comment]
This is potentially quite a bit of work to do, and I'm not convinced of the benefit. If you just want to look at other people's locations, you can use the web interface of the recorder.

**Comment by jpmens** [comment]
Additionally we should mention that since the data is controlled by an aquaintance or friend, they could, with a bit of effort, provide a read-only map showing specific locations.
