### ISSUE TITLE
Does not updating correct status in Move monitering Mode

### ISSUE THREAD

**Issue by delta010** [owntracks/android#727]
* **App build number**: 2.1.3(21302)
* **Android version**: 7.1.1
* **Device**: Moto X Play

While using Move monitering Mode ,if iam inside my home fist it will show the notification "inside home" then after some seconds it will show another notification "outside the home"

**Comment by binarybucks** [comment]
Check if the location publishes contain a large accuracy value and if so set `ignoreInaccurateLocations` to something lower.

**Comment by delta010** [comment]
the accuracy value changes all the time, I have a low accuracy value of "16" and high of "209" some times

**Comment by grheard** [comment]
I find an "ignoreInaccurateLocations" value of around 50 to be sufficient to cut down on errant notifications. That high of 209 means that the GPS has given you a location with an error of up to 209 meters. Setting "ignoreInaccurateLocations" to a higher value will ignore locations with high inaccuracies. Setting it too low you will stop getting some location updates do to satellite coverage as you are traveling.

**Comment by delta010** [comment]
InaccurateLocations = 200 is it ok

**Comment by grheard** [comment]
That may be a little too high. It will let any location from the GPS with an inaccuracy as high as 200m be reported. Try 50 and see if that doesn't quiet the enter/exiting notifications from bouncing.

**Comment by binarybucks** [comment]
If GPS positioning is inaccurate for your location you can also see if disabling location based geofences (have to look up the config key for that) helps. It disables checking region transitions for location updates and just uses the Android geofence API which is independent from the location API (and locator source)

**Comment by binarybucks** [comment]
It‘s `fusedRegionDetection` true|false

**Comment by delta010** [comment]
after changing the radius into 200 and InaccurateLocations into 50 everything working fine at this moment
