### ISSUE TITLE
power consumption

### ISSUE THREAD

**Issue by knobi4711** [owntracks/android#730]
Hello.
I have the version 21302 and Android 9.1.0.132 with EMUI 9.1.0. (Huwaei P20 lite)
In the evening my phone still has 60% battery charge, early only about 10%. The system information says: Owntracks consumes about 30% of the total electricity. Is there an improvement in sight?

**Comment by binarybucks** [comment]
Power consumption depends on a lot of things. Let us know your settings and we might be able to help.

**Comment by knobi4711** [comment]
Thanks, has done. Now use a Mi Note7. There does not break the behavior.
