### ISSUE TITLE
Remove friend

### ISSUE THREAD

**Issue by cburghardt** [owntracks/android#734]
I have read that it should be possible to remove a friend via the app but I can't find the option.
I am using http mode and apart from my own deviceId (which i have set) I can also see the previous deviceId (which was probably generated) on the map.
In the details menu of the old device I don't have an option to clear or remove it.

**Comment by jpmens** [comment]
Try swiping the friend left in the list of friends.

**Comment by binarybucks** [comment]
In HTTP mode you have to make sure that the backend is not returning the friend in the response array or it will reappear with every location report.

**Comment by cburghardt** [comment]
@jpmens in the current Android version I can't swipe

**Comment by cburghardt** [comment]
@binarybucks the backend doesn't return anything, it just stores the values

**Comment by binarybucks** [comment]
From what data are your friend entries constructed then? 
If they're old entries from other backends, try force closing the app

**Comment by cburghardt** [comment]
Force closing the app did the trick, the superfluous entry is gone
