### ISSUE TITLE
OwnTracks Connection issue with the CloudMqtt

### ISSUE THREAD

**Issue by karnasurendra** [owntracks/android#735]
* **App build number**:  2.1.2 
* **Android version**: 9 - Pie    
* **Device**:  OnePlus 5T

Hi,

I am trying to connect Owntracks android app through CloudMqtt. In CloudMqtt, i have created a instance and created users as well. Added user in OwnTracks android app, while connecting it is giving Error. When i debug android code it is showing MqttException. Sometimes errors be like SSLHandShake Exception... Can you help me to make connection with the CloudMqtt. Please find the attached debug file as well,

[11-09-2019.txt](https://github.com/owntracks/android/files/3599047/11-09-2019.txt)

- Below is the command to check status in command prompt

mosquitto_sub -h soldier.cloudmqtt.com -p 14506 -v -t 'owntracks' -u apprikart -P 'apprikart'

 Thanks in advance

**Comment by growse** [comment]
Your broker does not use TLS.

Is the client set to have  MQTT TLS enabled or disabled?

**Comment by karnasurendra** [comment]
Thanks for your reply

It is working now I have used normal port instead of WSL
