### ISSUE TITLE
Private HTTP Mode and client certificates?

### ISSUE THREAD

**Issue by MrMDavidson** [owntracks/android#736]
* **App build number**: 2.1.2 (21201)
* **Android version**:  9
* **Device**: Samsung S8

From what I can see of reading the documentation and looking in the app it seems that client certificates are only available when being used in Private MQTT mode. Given that the documentation recommends using Private HTTP mode for Android 6 and above, is there any plan to add support for client certificates for this mode?

**Comment by jpmens** [comment]
You’re quite right; it was inadvertently omitted.

**Comment by growse** [comment]
Fixed in 2be7fad5

**Comment by MrMDavidson** [comment]
The latest version I'm seeing on the Android store is 2.4.12 from August 2023 (which is the same as the latest release on the Github releases page). Is this likely to be released soon?

**Comment by growse** [comment]
When it's ready.
