### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by toggledbits** [owntracks/android#737]
Does the "notification" action work as a returned `_type=cmd` response? I have not been able to coax a whimper out of the Android app even directly copy-pasting the example response from the booklet. Notifications are enabled for the app, also remote commands, etc.

* 21201
* 8.0.0   
* Samsung SM-G935V (Galaxy S7 Edge) h/w 0.7

**Comment by binarybucks** [comment]
Notifications are not supported

**Comment by toggledbits** [comment]
Is that future, or not going to? If not, reason? Seems like it would be really useful.

**Comment by jpmens** [comment]
We’’ve no plans to implement that.
