### ISSUE TITLE
User/pass should not be required if using client certificates

### ISSUE THREAD

**Issue by numericOverflow** [owntracks/android#739]
I have a backend Mosquitto server setup for client certs auth w/out need for user/pass.  If I leave the username and password blank in the Prefs->Connection->Identification settings, I get a toast notification error:

> Configuration Incomplete

but if I enter anything (invalid since server doesn't use user/pass) then app connects perfectly.

Both username and password fields in the app are set to always required, even though they really are not required if using a PKCS12 certificate.  Leaving either field blank results in the error message above, and OwnTracks app won't connect to MQTT server.

Please relax the user/pass requirement if there is a cert configured.

* **App build number**: 2.1.2 (21201)
* **Android version**: Android 9 (Pie)   (LineageOS 16.0)
* **Device**: LG G4

**Comment by binarybucks** [comment]
Try using the config editor to set `auth` to false. 
It's indeed something I did not consider in the validation of the GUI

**Comment by unrelentingtech** [comment]
Just set up owntracks with a client cert and did not encounter this issue, I guess this was fixed?

**Comment by growse** [comment]
Just tested this, and I think you're right. You should be able to connect to an MQTT endpoint without specifying a username/password, but specifying a client & root cert.

How you then configure the broker to authorize you without asserting a username is your problem :p

**Comment by jpmens** [comment]
>How you then configure the broker to authorize you without asserting a >username is your problem :p

Right. Thankfully Mosquitto has `use_subject_as_username`. :-)

**Comment by growse** [comment]
I *knew* there would be some sneaky setting!
