### ISSUE TITLE
No place picker and cannot insert minus before longitude

### ISSUE THREAD

**Issue by Dannys485** [owntracks/android#740]
whilst trying to input regions via android app, there is no place picker available nor can i input a minus sign before longitude value, am i missing something really silly??
-->

* **version 2.1.3**: 
* **Android version  9**:    
* **huawei p20 pro**:

**Comment by growse** [comment]
Google deprecated the place picker earlier this year, so we had to take it out.

I'm just trying the region UI here, and I too can't input a "-" sign. Looks like the number validation is a bit wonky.

**Comment by howi42** [comment]
If you try to enter a new region, it is not possible to delete or change the already existing coordinates.
If you try to delete the numbers one by one, you get strange results;
if you highlight the coordinate and try to enter a new one, Owntrack crashes.

**Comment by growse** [comment]
PR #752 should fix this.
