### ISSUE TITLE
"batt":0  on Samsung Galaxy A3 device

### ISSUE THREAD

**Issue by done7k** [owntracks/android#741]
Struggling with the battery level on my Android. The app is set with HTTP mode at the moment. The msg I am receiving seems has the tag "batt" but it is always zero, I tried to play with the "battery optimization whitelisting" option but it does not change anything. Is it something related to Galaxy phones? Will it help if I use MQTT instead?

2019-09-25 13:29:16 DEBUG (MainThread) 
[homeassistant.components.owntracks.messages] 
Decrypted payload: 
{
"_type":"location",
"acc":16,
"alt":202,
"batt":0,
"inregions":["mol"],
"lat":99.9999555,
"lon":88.8888777,
"t":"u",
"tid":"s3",
"tst":1569408192,
"vac":0,
"vel":0
}

* **App build number**: 2.1.3 (21302)
* **Android version**: V 7.0   
* **Device**: Sansung Galaxy A3 (216)

**Comment by ipod86** [comment]
My wife's Galaxy s20 has the same problem.  My S21 transmits the battery level.

**Comment by growse** [comment]
Thanks for following up and apologies for not responding to your initial issue.

Can you check to see if you have extended data reporting enabled?

![image](https://user-images.githubusercontent.com/378067/129784332-5b0e68dd-5c7e-48cd-9b6b-5a7832442351.png)

Enabling this populates the location messages with the battery level, status, connection type and connected WiFi details.

**Comment by ipod86** [comment]
That was it.  Many Thanks.  However, the description is not well met.  Possibly you can write something there.

**Comment by growse** [comment]
Point taken well - I'll keep this open until updated.
