### ISSUE TITLE
Owntrack Client does not work reliable with mosquitto 1.6.7

### ISSUE THREAD

**Issue by avanc** [owntracks/android#745]
* **App build number**: 2.1.2 (21201)
* **Android version**: 9
* **Device**: Motorola G7

After upgrade mosquitto (1.6.7 => 1.6.4) and libwebsockets (3.2.0 => 3.1.0), Owntracks does not work reliable anymore.
When I start mosquitto, the clients (in my case  start to connect and upload their positions (also queued positions). However, after some time it stales and no new position updates are received.
I could not find any error logs in mosquitto.

Note: Currently, I doubt that it is an Owntracks issue. But I want to use this ticket to collect and track my findings.

**Comment by jpmens** [comment]
Are we right in thinking that you are using OwnTracks with Websockets to connect to Mosquitto? If so, that's the part you should be looking at -- I've heard reports of trouble with libwebsockets.

**Comment by avanc** [comment]
No, I'm using _plain_ MQTT. I just mentioned libwebsocket, as I had to also downgrade it to fulfill package dependencies while downgrading mosquitto.

**Comment by avanc** [comment]
Just for informational purpose the changes from 1.6.4 to 1.6.7:
https://github.com/eclipse/mosquitto/compare/95bf4a2714811f688700b02d2eacded67879580f...afb6a1367436f878be93b402c5ddec7996ae1bfc

**Comment by jpmens** [comment]
What I would try to do in your case, as we've not had other reports, is to attempt to downgrade Mosquitto to the release you had (1.6.4), verify all is working as it was, and then slowly, upgrade through the releases to determine where it went wrong. It's a nuisance, but I don't see how else to get to the bottom of this.

**Comment by grheard** [comment]
@avanc What OS is your mosquitto 1.6.7 running on?

When 1.6.7 was released for Ubuntu 16 & 18 it was not compiled with systemd notify. As a result, mosquitto was being restart by systems about every 30s.

**Comment by avanc** [comment]
@grheard Thanks for the hint. But I'm using Arch Linux and the systemd journal does not show anything strange.

@jpmens Was also my next planed step. However, 1.6.5 ans 1.6.6 was never released for Arch Linux: https://archive.archlinux.org/packages/m/mosquitto/

I might try to compile the releases by myself.

**Comment by growse** [comment]
No issues here running OT on the emulator (API 28) connecting to the 1.6.7 mosquitto docker image over plain MQTT.

**Comment by growse** [comment]
Going to close awaiting any further details from @avanc.

**Comment by avanc** [comment]
I have the same problem with mosquitto 1.6.8 on Arch Linux.

**Comment by jpmens** [comment]
@avanc there’s not much we can do with that report, unfortunately. Please enable debugging on your Android app and simultaneously logging broker-side. We’ll need that data to attempt for find out what is happening.

**Comment by avanc** [comment]
Where do I find the logs after activating Debug in the settings? I looked ad data7/org.owntracks.android/cache/debug. However, the folder is still empty after running two hours in debug mode.

**Comment by binarybucks** [comment]
See https://owntracks.org/booklet/features/android/#debug-log

**Comment by avanc** [comment]
@binarybucks Thanks, I missed the restart of Owntracks.

**Comment by avanc** [comment]
Find attached the [mosquitto log](https://github.com/owntracks/android/files/4023813/mosquitto.log) as well as the [owntracks log](https://github.com/owntracks/android/files/4023815/owntracks_log.html.log).

At 12:35:31 I updated mosquitto from 1.6.4 to 1.6.8 and did a restart of the service. For about 8 minutes everything runs fine, but the last message from any of the devices is received at 12:43:52.

However, mosquitto doesn't give any clue that something went wrong.

**Comment by avanc** [comment]
I also cannot publish a new message using mosquitto_pub. So it is definitely an mosquitto issue. Nevertheless, I would be glad about some hints how to continue digging, as the debug output gives no clue.

**Comment by jpmens** [comment]
You cannot publish with mosquitto_pub? that sounds very untoward.

Can you try using a specific clientId so we see that in the logs?

```
mosquitto_pub -i SHELLCLIENT -h ...
```
