### ISSUE TITLE
OwnTracks reports correct location but wrong address

### ISSUE THREAD

**Issue by LarryTX** [owntracks/android#756]
* **App build number**: 2.1.3(21302)
* **Android version**: Samsung   
* **Device**: Samsung Galaxy J3 SM-J337U
I'm not sure how much can be done about this because Google shares the same problem, but I'll try. When I get home, OwnTracks reports that I am at what I'll call Address1. This is not my home address and is not my location. Address1 is about two blocks away from my home address which I'll call Address2. I have entered Address2 in the Android OwnTracks app as a region with the name Home. The problem is that Address1 and Address2 are shown as having the same lattitude and longitude on Google.

For what it's worth, google.com has long shown that I'm at Address1 when I am at Address2.

Is there any way that I can straighten this out on the app so that it will actually and accurate reflect when I am at home?

**Comment by growse** [comment]
There's no capability in the app to override the address received from the geocoder.

 Have you tried the alternative OpenCage geocoder available in the app preferences (under advanced)? Does that give a better result?

**Comment by LarryTX** [comment]
Many thanks. I hadn’t thought about OpenCage. I’ve opened an account, entered the API Key. We’ll see how it does tomorrow. Actually, on every other address, except my grocery store, OwnTracks was being very accurate. (The grocery store is the same problem. Google reports an address a few block away rather than the actual address.

Larry E. Lutz

**Comment by growse** [comment]
I have a similar experience to you - my home address is just not geocoded properly by Google's database. What's interesting is that I notice it changing over time, but never to the right one :)

**Comment by LarryTX** [comment]
That’s terribly encouraging! I tried out OpenCage. Works great except that it has a different wrong address, also just a block or two away. On top of that, in looking up Google directions, I must take “unnamed streets” to get from where I live to where Google and OpenCage think I live. In the case of Google, the street isn’t “unnamed”; it’s nonexistent. Recognize that my actual location isn’t in some outlying, rural hinterlands. It’s wedged in between Houston’s most affluent incorporated city (surrounded by City of Houston) and the Texas Medical Center. If you relied on Google’s directions, you’d never be able to find where I live. No wonder, on the only two times I’ve used Uber from here, the drivers have arrived totally perplexed. Needless to say, I’ll never use Google for my GPS.

Larry E. Lutz

**Comment by growse** [comment]
Looking at the OpenCage FAQ (https://opencagedata.com/faq), it looks like you can contact them if you think their data is wrong.
