### ISSUE TITLE
topic in HTTP mode

### ISSUE THREAD

**Issue by davcx** [owntracks/android#760]
Hi,
I'm a new owntracks user, and it is working very well.
Reading the documentation (traccar section booklet) it seems that in Private HTTP mode the topic should be present in order to permit the identification the device instead the TID. 
ie: 
{"lon":2.29513,"lat":48.85833,"_type":"location","tst":1497476456, "tid":"JJ"}
or
{"lon":2.29513,"lat":48.85833,"_type":"location","topic":"owntracks/jane/phone", "tid": "JJ"}

The documentation recommends using Private HTTP mode for Android 6 and above, but the topic is mentioned and descripted only for MQTT mode.
Is there any flag to add the topic in POST payload for this mode?
Thanks

**Comment by jpmens** [comment]
The _topic_ is not required for Traccar, IIRC; we used it in our iOS app to uniquely identify a payload.

**Comment by jpmens** [comment]
To clarify: you should be able to use HTTP mode with Android and the TID only with Traccar.

**Comment by davcx** [comment]
I agree that it is possible to use the owntrack's TID, though this is long only 2 chars instead on traccar the ID is 16 long.
My question because in the "owntrack's documentation of traccar I/F" there is a specific description with explicit screenshot and example of the topic OR tid use.
thanks for the clarification.

**Comment by jpmens** [comment]
I've just checked again: the topic is added in iOS only, and not in Android, sorry. (As https://github.com/owntracks/android/issues/512 indicates, there are no plans to do so.)
