### ISSUE TITLE
waypoints published under wrong? (inconsistent?) topic

### ISSUE THREAD

**Issue by otdftr** [owntracks/android#762]
When publishing waypoints from an Android device
- the topic used is `owntracks/<user>/<device>/waypoint`
- iOS app uses topic `owntracks/<user>/<device>/waypoints`
- according to the JSON logic and _type designator, IMHO it should always be `.../waypoints`
- would be nice to have it consistent for both platforms

Android App 2.1.3 / iOS App  13.0.2

**Comment by jpmens** [comment]
Thank you for the report. I confirm that iOS uses

```
owntracks/<user>/<device>/waypoints {"_type":"waypoints","waypoints": [ ]}
```
