### ISSUE TITLE
App doesn't start after reboot

### ISSUE THREAD

**Issue by RichardvanGestel** [owntracks/android#766]
The Owntracks app on Android does not start after a reboot, even though the 'Autostart on device' setting is on.

* **App build number**: 2.1.3 (21302)
* **Android version**: 9  
* **Device**: Lenovo TB-X605F

**Comment by RichardvanGestel** [comment]
Problem solved. There is a special app.

**Comment by pszafer** [comment]
What is special app? Is it some Android feature?

**Comment by RichardvanGestel** [comment]
It's a special Lenovo-app named Tablet Manager.

Op vr 6 dec. 2019 12:15 schreef Pawel <notifications@github.com>:
