### ISSUE TITLE
Regions - cannot add custom Lat/Lon

### ISSUE THREAD

**Issue by liquid-motion** [owntracks/android#767]
* **App build number**: 2.1.3 (21302)
* **Android version**: Android 9.1.0 
* **Device**: Huawei P30 pro

When trying to enter new geofence Region, cannot change the pre-populated lat/lon settings. Only Region name and radius can be edited. When I try to remove the pre-populated numbers, the phone goes back to the app drawer.

This make it impossilbe to enter a Region unless you're actually at the location you want.

**Comment by growse** [comment]
This should be fixed by https://github.com/owntracks/android/pull/752. Just pending a new release.
