### ISSUE TITLE
Offline mode for app

### ISSUE THREAD

**Issue by jpds** [owntracks/android#768]
Follow up from https://github.com/owntracks/android/issues/467

This app requires an offline/airplane mode. For example, I could be frequently travelling and without a persistent data connection, but I would still like to record my steps and have them uploaded to a server at a time of my choosing.

This would also require making the local queue durable, a restart / app close shouldn't clear the local queue.

**Comment by jpmens** [comment]
There’s a lot of _requires_ in that comment...

As #467 already notes:

> The apps already store messages until a connection can be established.

If you don’t have a persistent connection the apps will upload your locations as soon as they can connect.

**Comment by jpds** [comment]
> If you don’t have a persistent connection the apps will upload your locations as soon as they can connect.

I lost half a days worth of tracking because I needed to reboot my phone yesterday.

**Comment by growse** [comment]
The queue should now be persisted between app / device restarts, fixed in b22b2edb71e352eed72d99c89f00396a742641ce
