### ISSUE TITLE
"move" mode updates are too slow

### ISSUE THREAD

**Issue by gardiol** [owntracks/android#778]
* **App build number**: 2.1.3 (21302)
* **Android version**: Android 5.0.2
* **Device**: Samsung Core Prime LTE

I use owntracks as a "pet GPS" tracker. I hooked up an old phone on my dog collar in a waterproof pouch and i am using OnwTracks to know where she is. 

Unfortunately "move" mode let GPS switch off for too long and the next point takes a long long time to get a fix. This is always in the open (meadows or at most light woods), and the phone with another tracking software (Alpine Quest) has flawless GPS reception. When using OwnTracks, the resulting track is jumpy and fragmented.

My guess is that one point every 30 seconds is way too far apart... Constant GPS on or at least configurable intervals would be much more useful.

Also, a dog moves way faster than an human and on much more irregular directions (where the rabbits go... :) )

Is there anything i can try?

**Comment by growse** [comment]
I'm generally against providing more configuration options to end users, but I think there may be a case to make for allowing users to customize the intervals specified to the runtime in each mode. The challenge here will be exposing this to the user in a non-confusing way. Experience shows that the way the location fixes work right now is already too confusing.

An initial option might be to bury everything under "Advanced Options" and see if that at least helps to solve the problem, then work on making the config UI more intuitive.

**Comment by gardiol** [comment]
While I tend to agree with you, some settings should be available, albeit under a "advanced" section, any time they can expand or improve the user experience. 

Maybe even a text only editable setting like the ones in the "configuration management" of the app could be fine. 






Il 3 febbraio 2020 11:31:46 CET, Andrew Rowson <notifications@github.com> ha scritto:
>I'm generally against providing more configuration options to end
>users, but I think there may be a case to make for allowing users to
>customize the intervals specified to the runtime in each mode. The
>challenge here will be exposing this to the user in a non-confusing
>way. Experience shows that the way the location fixes work right now is
>already too confusing.
>
>An initial option might be to bury everything under "Advanced Options"
>and see if that at least helps to solve the problem, then work on
>making the config UI more intuitive.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/owntracks/android/issues/778#issuecomment-581344822

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by growse** [comment]
I should have some time today to work on some of the open issues, let me see if I can get a PR together that lets the interval be more configurable.

**Comment by gardiol** [comment]
That would be awesome, I can test it if you can provide a test build.



Il 3 febbraio 2020 11:45:55 CET, Andrew Rowson <notifications@github.com> ha scritto:
>I should have some time today to work on some of the open issues, let
>me see if I can get a PR together that lets the interval be more
>configurable.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/owntracks/android/issues/778#issuecomment-581350911

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by growse** [comment]
Added this now, so closing. You can either generate an APK yourself or wait for the next beta release to test.
