### ISSUE TITLE
Please document Remote Commands

### ISSUE THREAD

**Issue by jgoerzen** [owntracks/android#782]
There is a "remote commands" setting in the Android app, but almost no documentation for it in the Booklet.  (I found "Remoteconfig" but a search for "remote commands" did nothing.)

The documentation should cover:

* What commands are possible (and any possible security risks for them)
* Are they encrypted?
* Can one send a remote command using the app or do you have to do it otherwise?
* Is there any benefit to having this enabled with friends?  (Ie, can you tap a button to request the friend's device to update its location immediately)

**Comment by xqyang2008** [comment]
I have the same question

**Comment by jpmens** [comment]
Remote commands are documented https://owntracks.org/booklet/tech/json/

If you think this isn’t sufficient we’ll gladly take constructive suggestions and PRs on how to improve the documentation

**Comment by xqyang2008** [comment]
> Remote commands are documented https://owntracks.org/booklet/tech/json/
> 
> If you think this isn’t sufficient we’ll gladly take constructive suggestions and PRs on how to improve the documentation

Thanks, I know the format of remote commands.  I have read all the documents, but I don't know where to send the remote commands.  Need other MQTT clients？ Why not design a command input window on the interface, or a button that can immediately update the device location?

**Comment by growse** [comment]
> 
> 
> > Remote commands are documented https://owntracks.org/booklet/tech/json/
> > If you think this isn’t sufficient we’ll gladly take constructive suggestions and PRs on how to improve the documentation
> 
> Thanks, I know the format of remote commands. I have read all the documents, but I don't know where to send the remote commands. Need other MQTT clients？ Why not design a command input window on the interface, or a button that can immediately request the device location?

From the booklet link:

> In MQTT mode apps subscribe to:
>    `owntracks/user/device/cmd` if remote commands are enabled

Sending a command to that MQTT topic will cause the device that's subscribing to that topic to act on that command (if that device has remote commands enabled).

It's not clear what you mean by a "command input window on the interface"?

**Comment by xqyang2008** [comment]
> > > Remote commands are documented https://owntracks.org/booklet/tech/json/
> > > If you think this isn’t sufficient we’ll gladly take constructive suggestions and PRs on how to improve the documentation
> > 
> > 
> > Thanks, I know the format of remote commands. I have read all the documents, but I don't know where to send the remote commands. Need other MQTT clients？ Why not design a command input window on the interface, or a button that can immediately request the device location?
> 
> From the booklet link:
> 
> > In MQTT mode apps subscribe to:
> > `owntracks/user/device/cmd` if remote commands are enabled
> 
> Sending a command to that MQTT topic will cause the device that's subscribing to that topic to act on that command (if that device has remote commands enabled).
> 
> It's not clear what you mean by a "command input window on the interface"?
Sorry, my English is not that good。What I mean is: add a command input box to the GUI of the Android app to enter the command text I want to send.
For example, I want to send a "_type":"cmd","action":"reportLocation" command to a certain device witch has subscribed the topic, how can I send this command through the Android app?

**Comment by xqyang2008** [comment]
> > > Remote commands are documented https://owntracks.org/booklet/tech/json/
> > > If you think this isn’t sufficient we’ll gladly take constructive suggestions and PRs on how to improve the documentation
> > 
> > 
> > Thanks, I know the format of remote commands. I have read all the documents, but I don't know where to send the remote commands. Need other MQTT clients？ Why not design a command input window on the interface, or a button that can immediately request the device location?
> 
> From the booklet link:
> 
> > In MQTT mode apps subscribe to:
> > `owntracks/user/device/cmd` if remote commands are enabled
> 
> Sending a command to that MQTT topic will cause the device that's subscribing to that topic to act on that command (if that device has remote commands enabled).
> 
> It's not clear what you mean by a "command input window on the interface"?

Sorry, my English is not that good。What I mean is: add a command input box to the GUI of the Android app to enter the command text I want to send.
For example, I want to send a "_type":"cmd","action":"reportLocation" command to a certain device witch has subscribed the topic, how can I send this command through the Android app?

**Comment by xqyang2008** [comment]
> > > > Remote commands are documented https://owntracks.org/booklet/tech/json/
> > > > If you think this isn’t sufficient we’ll gladly take constructive suggestions and PRs on how to improve the documentation
> > > 
> > > 
> > > Thanks, I know the format of remote commands. I have read all the documents, but I don't know where to send the remote commands. Need other MQTT clients？ Why not design a command input window on the interface, or a button that can immediately request the device location?
> > 
> > 
> > From the booklet link:
> > > In MQTT mode apps subscribe to:
> > > `owntracks/user/device/cmd` if remote commands are enabled
> > 
> > 
> > Sending a command to that MQTT topic will cause the device that's subscribing to that topic to act on that command (if that device has remote commands enabled).
> > It's not clear what you mean by a "command input window on the interface"?
> 
> Sorry, my English is not that good。What I mean is: add a command input box to the GUI of the Android app to enter the command text I want to send.
> For example, I want to send a "_type":"cmd","action":"reportLocation" command to a certain device witch has subscribed the topic, how can I send this command through the Android app?

Can one send a remote command using the app or do you have to do it otherwise?
Can you tap a button to request the friend's device to update its location immediately)

**Comment by growse** [comment]
Ah - I understand now. Thanks for clarifying.

This can't be done today, but is potentially something worth considering in future. Is it just `reportLocation` commands you'd be looking to send, or would you want something more complex than that?

**Comment by xqyang2008** [comment]
I just want to send the "reportLocation" command.

**Comment by xqyang2008** [comment]
But I found that the "reportLocation" command does not seem to have much effect.  Because the background service is not connected to the mttq broker in real time, it seems to connect when it needs to send a message, so when the device receives the "reportLocation" command, it is actually preparing to send a location message.

**Comment by growse** [comment]
The device wakes up periodically to establish a keepalive with the MQTT broker - regardless of whether there's a location to be sent or not. But there's no guarantee that the connection is permanently established - Android might kill the connection if it feels like it. Hence the reason for the periodic keepalive.

As above, it's worth considering the functionality to send specific commands to specific contacts in the future, but it'll take a bit of work and there's a few bugs to be fixed first. Will put it on the backlog.
