### ISSUE TITLE
Please document locatorPriority

### ISSUE THREAD

**Issue by jgoerzen** [owntracks/android#783]
Over at https://owntracks.org/booklet/features/location/, locatorPriority is mentioned, but the values are not.  It defaults to 2 on my fresh installation.  A Google reveals https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest.html#PRIORITY_LOW_POWER, which identifies various constants, all of which are >= 100.  What does "2" mean?  Does Owntracks implicitly add 100 to the value here?  Did I find the entirely wrong place?

**Comment by boogymantoo** [comment]
The current documentation of "configuration" includes the following:
locatorPriority source/power setting for location updates (Android/integer/)
0 NO_POWER / best accuracy possible with zero additional power consumption (Android)
1 LOW_POWER / city level accuracy (Android)
2 BALANCED_POWER / block level accuracy based on Wifi/Cell (Android)
3 HIGH_POWER / most accurate accuracy based on GPS (Android)

( So I presume this issue can actually be closed )

**Comment by Dopeyr** [comment]
I added a PR for this (and a few other clarifications) https://github.com/owntracks/booklet/pull/54

**Comment by jpmens** [comment]
Thank you very much, @Dopeyr; I've merged that PR. Closing this now.
