### ISSUE TITLE
Please support a minimum time between updates

### ISSUE THREAD

**Issue by jgoerzen** [owntracks/android#784]
The documentation at https://owntracks.org/booklet/features/location/ describes locationInterval, which is the maximum time between new fixes.  It states that data from other apps is published as soon as it arrives, but "at most every 10 seconds."  Please make this 10 seconds configurable.

locatorDisplacement may help but is not particularly great in general.  Perhaps updates are still desirable even if a device hasn't moved much (eg, person is on foot, keeping battery updated, etc.)  Also the timestamp is often relevant (a device is still at a particular place 8 hours later rather than just knowing it was there yesterday, for instance)  However, every 10 seconds would be an unnecessary drain on battery for both the sender and any recipients.  A 5 minute minimum would probably be fine for my purposes.

**Comment by growse** [comment]
The location interval in move mode is now configurable.
