### ISSUE TITLE
I'm sure I've moved into (or out of) a region, but OwnTracks isn't reporting that.

### ISSUE THREAD

**Issue by auriculaire** [owntracks/android#786]
This seems to be a frequent question (it's in the FAQ https://owntracks.org/booklet/faq/, but with no answer).

Apart from using Move Monitoring mode to force frequent updates, is there a way to get this working? If it's a question of Owntracks not getting notified, maybe a new trigger of "network changed" (e.g. connecting/disconnecting to/from home/office wifi) could be used to force an update?

**Comment by jpmens** [comment]
Transferred to Android issue tracker.

**Comment by linusg** [comment]
> latest version, I suppose

Please go into the app -> Preferences -> Information, look up the actual version and report it here, as well as the version of Android you're using.

Try to exclude OwnTracks from Android's battery optimisation (ensure it's working by going to the "Status" page within the app) - does that solve the problem?

Please also post you configuration, visible under "Preferences -> Configuration management". Exclude private information, of course.

**Comment by auriculaire** [comment]
Owntracks 2.1.3 (21302)
Android 10 (QQ1A.200205.002) on a Google Pixel 3A

[config.otrc.txt](https://github.com/owntracks/android/files/4193066/config.otrc.txt)

**Comment by petersohn** [comment]
I have the same problem. The location is not updated by OwnTracks. However, if I open my navigation app, then OwnTracks will update my location.

Same version (2.1.3 (21302)), Samsung Galaxy A8 (SM-A530F), Android 9 (A530FXXS9CSL5).

**Comment by growse** [comment]
> I have the same problem. The location is not updated by OwnTracks. However, if I open my navigation app, then OwnTracks will update my location.
> 
> Same version (2.1.3 (21302)), Samsung Galaxy A8 (SM-A530F), Android 9 (A530FXXS9CSL5).

How is this related to the region issue that @auriculaire initially raised?

**Comment by dannycohn** [comment]
Makes sense. If there's anything that I can do to contribute to move that along, let me know. I'm happy to help
