### ISSUE TITLE
Dark Theme / Night Mode

### ISSUE THREAD

**Issue by ktpx** [owntracks/android#787]
Dark theme / Night mode would be a much welcome addition to this app.

**Comment by linusg** [comment]
Agreed. I'd be happy to work on this.

**Comment by growse** [comment]
I think this should as simple as adding in a new `styles.xml` and then providing a preference to toggle it. I'll see if I can just get a quick stub together on a branch for the preference toggle, and then we can update the actual style.

**Comment by ktpx** [comment]
No progress on this?

**Comment by growse** [comment]
Added in c9ba408010226296a16397329964b69cfa36c0eb
