### ISSUE TITLE
Stops communicating via MQTT; says "connecting"

### ISSUE THREAD

**Issue by jgoerzen** [owntracks/android#791]
I've now seen this issue twice, on two different phones.

Owntracks will simply stop communicating via MQTT.  It will not receive events, and it will not transmit locations.  The swipe-down persistent notification is dated 14 hours ago and just says "Connecting".  It showed no update from friends over that time.

Opening up the app doesn't cause it to transmit.  Nor does disabling wifi, requesting a manual packet transmission, or going into airplane mode and returning.  The only thing that solves this is a Force Stop.

* **App build number**: 2.1.3 (21302)
* **Android version**: 10
* **Device**: Pixel 2 XL

**Comment by growse** [comment]
Can you share the debug log?

**Comment by jgoerzen** [comment]
I've got it capturing now.  Sadly it wasn't in debug mode when that happened, but I did turn it on before I did the force stop, so once it recurs I'll post it here.

**Comment by jgoerzen** [comment]
I have now had the problem recur and captured a debug log.  This time, it eventually managed to reconnect but it was still nonresponsive for 13 hours.  The debug log is huge, however, and contains various sensitive information (names of regions, coordinates, geocoded addresses, etc.)  Is there a premade script to anonymize it by any chance?  (Or a less-public place I could send it?)

**Comment by jpmens** [comment]
You can send it to support at OwnTracks.org

**Comment by jgoerzen** [comment]
Thanks.  I sent the file as well as some supporting information to you there.
