### ISSUE TITLE
Can't disable geocoding and associated information leak

### ISSUE THREAD

**Issue by jgoerzen** [owntracks/android#794]
Owntracks is using a service to geocode addresses, presumably Google by default.  As my point in using Owntracks is to stop location leakage to Google, this is not particularly desirable.

According to https://owntracks.org/booklet/tech/json/, there is a notificationGeocoder boolean that perhaps could disable this.  However, no such setting is visible in the configuration editor, and trying to add it has no effect.

It should be carefully documented, for both Android and iOS, how to completely disable location leakage to third parties.

* **App build number**: 2.1.3 (21302)
* **Android version**: 10
* **Device**: Pixel 2 XL

**Comment by jpmens** [comment]
On Android you can configure `opencageApiKey` to use an alternative geocoder. I think some of the values aren’t visible in the editor but they can be set via OTRC.

These two, specifically, exist for Android only; on iOS we cannot disable reverse geocoding.

**Comment by jgoerzen** [comment]
Thanks -- I did see the Opencage support, but it's not that I want to
switch to them; I just want to disable that stuff entirely.

**Comment by linusg** [comment]
The `notificationGeocoder` functionality was removed in https://github.com/owntracks/android/commit/95582a5410523757a9f09f647b44b50b73a54fa2, although I don't know why. It used to be a toggle switch preference.

**Comment by jpmens** [comment]
Closing as solved in #796
