### ISSUE TITLE
Behavior with location tracking off

### ISSUE THREAD

**Issue by ktaragorn** [owntracks/android#797]
The issue is with my wifes phone, according to her, her location setting was disabled globally as of 29th feb (~4days ago) and yet the last report I have from her phone shows 1) The wrong location (i.e location at the time the setting was disabled) 2) Time stamp earlier today ~3 hrs ago 3) Accuracy of 29 meters.
I am not sure if this is a quirk of her phone.. I use the exact same config as hers (on Xiaomi Mi A2 Lite) and my accuracy is 500 m always.

Would ignore stale locations help here? I am wondering how I can make my home automation more resistant to her just disabling her location..

* **App build number**: 2.1.3
* **Android version**: 9   
* **Device**: Redmi 4x

**Comment by growse** [comment]
I think we've seen some issues on Redmi devices in the past with how they expose locations through to apps that request it.

Stale (as in, the timestamp of the fix given to the app is too far behind the current timestamp) locations should be dropped. If OT publishes a fix, it's pretty likely that the device gave it a fix that was recent, or the device's current timestamp is doing something strange. Could you enable debug logging and try and re-create, then attach (or send) the dump through?

**Comment by jpmens** [comment]
@ktaragorn is this now solved? I believe we're expecting your debug log ...

**Comment by ktaragorn** [comment]
With the current situation, its hard to debug since she is staying at home :| ill try to get the log soon.

**Comment by ktaragorn** [comment]
I havent been able to replicate, and we have now replaced the phone, gonna close this for now
