### ISSUE TITLE
feature request drop Google play services requirement

### ISSUE THREAD

**Issue by nutpantz** [owntracks/android#798]
Not every one wants Google in their lives... Please drop the Google play services requirement.

**Comment by jpmens** [comment]
Are you quite sure you want to use Android?

**Comment by binarybucks** [comment]
Sure, submit a PR to rip out all the location code and replace it with a working alternative

**Comment by nutpantz** [comment]
I have over 250 apps on 4 devices and all work fine without Google play services..
If you want to use proprietary code that's up to you.. don't pretend you have to.

Maybe you should switch to Apple and be forced into their ecosystem.

**Comment by growse** [comment]
As ever, pull requests welcome.
