### ISSUE TITLE
Issue with OwnTracks cards and friends...

### ISSUE THREAD

**Issue by mrose17** [owntracks/android#799]
* **App build number**: 2.1.3 (21302)
* **Android version**: 10
* **Device**: Pixel 3a XL

i have one user that has an OwnTracks card. It displays as expected on iOS: 
![IMG_0099](https://user-images.githubusercontent.com/400552/76153080-18c24580-6095-11ea-8d09-762d164ca754.png)

however on Android, the entry is duplicated:
![Screenshot_20200307-164203](https://user-images.githubusercontent.com/400552/76153084-2ed00600-6095-11ea-88d0-19a4bc8efa50.png)
i.e., "Driver 14" and the image are from the card which has a "zero-valued" timestamp (12/31/69), and the "14" appears to be a duplicate but with an older timestamp (compare to the iOS value).

any ideas as to what i'm doing wrong? thank you!

**Comment by binarybucks** [comment]
Try force quitting the app and starting it again. I've seen the issue before but haven't been able to reproduce it yet

**Comment by mrose17** [comment]
alexander - hello again (after N years): a force-quit didn't fix it. nor did deleting the app and re-installing it. if you wish, i am happy to send you the config file that i am using so you can debug it. it's on a development server, so i'm not worried about anything breaking (-;

if so, drop me an email -- mrose17@gmail.com

thanks!

**Comment by growse** [comment]
@mrose17 Does this still happen on the latest version?

**Comment by mrose17** [comment]
I no longer hav an android phone with which to test, so let me close the issue! Thank you for the follow-up.
