### ISSUE TITLE
"tst" field reports wrong time.

### ISSUE THREAD

**Issue by bwims** [owntracks/android#804]
* **App build number**: 2.1.3 (21302)
* **Android version**: 9
* **Device**: Huawei P Smart 2019

According to the Owntracks booklet, tst is the UNIX epoch timestamp in seconds of the location fix .

The following is cut and paste from a Node-Red debug output of the JSON details sent back during a walk today.  Notice that the time of the message was 3/24/2020, 5:19:43 PM (GMT - I am in the UK) - but the Unix epoch time translated to 3/24/2020, 6:49:58 AM [UTC0]

Since UTC0 = coordinated universal time with no summer time shift, right now that means GMT.  So the "tst" time is out by 10hours and 30mins, but the walk only lasted about half an hour! :)

Am I missing something here?

Otherwise, it's great app!

3/24/2020, 5:19:43 PM node: 59e04388.27fe4c
owntracks/DVES_USER/Huawei : msg : Object
object
topic: "owntracks/DVES_USER/Huawei"
payload: object
_type: "location"
acc: 15
alt: 0
batt: 100
conn: "w"
lat: 51.2020973
lon: 1.2673315
tid: "MW"
tst: 3/24/2020, 6:49:58 AM [UTC0]
vac: 0
vel: 0
qos: 1
retain: true
_msgid: "2a5e6210.7d52ae"

**Comment by bwims** [comment]
1. 1585032598

2.  Preceding message: 1585066388 .  Full copy below - also with a big time divergence from a different device (2 people on the same walk).
  No Succeeding messages, that was the last one.
3.  That is a good point.  I have not had a lot of experience with this app so far.  I will perform some tests,  

Apologies in advance if I have misunderstood the situation!

**Comment by bwims** [comment]
This is the second message referred to above
3/24/2020, 5:19:43 PMnode: 59e04388.27fe4c
owntracks/DVES_USER/zplay2 : msg : Object
object
topic: "owntracks/DVES_USER/zplay2"
payload: object
_type: "location"
acc: 13
alt: 0
batt: 38
conn: "w"
lat: 51.2020854
lon: 1.2673564
tid: "BW"
tst: 3/24/2020, 4:13:08 PM [UTC0]
vac: 0
vel: 0
qos: 1
retain: true
_msgid: "8a2cfaab.526bf8"

**Comment by jpmens** [comment]
@bwims please do test further, and if you see something untoward don't hesitate to tell us. If possible provide is with the raw JSON data as published by the apps; we can't really work with the NodeRed data you are showing us.

**Comment by growse** [comment]
>     2. Preceding message: 1585066388 .  Full copy below - also with a big time divergence from a different device (2 people on the same walk).
>        No Succeeding messages, that was the last one.

Ah - I should have been clearer. Do you know what the timestamp of the preceding message *from your device* was, not that which was received by NodeRed. I'm trying to figure out if OT on a single device is sending messages out of order - I believe that for the same message type, `tst` should always increase. 

As @jpmens indicates, if you can get hold of the raw JSON that's being put onto MQTT by the device, that'd be useful.

**Comment by bwims** [comment]
All is well.  I'm sorry to have troubled you.  It was due to a misunderstanding on my part of the mechanics of reporting.  My test data follows, and I assume you will close this issue.  Many thanks for your speedy and helpful response!

-------------------------------------------------------------------------------

First 2 records generated by cycling through the reporting modes, landing on manual.  Each record preceded by time it appeared in Node Red debug log, and how the tst time was translated.   (NB There is a 15 second diff between my phone and my PC)

3/25/2020, 2:02:38 PM tst: 3/25/2020, 2:02:23 PM [UTC0]
{"_type":"location","acc":14,"alt":0,"batt":90,"conn":"w","lat":51.2020889,"lon":1.2673664,"tid":"BW","tst":1585144943,"vac":0,"vel":0}

3/25/2020, 2:02:39 PM tst: 3/25/2020, 2:02:25 PM [UTC0]
{"_type":"location","acc":14,"alt":0,"batt":90,"conn":"w","lat":51.2020889,"lon":1.2673664,"tid":"BW","tst":1585144945,"vac":0,"vel":0}

The next two were created by manual publish trigger.  tst does not change which makes sense.

3/25/2020, 2:05:34 PM tst: 3/25/2020, 2:02:28 PM [UTC0]
{"_type":"location","acc":14,"alt":0,"batt":90,"conn":"w","lat":51.2020625,"lon":1.2673693,"t":"u","tid":"BW","tst":1585144948,"vac":0,"vel":0}

3/25/2020, 2:11:45 PM tst: 3/25/2020, 2:02:28 PM [UTC0]
{"_type":"location","acc":14,"alt":0,"batt":90,"conn":"w","lat":51.2020625,"lon":1.2673693,"t":"u","tid":"BW","tst":1585144948,"vac":0,"vel":0}

Finally, I cycle through the reporting modes again, and tst appears to be correct 

3/25/2020, 2:18:30 PM tst: 3/25/2020, 2:18:15 PM [UTC0]
{"_type":"location","acc":14,"alt":0,"batt":89,"conn":"w","lat":51.2020851,"lon":1.2673577,"tid":"BW","tst":1585145895,"vac":0,"vel":0}

**Comment by jpmens** [comment]
Glad to hear you got it working, and thanks for reporting back.
