### ISSUE TITLE
How to create waypoints?

### ISSUE THREAD

**Issue by bwims** [owntracks/android#805]
This is really a documentation clarification:  

In the booklet, under Waypoints, it says:

"Adding on Android
On Android, waypoints can be configured on a separate activity. Coordinates for the geographical region can be entered by hand or by using the place picker."

What is the "separate activity" ?  I cannot see any way of creating a waypoint on the Android.
Sorry to be such a noob!

**Comment by jpmens** [comment]
Do you see this `+` on the top right?

![jmbp-6257](https://user-images.githubusercontent.com/60706/77561289-cb304000-6ebe-11ea-8723-36ce46fa8a45.png)

**Comment by bwims** [comment]
Yes, but I assumed a radius was required (I now know otherwise)

So is a radius of zero the determining difference between a waypoint and a region?  To be fair, this isn't clear from the booklet (or I missed it).

I notice the JSON thinks regions are Waypoints...
{"_type":"waypoint","desc":"test2","lat":51.2020849,"lon":1.267357,"rad":100,"tst":1585163944}

Isn't this a little confusing? 

Suggestion: Why not call it Regions/Waypoints? Maybe make if clear that radius is only used for geofencing?

Again, sorry for being a noob! :)

**Comment by jpmens** [comment]
It is highly likely that it was I who originally created this confusion by using two different terms. OwnTracks uses the terms interchangeably, and I will admit this is confusing.

If you can think of a decent phrasing for the Booklet and care to submit a PR I’ll gladly take it.

**Comment by bwims** [comment]
Argh!  I'm much better at finding problems than fixing them! :)   (I'm also not experienced in submitting PRs.... )   If and when I become expert at using Owntracks and fully to grips with the documentation, I might have a go!  Until then, thanks for putting up with me :)

Case closed!

**Comment by jpmens** [comment]
Small clarification added to Booklet; thanks for pointing this out.

**Comment by BrianHepler** [comment]
What is the "place picker"? I can see the means to manually enter coordinates as indicated in the screenshot (thank, jpmens!). I see no means of adding a region beyond this method.

**Comment by growse** [comment]
The place picker was a feature that was deprecated by Google back last year, and their new API doesn't support this functionality. We're working on alternatives, but for the moment it might be better to take that bit out of the booklet.
