### ISSUE TITLE
OwnTracks Internationalization

### ISSUE THREAD

**Issue by mekhaba** [owntracks/android#817]
Hello, 
How can I choose between translation pragmatically  please ?
In fact, i added string.xml for FR translation and I did translation. now I want to load this translation, how can I did it please ? 
can you help me ? 
thanks in advance.

**Comment by growse** [comment]
Hi! You can either open a pull request with your French(?) version of `strings.xml` and we can review and fill in anything extra that's needed, or you can email support@owntracks.org (or even attach it here?) and we'll try and add it to the next build.

One of the challenges with new localizations is keeping them maintained as we add / change new features, so we'll just need to be sure we have a reliable French resource available to us going forward.

**Comment by mekhaba** [comment]
Hi, 
The Strings.xml for French language has been attached.
For information, I can help also for Arabic language if needed.

How can choose/change between different languages dynamically ( with code )  ?
thanks in advance.

[values-fr.zip](https://github.com/owntracks/android/files/4567583/values-fr.zip)

**Comment by growse** [comment]
Thanks for this, I'll take a look. 

I *believe* that the locale is taken from the device settings. Adjusting the device "language" (under "Languages & Input" on the latest Android) *should* toggle the UI. I've not tested this though, so apologies in advance if this isn't right.

**Comment by mekhaba** [comment]
Yes RTL, is great feature and most of applications support it.
If all right let me know please.
Thanks.

**Comment by jpmens** [comment]
@mekhaba thank you very much for the contribution. Could you kindly verify my comments on #820 ?

**Comment by jpmens** [comment]
@mekhaba never mind, thank you; I think we've got it now. Thank you again.
