### ISSUE TITLE
Import config file fails with nullpointer exception (if no waypoints array in file)

### ISSUE THREAD

**Issue by boogymantoo** [owntracks/android#818]
* **App build number**: 21302
* **Android version**: issue present on 5.1 as well as 9   
* **Device**: Motorola Moto G (Android 5.1) and Samsung S9+ (Android 9)

When trying to import a configuration file that contains *no* waypoints, I get an error. If it would be important: I have no waypoints defined in the app either. Simply adding an empty waypoints array works around the issue. Here-below is a copy-paste taken from the debug-log.

za mei 02 2020 at 12:09:42:335 p.m./6/LoadActivity :    load exception java.lang.NullPointerException: Attempt to invoke virtual method 'int org.owntracks.android.support.MessageWaypointCollection.size()' on a null object reference at org.owntracks.android.ui.preferences.load.LoadViewModel.setConfiguration(LoadViewModel.java:48) at org.owntracks.android.ui.preferences.load.LoadActivity.extractPreferences(LoadActivity.java:169) at org.owntracks.android.ui.preferences.load.LoadActivity.onActivityResult(LoadActivity.java:134) at android.app.Activity.dispatchActivityResult(Activity.java:8292) at android.app.ActivityThread.deliverResults(ActivityThread.java:5090) at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138) at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:7811) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by growse** [comment]
I *think* we've fixed this in the latest. I've got a test case here that seems pretty happy to treat an empty list of waypoints as just that. Please re-open if this reoccurs.

**Comment by growse** [comment]
Thanks! Will be in the next release.
