### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by smurfix** [owntracks/android#82]
Would it be possible to add this app to the F-Droid repository?

**Comment by jpmens** [comment]
Sorry, but we don't have the resources to do this at the moment.

**Comment by binarybucks** [comment]
We're now considering this if we can find suitable replacements for the Google Play Services without crippling functionality.

**Comment by hoedlmoser** [comment]
you can also just create your own repo https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo as I have done quick and dirty especially for owntracks http://fdroid.rekmp.net/repo to be up2date on family devices.

**Comment by friesenkiwi** [comment]
I guess, that would only be the second-best option, also it requires more and additional effort...

**Comment by mvdan** [comment]
Hey! F-Droid dev here. If you want to publish on our main repo, which requires building from source, you'd have to get rid of the third party maven repositories (we only allow maven central and jcenter for now) and the binary aar in `libs/`.

Alternatively, like other say, you can just set up your own F-Droid repository. You can just feed it apks directly, without having to worry about building your app with our fdroidserver tools.

**Comment by binarybucks** [comment]
Thanks for your response. Please see my comment over at #88 so we don't have to keep an eye on two threads.

**Comment by egils-consulting** [comment]
How is the status now? Have you removed google play services and the maven stuff mentioned above?

**Comment by jpmens** [comment]
There has been no change.

**Comment by egils-consulting** [comment]
Would you accept a PR? What is aar used for? What is pulled from the maven repos?

**Comment by growse** [comment]
> 
> 
> Would you accept a PR? What is aar used for? What is pulled from the maven repos?

PRs always welcome. Acceptance subject to review of course.

**Comment by poisonborz** [comment]
Any updates on this? A lot of people - especially the target group of OwnTracks, who don't want to depend on FAANG for such features - use FDroid, or Android phones that don't even come with GPlay.

**Comment by mnalis** [comment]
FYI, owntracks 2.5.0 seems to  have finally landed in F-droid few days ago

**Comment by growse** [comment]
Yep, we're back.
