### ISSUE TITLE
Please allow separate field to specify client id

### ISSUE THREAD

**Issue by bwims** [owntracks/android#821]
* **2.1.3 (21302)**: 
* **8.0.0**:    
* **Moto Z2 Play**: 

I have an MQTT account with MyQTT .   It requires me to use my email address as a client ID in addition to a specific username and password.

Because the nature of Owntracks is to generate a clientId, which does not usually matter on public systems, the only way I can make a connection is to edit the config.otrc file, (which isn't anything like fun :)  

Would it be possible to provide a field in a future release where you can override the generated clientID ?    

I'm sure as the popularity of MQTT grows, this might come in useful for others.

Thanks!

**Comment by growse** [comment]
You can currently set this through the configuration management screen, which shows the complete configuration for the app. I'll do some work to expose this in the Config UI though and keep this issue open to track that.

**Comment by bwims** [comment]
Many thanks. That workaround is what I meant by editing the config file...not much fun on a phone :-)

**Comment by binarybucks** [comment]
Is this key not editable through the config editor?

**Comment by bwims** [comment]
Yes it is.  It's what I meant by editing the config file.  Just my sloppy
terminology!  Sorry!

B.
