### ISSUE TITLE
Entering Region Long/Lat has issues with zeros

### ISSUE THREAD

**Issue by BrianHepler** [owntracks/android#822]
* **App build number**: 2.1.3 (21302)
* **Android version**: 10, build QQ2A.200501.001.B2
* **Device**: Google Pixel 3

When entering a new region, the longitude and latitude have real problems with the number 0. Any time the cursor attempts to write a zero, it jumps to the beginning of the line.

To replicate: 

- Regions -> Add new region
- Give it any name
- Click to the right of the provided latitude, start backspacing over the decimals
- Observe that when you get to the last number (tenths) it inserts a zero and the cursor jumps to the beginning of the line.
- Click to the right of the zero (tenths) and enter two random numbers that are not zeros
- Click on the zero number on the keypad. Observe that the cursor has jumped to the beginning of the line
- Repeat for longitude.

**Comment by Dopeyr** [comment]
I'm experiencing this issue too. Is there a workaround?

**Comment by Dopeyr** [comment]
Copy and paste seems to be a workaround, but I don't know if this is related but I can't paste in negative longitude values. The minus sign is stripped.

**Comment by growse** [comment]
This is already fixed (https://github.com/owntracks/android/commit/4200df4e415eb339020fb798c7558885b0915093), but the fix hasn't been released yet.

**Comment by Dopeyr** [comment]
Thank you @growse

**Comment by BrianHepler** [comment]
Yes, indeed. Thank you for the update.

**Comment by kaysond** [comment]
@growse Is there a workaround for pasting negative numbers? I try to paste in something like "-117.5" to longitude but it strips the "-"
