### ISSUE TITLE
Support for older phones

### ISSUE THREAD

**Issue by compusolve-rsa** [owntracks/android#823]
**lower level api for old mobile (>android2.1) phones

The android app works well but fails to install on older devices. I got an old cm11 phone lying around that would be great as a tracking device, but a parsing error keeps popping up when I try to install the app.

**Comment by jpmens** [comment]
OwnTracks for Android requires version 5.0 of the OS.

**Comment by growse** [comment]
Supporting anything older than SDK21 (which came out December 2014) would require a significant effort to maintain.
