### ISSUE TITLE
Connect Bluetooth OBD2 device to Android phone

### ISSUE THREAD

**Issue by Baggerfahrer** [owntracks/android#825]
Hi Folks,

Many thx for the creation of this cool piece of Software. Very easy to set- Up!!

I want to Bring above mentioned use-case to reality, i have already an OBD2 Adapter connected to my Phone, incl. The Android App and an own hosted Server with owntracks running via docker.

Is there a way to Bring this Data from the sensor to owntracks?

Many thx for the Help!

**Comment by growse** [comment]
Hi - not currently. The only inputs are what the device provides in terms of Location (+ regions etc).

What sort of data are you looking to capture, and what are you hoping to do with it?

**Comment by Baggerfahrer** [comment]
thanks for the answer.

the use case is:
as owntrack is a system to control e.g. a fleet, cars, etc. i am also interested in the data about the devices incl. location and all the data owntracks delivers. 
e.g. the torque, the speed, the behaviour of the cars, etc. 
this data is valuable to get the actual "health" of the fleet (e.g. plan maintenance schedules) or monitor cars, drivers, etc.

i think these use cases are very interesting for potential customers of this piece of software.
as im "only" a private user, i want to bring the data to an influxdb -- grafana to monitor my cars and their conditons.

**Comment by growse** [comment]
I don't think this is really in scope for OT - we're just concerned with location.
