### ISSUE TITLE
Request: optional url to get map tiles from same server ip.

### ISSUE THREAD

**Issue by compusolve-rsa** [owntracks/android#826]
* **App build number**: 2.1.3(21302)
* **Android version**: 6
* **Device**: htc desire 816

Request to expose the map url in settings. Usage case is when the same ip for mqtt service provides a tileserver.

Example map url: http://ip-address:8080/styles/osm-bright/

**Comment by growse** [comment]
The map is currently Google Maps.

There is a plan to migrate to OSM at some point, but this isn't actively being worked on.
