### ISSUE TITLE
Cannot connect using TLS 1.3

### ISSUE THREAD

**Issue by mjforanVT** [owntracks/android#827]
I am trying to connect Owntracks to my Mosquitto broker with MQTT over TLS. I am able to connect using TLS 1.2 but when I change to 1.3 there is an SSL handshake error. I'm pretty sure this was working in the past but I recently upgraded both my phone and server so I can't test the old setup. I am able to connect to my broker with TLS1.3 from a different Android app so I don't think the fault is with my phone or broker.

[app_log.txt](https://github.com/owntracks/android/files/4664185/app_log.txt)
[broker_log.txt](https://github.com/owntracks/android/files/4664186/broker_log.txt)

* **App build number**: 2.1.3 (213002)
* **Android version**: 10, build# QQ2A.200501.001.B3   
* **Device**: Google Pixel 2

**Comment by growse** [comment]
Hmm, I'm having difficulty reproducing this. I've updated my broker to use `tls_version tlsv1.3` and the app is successfully publishing.

Can you connect to your broker using `mosquitto_sub` with the `--tls-version tlsv1.3` option?

**Comment by mjforanVT** [comment]
Yes, I am able to use mosquitto_sub/_pub on my broker with TLSv1.3 (but only when 1.3 is the version specified in the configuration file). When getting this to work I noticed the command requires the CA file to be specified. I'm using LetsEncrypt (not self-signed) so this typically isn't required. I did try specifying the CA file on OwnTracks as well but that didn't help. MQTTDash, the other Android app I'm using, has no problems connecting with either TLS version.

**Comment by growse** [comment]
Good news! I reproduced it!

So, it's because the MQTT library doesn't support TLS1.3: https://github.com/eclipse/paho.mqtt.java/issues/781 

There's a couple of options here:

1) Either replace paho (on the roadmap anyway)
2) Do something hacky. 

I'm going to see if I can make (2) work somehow, but I'm not optimistic.

**Comment by mjforanVT** [comment]
Thanks for following up! I'm surprised paho doesn't support TLSv1.3. I'm not even aware of any other libraries which could replace it. I feel like it would be easier to add TLSv1.3 to paho than to find and implement a new solution.

**Comment by growse** [comment]
I've a tentative fix. Just need to test it out on all the api versions (don't have an automated test for this yet).

It's not entirely on Paho - I can fix just by tweaking a custom socketfactory that I can supply to paho to init the MQTT connection. That said, paho's pretty not-very-often-updated, so we're on the lookouts for alternatives (HiveMQ is one option). 

Once I test, it'll hopefully be up on 2.2.1.
