### ISSUE TITLE
locatorPriority: zero-value not accepted

### ISSUE THREAD

**Issue by boogymantoo** [owntracks/android#828]
* **App build number**: 2.1.3 (21302)
* **Android version**: 5.1   
* **Device**: Motorola Moto G

Context:
- receive location updates in http mode
- app is in "move monitoring mode"
- sending http response containing setConfiguration command, with (a.o.)
  * monitoring=1
  * locatorPriority=0
=> **locatorPriority is refused** (if set to 1, it works perfectly well)

**Copy-paste of the relevant debug-log** (removed some irrelevant lines):
vr mei 22 2020 at 02:29:47:185 PM/2/Preferences :    importing 5 keys
[ ... ]
vr mei 22 2020 at 02:29:47:228 PM/2/Preferences :    load for key locatorPriority:0
vr mei 22 2020 at 02:29:47:229 PM/2/Preferences :    method: setLocatorPriority
vr mei 22 2020 at 02:29:47:230 PM/6/Preferences :    invalid locator priority specified 0
[ ... ]
vr mei 22 2020 at 02:29:47:236 PM/2/BackgroundService :    locator preferences changed. Resetting location request.

**Relevant code snippet from Preferences.java**:
private void setLocatorPriority(int anInt) {
	if(**anInt > 0** && anInt <= 3) {
		setInt(Keys.LOCATOR_PRIORITY, anInt);
	} else {
		Timber.e("invalid locator priority specified %s", anInt);
	}
}

**Comment by growse** [comment]
Fixed with #830.
