### ISSUE TITLE
Any interest in an OwnTracks Dev Mailing List and / or Discourse site?

### ISSUE THREAD

**Issue by philiprhoades** [owntracks/android#832]
People,

I went looking for a mailing list and / or Discourse Forum site for OT but couldn't find them . . is there any interest here in setting up those community support facilities? - I could help do it if there is.

My own interest is in developing a combination replacement for both Glympse and MyTracks . . 

Thanks,
Phil.

**Comment by kaysond** [comment]
Yes!

**Comment by jpmens** [comment]
I think this would, at least currently, be overkill for this small project. We've had success using issues in the respective trackers (or in our "talk/" project for topics which encompass both Android and iOS).

**Comment by philiprhoades** [comment]
> I think this would, at least currently, be overkill for this small project.

Right I have been looking at OT every now and then - in between getting frustrated with other Android "solutions" but I have never quite found the time to put some effort into working with it . . I find Discourse sites and email lists work well for me - even in low volume - but I will try and get started and come back here if I need to . .
