### ISSUE TITLE
Trying to manually edit region latitude and longitude crashes OwnTracks.

### ISSUE THREAD

**Issue by jamiebegin** [owntracks/android#835]
App build number: 2.1.3 (21302)
Android version: 10
Device: Google Pixel XL

When I add a region, it prefills the latitude and longitude. I want to manually change it to represent the center of my house, rather than where my phone is currently located.

I place focus in the "Latitude" text box and backspace right-to-left over the decimal numbers. Once I backspace over the "3" in "42.3", the text box value changes itself to "42.0" and the cursor jumps to the beginning of the text box. Returning the cursor to the end of the value and trying to backspace over the "0" results in the cursor jumping to the beginning again. If I double tap the value to highlight it and cut it to my clipboard, OwnTracks suddenly exits/crashes.

The same issue exists with the Longitude box.

**Comment by growse** [comment]
Looks similar to #822, was fixed in https://github.com/owntracks/android/commit/4200df4e415eb339020fb798c7558885b0915093 but is not yet released.
