### ISSUE TITLE
Location server update (more accuracy) and Background update 

### ISSUE THREAD

**Issue by DrCard** [owntracks/android#837]
**- i have tried both (Move Mode) and (significant change monitoring Mode) as im trying to make the app update more frequently to get more accuracy on the map  **  

in (Move Mode) iv set (locatorInterval = 10) can i go lower then 10 sec, will 1 sec work ?

mosquitto_pub -h broker -p 1883 -t 'owntracks/amjad/amjad/cmd' -m '{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration","locatorInterval":10,"monitor":2,"locatorPriority":3,"ping":10,"keepalive":10,"tid":"AH"}}' -u david -P BinonwgOd1

**- but im still geting updates ever 45 sec as you can see in the logs below ** 

owntracks/amjad/amjad {"_type":"location","acc":18,"alt":-15,"batt":36,"conn":"m","lat":26.1428281,"lon":50.4974793,"tid":"AH","tst":1592163592,"vac":2,"vel":11}
owntracks/david/david {"_type":"location","acc":14,"alt":-19,"batt":76,"conn":"w","lat":26.1310604,"lon":50.490253,"tid":"DV","tst":1592163595,"vac":2,"vel":0}
owntracks/amjad/amjad {"_type":"location","acc":55,"alt":-15,"batt":36,"conn":"m","lat":26.1428281,"lon":50.4974793,"tid":"AH","tst":1592163616,"vac":2,"vel":0}
owntracks/david/david {"_type":"location","acc":14,"alt":-19,"batt":76,"conn":"w","lat":26.131061,"lon":50.4902533,"tid":"DV","tst":1592163625,"vac":2,"vel":0}
owntracks/david/david {"_type":"location","acc":14,"alt":-19,"batt":76,"conn":"w","lat":26.131061,"lon":50.4902533,"tid":"DV","tst":1592163655,"vac":2,"vel":0}
owntracks/amjad/amjad {"_type":"location","acc":13,"alt":-17,"batt":36,"conn":"m","lat":26.1388876,"lon":50.4987527,"tid":"AH","tst":1592163669,"vac":13,"vel":46}
owntracks/david/david {"_type":"location","acc":43,"alt":-19,"batt":76,"conn":"w","lat":26.1310276,"lon":50.4902528,"tid":"DV","tst":1592163686,"vac":2,"vel":0}
owntracks/amjad/amjad {"_type":"location","acc":18,"alt":-24,"batt":36,"conn":"m","lat":26.1345562,"lon":50.4974328,"tid":"AH","tst":1592163710,"vac":18,"vel":38}
owntracks/david/david {"_type":"location","acc":43,"alt":-19,"batt":75,"conn":"w","lat":26.131035,"lon":50.4902613,"tid":"DV","tst":1592163716,"vac":2,"vel":0}
owntracks/david/david {"_type":"location","acc":43,"alt":-19,"batt":75,"conn":"w","lat":26.1310352,"lon":50.4902599,"tid":"DV","tst":1592163746,"vac":2,"vel":0}
owntracks/amjad/amjad  

**- I Also tried significant change monitoring Mode Set the locatorInterval = 10 & locatorDisplacement=10** 

mosquitto_pub -h broker -p 1883 -t 'owntracks/amjad/amjad/cmd' -m '{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration","locatorInterval":10,"locatorDisplacement":10,"monitor":1,"locatorPriority":3,"ping":10,"keepalive":10,"tid":"AH"}}' -u david -P BinonwgOd1

but the device didn't send any update to the server even after 3 minutes and after driving 1 KM

1. - am i doing someone wrong ?!!!
2. - or is there a bug or is my phone not compatible?

thank you so much for this amazing Tracker and hope i can get it fully working 
  
App build number (10.0.0.20c(C185E8R1P3))
Android version (10)
Device (HUAWEI P30 pro

**Comment by growse** [comment]
Does the behaviour change if you restart the app after sending the cfg msg?

**Comment by DrCard** [comment]
> Does the behaviour change if you restart the app after sending the cfg msg?

Yes it dose 

i also found out when the app is working in the background it stops sending locations (its sent only 6 location points i was driving around 10 KM)   and it became more accurate once the app was displayed on the screen (every 10 secs a location point was posted)

if you where using google maps and change to owntracks you really feel the difference (even if you want to send the location to the server ever 10 secs the point on the app should move as it stays put for 10 sec and this really gives bad user experience, i think a better solution is making the cursor blink each time it send the location to the server while keeping the cursor moving on the map this will make the app give you the google map experience 


regards thank thank you so much

**Comment by growse** [comment]
Sounds like that the config change is not causing the `LocationRequest` to be refreshed. We've got a new version in the works and I've specifically got a test case for this, so hopefully that'll be fixed by that version.

**Comment by DrCard** [comment]
> Sounds like that the config change is not causing the `LocationRequest` to be refreshed. We've got a new version in the works and I've specifically got a test case for this, so hopefully that'll be fixed by that version.

that is great to know 
but i still couldn't get the app to update from the background  after 5 mins it stops posting and sometime, it is able to post 1 or 2 points then it stops again .

i think the version of android im using is the problem (10.0.0.2)i will test an old version and see if it keeps running.

thank you so much for the great work if you need me to test the new ver i would be very happy to do so.

thanks again

**Comment by growse** [comment]
Is this bug still valid with the latest (2.2.0) version?
