### ISSUE TITLE
IgnoreStaleLocations discards all location updates, Friends location don't show up.

### ISSUE THREAD

**Issue by alexte** [owntracks/android#839]
FYI:

The current release version 2.1.3 discards all friend location updates (HTTP) not old enough.

I found out that the log shows "discarding stale location", so I changed the ignoreStaleLocations setting from default 0 to higher 
numbers. After that change the local location updates where discarded, too.

With some digging through the source I found out that the the stale comparison was the wrong way around:

   `     if((System.currentTimeMillis() - message.getTst() * 1000) < timeUnit.DAYS.toMillis(preferences.getIgnoreStaleLocations())) ...discard`

This line was fixed in "master":

`         if ((preferences.getIgnoreStaleLocations() > 0) && (System.currentTimeMillis() - (message.getTst() * 1000) >(preferences.getIgnoreStaleLocations() * 24 * 60 * 60 * 1000)) ... discard
 `

The "<" was changed to ">"

I write this issue to help others who have this problem with the current release version.

My current workarround: set ignoreStaleLocations to 0 and let the server send  tst timestamps that are older.

**Comment by growse** [comment]
Thanks for pointing this one out - this got fixed in master a while back. I'm due to do a beta release very soon, just a few really annoying things to iron out.
