### ISSUE TITLE
does not work on devices without google play services

### ISSUE THREAD

**Issue by ola-** [owntracks/android#84]
google play services is not present on all android devices
also, it is proprietary.  It would be awesome if this app could be included in f-droid repository. They do not allow proprietary software dependancy.
 
maybe https://github.com/mapzen/LOST would help

**Comment by binarybucks** [comment]
The Play Services are an integral part of the app as they're used for location services. 

As such, there will probably never be a version without them, sorry.

--
Alexander Rust
