### ISSUE TITLE
Charging (battery) status for Android

### ISSUE THREAD

**Issue by gitmayer** [owntracks/android#841]
Is it possible to get the charging status feature from iOS added to the Android app?

Specifically the bs element in the JSON
`bs` `Battery Status 0=unknown, 1=unplugged, 2=charging, 3=full (iOS)`

Thank you

**Comment by growse** [comment]
*Should* be possible. I'll put it on the post-22000-release list.

**Comment by jpmens** [comment]
@gitmayer FYI this will be in the next release. Thanks for the suggestion.

**Comment by gitmayer** [comment]
Thanks for implementing this!
