### ISSUE TITLE
Publishing to /cmd seems not to work

### ISSUE THREAD

**Issue by JsBergbau** [owntracks/android#842]
I try cmd according to https://owntracks.org/booklet/tech/json/#_typecmd

As you can see owntracks is successfully connected to broker 

![grafik](https://user-images.githubusercontent.com/37013344/88660782-ef976580-d0c6-11ea-9860-bf7cfdba78d0.png)

Trying to publish a test message
![grafik](https://user-images.githubusercontent.com/37013344/88661526-2c179100-d0c8-11ea-9023-4e76f47490b6.png)
But nothing happens.

My usecase is to disable automatic location reporting and just to get it reported back via a 
`{"_type":"cmd","action":"reportLocation"}`
but as long as even notifications don't get displayed I don't expect location report to work (and yes, there also nothing happens when sending this message).

And of course remote commands are enabled.

**Comment by underdog** [comment]
Is this still a bug?  I am running owntracks v 16.4.1 and it seems that owntracks will only respond to reportLocation cmd when it is is foreground.  If I leave it running and i am in another application, it still wont respond to cmds. 

settings:
subQos 1
keepAlive 1200
pubQos 1
willQos 1
ranging - enabled
extendedData - enabled
locked - disabled
sub - enabled
cmd - enabled
pubRetain - enabled
willRetain- disabled
cleanSession - enabled
allowRemoteLocation - enabled

**Comment by growse** [comment]
Are you on iOS? This is the issue tracker for the android client, so you might have more success at https://github.com/owntracks/ios

**Comment by wir3z** [comment]
Is "reportLocation" supported in HTTP mode, or only MQTT?  I cannot seem to enable "allowRemoteLocation" in HTTP mode either (which is making me wonder...  :) )

**Comment by growse** [comment]
Should do - command handling is independent of connection mode. What are you seeing in the logs?

**Comment by wir3z** [comment]
Ahhh...  Never had the luxury of logging in most mobile apps!  Turns out the response is "Command not supported in HTTP mode", so there you go!

**Comment by wir3z** [comment]
Awesome!  Looking forward to this.
