### ISSUE TITLE
Log location data to file on device

### ISSUE THREAD

**Issue by kovasap** [owntracks/android#870]
Is there any way for this app to log location data to a file on my device instead of sending it to a server?  I'd like to just get the data on a regular basis so i can sync it to google drive and process it from there.

**Comment by jpmens** [comment]
No, that is not possible; we transmit the data to an MQTT broker or HTTP server only.
You will  find other apps which do this.

**Comment by kovasap** [comment]
Can you suggest any?  I haven't been able to find one yet.

**Comment by jpmens** [comment]
Have you tried `"gps recording"` in the play store?

**Comment by kovasap** [comment]
ah yes, thanks, i didn't try using the "recording" keyword.
