### ISSUE TITLE
BSSID and SSID

### ISSUE THREAD

**Issue by bdwilson** [owntracks/android#871]
I noticed that BSSID and SSID were recently added to owntracks/ios#615 and was hoping the same could be done for Android.   

I did see #507 closed but unsure of why. 

Use case is implementing into home automation to allow actions to happen when home and on WiFi vs at home. 

Thank you!

**Comment by growse** [comment]
I think this is worth doing. I've got a few issues to fix before getting 2.2.1 out the door, but let's see if we can get it in after that.

**Comment by growse** [comment]
Fixed in 89e100d
