### ISSUE TITLE
OpenCageData reverse geocoding doesn't appear to work

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#874]
Geocoding is enabled, OpenCageData API key is configured, app was restarted, but no reverse geocoding is being performed.

```
"geocodeEnabled": true,
"opencageApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
```

Geocoding should happen when the location is received from the device.

**Comment by jpmens** [comment]
I confirm it now works with build 22121, thank you.

**Comment by growse** [comment]
Going to keep an eye on this one though, because it sometimes does unusual things.
