### ISSUE TITLE
 Queue does not work over HTTP

### ISSUE THREAD

**Issue by clevertonh** [owntracks/android#893]
* **App build number**: 2.2.0 (22061)
* **Android version**: 9 PKQ1.190616.001
* **Device**: Xiaomi Redmi Note 8

Hi,
a queue is not working when the smartphone is without internet and using the HTTP protocol, a queue is always 0 even in motion.

`{
  "_type": "configuration",
  "waypoints": [],
  "_build": 22061,
  "autostartOnBoot": true,
  "cleanSession": false,
  "cmd": true,
  "debugLog": true,
  "deviceId": "000001",
  "dontReuseHttpClient": true,
  "fusedRegionDetection": true,
  "geocodeEnabled": true,
  "ignoreInaccurateLocations": 0,
  "ignoreStaleLocations": 0,
  "locatorDisplacement": 10,
  "locatorInterval": 10,
  "locatorPriority": 3,
  "mode": 3,
  "monitoring": 2,
  "moveModeLocatorInterval": 10,
  "notificationEvents": false,
  "notificationHigherPriority": false,
  "password": "000001",
  "ping": 15,
  "pubExtendedData": true,
  "tid": "01",
  "url": "https://localhost/owntracks/pub",
  "username": "000001"
}`

[
![app](https://user-images.githubusercontent.com/1263297/102888809-4025ab80-4438-11eb-8efa-0ceacf59823b.jpg)
](url)

**Comment by clevertonh** [comment]
Hello, I'm using the 'Lockito' APP to simulate the movement.

https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito

**Comment by growse** [comment]
Thanks! Was an issue in how the HTTP processor handled failures. Should be fixed in 2.2.2, out as soon as I figure out what all these buttons do.

**Comment by clevertonh** [comment]
Thanks @growse for the correction, any prediction of the next version to be available on Google Play?

Were you able to provide an APK for testing?

**Comment by growse** [comment]
Next version (v2.2.2) will be in the next day or so.
