### ISSUE TITLE
subTopic - multiple subscriptions?

### ISSUE THREAD

**Issue by sokol99** [owntracks/android#898]
Hi, I am new to OwnTracks (ok, I"m using the NextTracks fork) and am wondering whether the option to support multiple subscriptions is a working feature (in at least OwnTracks proper)?

The booklet says:
"subTopic A whitespace separated list of MQTT topics to which the app subscribes if sub is true (defaults see topics) (iOS,Android/string)"

However when I use the config editor in the app and separate the topics by whitespace the app fails to connect to my MQTT mosquitto broker.  

For example either of these will work as standalone/single entries in the config editor. Minus needing the tick marks.
'owntracks/#'
'owntracks/+/+'

But if I attempt something like so, my connection fails to the broker (minus tick marks):
'owntracks/user/# owntracks/test'

The reason I am doing this is that on my phone I am getting notifications for both my own device and other devices.  I would like to NOT get my own device notifications. (I know that I've left home for example).  

I've also tried to add the "-T" subscription filter in the value entry with no luck. 

* **App build number**: 3.2.1
* **Android version**: Android 10
* **Device**:Pixel 4a

**Comment by jpmens** [comment]
I don't know what you're trying to do with `-T` ; I think you're confusing us with a mosquitto client...  You also say 'fails to the broker': what does your broker log?

IIRC if you filter out your own publishes you won't be displayed on your map, so that is something I'd consider. 

Needless to say you'll have to raise this with nexttracks (who haven't spoken to us about the fork) as their handling might be different.

**Comment by jpmens** [comment]
This is indeed a bug.

With `subTopic` configured as default (`owntracks/+/+`) my broker shows the following logs:

```
1609158390: New client connected from 192.168.1.145:57826 as jpms8 (p2, c0, k3600, u'jpm').
1609158390: Will message specified (32 bytes) (r0, q0).
1609158390:     owntracks/jpm/s8
1609158390: Sending CONNACK to jpms8 (1, 0)
1609158390: Received SUBSCRIBE from jpms8
1609158390:     owntracks/+/+ (QoS 2)
1609158390: jpms8 2 owntracks/+/+
1609158390:     owntracks/+/+/info (QoS 2)
1609158390: jpms8 2 owntracks/+/+/info
1609158390:     owntracks/jpm/s8/cmd (QoS 2)
1609158390: jpms8 2 owntracks/jpm/s8/cmd
1609158390:     owntracks/+/+/event (QoS 2)
1609158390: jpms8 2 owntracks/+/+/event
1609158390:     owntracks/+/+/waypoints (QoS 2)
1609158390: jpms8 2 owntracks/+/+/waypoints
1609158390: Sending SUBACK to jpms8
```

If I reconfigure to

```json
"subTopic": "owntracks/+/+ bla/foo exam/ple/#",
```

Mosquitto logs this, endlessly:

```
1609158437: New connection from 192.168.1.145:57846 on port 1883.
1609158438: New client connected from 192.168.1.145:57846 as jpms8 (p2, c0, k3600, u'jpm').
1609158438: Will message specified (32 bytes) (r0, q0).
1609158438: 	owntracks/jpm/s8
1609158438: Sending CONNACK to jpms8 (1, 0)
1609158438: Client jpms8 closed its connection.
1609158438: New connection from 192.168.1.145:57848 on port 1883.
1609158438: New client connected from 192.168.1.145:57848 as jpms8 (p2, c0, k3600, u'jpm').
1609158438: Will message specified (32 bytes) (r0, q0).
1609158438: 	owntracks/jpm/s8
1609158438: Sending CONNACK to jpms8 (1, 0)
1609158438: Client jpms8 closed its connection.
1609158438: New connection from 192.168.1.145:57850 on port 1883.
1609158438: New client connected from 192.168.1.145:57850 as jpms8 (p2, c0, k3600, u'jpm').
1609158438: Will message specified (32 bytes) (r0, q0).
1609158438: 	owntracks/jpm/s8
1609158438: Sending CONNACK to jpms8 (1, 0)
1609158438: Client jpms8 closed its connection.
```

Looks like a crash to me.

**Comment by jpmens** [comment]
This is `2.2.1` (`22127`)

**Comment by growse** [comment]
I'll get a fix into 2.2.2 if I can.

**Comment by sokol99** [comment]
Thank you @jpmens.  For the time being I was able to set up an acl file on the broker/mosquitto to achieve the desired effect. 
Thank you to you and the team!

**Comment by growse** [comment]
I'm going to punt this to 2.2.3 as there's some design issues that need to be agreed before we implement, and I don't want to hold up 2.2.2.
