### ISSUE TITLE
Show waypoints on map

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#9]
Copy of https://github.com/binarybucks/mqttitude/issues/273

**Comment by jpmens** [comment]
Bluish circles like we do in iOS. Luxury version is: circles turn redish to show "hot" when I'm in a waypoint region.

**Comment by Snigdha29** [comment]
@binarybucks @jpmens @joshproehl @dlitz @CloCkWeRX :I am somewhat new to this project. I find this import "org.owntracks.android.db.WaypointDao"
in the ServiceLocator class of org.owntracks.android.services package. But I find no class as "WaypointDao" in db package. Only Waypoint and Dao classes are present there. M I missing something?

**Comment by binarybucks** [comment]
You are. The class is auto generated during compilation.

**Comment by Snigdha29** [comment]
@binarybucks But should it not be then somewhere in build.generated.source instead of being in "org.owntracks.android.db.WaypointDao" as mentioned in import "org.owntracks.android.db.WaypointDao"
