### ISSUE TITLE
Invalid config URL when importing from .otrc file

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#913]
2.2.3 (22302) is reporting `invalid config URL` when importing from an `.otrc` file. Both when launching from a mail and when opening from the file system.

**Comment by growse** [comment]
Can you narrow down which bit of the otrc file is causing it? Or is it any otrc file?

**Comment by jpmens** [comment]
It's the export I did from the same device before beginning to test `config?inline=`

**Comment by jpmens** [comment]
I thought it might be the waypoints, but if I remove `waypoints: []` from the file, the error persists.

**Comment by jpmens** [comment]
it seems to be any `.otrc` file irrespective of content.

**Comment by growse** [comment]
Reproduced.

**Comment by jpmens** [comment]
22303 still cannot open `.otrc`

**Comment by growse** [comment]
Fix isn't published yet :)

**Comment by jpmens** [comment]
I confirm fixed in 22304. Thank you.
