### ISSUE TITLE
Disable Friends and Family capability

### ISSUE THREAD

**Issue by anhtu91** [owntracks/android#932]
Hi,
I have read the docs and found that Friends and Family is enabled by default. My question is, how can I disable this function.
Thanks in advance

**Comment by anhtu91** [comment]
Please give me a hand. I really need to disable this function.

**Comment by jpmens** [comment]
What are you trying to disable? (Please don't say "Friends and Family" unless you can explain what you think that is.) 

If neither your friends nor your family shares broker ACLs then there is no such thing as Friends and Family.

**Comment by anhtu91** [comment]
My friends don’t want to share their locations with others. Is there anyway
to use the same Mqtt Broker but don‘t share location with others?

JP Mens <notifications@github.com> schrieb am Mi. 17. Feb. 2021 um 10:37:

**Comment by jpmens** [comment]
Yes: set ACLs on the broker.

**Comment by anhtu91** [comment]
> Yes: set ACLs on the broker.

Are you sure? I tried with the following link but it didn't work at all:
`https://mosquitto.org/man/mosquitto-conf-5.html`

**Comment by jpmens** [comment]
I am very sure I'm sure; we do that a lot. 

Linking to the man page isn't showing what you attempted to do, what you expected, and the result. You need to do better for me to remain interested in helping.

**Comment by anhtu91** [comment]
Let me explain my case.
I use NodeRED to read all the position of user from Mosquitto and do some backend then display their locations.
![image](https://user-images.githubusercontent.com/38013626/108213768-af193b00-712f-11eb-9762-33529290025c.png)
I have in this test case 2 user, who use the same MQTT Broker and as your suggestion I have create the ACLs file to deny user see location of each others.
This is ACLs file:
![image](https://user-images.githubusercontent.com/38013626/108214058-00c1c580-7130-11eb-8ae6-19a351560c0d.png)
and this is mosquitto.conf file:
![image](https://user-images.githubusercontent.com/38013626/108214200-2f3fa080-7130-11eb-916c-bafe61f257f5.png)
But when I use restart my docker container (I use Mosquitto 1.6.12 in Docker) with these config files. It doesn't run at all.
![image](https://user-images.githubusercontent.com/38013626/108214316-51d1b980-7130-11eb-9d2a-0b02d466058c.png)

When I put read/write/readwrite or empty in this line 
`user 01
topic write owntracks/02/genericx86

user 02
topic write owntracks/01/genericx86`
Then it didn't change anything. All users can see locations of each others.
Please let me know if something is wrong.

**Comment by ckrey** [comment]
Yes it is, please read your log:
![Bildschirmfoto 2021-02-17 um 15 07 25](https://user-images.githubusercontent.com/4027289/108215729-ef79b880-7131-11eb-835e-c0aea6bde4d5.png)

**Comment by jpmens** [comment]
It clearly says in the log that ACL type `deny` is invalid..

you have user `01` being permitted to write to `02` and vice versa.

**Comment by jpmens** [comment]
There's a [snippet](https://owntracks.org/booklet/guide/broker/#acls) in our Booklet which touches upon this. Other than that, please study the Mosquitto documentation.

**Comment by anhtu91** [comment]
> Yes it is, please read your log:
> ![Bildschirmfoto 2021-02-17 um 15 07 25](https://user-images.githubusercontent.com/4027289/108215729-ef79b880-7131-11eb-835e-c0aea6bde4d5.png)
In this [link](https://mosquitto.org/man/mosquitto-conf-5.html), it said:

> If this parameter is defined then only the topics listed will have access. Topic access is added with lines of the format:
> 
> topic [read|write|readwrite|deny] <topic>

So I think use deny is nothing wrong here. Correct me if I am wrong.

**Comment by jpmens** [comment]
`deny` was added in October 2020. You are on version 1.6.12 which was released in August 2020.

**Comment by anhtu91** [comment]
> `deny` was added in October 2020. You are on version 1.6.12 which was released in August 2020.

After upgrade Mosquitto to lastest version 2.0.7 and restart Container. Mosquitto runs without errors "deny". But it still shares the locations between 2 user. Even when I use read/write or readwrite or left the topic like this:
![image](https://user-images.githubusercontent.com/38013626/108222947-8f871000-7139-11eb-98e2-f03b90c63cdd.png)
The result is same as before
![image](https://user-images.githubusercontent.com/38013626/108223141-c826e980-7139-11eb-801d-209e66c1d4b7.png)

**Comment by jpmens** [comment]
Show us a screenshot of the settings page in the app which shows the user as which you are connecting, please, and show us a snippet of (text please) in the logs when one device publishes and the subscribe is sent to the other device. You might need to up the log level to `all`.

**Comment by anhtu91** [comment]
> Show us a screenshot of the settings page in the app which shows the user as which you are connecting, please, and show us a snippet of (text please) in the logs when one device publishes and the subscribe is sent to the other device. You might need to up the log level to `all`.
This is the [log](https://drive.google.com/file/d/1JZcyraELn_sauZKD8BHF_BOvGl5dZ1SM/view?usp=sharing) file. Is that what you need?

**Comment by jpmens** [comment]
Sorry, I meant the Mosquitto log, not the Android device log.

**Comment by anhtu91** [comment]
And here is the [screenshot](https://imgur.com/a/1zOva6H) of my connection settings

**Comment by anhtu91** [comment]
> Sorry, I meant the Mosquitto log, not the Android device log.

> 
1613574192: mosquitto version 2.0.7 starting


1613574192: Config loaded from /mosquitto/config/mosquitto.conf.


1613574192: Opening ipv4 listen socket on port 8883.


1613574192: Opening ipv6 listen socket on port 8883.


1613574192: Opening ipv4 listen socket on port 1883.


1613574192: Opening ipv6 listen socket on port 1883.


1613574192: mosquitto version 2.0.7 running


1613574193: New connection from 192.168.1.3:49074 on port 8883.


1613574193: New connection from 192.168.1.3:49072 on port 8883.


1613574193: New client connected from 192.168.1.3:49074 as owntracks/01 (p2, c0, k900, u'fhDO').


1613574193: New client connected from 192.168.1.3:49072 as owntracks/02 (p2, c0, k900, u'fhDO').


1613574207: New connection from 172.18.0.6:48026 on port 8883.


1613574207: New client connected from 172.18.0.6:48026 as fhDO (p1, c1, k60, u'fhDO').

**Comment by jpmens** [comment]
Judging by that last log, your devices are always connecting as user `fhDO`, and that user has an ACL of `owntracks/#` so they can see all publishes sent to the topic branch `owntracks/#`. 

```
1613574193: New client connected from 192.168.1.3:49074 as owntracks/01 (p2, c0, k900, u'fhDO').
1613574193: New client connected from 192.168.1.3:49072 as owntracks/02 (p2, c0, k900, u'fhDO').
1613574207: New client connected from 172.18.0.6:48026 as fhDO (p1, c1, k60, u'fhDO').
```

**Comment by anhtu91** [comment]
> Judging by that last log, your devices are always connecting as user `fhDO`, and that user has an ACL of `owntracks/#` so they can see all publishes sent to the topic branch `owntracks/#`.
> 
> ```
> 1613574193: New client connected from 192.168.1.3:49074 as owntracks/01 (p2, c0, k900, u'fhDO').
> 1613574193: New client connected from 192.168.1.3:49072 as owntracks/02 (p2, c0, k900, u'fhDO').
> 1613574207: New client connected from 172.18.0.6:48026 as fhDO (p1, c1, k60, u'fhDO').
> ```

The IP Address 172.18.0.6 is my NodeRED, which use fhDO as Mosquitto username. 
I run 2 Android Emulator which both live in my local computer with IP 192.168.1.3.
These lines (p1, c1, k60, u'fhDO'), (p2, c0, k900, u'fhDO'), (p2, c0, k900, u'fhDO'). I think it becauses of my MQTT TLS settings.

**Comment by anhtu91** [comment]
And as the [screenshots](https://imgur.com/a/1zOva6H), I have configured the Mosquitto username/password for every single Android Emulator

**Comment by jpmens** [comment]
```
1613574193: New client connected from 192.168.1.3:49074 as owntracks/01 (p2, c0, k900, u'fhDO').
1613574193: New client connected from 192.168.1.3:49072 as owntracks/02 (p2, c0, k900, u'fhDO').
```

That IP is connecting and authenticating as `fhDO` to the broker. Twice.

**Comment by growse** [comment]
The log shows that the device it's taken from is receiving messages on both the `01` and `02` topics, so it looks like the mosquito ACL isn't behaving as needed.

**Comment by jpmens** [comment]
@growse IMO the ACL is behaving: https://github.com/owntracks/android/issues/932#issuecomment-780635596

**Comment by anhtu91** [comment]
If user "fhDO", which uses in NodeRED, is disabled, then my NodeRED cannot receive anything. So I guess ACLs works but somehow it doesn't work for my Android Emulator

**Comment by jpmens** [comment]
@anhtu91 please increase the Mosquitto log level to

```
log_type all
log_type debug
```

Then re-connect one of the emulators and PUBlish a location. Then show us the Mosquitto log please, which should include PUBLISH and SUBSCRIBE messages.

**Comment by anhtu91** [comment]
> 
1613577257: Received PUBACK from fhDO (Mid: 13, RC:0)


1613577257: Received PUBACK from owntracks/02 (Mid: 15, RC:0)


1613577268: Received PUBLISH from owntracks/02 (d0, q1, r1, m8, 'owntracks/02/genericx86', ... (176 bytes))


1613577268: Sending PUBLISH to owntracks/02 (d0, q1, r0, m16, 'owntracks/02/genericx86', ... (176 bytes))


1613577268: Sending PUBLISH to fhDO (d0, q1, r0, m14, 'owntracks/02/genericx86', ... (176 bytes))


1613577268: Sending PUBACK to owntracks/02 (m8, rc0)


1613577268: Received PUBACK from fhDO (Mid: 14, RC:0)


1613577268: Received PUBACK from owntracks/02 (Mid: 16, RC:0)


1613577268: Received PUBLISH from owntracks/02 (d0, q1, r1, m9, 'owntracks/02/genericx86', ... (168 bytes))


1613577268: Sending PUBLISH to owntracks/02 (d0, q1, r0, m17, 'owntracks/02/genericx86', ... (168 bytes))


1613577268: Sending PUBLISH to fhDO (d0, q1, r0, m15, 'owntracks/02/genericx86', ... (168 bytes))


1613577268: Sending PUBACK to owntracks/02 (m9, rc0)


1613577268: Received PUBACK from fhDO (Mid: 15, RC:0)


1613577268: Received PUBACK from owntracks/02 (Mid: 17, RC:0)


1613577273: Received PUBLISH from owntracks/02 (d0, q1, r1, m10, 'owntracks/02/genericx86', ... (168 bytes))


1613577273: Sending PUBLISH to owntracks/02 (d0, q1, r0, m18, 'owntracks/02/genericx86', ... (168 bytes))


1613577273: Sending PUBLISH to fhDO (d0, q1, r0, m16, 'owntracks/02/genericx86', ... (168 bytes))


1613577273: Sending PUBACK to owntracks/02 (m10, rc0)


1613577273: Received PUBACK from fhDO (Mid: 16, RC:0)


1613577273: Received PUBACK from owntracks/02 (Mid: 18, RC:0)

I use emulator with user 02. User 01 is disabled.

**Comment by anhtu91** [comment]
This is what I got when enable both emulator:

> 
1613577471: Sending PUBLISH to owntracks/02 (d0, q1, r0, m83, 'owntracks/02/genericx86', ... (168 bytes))


1613577471: Sending PUBLISH to fhDO (d0, q0, r0, m0, 'owntracks/02/genericx86', ... (168 bytes))


1613577471: Sending PUBACK to owntracks/02 (m34, rc0)


1613577471: Received PUBACK from owntracks/01 (Mid: 87, RC:0)


1613577471: Received PUBACK from owntracks/02 (Mid: 83, RC:0)


1613577475: Received PUBLISH from owntracks/01 (d0, q1, r1, m43, 'owntracks/01/genericx86', ... (167 bytes))


1613577475: Sending PUBLISH to owntracks/01 (d0, q1, r0, m88, 'owntracks/01/genericx86', ... (167 bytes))


1613577475: Sending PUBLISH to owntracks/02 (d0, q1, r0, m84, 'owntracks/01/genericx86', ... (167 bytes))


1613577475: Sending PUBLISH to fhDO (d0, q0, r0, m0, 'owntracks/01/genericx86', ... (167 bytes))


1613577475: Sending PUBACK to owntracks/01 (m43, rc0)


1613577475: Received PUBACK from owntracks/01 (Mid: 88, RC:0)


1613577475: Received PUBACK from owntracks/02 (Mid: 84, RC:0)


1613577477: Received PUBLISH from owntracks/02 (d0, q1, r1, m35, 'owntracks/02/genericx86', ... (168 bytes))


1613577477: Sending PUBLISH to owntracks/01 (d0, q1, r0, m89, 'owntracks/02/genericx86', ... (168 bytes))


1613577477: Sending PUBLISH to owntracks/02 (d0, q1, r0, m85, 'owntracks/02/genericx86', ... (168 bytes))


1613577477: Sending PUBLISH to fhDO (d0, q0, r0, m0, 'owntracks/02/genericx86', ... (168 bytes))


1613577477: Sending PUBACK to owntracks/02 (m35, rc0)


1613577477: Received PUBACK from owntracks/02 (Mid: 85, RC:0)


As you can see, mosquitto sent topic 'owntracks/02/genericx86' to both user:

> 
1613577477: Sending PUBLISH to owntracks/01 (d0, q1, r0, m89, 'owntracks/02/genericx86', ... (168 bytes))


1613577477: Sending PUBLISH to owntracks/02 (d0, q1, r0, m85, 'owntracks/02/genericx86', ... (168 bytes))

And my currently ACLs file is:

> user 01
topic owntracks/01/#

user 02
topic owntracks/02/#

user fhDO
topic owntracks/#

**Comment by jpmens** [comment]
You've not shown that the devices authenticate as different users. As long as https://github.com/owntracks/android/issues/932#issuecomment-780635596 is still the case nothing will change.

**Comment by jpmens** [comment]
The issue might be due to your use of client certificates (thanks, @growse). Only now do I notice that you're authenticating with a client certificate `fhDO2021.p12`. If your Mosquitto has `use_identity_as_username` configured `true`, then these two clients are connecting as the same identity, i.e. as the same user.

You would need to disable that setting and ensure username is configured in the apps (which it is).

**Comment by ckrey** [comment]
you are using the same user (fhD0) for all your clients. Hence they all have full access.
The acl works on the user, not the clientId (owntracks/01, owntracks/02)

<img width="863" alt="Screenshot 2021-02-17 at 17 30 21" src="https://user-images.githubusercontent.com/4027289/108235298-fb6f7580-7145-11eb-9a9c-4527d6956157.png">

**Comment by growse** [comment]
How many users do you have configured in your mosquito users.db?

**Comment by jpmens** [comment]
Either you create a certificate for each user or you use the certificate and additional user/password

**Comment by anhtu91** [comment]
> Either you create a certificate for each user or you use the certificate and additional user/password

Firstly, thanks you guys so much. I have created for every single user a certificate and it worked!

**Comment by jpmens** [comment]
Hallelujah! :-)

Glad you got it going.
