### ISSUE TITLE
TLS Certificate errors

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#94]
Version 0.5.0 seems to have a problem on Android 5 with CAcert certificates. I'm using a root 3 for my domain, installed root into android as user trusted certificate, but I just get connection problems. Worked with play store version﻿

**Comment by kromonos** [comment]
"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found﻿"
After selecting TLS (custom certificate) and set the path to intermediate certificate, it works. Also getting back to "normal" TLS works, after that.

**Comment by binarybucks** [comment]
Trust anchor for certification path not found hints that you're missing one or more trusted ca certificates that can validate the certificate that your server presents.

Try importing the CA bundle into Android instead of just the Class 3 CA certificate.

I changed some TLS things in 0.5 so i'd like to make sure that it's not a user error. Can you provide me with the address and port of your broker that presents the class 3 certificate so I can try to establish a TLS connection? You can also mail it to me if you don't want it published on Github.





> Am 11.02.2015 um 00:08 schrieb kromonos <notifications@github.com>:
> 
> Trust anchor for certification path not found

**Comment by kromonos** [comment]
For better debuging on your site, I've created an account for you on my broker. Mail was send with auth creds.

**Comment by binarybucks** [comment]
Ok, I'm able to connect with mosquitto_sub but not with the app. 
I'm not seeing any other error than the trust-anchor one you reported. 

Wil have to dig a bit deeper. 

Have you set a specific TLS version in mosquitto?

**Comment by kromonos** [comment]
Here is my mosquitto config: http://paste.bka.li/8D6NaA/

**Comment by binarybucks** [comment]
Could you test it with 
tls_version tlsv1.2 ?

--
Alexander Rust

**Comment by kromonos** [comment]
set

**Comment by binarybucks** [comment]
Oh, somehow I mixed up CACert and StartSSL. Of course, connecting to your CACert secured broker with a StartSSL root certificate doesn't work. 

When importing the Class 3 Root certificate (http://www.cacert.org/certs/class3.crt) to the Android keystore I can connect without any problems. 
Specifying the absolute path to the same certificate for TLS (custom certificate) also works. 

Please verify if you're using the correct root certificate and reopen this issue if your problems persist.

**Comment by kromonos** [comment]
I'm sure, imported correct certificates.
Tried it also more than 5 times. Deleting/uninstalling the App/-data to be sure, that the cached path is deleted and then tried to connect. The "normal" TLS Version works without any problems, when 1 connection was made with custom certificate path

**Comment by jpbarraca** [comment]
I'm having the same problem.

In my setup I have a custom CA certificate, and a server certificate signed by the CA. The phone has the CA installed as a trusted root. Other applications connecting to this server connect flawlessly. 

When using the Play Store version, I can use the application as expected.
When using the github version, I get the same error "Trust anchor for certification path not found.".

**Comment by binarybucks** [comment]
Which Android versions are you two on?

Do you have Android Studio or Eclipse installed so we could get some logs from the device?

I'll see if I can get you a new version to test and see whether I can reproduce that normal TLS working after connecting once with a custom cert.

--
Alexander Rust

**Comment by kromonos** [comment]
Android 5.0.1 (Moto G) and Android 5.0.2 (Nexus 7)

**Comment by jpbarraca** [comment]
LG G3 with AndroidNow HD 9.3 SE (custom based on Stock V20H, Android 5.0)

Yes. Will send it after dinner :)

**Comment by binarybucks** [comment]
Can you please try if 0.5.02 https://github.com/owntracks/android/raw/Android-v.0.5.02/apk/owntracks.apk works better now?

Please note:
- that this is not yet an official beta version. There are still some raw edges and my brain is a bit broken from a bad cold ;)
- this is a different application that the one you have installed as the application identifier changed from st.alr.mqttitude to org.owntracks.android

**Comment by kromonos** [comment]
Works great, but: https://github.com/owntracks/android/issues/97
