### ISSUE TITLE
Detect OpenCage usage limit nearing and do something with that (notify, prevent sending requests if over limit etc.)

### ISSUE THREAD

**Issue by growse** [owntracks/android#942]
Free tier users on OpenCage get a quota, so we should work a bit harder at detecting when the user is near their quota and backing off the requests / notifying the users.

**Comment by freyfogle** [comment]
Perhaps useful: here is the documentation of the rate limiting response:
https://opencagedata.com/api#rate-limiting

We also have some public testing keys for testing to trigger various error responses:
https://opencagedata.com/api#testingkeys

Of course we (OpenCage) are happy to answer any questions. 
Many thanks for your help with this, it is appreciated.

**Comment by freyfogle** [comment]
that's perfect. thanks very much

**Comment by growse** [comment]
Just need to do some lower android version testing, then I'll merge and push out a 2.3 beta.
