### ISSUE TITLE
Mind cutting a new release on the play store?

### ISSUE THREAD

**Issue by nwf** [owntracks/android#947]
Sorry to be a bother, but with #896 fixed some while ago, it'd be nice to have a new release in the official update channel, especially as the weather gets nicer in this hemisphere and I'm more likely to go out and about again. :)

**Comment by growse** [comment]
Hi - yes, sorry. 2.3.0 is very nearly done (just one more bit to go) and then I can get the beta out there to soak for a week or so (join the beta! find bugs! win prizes*!).

Apologies progess has been slow. New parent etc.

*no actual prizes.

**Comment by nwf** [comment]
No apologies necessary; thanks for continuing to push things through.  And congratulations!
