### ISSUE TITLE
Receiving subscribtions

### ISSUE THREAD

**Issue by kromonos** [owntracks/android#95]
Subscribed topics would only send to the last device, which was logged in with one account.
Example:
* 1 Account
* Login with my Moto G. Got Subscriptions without any problems
* Login with same account into my Nexus 7 tablet, subs got lost onto my Moto G ("No contact information received yet") and I don't see the other devices. But Nexus 7 works without problems.
* Remove data an my Moto G and login back, Nexus 7 says "No contact information received yet"

Is it an owntracks "problem" or mgtt?

**Comment by binarybucks** [comment]
Probably a bit of both. Are you using the same client id on both devices?

--
Alexander Rust

**Comment by kromonos** [comment]
Different device ids

**Comment by binarybucks** [comment]
Strange. Can you try to subscribe with two instances of mosquitto_sub and check if you can reproduce it there?

**Comment by kromonos** [comment]
Seems to work without any problems. Also subscribes on my Moto G are shown :)

# mosquitto_sub -u kromonos -P ********* -h localhost -t owntracks/+/+ -d
Client mosqsub/18691-bka.li sending CONNECT
Client mosqsub/18691-bka.li received CONNACK
Client mosqsub/18691-bka.li sending SUBSCRIBE (Mid: 1, Topic: owntracks/+/+, QoS: 0)
Client mosqsub/18691-bka.li received SUBACK
Subscribed (mid: 1): 0
Client mosqsub/18691-bka.li received PUBLISH (d0, q0, r1, m0, 'owntracks/kromonos/motog', ... (121 bytes))
{"_type":"location","lat":"22.2222222","lon":"1.1111111","tst":"1424123424","acc":"23.38","batt":"87","t":"u","tid":"og"}
Client mosqsub/18691-bka.li received PUBLISH (d0, q0, r1, m0, 'owntracks/kromonos/nexus7', ... (101 bytes))
{"_type":"location","lat":"22.2222222","lon":"1.1111111","tst":"1424109023","acc":"21.21","tid":"s7"}

**Comment by kromonos** [comment]
Next "problem" with subscriptions:
After reboot with autostart, subscriptions where not shown. 
![screenshot_2015-03-08-17-00-01](https://cloud.githubusercontent.com/assets/1553902/6546476/dabf1be4-c5b4-11e4-8a69-2e857b79823e.png)

**Comment by binarybucks** [comment]
This is not related, you're just seeing #110

**Comment by jpmens** [comment]
I think we can close this: not reproducible with 0.5.15
