### ISSUE TITLE
Inverted avatar's colors in the dark mode.

### ISSUE THREAD

**Issue by Allineer** [owntracks/android#957]
* **App build number**: 2.3.0 (23030)
* **Android version**: 10 QKQ1.190828.002
* **Device**: Xiaomi mi9se

Look at my avatar :)

![image](https://user-images.githubusercontent.com/1168049/111150025-a553ed80-859e-11eb-9679-b06ee24f8c5a.png)

![image](https://user-images.githubusercontent.com/1168049/111150047-ad139200-859e-11eb-902d-d4e89c213cc8.png)

Why avatars are inverted?

**Comment by growse** [comment]
Unsure - how are you enabling the dark mode? I didn't think we had that supported in the app yet...

**Comment by Allineer** [comment]
![Screenshot_2021-03-15-19-49-25-331_com android settings](https://user-images.githubusercontent.com/1168049/111190013-ba914200-85c7-11eb-8e02-6c828565f639.jpg)
![Screenshot_2021-03-15-19-49-17-600_com android settings](https://user-images.githubusercontent.com/1168049/111190017-bbc26f00-85c7-11eb-90a8-4b86a35d7ceb.jpg)
@growse default android future...

**Comment by growse** [comment]
I completely failed to notice / test this. Will try and figure out how to sort and get into the next ver. Thanks!

**Comment by growse** [comment]
Ok, this is weird - on the emulator (API30), I don't see any visual change in the app when enabling the device dark mode:

![Screenshot_1615830431](https://user-images.githubusercontent.com/378067/111197589-8d886380-85b6-11eb-9ebc-d782ffadbea4.png)

![2021-03-15 17_48_41-Screenshot_1615830435 png ‎- Photos](https://user-images.githubusercontent.com/378067/111197809-d213ff00-85b6-11eb-9b2a-b73b452d7a8f.png)

I wonder if this is a Xiaomi thing?

**Comment by Allineer** [comment]
I dont know and I can't test it on another vendor devices - only xiaomi around.

**Comment by Allineer** [comment]
Resolved in 2.4.0 (24028)

**Comment by growse** [comment]
If you can update to the 2.4.0-beta, I'd be interested in knowing if it still behaves the same. 2.4 has a specific dark theme that it now uses when the device is in night/dark mode.

**Comment by Allineer** [comment]
@growse 

OwnTracks 2.4.0 (24028) - Google Play

Light mode in OS, "Always in light mode" in app:

![image](https://user-images.githubusercontent.com/1168049/124872889-78ed3280-dfce-11eb-90bf-071ca2722e4e.png)

Light mode in OS, "Always in dark mode" in app:

![image](https://user-images.githubusercontent.com/1168049/124872906-80144080-dfce-11eb-83de-33765e50b498.png)

Dark mode in OS,  "Always in dark mode" in app:

![image](https://user-images.githubusercontent.com/1168049/124872927-873b4e80-dfce-11eb-9c3a-034393b1ea47.png)

**Comment by growse** [comment]
Looks like this might be a Xiaomi-specific thing. There's a few articles / threads around talking about this exact issue of bitmaps being inverted in a device "dark mode". Apparently it's called "colour inversion"?:

https://en.gizchina.it/2021/04/xiaomi-miui-12-modalita-scura-colori-invertiti/

https://www.techbone.net/xiaomi/user-manual/color-inversion

https://www.reddit.com/r/Xiaomi/comments/mrzwdn/image_colour_inversion/

Usefully, it does seem that you can disable it per-app, but I'm not sure there's anything that can be done on the OT side.

**Comment by Allineer** [comment]
@grows, Thanks for your work!
