### ISSUE TITLE
Display a popup when receive a MQTT message

### ISSUE THREAD

**Issue by anhtu91** [owntracks/android#960]
Hi, 
I want to display a popup when receive a MQTT message. I think, the uithread should be updated when receive message but I am confusing, how the uithread can be updated.  Could you guys give me some hints? Thanks in advance.

**Comment by growse** [comment]
What's the use case?

I'd probably start by managing the notification from the `BackgroundService` and then using the event bus to notify the service from the `MessageProcessor` when a message arrives matching whatever criteria you want. But I'm not sure that's the best way necessarily.

**Comment by anhtu91** [comment]
> What's the use case?
> 
> I'd probably start by managing the notification from the `BackgroundService` and then using the event bus to notify the service from the `MessageProcessor` when a message arrives matching whatever criteria you want. But I'm not sure that's the best way necessarily.
My use case is, I have created a geofence backend, whenever user comes to a specific location, the user receives a MQTT message from backend, which says "welcome to location.....". 
I have modified function _processIncomingMessage_ in _MessageProcess.java_ and it displays MQTT message in the running terminal. But now, I want to diplay this message as a popup and moreover, display a QRCode for user to enter the location.

**Comment by anhtu91** [comment]
> What's the use case?
> 
> I'd probably start by managing the notification from the `BackgroundService` and then using the event bus to notify the service from the `MessageProcessor` when a message arrives matching whatever criteria you want. But I'm not sure that's the best way necessarily.

One more question, how can I connect `BackgroundService` to uithread?

**Comment by growse** [comment]
It's not obvious how a UI thread is relevant here. If you want to show a notification, you can manage that from the `BackgroundService` in the same way the other notifications are managed. Similarly, a toast can also be managed there. For anything more complex, you probably want a new activity, which you can probably start with an intent from either the service or maybe directly from the processor itself.

**Comment by jpmens** [comment]
@anhtu91 nice that you're interested in our app, and we always welcome new ideas for improving it or users' experience, but please understand that we cannot lead you through Android programming for modifying the app. We're just a very small team with @growse as our only Android developer and can spare only enough time to do this project in our spare time.

I think @growse has pointed you in the right directions, so I'm now going to close this issue.
