### ISSUE TITLE
launch at startup does not work

### ISSUE THREAD

**Issue by nbrignon** [owntracks/android#962]
the settings "launch app  th the startup" is not working.
I have to manually start the app.
All is working after the manual launch, even if we close it, it still running in the background.
BUT all app activity stop à 0:00 !

* **App build number**: 2.2.2 (22202)
* **Android version**: 9
* **Device**: SM-J530F

**Comment by growse** [comment]
Could you try the latest version from the play store?

**Comment by nbrignon** [comment]
yes, it seems working now, many thanks.
