### ISSUE TITLE
No Map view

### ISSUE THREAD

**Issue by kromonos** [owntracks/android#97]
With Version 0.5.02, there is no map view anymore. See http://bka.li/Screenshot_2015-02-23-16-14-40.png

**Comment by binarybucks** [comment]
My bad, compiled in a wrong Maps API key. 
Please try https://github.com/owntracks/android/raw/Android-v.0.5.03/apk/owntracks.apk

**Comment by kromonos** [comment]
Works great :) 
Thank you

**Comment by binarybucks** [comment]
If the app freezes when opening the preferences, please uninstall the app and install 0.5.03 from Github again. I had to upload it again due to a recursion issue.
