### ISSUE TITLE
No location updates when app not open

### ISSUE THREAD

**Issue by alexte** [owntracks/android#976]
* **App build number**: 2.3.0
* **Android version**:  Android 11 Current Build as of 15.4.2021 RQ2A.210405.005   
* **Device**: Pixel4a

Since the last update of Android the app doesn't receive (or send?) location updates, unless it is opened.
No matter if in "significant changes" or "move mode", no location updates. My work around
switching to "move mode" when on the go, does not work any longer.

How can I help debugging this issue?

I think it has to do with google now enforcing "Location Updates: only while is in use"
https://developer.android.com/about/versions/oreo/background-location-limits

**Comment by growse** [comment]
Hmm. I'm on literally the same device and version, and don't see the same issue. Just to clarify, even in move mode, if you foreground the application, you get locations posted to MQTT/HTTP. But if you switch to another app or the launcher, those location updates stop?

Do you see the service notification? Does that notification display the reverse geocoded address on it, or does it just say the mode name?

The background limits don't apply to the OT service, because it's a foreground service. The app doesn't have permission to even receive background location.

**Comment by alexte** [comment]
I see in the notification that I am in move mode, but I don't see an address because I don't use geocode.
Wen opening the app I received location updates.
Is there a logfile I can check, when and if the app received location information ?

**Comment by growse** [comment]
You should be able to view and export the adb log from the `Status` page.

**Comment by alexte** [comment]
Is there a way to see if the "foreground service" is actually running. would the notification go away when killed ?

Battery optimization for the app is already disabled

**Comment by growse** [comment]
Yes - the notification is tied to the foreground service. I don't believe there's a way to have the the persistent notification without a foreground service running.

**Comment by alexte** [comment]
I checked the logs in the status page in the app, and the output of "adb logcat | grep owntracks".

There is no entry up to the point where I actively opened the app.

Could it be I have to open OT after a restart at least once ? That would explain that it stopped working after update (reboot)
But on the other hand the notification was there, hence the foreground service was running.

**Comment by growse** [comment]
Ah - there is an issue where the service doesn't receive locations up until the first time that it's opened after a reboot, and that's described in the first link you posted. But after the activity has been opened once, the service should then start to receive notifications regardless of the activity being in the foreground or not.

This is ultimately down to the background restrictions - a foreground service started by a *background process* (e.g. a `android.intent.action.BOOT_COMPLETED` intent) don't get locations. I guess this is down to Google wanting to enforce that a process that is capturing a user's location is doing so as a result of an explicit action they took.

This is, ultimately, a bug in how the OT behaves. In the short term, it's likely that we'll have a extra notification displayed when the foreground service has been started in such a way that can notify the user that locations aren't currently being captured. Longer term, I want to look at adding the `BACKGROUND_LOCATION` permission back in (which would allow the foreground service to capture locations when started by a background task). The problem with this is that you effectively have to ask Google very nicely, put a lot of effort into a submission request, and there's no guarantee they say "yes".

**Comment by alexte** [comment]
I think that's it: 
After opening the app activily, the move mode updates resumed even when with the app closed. 

Reverse test: after reboot the location updates  stopped, even though the notification is present.

**Comment by alexte** [comment]
You are right: It would help as work around if you show the user in the notification that OT doesn't receive updates until opened once.

**Comment by growse** [comment]
> You are right: It would help as work around if you show the user in the notification that OT doesn't receive updates until opened once, or OT actually receives an update.

It'll 100% be in the next release. Hopefully within a week or so.
