### ISSUE TITLE
Red frame after using Intent to open file manager in Owntracks

### ISSUE THREAD

**Issue by anhtu91** [owntracks/android#978]
I am trying to open file manager to import a QR Code image but after using Intent to open file manger and import the QR Code, my app runs with a red frame around the screen. I have googled it and found that, the strict mode should be deactivated and then the device should also be reset. But it didn't work at all. My code is below:

`https://paste.ofcode.org/d4rJjUPsxVdXrhh25YbAz9`

**Comment by growse** [comment]
I don't follow.

What's the bug?

**Comment by anhtu91** [comment]
> I don't follow.
> 
> What's the bug?

Hi, I am trying to add some features to Owntracks. I have already added a feature "Parking code" to slide bar 

[https://imgur.com/a/907BffL](url)

When I don't use/ open this feature, Owntracks works perfectly but when I open this feature, a red frame appears around the device and start flashing.

**Comment by growse** [comment]
I suggest asking on stackoverflow.com or similar.
