### ISSUE TITLE
Opening Exports

### ISSUE THREAD

**Issue by kromonos** [owntracks/android#98]
Opening backup file comes with every file extension. As of backups will be saved as .otrc file, I think, it would be better, that .otrc is kombined with opening with "export", see: http://bka.li/Screenshot_2015-02-23-16-36-41.png

Also a rename from "Export" to something like "Import to owntracks" would be nice

**Comment by binarybucks** [comment]
Noticed those points too. 
I've not contributed the export code and file extensions in Android are generally a bit weird. 

Will see what I can do.

**Comment by massimilianozilio** [comment]
About file extension association, please read my comment dated Nov-9 on
https://github.com/owntracks/android/issues/7

Let me know if you have any suggestion other than what I have already
suggested in the comment.

Max

**Comment by binarybucks** [comment]
I think I found a mix of intent filters that are working quite good now. At least imports from the Gmail app, Google Drive and Dropbox are working now.

I also split up the import and export into two activities and added a preview screen to review the configuration before importing it. 

I'll submit a Play Store beta this week I think. There will be a lot of things that need testing.

--
Alexander Rust

**Comment by massimilianozilio** [comment]
Hi 
I also played with filters a lot but I found that different apps set different mine type so what a filter that works for gmail might not work for another email client at all. 

The more restrictive the filter is the higher is the risk that association won't work with some app.  Which is why I went for a loose filter which basically accept ALL.

Max

**Comment by binarybucks** [comment]
Have a look at my changes: https://github.com/owntracks/android/blob/master/AndroidManifest.xml#L53
I also moved the filters into the activity element. Before they were in the application element and Android Lint was complaining about misplaced elements. I cannot say if your or this new solution is better or why this works differently but as long as the results are ok I'm fine with that :D 

This also works when opening an otrc from the Downloads app.

**Comment by jpmens** [comment]
Testing 0.5.04 (APK). Import works fine here.

**Comment by kromonos** [comment]
Where can I get 0.5.04 for testing?

**Comment by jpmens** [comment]
In the repo, directory /apk

**Comment by binarybucks** [comment]
Or wait an hour to get it on Google Play.

--
Alexander Rust

**Comment by kromonos** [comment]
Very nice :)

**Comment by binarybucks** [comment]
Make sure to join the Beta Program in the Google Plus community to be able to install the new version. Search for org.owntracks.android in the store so you don't get the old app (now called Owntracks Legacy).

--
Alexander Rust

**Comment by kromonos** [comment]
I've got 0.5.03 from here. Isn't it org.owntracks.android?

**Comment by binarybucks** [comment]
Opening import work solid now.
