### ISSUE TITLE
Stopp / Kill OwnTracks with Tasker

### ISSUE THREAD

**Issue by Plggeldy** [owntracks/android#982]
Hi,
is there a chance, to stop/shutdown/kill OT via Tasker?

I want to start OT when WiFi is disconnected - this works fine. 
But I also want OT to close (when WiFi is connected) - this dosen't work at all. 

I tried  "send intent" with various actions like "org.owntracks.android.KILL_APP"     or "org.owntracks.android.title_exit" 

* **App build number**: OT 2.3.0 (23024)   Tasker2.0 (?)
* **Android version**: 10
* **Device**: Samsung Galaxy A7 (2018)

Thanks a lot! Piggeldy!

PS: It's my first Issues, please ask, if i forgot something.

**Comment by growse** [comment]
I feel like if you can start the service with an intent, you should also be able to end it.
