### ISSUE TITLE
Lost data after a connection errors + Android reboot

### ISSUE THREAD

**Issue by nicbou** [owntracks/android#994]
I am not sure which is the culprit, but I lost a day of data when my phone ran out of battery. At the same time, the MQTT server was down (I don't know for how long). I see data from today, but yesterday's bicycle trip seems lost.

If the phone reboots, it should not lose the data it hasn't yet submitted. It should be preserved until it's successfully posted to the MQTT server.

**Comment by growse** [comment]
Yes - we've long had an enhancement request for preserving the message queue to device storage rather than just memory. It's not there yet, but it's on the list to do.

**Comment by nicbou** [comment]
Thanks @growse!

**Comment by growse** [comment]
Should be in 2.4.0 release, once I've finished off a few other bits and done some testing.
